import Kourovka.Problems.P21_03.Proof.ForestSupportCount

/-!
# Transposition cores under transport of permutation actions

Conjugating a permutation representation along an equivalence preserves swaps,
and hence preserves the subgroup generated by swaps.  This identifies the
transposition core of a forest action with that of its transported target
envelope.
-/

namespace Kourovka213

universe u v w z

private theorem permCongr_isSwap
    {X Y : Type*} [DecidableEq X] [DecidableEq Y]
    (e : X ≃ Y) {g : Equiv.Perm X} (hg : g.IsSwap) :
    (permCongrMulEquiv e g).IsSwap := by
  obtain ⟨a, b, hab, rfl⟩ := hg
  refine ⟨e a, e b, e.injective.ne hab, ?_⟩
  apply Equiv.ext
  intro y
  obtain ⟨x, rfl⟩ := e.surjective y
  simp [permCongrMulEquiv, Equiv.permCongr_apply,
    Equiv.swap_apply_def, e.injective.eq_iff]
  split_ifs <;> rfl

private theorem permCongr_inverse_apply
    {X Y : Type*} (e : X ≃ Y) (g : Equiv.Perm X) :
    permCongrMulEquiv e.symm (permCongrMulEquiv e g) = g := by
  apply Equiv.ext
  intro x
  simp [permCongrMulEquiv, Equiv.permCongr_apply]

private theorem permCongr_transpositionCore_iff
    {X Y : Type*} [DecidableEq X] [DecidableEq Y]
    (e : X ≃ Y) (H : Subgroup (Equiv.Perm X)) (g : Equiv.Perm X) :
    permCongrMulEquiv e g ∈
        transpositionCore (H.map (permCongrMulEquiv e).toMonoidHom) ↔
      g ∈ transpositionCore H := by
  let C := permCongrMulEquiv e
  let D := permCongrMulEquiv e.symm
  have hforward : ∀ σ : Equiv.Perm X,
      σ ∈ transpositionCore H →
        C σ ∈ transpositionCore (H.map C.toMonoidHom) := by
    intro σ hσ
    change σ ∈ Subgroup.closure (transpositionsIn H) at hσ
    induction hσ using Subgroup.closure_induction with
    | mem σ hσ =>
        rw [transpositionCore]
        apply Subgroup.subset_closure
        exact ⟨permCongr_isSwap e hσ.1,
          Subgroup.mem_map.mpr ⟨σ, hσ.2, rfl⟩⟩
    | one => simpa only [map_one] using
        (Subgroup.one_mem (transpositionCore (H.map C.toMonoidHom)))
    | mul a b _ _ ha hb =>
        rw [map_mul]
        exact Subgroup.mul_mem (transpositionCore (H.map C.toMonoidHom)) ha hb
    | inv a _ ha =>
        rw [map_inv]
        exact Subgroup.inv_mem (transpositionCore (H.map C.toMonoidHom)) ha
  have hreverse : ∀ τ : Equiv.Perm Y,
      τ ∈ transpositionCore (H.map C.toMonoidHom) →
        D τ ∈ transpositionCore H := by
    intro τ hτ
    change τ ∈ Subgroup.closure
      (transpositionsIn (H.map C.toMonoidHom)) at hτ
    induction hτ using Subgroup.closure_induction with
    | mem τ hτ =>
        rw [transpositionCore]
        apply Subgroup.subset_closure
        refine ⟨permCongr_isSwap e.symm hτ.1, ?_⟩
        obtain ⟨σ, hσ, rfl⟩ := Subgroup.mem_map.mp hτ.2
        change permCongrMulEquiv e.symm (permCongrMulEquiv e σ) ∈ H
        rw [permCongr_inverse_apply]
        exact hσ
    | one => simpa only [map_one] using
        (Subgroup.one_mem (transpositionCore H))
    | mul a b _ _ ha hb =>
        rw [map_mul]
        exact Subgroup.mul_mem (transpositionCore H) ha hb
    | inv a _ ha =>
        rw [map_inv]
        exact Subgroup.inv_mem (transpositionCore H) ha
  constructor
  · intro hg
    have := hreverse (C g) hg
    change permCongrMulEquiv e.symm (permCongrMulEquiv e g) ∈
      transpositionCore H at this
    rw [permCongr_inverse_apply] at this
    exact this
  · exact hforward g

/-- The target-envelope isomorphism preserves and reflects transposition-core
membership. -/
theorem ActionEmbedding.targetEnvelopeMulEquiv_mem_transpositionCore_iff
    {A : SolubleAction.{u, v}} {B : SolubleAction.{w, z}}
    (f : ActionEmbedding A B) (g : B.Actor) :
    ((f.targetEnvelopeMulEquiv g : f.targetEnvelope) : Equiv.Perm A.Point) ∈
        transpositionCore f.targetEnvelope ↔
      B.toPermHom g ∈ transpositionCore B.toPermHom.range := by
  let C := permCongrMulEquiv f.pointEquiv.symm
  have hrange : f.targetEnvelope = B.toPermHom.range.map C.toMonoidHom := by
    ext σ
    constructor
    · rintro ⟨g, rfl⟩
      exact Subgroup.mem_map.mpr ⟨B.toPermHom g, ⟨g, rfl⟩, rfl⟩
    · intro hσ
      obtain ⟨τ, ⟨g, rfl⟩, rfl⟩ := Subgroup.mem_map.mp hσ
      exact ⟨g, rfl⟩
  rw [ActionEmbedding.targetEnvelopeMulEquiv_coe, hrange]
  exact permCongr_transpositionCore_iff f.pointEquiv.symm B.toPermHom.range
    (B.toPermHom g)

end Kourovka213
