import Mathlib.GroupTheory.Perm.ClosureSwap
import Mathlib.GroupTheory.Perm.ViaEmbedding
import Mathlib.GroupTheory.Solvable
import Mathlib.Data.Set.Card

/-!
# The transposition core of a permutation subgroup

For a subgroup `H` of a finite symmetric group, `transpositionCore H` is the
subgroup generated by the transpositions contained in `H`.  Its orbits have
size at most four when `H` is soluble.
-/

open Equiv MulAction Set Subgroup

namespace Kourovka213

variable {α : Type*} [DecidableEq α]

/-- The set of transpositions which belong to `H`. -/
def transpositionsIn (H : Subgroup (Equiv.Perm α)) : Set (Equiv.Perm α) :=
  {σ | σ.IsSwap ∧ σ ∈ H}

/-- The subgroup generated by all transpositions in `H`. -/
def transpositionCore (H : Subgroup (Equiv.Perm α)) : Subgroup (Equiv.Perm α) :=
  Subgroup.closure (transpositionsIn H)

theorem transpositionsIn_isSwap (H : Subgroup (Equiv.Perm α)) :
    ∀ σ ∈ transpositionsIn H, σ.IsSwap :=
  fun _ hσ ↦ hσ.1

/-- The transposition core is contained in the original subgroup. -/
theorem transpositionCore_le (H : Subgroup (Equiv.Perm α)) :
    transpositionCore H ≤ H :=
  by
    rw [transpositionCore, Subgroup.closure_le]
    exact fun _ hσ ↦ hσ.2

/-- A swap belongs to the transposition core exactly when its endpoints lie
in the same core orbit. -/
theorem swap_mem_transpositionCore_iff (H : Subgroup (Equiv.Perm α)) {x y : α} :
    Equiv.swap x y ∈ transpositionCore H ↔
      x ∈ MulAction.orbit (transpositionCore H) y := by
  exact swap_mem_closure_isSwap (transpositionsIn_isSwap H)

/-- Orbit-wise characterization of membership in the transposition core. -/
theorem mem_transpositionCore_iff (H : Subgroup (Equiv.Perm α))
    [Finite α] (f : Equiv.Perm α) :
    f ∈ transpositionCore H ↔
      ∀ x, f x ∈ MulAction.orbit (transpositionCore H) x := by
  rw [transpositionCore, mem_closure_isSwap (transpositionsIn_isSwap H)]
  exact and_iff_right (Set.toFinite _)

/-- `H` normalizes its transposition core. -/
theorem le_normalizer_transpositionCore (H : Subgroup (Equiv.Perm α)) :
    H ≤ Subgroup.normalizer (transpositionCore H) := by
  rw [transpositionCore, Subgroup.le_normalizer_closure_iff]
  intro h hh σ hσ
  apply Subgroup.subset_closure
  constructor
  · obtain ⟨x, y, hxy, rfl⟩ := hσ.1
    refine ⟨h x, h y, h.injective.ne hxy, ?_⟩
    exact (Equiv.swap_apply_apply h x y).symm
  · exact H.mul_mem (H.mul_mem hh hσ.2) (H.inv_mem hh)

/-- The transposition core, regarded as a subgroup of `H`. -/
def transpositionCoreIn (H : Subgroup (Equiv.Perm α)) : Subgroup H :=
  (transpositionCore H).comap H.subtype

instance transpositionCoreIn_normal (H : Subgroup (Equiv.Perm α)) :
    (transpositionCoreIn H).Normal := by
  rw [← Subgroup.normalizer_eq_top_iff, Subgroup.eq_top_iff']
  intro h
  rw [Subgroup.mem_normalizer_iff]
  intro k
  change (k : Equiv.Perm α) ∈ transpositionCore H ↔
    ((h : Equiv.Perm α) * (k : Equiv.Perm α) * (h : Equiv.Perm α)⁻¹) ∈
      transpositionCore H
  exact le_normalizer_transpositionCore H h.property k

/-- The orbit of `a` under the transposition core. -/
abbrev TranspositionOrbit (H : Subgroup (Equiv.Perm α)) (a : α) :=
  MulAction.orbit (transpositionCore H) a

private theorem viaEmbedding_mem_transpositionCore
    [Finite α] (H : Subgroup (Equiv.Perm α)) (a : α)
    (f : Equiv.Perm (TranspositionOrbit H a)) :
    Equiv.Perm.viaEmbeddingHom (Function.Embedding.subtype _) f ∈ transpositionCore H := by
  rw [mem_transpositionCore_iff H]
  intro x
  by_cases hx : x ∈ MulAction.orbit (transpositionCore H) a
  · let x' : TranspositionOrbit H a := ⟨x, hx⟩
    rw [show x = (x' : α) by rfl, Equiv.Perm.viaEmbeddingHom_apply]
    change
      f.viaEmbedding (Function.Embedding.subtype _)
          ((Function.Embedding.subtype _) x') ∈
        MulAction.orbit (transpositionCore H) ((Function.Embedding.subtype _) x')
    rw [Equiv.Perm.viaEmbedding_apply f (Function.Embedding.subtype _) x']
    change ((f x' : TranspositionOrbit H a) : α) ∈
      MulAction.orbit (transpositionCore H) (x' : α)
    have hx' : (x' : α) ∈ MulAction.orbit (transpositionCore H) a := hx
    rw [MulAction.orbit_eq_iff.mpr hx']
    exact (f x').property
  · rw [Equiv.Perm.viaEmbeddingHom_apply,
      Equiv.Perm.viaEmbedding_apply_of_notMem]
    · exact MulAction.mem_orbit_self x
    · simpa using hx

/-- Every permutation of a core orbit extends by the identity to an element
of the core. -/
noncomputable def orbitExtensionHom [Finite α]
    (H : Subgroup (Equiv.Perm α)) (a : α) :
    Equiv.Perm (TranspositionOrbit H a) →* transpositionCore H :=
  (Equiv.Perm.viaEmbeddingHom (Function.Embedding.subtype _)).codRestrict
    (transpositionCore H) (viaEmbedding_mem_transpositionCore H a)

theorem orbitExtensionHom_injective [Finite α]
    (H : Subgroup (Equiv.Perm α)) (a : α) :
    Function.Injective (orbitExtensionHom H a) := by
  rw [orbitExtensionHom, MonoidHom.injective_codRestrict]
  exact Equiv.Perm.viaEmbeddingHom_injective _

/-- If `H` is soluble, every orbit of its transposition core has at most four
points. -/
theorem ncard_transpositionCore_orbit_le_four
    [Finite α] (H : Subgroup (Equiv.Perm α)) [Group.IsSolvable H] (a : α) :
    Set.ncard (MulAction.orbit (transpositionCore H) a) ≤ 4 := by
  classical
  let _ : Group.IsSolvable (transpositionCore H) :=
    Group.isSolvable_of_isSolvable_injective
      (Subgroup.inclusion_injective (transpositionCore_le H))
  let _ : Group.IsSolvable (Equiv.Perm (TranspositionOrbit H a)) :=
    Group.isSolvable_of_isSolvable_injective (orbitExtensionHom_injective H a)
  by_contra h
  let _ : Fintype (TranspositionOrbit H a) := Fintype.ofFinite _
  have hcard : 5 ≤ Fintype.card (TranspositionOrbit H a) := by
    rw [Set.fintypeCard_eq_ncard]
    exact Nat.lt_of_not_ge h
  have hemb : Nonempty (Fin 5 ↪ TranspositionOrbit H a) := by
    apply Function.Embedding.nonempty_of_card_le
    simpa using hcard
  have h5 : 5 ≤ Cardinal.mk (TranspositionOrbit H a) := by
    rwa [← Cardinal.lift_mk_le, Cardinal.mk_fin, Cardinal.lift_natCast,
      Cardinal.lift_id] at hemb
  exact Equiv.Perm.not_isSolvable (TranspositionOrbit H a) h5 inferInstance

end Kourovka213
