import Kourovka.Problems.P21_38.Proof.Spread
import Mathlib.Algebra.Group.Int.Defs
import Mathlib.Algebra.Group.Prod
import Mathlib.GroupTheory.Abelianization.Defs

/-!
# Recognizing the kernel of an abelian quotient

Agreement on an ordinary generating pair proves that a homomorphism to an
abelian group has exactly the commutator subgroup as its kernel. The coordinate
specializations construct the required homomorphism into the abelianization
explicitly; the kernel description is a conclusion, not a hypothesis.
-/

namespace Kourovka.P21_38

variable {G A : Type*} [Group G] [CommGroup A]

/-- If a homomorphism back to the abelianization agrees with its quotient map
on a generating pair, the original homomorphism kills exactly the commutator. -/
theorem ker_eq_commutator_of_generatesPair_of_section
    {a b : G} (hgen : GeneratesPair a b) (q : G →* A)
    (s : A →* Abelianization G)
    (ha : s (q a) = Abelianization.of a)
    (hb : s (q b) = Abelianization.of b) :
    q.ker = commutator G := by
  have hcomp : s.comp q = Abelianization.of := by
    apply MonoidHom.eq_of_eqOn_dense hgen
    intro x hx
    rcases Set.mem_insert_iff.mp hx with rfl | hx
    · exact ha
    · have hxb : x = b := Set.mem_singleton_iff.mp hx
      simpa only [hxb, MonoidHom.comp_apply] using hb
  apply le_antisymm
  · intro x hx
    rw [← Abelianization.ker_of]
    change Abelianization.of x = 1
    have h := DFunLike.congr_fun hcomp x
    simpa only [MonoidHom.comp_apply, MonoidHom.mem_ker.mp hx, map_one] using h.symm
  · exact Abelianization.commutator_subset_ker q

/-- The homomorphism from two integer coordinates sending the coordinate
basis to the prescribed elements of a commutative group. -/
def integerPairHom (u v : A) : Multiplicative (ℤ × ℤ) →* A where
  toFun z := u ^ z.toAdd.1 * v ^ z.toAdd.2
  map_one' := by simp
  map_mul' x y := by
    change u ^ (x.toAdd.1 + y.toAdd.1) * v ^ (x.toAdd.2 + y.toAdd.2) = _
    simp only [zpow_add]
    exact mul_mul_mul_comm _ _ _ _

@[simp]
theorem integerPairHom_ofAdd (u v : A) (i j : ℤ) :
    integerPairHom u v (Multiplicative.ofAdd (i, j)) = u ^ i * v ^ j := rfl

/-- A group generated by two elements whose images are the standard basis
of `ℤ × ℤ` has commutator kernel under that homomorphism. -/
theorem ker_eq_commutator_of_generatesPair_of_basis_images
    {a b : G} (hgen : GeneratesPair a b) (q : G →* Multiplicative (ℤ × ℤ))
    (ha : q a = Multiplicative.ofAdd (1, 0))
    (hb : q b = Multiplicative.ofAdd (0, 1)) :
    q.ker = commutator G := by
  apply ker_eq_commutator_of_generatesPair_of_section hgen q
    (integerPairHom (Abelianization.of a) (Abelianization.of b))
  · simp [ha]
  · simp [hb]

/-- The same kernel criterion for the basis `(1,-1), (0,-1)`, a common
endpoint-germ convention for the standard generators of Thompson's group. -/
theorem ker_eq_commutator_of_generatesPair_of_signed_basis_images
    {a b : G} (hgen : GeneratesPair a b) (q : G →* Multiplicative (ℤ × ℤ))
    (ha : q a = Multiplicative.ofAdd (1, -1))
    (hb : q b = Multiplicative.ofAdd (0, -1)) :
    q.ker = commutator G := by
  apply ker_eq_commutator_of_generatesPair_of_section hgen q
    (integerPairHom (Abelianization.of a * (Abelianization.of b)⁻¹)
      ((Abelianization.of b)⁻¹))
  · simp [ha]
  · simp [hb]

end Kourovka.P21_38
