import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Tactic.Group

/-!+Elementary subgroup bridges for the concrete Wilson BN-pair instantiation.
The normalizer hypotheses are supplied by the finite root and torus data.
-/

namespace ReeStructural

variable {G : Type*} [Group G]

open scoped Pointwise

theorem sup_factor_right (U H : Subgroup G) (hn : H ≤ Subgroup.normalizer (U : Set G))
    {b : G} (hb : b ∈ U ⊔ H) :
    ∃ u ∈ U, ∃ h ∈ H, b = u * h := by
  have heq := Subgroup.coe_mul_of_right_le_normalizer_left U H hn
  have hb' : b ∈ (U : Set G) * (H : Set G) := heq ▸ hb
  obtain ⟨u, hu, h, hh, hprod⟩ := hb'
  exact ⟨u, hu, h, hh, hprod.symm⟩

theorem sup_factor_left (U H : Subgroup G) (hn : H ≤ Subgroup.normalizer (U : Set G))
    {b : G} (hb : b ∈ U ⊔ H) :
    ∃ h ∈ H, ∃ u ∈ U, b = h * u := by
  have heq := Subgroup.coe_mul_of_left_le_normalizer_right H U hn
  have hb' : b ∈ (H : Set G) * (U : Set G) := by
    rw [← heq]
    change b ∈ H ⊔ U
    rw [sup_comm]
    exact hb
  obtain ⟨h, hh, u, hu, hprod⟩ := hb'
  exact ⟨h, hh, u, hu, hprod.symm⟩

/-- `B=UH`, `U=RV`, and simple-reflection stability of `V,H` give the exact
factorization premise of `rankOne_middle_step`. -/
theorem simple_factor_of_radical
    (U H R V : Subgroup G) (s : G)
    (hn : H ≤ Subgroup.normalizer (U : Set G))
    (hUV : ∀ u ∈ U, ∃ r ∈ R, ∃ v ∈ V, u = r * v)
    (hV : ∀ v ∈ V, s⁻¹ * v * s ∈ U ⊔ H)
    (hH : ∀ h ∈ H, s⁻¹ * h * s ∈ U ⊔ H) :
    ∀ b ∈ U ⊔ H, ∃ r ∈ R, ∃ c : G,
      b = r * c ∧ s⁻¹ * c * s ∈ U ⊔ H := by
  intro b hb
  obtain ⟨u, hu, h, hh, rfl⟩ := sup_factor_right U H hn hb
  obtain ⟨r, hr, v, hv, rfl⟩ := hUV u hu
  refine ⟨r, hr, v * h, by group, ?_⟩
  have hc := (U ⊔ H).mul_mem (hV v hv) (hH h hh)
  simpa only [mul_assoc, mul_inv_cancel_left] using hc

/-- Absorb the torus factor of a rank-one Bruhat decomposition into its final
Borel factor. This is exactly the format of the 70 finite rank-one identities. -/
theorem rankOne_absorb_torus
    (B H R : Subgroup G) (s : G) (hRB : R ≤ B)
    (hH : ∀ h ∈ H, s * h * s⁻¹ ∈ B)
    (hRank : ∀ u ∈ R, u ≠ 1 →
      ∃ u' ∈ R, ∃ h ∈ H, ∃ u'' ∈ R,
        s⁻¹ * u * s = u' * h * s⁻¹ * u'') :
    ∀ u ∈ R, u ≠ 1 → ∃ u' ∈ R, ∃ b ∈ B,
      s⁻¹ * u * s = u' * s⁻¹ * b := by
  intro u hu hne
  obtain ⟨u', hu', h, hh, u'', hu'', heq⟩ := hRank u hu hne
  refine ⟨u', hu', (s * h * s⁻¹) * u'', B.mul_mem (hH h hh) (hRB hu''), ?_⟩
  rw [heq]
  group

/-- Root orientation verified on the finite Weyl representatives remains true
after multiplication on the left by any torus element in `B`. -/
theorem orientation_torus_left
    (B R : Subgroup G) (s w h : G) (hh : h ∈ B)
    (hw : (∀ u ∈ R, w * u * w⁻¹ ∈ B) ∨
      (∀ u ∈ R, (w * s) * u * (w * s)⁻¹ ∈ B)) :
    (∀ u ∈ R, (h * w) * u * (h * w)⁻¹ ∈ B) ∨
      (∀ u ∈ R, ((h * w) * s) * u * ((h * w) * s)⁻¹ ∈ B) := by
  rcases hw with hpos | hneg
  · left
    intro u hu
    have hc := B.mul_mem (B.mul_mem hh (hpos u hu)) (B.inv_mem hh)
    convert hc using 1
    group
  · right
    intro u hu
    have hc := B.mul_mem (B.mul_mem hh (hneg u hu)) (B.inv_mem hh)
    convert hc using 1
    group

/-- To prove `B ∩ N=H`, it suffices to inspect the Weyl representatives of `N=HW`.
For the explicit matrices, the inspection is simply lower triangularity. -/
theorem intersection_eq_of_weyl_tests
    {K : Type*} (B N H : Subgroup G) (W : K → G)
    (hHB : H ≤ B) (hHN : H ≤ N)
    (factor : ∀ n ∈ N, ∃ h ∈ H, ∃ k, n = h * W k)
    (test : ∀ k, W k ∈ B → W k ∈ H) :
    B ⊓ N = H := by
  apply le_antisymm
  · intro n hn
    obtain ⟨h, hh, k, rfl⟩ := factor n hn.2
    have hw : W k ∈ B := by
      have ht := B.mul_mem (B.inv_mem (hHB hh)) hn.1
      simpa only [inv_mul_cancel_left] using ht
    exact H.mul_mem hh (test k hw)
  · exact le_inf hHB hHN

/-- A quotient generated by the images of a finite Weyl list is generated by
the simple images once every listed word is in their generated subgroup. -/
theorem quotient_generated_of_factor_words
    {Q K : Type*} [Group Q] (π : G →* Q) (hπ : Function.Surjective π)
    (S : Set Q) (W : K → G)
    (factor : ∀ g : G, ∃ h : G, ∃ k, π h = 1 ∧ g = h * W k)
    (words : ∀ k, π (W k) ∈ Subgroup.closure S) :
    Subgroup.closure S = ⊤ := by
  apply top_le_iff.mp
  intro q _
  obtain ⟨g, rfl⟩ := hπ q
  obtain ⟨h, k, hh, rfl⟩ := factor g
  simpa only [map_mul, hh, one_mul] using words k

#print axioms simple_factor_of_radical
#print axioms rankOne_absorb_torus
#print axioms orientation_torus_left
#print axioms intersection_eq_of_weyl_tests
#print axioms quotient_generated_of_factor_words

end ReeStructural
