import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.RepresentationTheory.Invariants
import Mathlib.Algebra.CharP.Two
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic.Abel

/-! A short universal binary relative-module certificate.

Human labels for the concrete permutations are u=(123), v=(243), w=(142).
Thus w belongs to the point stabilizer L fixing 3.  The exact identity is

  1 = (1+u+u²)(1+v+w) + (w-1)(w+u²w+u²+v).

It uses only the A4 fixing 5 inside A5.  Evaluation in any binary module
gives V = (w-1)V + Fix(u), and hence V = [V,L] + V^<u>.
No finite-dimensionality, irreducibility, or module classification is used.
-/

set_option autoImplicit false
noncomputable section

namespace Kourovka2135.A5RelativeModuleCertificate

abbrev A5 := alternatingGroup (Fin 5)

/-- The human-label cycle (123), with zero-based Lean indices. -/
def u : A5 :=
  ⟨Equiv.swap 0 1 * Equiv.swap 1 2, by
    simp [A5, Equiv.Perm.mem_alternatingGroup]⟩

/-- The human-label cycle (243). -/
def v : A5 :=
  ⟨Equiv.swap 1 3 * Equiv.swap 3 2, by
    simp [A5, Equiv.Perm.mem_alternatingGroup]⟩

/-- The human-label cycle (142); it fixes human point 3. -/
def w : A5 :=
  ⟨Equiv.swap 0 3 * Equiv.swap 3 1, by
    simp [A5, Equiv.Perm.mem_alternatingGroup]⟩

/-- The actual point stabilizer fixing human point 3. -/
def L : Subgroup A5 :=
  (MulAction.stabilizer (Equiv.Perm (Fin 5)) (2 : Fin 5)).comap
    (alternatingGroup (Fin 5)).subtype

/-- The actual cyclic subgroup generated by (123). -/
def P : Subgroup A5 := Subgroup.zpowers u

theorem w_mem_L : w ∈ L := by
  change w.val (2 : Fin 5) = 2
  decide
theorem u_cube : u ^ 3 = 1 := by decide
theorem u_mul_u_sq : u * u ^ 2 = 1 := by decide
theorem w_mul_w : w * w = u * v := by decide
theorem w_mul_u_sq_w : w * (u ^ 2 * w) = u := by decide
theorem w_mul_u_sq : w * u ^ 2 = u ^ 2 * v := by decide
theorem w_mul_v : w * v = u * w := by decide

section RingCertificate

variable {R : Type*} [Ring R]

/-- The certificate in any ring whose additive group has exponent two.
The hypothesis includes the zero ring, as needed for zero modules. -/
theorem ring_certificate (f : A5 →* R) (h2 : ∀ x : R, x + x = 0) :
    (1 + f u + f (u ^ 2)) * (1 + f v + f w) +
      (f w - 1) * (f w + f (u ^ 2 * w) + f (u ^ 2) + f v) = 1 := by
  simp only [mul_add, add_mul, sub_mul, one_mul, mul_one, ← map_mul,
    w_mul_w, w_mul_u_sq_w, w_mul_u_sq, w_mul_v]
  calc
    _ = 1 + ((f u + f (u * v) + f (u ^ 2 * v) + f (u * w)) +
      (f u + f (u * v) + f (u ^ 2 * v) + f (u * w))) := by abel
    _ = 1 := by rw [h2, add_zero]

/-- Left multiplication by u fixes the actual order-three norm operator. -/
theorem norm_fixed (f : A5 →* R) :
    f u * (1 + f u + f (u ^ 2)) = 1 + f u + f (u ^ 2) := by
  simp only [mul_add, mul_one, ← map_mul, (pow_two u).symm, u_mul_u_sq, map_one]
  abel

/-- The actual F2 group-algebra identity, with no assumed algebra certificate. -/
theorem groupAlgebra_certificate :
    let f := MonoidAlgebra.of (ZMod 2) A5
    (1 + f u + f (u ^ 2)) * (1 + f v + f w) +
      (f w - 1) * (f w + f (u ^ 2 * w) + f (u ^ 2) + f v) = 1 := by
  apply ring_certificate (MonoidAlgebra.of (ZMod 2) A5)
  intro x
  ext g
  exact CharTwo.add_self_eq_zero (x.coeff g)

end RingCertificate

section Modules

variable {k V : Type*} [CommRing k] [CharP k 2] [AddCommGroup V] [Module k V]

private theorem end_add_self (T : Module.End k V) : T + T = 0 := by
  ext y
  have h := congrArg (fun c : k => c • T y) (CharTwo.add_self_eq_zero (1 : k))
  simpa only [add_smul, one_smul, zero_smul, LinearMap.add_apply,
    LinearMap.zero_apply] using h

/-- Every vector is one w-difference plus a u-fixed vector. -/
theorem exists_decomposition (ρ : Representation k A5 V) (y : V) :
    ∃ a b : V, y = (ρ w a - a) + b ∧ ρ u b = b := by
  let Z : Module.End k V := 1 + ρ v + ρ w
  let A : Module.End k V := ρ w + ρ (u ^ 2 * w) + ρ (u ^ 2) + ρ v
  let T : Module.End k V := 1 + ρ u + ρ (u ^ 2)
  refine ⟨A y, (T * Z) y, ?_, ?_⟩
  · have h := congrArg (fun S : Module.End k V => S y)
      (ring_certificate ρ end_add_self)
    change (T * Z) y + (ρ w (A y) - A y) = y at h
    exact h.symm.trans (add_comm _ _)
  · have h := congrArg (fun S : Module.End k V => S (Z y)) (norm_fixed ρ)
    exact h

/-- The concrete rank-free operator identity, on the actual binary module. -/
theorem range_sup_fixed_eq_top (ρ : Representation k A5 V) :
    LinearMap.range (ρ w - 1) ⊔ LinearMap.ker (ρ u - 1) = ⊤ := by
  apply top_unique
  intro y _
  obtain ⟨a, b, hy, hb⟩ := exists_decomposition ρ y
  refine Submodule.mem_sup.mpr ⟨ρ w a - a, ⟨a, rfl⟩, b, ?_, hy.symm⟩
  change ρ u b - b = 0
  exact sub_eq_zero.mpr hb

/-- The scalar submodule generated by all l-differences for l in H. -/
def commutatorSubmodule (ρ : Representation k A5 V) (H : Subgroup A5) : Submodule k V :=
  Submodule.span k {y | ∃ g ∈ H, ∃ x : V, y = ρ g x - x}

omit [CharP k 2] in
/-- Fixing the named generator is exactly invariance under the actual subgroup P. -/
theorem mem_P_invariants_iff (ρ : Representation k A5 V) (y : V) :
    y ∈ Representation.invariants (ρ.comp P.subtype) ↔ ρ u y = y := by
  let up : P := ⟨u, Subgroup.mem_zpowers u⟩
  have hg (x : P) : x ∈ Subgroup.zpowers up := by
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp x.property
    exact Subgroup.mem_zpowers_iff.mpr ⟨n, Subtype.ext hn⟩
  exact Representation.mem_invariants_iff_of_forall_mem_zpowers
    (ρ.comp P.subtype) up hg y

/-- The requested actual relative-module identity for L fixing 3 and P=<(123)>. -/
theorem commutator_sup_invariants_eq_top (ρ : Representation k A5 V) :
    commutatorSubmodule ρ L ⊔ Representation.invariants (ρ.comp P.subtype) = ⊤ := by
  apply top_unique
  intro y _
  obtain ⟨a, b, hy, hb⟩ := exists_decomposition ρ y
  refine Submodule.mem_sup.mpr ⟨ρ w a - a, ?_, b,
    (mem_P_invariants_iff ρ b).mpr hb, hy.symm⟩
  exact Submodule.subset_span ⟨w, w_mem_L, a, rfl⟩

/-- The same explicit decomposition after any actual group homomorphism. -/
theorem exists_decomposition_of_hom {G : Type*} [Monoid G]
    (ρ : Representation k G V) (j : A5 →* G) (y : V) :
    ∃ a b : V, y = (ρ (j w) a - a) + b ∧ ρ (j u) b = b :=
  exists_decomposition (ρ.comp j) y

end Modules

end Kourovka2135.A5RelativeModuleCertificate
