import Kourovka2135.AbelianDifference

/-! Moving subgroups for actions generated by two operators; no finiteness is needed. -/

set_option autoImplicit false
universe u v
namespace Kourovka2135.AbelianDifference
variable {V : Type u} [CommGroup V]

theorem delta_mem_of_mem_closure {B : Set (MulAut V)} {U : Subgroup V}
    (hB : ∀ b ∈ B, movingSubgroup b ≤ U) {a : MulAut V}
    (ha : a ∈ Subgroup.closure B) (x : V) : delta a x ∈ U := by
  have hle : Subgroup.closure B ≤ modFixer ⊤ U := by
    apply (Subgroup.closure_le _).mpr
    intro b hb
    refine ⟨fun _ => iff_of_true (Subgroup.mem_top _) (Subgroup.mem_top _), ?_⟩
    intro y _
    exact hB b hb ⟨y, rfl⟩
  exact (hle ha).2 x (Subgroup.mem_top x)

variable {G : Type v} [Group G]

theorem iSup_movingSubgroup_eq_of_generating_pair
    (ρ : G →* MulAut V) (a b : G)
    (hgen : Subgroup.closure ({a, b} : Set G) = ⊤) :
    (⨆ g : G, movingSubgroup (ρ g)) = movingSubgroup (ρ a) ⊔ movingSubgroup (ρ b) := by
  let U := movingSubgroup (ρ a) ⊔ movingSubgroup (ρ b)
  have hoperators : Subgroup.closure ({a, b} : Set G) ≤ (modFixer ⊤ U).comap ρ := by
    apply (Subgroup.closure_le _).mpr
    intro g hg
    refine ⟨fun _ => iff_of_true (Subgroup.mem_top _) (Subgroup.mem_top _), ?_⟩
    intro x _
    rcases Set.mem_insert_iff.mp hg with hga | hg
    · subst g
      exact Subgroup.mem_sup_left (show delta (ρ a) x ∈ movingSubgroup (ρ a) from ⟨x, rfl⟩)
    · have heq : g = b := Set.mem_singleton_iff.mp hg
      subst g
      exact Subgroup.mem_sup_right (show delta (ρ b) x ∈ movingSubgroup (ρ b) from ⟨x, rfl⟩)
  rw [hgen] at hoperators
  apply le_antisymm
  · apply iSup_le
    intro g x hx
    obtain ⟨y, rfl⟩ := hx
    exact (hoperators (Subgroup.mem_top g)).2 y (Subgroup.mem_top y)
  · exact sup_le (le_iSup (fun g : G => movingSubgroup (ρ g)) a)
      (le_iSup (fun g : G => movingSubgroup (ρ g)) b)

theorem exists_delta_mul_delta_of_generating_pair
    (ρ : G →* MulAut V) (a b : G)
    (hgen : Subgroup.closure ({a, b} : Set G) = ⊤)
    (hmove : (⨆ g : G, movingSubgroup (ρ g)) = ⊤) (t : V) :
    ∃ x y : V, delta (ρ a) x * delta (ρ b) y = t := by
  have ht : t ∈ movingSubgroup (ρ a) ⊔ movingSubgroup (ρ b) := by
    rw [← iSup_movingSubgroup_eq_of_generating_pair ρ a b hgen, hmove]
    trivial
  obtain ⟨x, ⟨u, rfl⟩, y, ⟨v, rfl⟩, hxy⟩ := Subgroup.mem_sup_of_normal_right.mp ht
  exact ⟨u, v, hxy⟩

end Kourovka2135.AbelianDifference
