import Mathlib.Algebra.Group.Prod
import Mathlib.Algebra.Group.Subgroup.Defs
import Mathlib.Data.Fin.VecNotation
import Mathlib.Data.Fintype.Fin
import Mathlib.Tactic.FinCases

/-! Abstract eight-generator binary words, in left-associated order.
Generated by computation/suzuki-eight-cover/generate_generic_eight_pc_words.py.
Bit 7 selects pc 0 and bit 0 selects pc 7. The empty word is 1. -/

set_option autoImplicit false
set_option maxRecDepth 16384
set_option maxHeartbeats 8000000

universe u v
namespace Kourovka2135.FiniteEightPcWords

def word {G : Type u} [Group G] (pc : Fin 8 → G) : Fin 256 → G :=
  ![1,
    pc 7,
    pc 6,
    (pc 6 * pc 7),
    pc 5,
    (pc 5 * pc 7),
    (pc 5 * pc 6),
    ((pc 5 * pc 6) * pc 7),
    pc 4,
    (pc 4 * pc 7),
    (pc 4 * pc 6),
    ((pc 4 * pc 6) * pc 7),
    (pc 4 * pc 5),
    ((pc 4 * pc 5) * pc 7),
    ((pc 4 * pc 5) * pc 6),
    (((pc 4 * pc 5) * pc 6) * pc 7),
    pc 3,
    (pc 3 * pc 7),
    (pc 3 * pc 6),
    ((pc 3 * pc 6) * pc 7),
    (pc 3 * pc 5),
    ((pc 3 * pc 5) * pc 7),
    ((pc 3 * pc 5) * pc 6),
    (((pc 3 * pc 5) * pc 6) * pc 7),
    (pc 3 * pc 4),
    ((pc 3 * pc 4) * pc 7),
    ((pc 3 * pc 4) * pc 6),
    (((pc 3 * pc 4) * pc 6) * pc 7),
    ((pc 3 * pc 4) * pc 5),
    (((pc 3 * pc 4) * pc 5) * pc 7),
    (((pc 3 * pc 4) * pc 5) * pc 6),
    ((((pc 3 * pc 4) * pc 5) * pc 6) * pc 7),
    pc 2,
    (pc 2 * pc 7),
    (pc 2 * pc 6),
    ((pc 2 * pc 6) * pc 7),
    (pc 2 * pc 5),
    ((pc 2 * pc 5) * pc 7),
    ((pc 2 * pc 5) * pc 6),
    (((pc 2 * pc 5) * pc 6) * pc 7),
    (pc 2 * pc 4),
    ((pc 2 * pc 4) * pc 7),
    ((pc 2 * pc 4) * pc 6),
    (((pc 2 * pc 4) * pc 6) * pc 7),
    ((pc 2 * pc 4) * pc 5),
    (((pc 2 * pc 4) * pc 5) * pc 7),
    (((pc 2 * pc 4) * pc 5) * pc 6),
    ((((pc 2 * pc 4) * pc 5) * pc 6) * pc 7),
    (pc 2 * pc 3),
    ((pc 2 * pc 3) * pc 7),
    ((pc 2 * pc 3) * pc 6),
    (((pc 2 * pc 3) * pc 6) * pc 7),
    ((pc 2 * pc 3) * pc 5),
    (((pc 2 * pc 3) * pc 5) * pc 7),
    (((pc 2 * pc 3) * pc 5) * pc 6),
    ((((pc 2 * pc 3) * pc 5) * pc 6) * pc 7),
    ((pc 2 * pc 3) * pc 4),
    (((pc 2 * pc 3) * pc 4) * pc 7),
    (((pc 2 * pc 3) * pc 4) * pc 6),
    ((((pc 2 * pc 3) * pc 4) * pc 6) * pc 7),
    (((pc 2 * pc 3) * pc 4) * pc 5),
    ((((pc 2 * pc 3) * pc 4) * pc 5) * pc 7),
    ((((pc 2 * pc 3) * pc 4) * pc 5) * pc 6),
    (((((pc 2 * pc 3) * pc 4) * pc 5) * pc 6) * pc 7),
    pc 1,
    (pc 1 * pc 7),
    (pc 1 * pc 6),
    ((pc 1 * pc 6) * pc 7),
    (pc 1 * pc 5),
    ((pc 1 * pc 5) * pc 7),
    ((pc 1 * pc 5) * pc 6),
    (((pc 1 * pc 5) * pc 6) * pc 7),
    (pc 1 * pc 4),
    ((pc 1 * pc 4) * pc 7),
    ((pc 1 * pc 4) * pc 6),
    (((pc 1 * pc 4) * pc 6) * pc 7),
    ((pc 1 * pc 4) * pc 5),
    (((pc 1 * pc 4) * pc 5) * pc 7),
    (((pc 1 * pc 4) * pc 5) * pc 6),
    ((((pc 1 * pc 4) * pc 5) * pc 6) * pc 7),
    (pc 1 * pc 3),
    ((pc 1 * pc 3) * pc 7),
    ((pc 1 * pc 3) * pc 6),
    (((pc 1 * pc 3) * pc 6) * pc 7),
    ((pc 1 * pc 3) * pc 5),
    (((pc 1 * pc 3) * pc 5) * pc 7),
    (((pc 1 * pc 3) * pc 5) * pc 6),
    ((((pc 1 * pc 3) * pc 5) * pc 6) * pc 7),
    ((pc 1 * pc 3) * pc 4),
    (((pc 1 * pc 3) * pc 4) * pc 7),
    (((pc 1 * pc 3) * pc 4) * pc 6),
    ((((pc 1 * pc 3) * pc 4) * pc 6) * pc 7),
    (((pc 1 * pc 3) * pc 4) * pc 5),
    ((((pc 1 * pc 3) * pc 4) * pc 5) * pc 7),
    ((((pc 1 * pc 3) * pc 4) * pc 5) * pc 6),
    (((((pc 1 * pc 3) * pc 4) * pc 5) * pc 6) * pc 7),
    (pc 1 * pc 2),
    ((pc 1 * pc 2) * pc 7),
    ((pc 1 * pc 2) * pc 6),
    (((pc 1 * pc 2) * pc 6) * pc 7),
    ((pc 1 * pc 2) * pc 5),
    (((pc 1 * pc 2) * pc 5) * pc 7),
    (((pc 1 * pc 2) * pc 5) * pc 6),
    ((((pc 1 * pc 2) * pc 5) * pc 6) * pc 7),
    ((pc 1 * pc 2) * pc 4),
    (((pc 1 * pc 2) * pc 4) * pc 7),
    (((pc 1 * pc 2) * pc 4) * pc 6),
    ((((pc 1 * pc 2) * pc 4) * pc 6) * pc 7),
    (((pc 1 * pc 2) * pc 4) * pc 5),
    ((((pc 1 * pc 2) * pc 4) * pc 5) * pc 7),
    ((((pc 1 * pc 2) * pc 4) * pc 5) * pc 6),
    (((((pc 1 * pc 2) * pc 4) * pc 5) * pc 6) * pc 7),
    ((pc 1 * pc 2) * pc 3),
    (((pc 1 * pc 2) * pc 3) * pc 7),
    (((pc 1 * pc 2) * pc 3) * pc 6),
    ((((pc 1 * pc 2) * pc 3) * pc 6) * pc 7),
    (((pc 1 * pc 2) * pc 3) * pc 5),
    ((((pc 1 * pc 2) * pc 3) * pc 5) * pc 7),
    ((((pc 1 * pc 2) * pc 3) * pc 5) * pc 6),
    (((((pc 1 * pc 2) * pc 3) * pc 5) * pc 6) * pc 7),
    (((pc 1 * pc 2) * pc 3) * pc 4),
    ((((pc 1 * pc 2) * pc 3) * pc 4) * pc 7),
    ((((pc 1 * pc 2) * pc 3) * pc 4) * pc 6),
    (((((pc 1 * pc 2) * pc 3) * pc 4) * pc 6) * pc 7),
    ((((pc 1 * pc 2) * pc 3) * pc 4) * pc 5),
    (((((pc 1 * pc 2) * pc 3) * pc 4) * pc 5) * pc 7),
    (((((pc 1 * pc 2) * pc 3) * pc 4) * pc 5) * pc 6),
    ((((((pc 1 * pc 2) * pc 3) * pc 4) * pc 5) * pc 6) * pc 7),
    pc 0,
    (pc 0 * pc 7),
    (pc 0 * pc 6),
    ((pc 0 * pc 6) * pc 7),
    (pc 0 * pc 5),
    ((pc 0 * pc 5) * pc 7),
    ((pc 0 * pc 5) * pc 6),
    (((pc 0 * pc 5) * pc 6) * pc 7),
    (pc 0 * pc 4),
    ((pc 0 * pc 4) * pc 7),
    ((pc 0 * pc 4) * pc 6),
    (((pc 0 * pc 4) * pc 6) * pc 7),
    ((pc 0 * pc 4) * pc 5),
    (((pc 0 * pc 4) * pc 5) * pc 7),
    (((pc 0 * pc 4) * pc 5) * pc 6),
    ((((pc 0 * pc 4) * pc 5) * pc 6) * pc 7),
    (pc 0 * pc 3),
    ((pc 0 * pc 3) * pc 7),
    ((pc 0 * pc 3) * pc 6),
    (((pc 0 * pc 3) * pc 6) * pc 7),
    ((pc 0 * pc 3) * pc 5),
    (((pc 0 * pc 3) * pc 5) * pc 7),
    (((pc 0 * pc 3) * pc 5) * pc 6),
    ((((pc 0 * pc 3) * pc 5) * pc 6) * pc 7),
    ((pc 0 * pc 3) * pc 4),
    (((pc 0 * pc 3) * pc 4) * pc 7),
    (((pc 0 * pc 3) * pc 4) * pc 6),
    ((((pc 0 * pc 3) * pc 4) * pc 6) * pc 7),
    (((pc 0 * pc 3) * pc 4) * pc 5),
    ((((pc 0 * pc 3) * pc 4) * pc 5) * pc 7),
    ((((pc 0 * pc 3) * pc 4) * pc 5) * pc 6),
    (((((pc 0 * pc 3) * pc 4) * pc 5) * pc 6) * pc 7),
    (pc 0 * pc 2),
    ((pc 0 * pc 2) * pc 7),
    ((pc 0 * pc 2) * pc 6),
    (((pc 0 * pc 2) * pc 6) * pc 7),
    ((pc 0 * pc 2) * pc 5),
    (((pc 0 * pc 2) * pc 5) * pc 7),
    (((pc 0 * pc 2) * pc 5) * pc 6),
    ((((pc 0 * pc 2) * pc 5) * pc 6) * pc 7),
    ((pc 0 * pc 2) * pc 4),
    (((pc 0 * pc 2) * pc 4) * pc 7),
    (((pc 0 * pc 2) * pc 4) * pc 6),
    ((((pc 0 * pc 2) * pc 4) * pc 6) * pc 7),
    (((pc 0 * pc 2) * pc 4) * pc 5),
    ((((pc 0 * pc 2) * pc 4) * pc 5) * pc 7),
    ((((pc 0 * pc 2) * pc 4) * pc 5) * pc 6),
    (((((pc 0 * pc 2) * pc 4) * pc 5) * pc 6) * pc 7),
    ((pc 0 * pc 2) * pc 3),
    (((pc 0 * pc 2) * pc 3) * pc 7),
    (((pc 0 * pc 2) * pc 3) * pc 6),
    ((((pc 0 * pc 2) * pc 3) * pc 6) * pc 7),
    (((pc 0 * pc 2) * pc 3) * pc 5),
    ((((pc 0 * pc 2) * pc 3) * pc 5) * pc 7),
    ((((pc 0 * pc 2) * pc 3) * pc 5) * pc 6),
    (((((pc 0 * pc 2) * pc 3) * pc 5) * pc 6) * pc 7),
    (((pc 0 * pc 2) * pc 3) * pc 4),
    ((((pc 0 * pc 2) * pc 3) * pc 4) * pc 7),
    ((((pc 0 * pc 2) * pc 3) * pc 4) * pc 6),
    (((((pc 0 * pc 2) * pc 3) * pc 4) * pc 6) * pc 7),
    ((((pc 0 * pc 2) * pc 3) * pc 4) * pc 5),
    (((((pc 0 * pc 2) * pc 3) * pc 4) * pc 5) * pc 7),
    (((((pc 0 * pc 2) * pc 3) * pc 4) * pc 5) * pc 6),
    ((((((pc 0 * pc 2) * pc 3) * pc 4) * pc 5) * pc 6) * pc 7),
    (pc 0 * pc 1),
    ((pc 0 * pc 1) * pc 7),
    ((pc 0 * pc 1) * pc 6),
    (((pc 0 * pc 1) * pc 6) * pc 7),
    ((pc 0 * pc 1) * pc 5),
    (((pc 0 * pc 1) * pc 5) * pc 7),
    (((pc 0 * pc 1) * pc 5) * pc 6),
    ((((pc 0 * pc 1) * pc 5) * pc 6) * pc 7),
    ((pc 0 * pc 1) * pc 4),
    (((pc 0 * pc 1) * pc 4) * pc 7),
    (((pc 0 * pc 1) * pc 4) * pc 6),
    ((((pc 0 * pc 1) * pc 4) * pc 6) * pc 7),
    (((pc 0 * pc 1) * pc 4) * pc 5),
    ((((pc 0 * pc 1) * pc 4) * pc 5) * pc 7),
    ((((pc 0 * pc 1) * pc 4) * pc 5) * pc 6),
    (((((pc 0 * pc 1) * pc 4) * pc 5) * pc 6) * pc 7),
    ((pc 0 * pc 1) * pc 3),
    (((pc 0 * pc 1) * pc 3) * pc 7),
    (((pc 0 * pc 1) * pc 3) * pc 6),
    ((((pc 0 * pc 1) * pc 3) * pc 6) * pc 7),
    (((pc 0 * pc 1) * pc 3) * pc 5),
    ((((pc 0 * pc 1) * pc 3) * pc 5) * pc 7),
    ((((pc 0 * pc 1) * pc 3) * pc 5) * pc 6),
    (((((pc 0 * pc 1) * pc 3) * pc 5) * pc 6) * pc 7),
    (((pc 0 * pc 1) * pc 3) * pc 4),
    ((((pc 0 * pc 1) * pc 3) * pc 4) * pc 7),
    ((((pc 0 * pc 1) * pc 3) * pc 4) * pc 6),
    (((((pc 0 * pc 1) * pc 3) * pc 4) * pc 6) * pc 7),
    ((((pc 0 * pc 1) * pc 3) * pc 4) * pc 5),
    (((((pc 0 * pc 1) * pc 3) * pc 4) * pc 5) * pc 7),
    (((((pc 0 * pc 1) * pc 3) * pc 4) * pc 5) * pc 6),
    ((((((pc 0 * pc 1) * pc 3) * pc 4) * pc 5) * pc 6) * pc 7),
    ((pc 0 * pc 1) * pc 2),
    (((pc 0 * pc 1) * pc 2) * pc 7),
    (((pc 0 * pc 1) * pc 2) * pc 6),
    ((((pc 0 * pc 1) * pc 2) * pc 6) * pc 7),
    (((pc 0 * pc 1) * pc 2) * pc 5),
    ((((pc 0 * pc 1) * pc 2) * pc 5) * pc 7),
    ((((pc 0 * pc 1) * pc 2) * pc 5) * pc 6),
    (((((pc 0 * pc 1) * pc 2) * pc 5) * pc 6) * pc 7),
    (((pc 0 * pc 1) * pc 2) * pc 4),
    ((((pc 0 * pc 1) * pc 2) * pc 4) * pc 7),
    ((((pc 0 * pc 1) * pc 2) * pc 4) * pc 6),
    (((((pc 0 * pc 1) * pc 2) * pc 4) * pc 6) * pc 7),
    ((((pc 0 * pc 1) * pc 2) * pc 4) * pc 5),
    (((((pc 0 * pc 1) * pc 2) * pc 4) * pc 5) * pc 7),
    (((((pc 0 * pc 1) * pc 2) * pc 4) * pc 5) * pc 6),
    ((((((pc 0 * pc 1) * pc 2) * pc 4) * pc 5) * pc 6) * pc 7),
    (((pc 0 * pc 1) * pc 2) * pc 3),
    ((((pc 0 * pc 1) * pc 2) * pc 3) * pc 7),
    ((((pc 0 * pc 1) * pc 2) * pc 3) * pc 6),
    (((((pc 0 * pc 1) * pc 2) * pc 3) * pc 6) * pc 7),
    ((((pc 0 * pc 1) * pc 2) * pc 3) * pc 5),
    (((((pc 0 * pc 1) * pc 2) * pc 3) * pc 5) * pc 7),
    (((((pc 0 * pc 1) * pc 2) * pc 3) * pc 5) * pc 6),
    ((((((pc 0 * pc 1) * pc 2) * pc 3) * pc 5) * pc 6) * pc 7),
    ((((pc 0 * pc 1) * pc 2) * pc 3) * pc 4),
    (((((pc 0 * pc 1) * pc 2) * pc 3) * pc 4) * pc 7),
    (((((pc 0 * pc 1) * pc 2) * pc 3) * pc 4) * pc 6),
    ((((((pc 0 * pc 1) * pc 2) * pc 3) * pc 4) * pc 6) * pc 7),
    (((((pc 0 * pc 1) * pc 2) * pc 3) * pc 4) * pc 5),
    ((((((pc 0 * pc 1) * pc 2) * pc 3) * pc 4) * pc 5) * pc 7),
    ((((((pc 0 * pc 1) * pc 2) * pc 3) * pc 4) * pc 5) * pc 6),
    (((((((pc 0 * pc 1) * pc 2) * pc 3) * pc 4) * pc 5) * pc 6) * pc 7)]

theorem word_mem {G : Type u} [Group G] (H : Subgroup G)
    (pc : Fin 8 → G) (hp : ∀ j, pc j ∈ H) (i : Fin 256) :
    word pc i ∈ H := by
  have hpc0 := hp (0 : Fin 8)
  have hpc1 := hp (1 : Fin 8)
  have hpc2 := hp (2 : Fin 8)
  have hpc3 := hp (3 : Fin 8)
  have hpc4 := hp (4 : Fin 8)
  have hpc5 := hp (5 : Fin 8)
  have hpc6 := hp (6 : Fin 8)
  have hpc7 := hp (7 : Fin 8)
  fin_cases i
  · exact H.one_mem
  · exact hpc7
  · exact hpc6
  · exact (H.mul_mem hpc6 hpc7)
  · exact hpc5
  · exact (H.mul_mem hpc5 hpc7)
  · exact (H.mul_mem hpc5 hpc6)
  · exact (H.mul_mem (H.mul_mem hpc5 hpc6) hpc7)
  · exact hpc4
  · exact (H.mul_mem hpc4 hpc7)
  · exact (H.mul_mem hpc4 hpc6)
  · exact (H.mul_mem (H.mul_mem hpc4 hpc6) hpc7)
  · exact (H.mul_mem hpc4 hpc5)
  · exact (H.mul_mem (H.mul_mem hpc4 hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc4 hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc4 hpc5) hpc6) hpc7)
  · exact hpc3
  · exact (H.mul_mem hpc3 hpc7)
  · exact (H.mul_mem hpc3 hpc6)
  · exact (H.mul_mem (H.mul_mem hpc3 hpc6) hpc7)
  · exact (H.mul_mem hpc3 hpc5)
  · exact (H.mul_mem (H.mul_mem hpc3 hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc3 hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc3 hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc3 hpc4)
  · exact (H.mul_mem (H.mul_mem hpc3 hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc3 hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc3 hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc3 hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc3 hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc3 hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc3 hpc4) hpc5) hpc6) hpc7)
  · exact hpc2
  · exact (H.mul_mem hpc2 hpc7)
  · exact (H.mul_mem hpc2 hpc6)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc6) hpc7)
  · exact (H.mul_mem hpc2 hpc5)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc2 hpc4)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc2 hpc3)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc3) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc3) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc3) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc2 hpc3) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc2 hpc3) hpc4) hpc5) hpc6) hpc7)
  · exact hpc1
  · exact (H.mul_mem hpc1 hpc7)
  · exact (H.mul_mem hpc1 hpc6)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc6) hpc7)
  · exact (H.mul_mem hpc1 hpc5)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc1 hpc4)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc1 hpc3)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc3) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc3) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc3) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc3) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc3) hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc1 hpc2)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc2) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc2) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc2) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc2) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc1 hpc2) hpc3) hpc4) hpc5) hpc6) hpc7)
  · exact hpc0
  · exact (H.mul_mem hpc0 hpc7)
  · exact (H.mul_mem hpc0 hpc6)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc6) hpc7)
  · exact (H.mul_mem hpc0 hpc5)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc0 hpc4)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc0 hpc3)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc3) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc3) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc3) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc3) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc3) hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc0 hpc2)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc2) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc2) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc2) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc2) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc2) hpc3) hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem hpc0 hpc1)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc1) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc1) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc1) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc1) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc3) hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc4) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc5) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc4)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc4) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc4) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc4) hpc6) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc4) hpc5)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc4) hpc5) hpc7)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc4) hpc5) hpc6)
  · exact (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem hpc0 hpc1) hpc2) hpc3) hpc4) hpc5) hpc6) hpc7)

theorem word_prod {A : Type u} {B : Type v} [Group A] [Group B]
    (a : Fin 8 → A) (b : Fin 8 → B) (i : Fin 256) :
    (word a i, word b i) = word (fun j => (a j, b j)) i := by
  fin_cases i <;> rfl

end Kourovka2135.FiniteEightPcWords
