import Kourovka2135.FiniteAdjoinCard

/-! A triangular list of generators with relative orders dividing two
gives a power-of-two cardinal bound. Relations are hypotheses of this reusable
certificate checker and must be verified in each actual group application.
-/

set_option autoImplicit false
namespace Kourovka2135.FinitePcCertificate

variable {G : Type*} [Group G] {n : ℕ}

def tail (pc : Fin n → G) (i : ℕ) : Subgroup G :=
  Subgroup.closure {g | ∃ j : Fin n, i ≤ j.val ∧ pc j = g}

/-- The initial tail is the actual subgroup generated by the supplied elements. -/
theorem tail_zero (pc : Fin n → G) : tail pc 0 = Subgroup.closure (Set.range pc) := by
  exact congrArg Subgroup.closure (show {g | ∃ j : Fin n, 0 ≤ j.val ∧ pc j = g} =
      Set.range pc from by
    ext g
    simp only [Set.mem_ofPred_eq, Nat.zero_le, true_and, Set.mem_range])

theorem mem_tail (pc : Fin n → G) (i : ℕ) (j : Fin n) (h : i ≤ j.val) :
    pc j ∈ tail pc i := Subgroup.subset_closure ⟨j, h, rfl⟩

theorem tail_mono (pc : Fin n → G) {i j : ℕ} (h : i ≤ j) :
    tail pc j ≤ tail pc i := by
  apply (Subgroup.closure_le _).mpr
  rintro g ⟨k, hk, rfl⟩
  exact mem_tail pc i k (h.trans hk)

theorem tail_last (pc : Fin n → G) : tail pc n = ⊥ := by
  apply le_antisymm ?_ bot_le
  apply (Subgroup.closure_le _).mpr
  rintro g ⟨j, hj, rfl⟩
  omega

theorem tail_split (pc : Fin n → G) (i : Fin n) :
    tail pc i.val = tail pc (i.val + 1) ⊔ Subgroup.zpowers (pc i) := by
  apply le_antisymm
  · apply (Subgroup.closure_le _).mpr
    rintro g ⟨j, hj, rfl⟩
    by_cases he : j = i
    · subst j
      exact (le_sup_right : Subgroup.zpowers (pc i) ≤
        tail pc (i.val + 1) ⊔ Subgroup.zpowers (pc i)) (Subgroup.mem_zpowers _)
    · have hv : i.val + 1 ≤ j.val := by
        have : j.val ≠ i.val := fun h => he (Fin.ext h)
        omega
      exact (le_sup_left : tail pc (i.val + 1) ≤
        tail pc (i.val + 1) ⊔ Subgroup.zpowers (pc i)) (mem_tail pc (i.val + 1) j hv)
  · apply sup_le
    · exact tail_mono pc (by omega)
    · exact Subgroup.zpowers_le.mpr (mem_tail pc i.val i le_rfl)

variable [Finite G]

theorem card_tail_le (pc : Fin n → G)
    (square : ∀ i : Fin n, pc i ^ 2 ∈ tail pc (i.val + 1))
    (conjugate : ∀ i j : Fin n, i.val < j.val →
      (pc i)⁻¹ * pc j * pc i ∈ tail pc (i.val + 1))
    (i : ℕ) (hi : i ≤ n) : Nat.card (tail pc i) ≤ 2 ^ (n - i) := by
  induction hi using Nat.decreasingInduction with
  | self => simp [tail_last]
  | of_succ i hi ih =>
    let a : Fin n := ⟨i, hi⟩
    have hn : pc a ∈ Subgroup.normalizer (tail pc (i + 1)) := by
      apply FiniteAdjoinCard.mem_normalizer_closure_of_generators
      rintro g ⟨j, hj, rfl⟩
      exact conjugate a j (by dsimp [a]; omega)
    have hc := FiniteAdjoinCard.card_le (tail pc (i + 1)) (pc a) hn 2 (by decide)
      (square a)
    rw [show i = a.val from rfl, tail_split pc a]
    have he : n - i = (n - (i + 1)) + 1 := by omega
    calc
      Nat.card ↥(tail pc (i + 1) ⊔ Subgroup.zpowers (pc a))
          ≤ Nat.card (tail pc (i + 1)) * 2 := hc
      _ ≤ 2 ^ (n - (i + 1)) * 2 := Nat.mul_le_mul_right 2 ih
      _ = 2 ^ (n - i) := by rw [he, pow_succ]

theorem card_le (pc : Fin n → G)
    (square : ∀ i : Fin n, pc i ^ 2 ∈ tail pc (i.val + 1))
    (conjugate : ∀ i j : Fin n, i.val < j.val →
      (pc i)⁻¹ * pc j * pc i ∈ tail pc (i.val + 1)) :
    Nat.card (tail pc 0) ≤ 2 ^ n := by
  simpa using card_tail_le pc square conjugate 0 (Nat.zero_le n)

/-- Verified triangular relations bound the actual generated subgroup;
no presentation-completeness hypothesis is required. -/
theorem card_closure_le (pc : Fin n → G)
    (square : ∀ i : Fin n, pc i ^ 2 ∈ tail pc (i.val + 1))
    (conjugate : ∀ i j : Fin n, i.val < j.val →
      (pc i)⁻¹ * pc j * pc i ∈ tail pc (i.val + 1)) :
    Nat.card (Subgroup.closure (Set.range pc)) ≤ 2 ^ n := by
  rw [← tail_zero]
  exact card_le pc square conjugate

end Kourovka2135.FinitePcCertificate
