import Kourovka2135.DerivedCentralization
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.GroupTheory.Solvable

/-!
# Commutator-closed generating sets

The generation step of Alves–Shumyatsky, Lemma 2.2, is proved for finite groups.
The finiteness hypothesis makes one-sided conjugation stability sufficient for
normalization. Single derived-word values remain distinct from their closure.
-/

set_option autoImplicit false
universe u v
namespace Kourovka2135
open scoped commutatorElement
variable {G : Type u} {H : Type v} [Group G] [Group H]

def commutatorImage (X Y : Set G) : Set G :=
  {z | ∃ x ∈ X, ∃ y ∈ Y, paperCommutator x y = z}

def IsCommutatorClosed (X : Set G) : Prop :=
  ∀ x ∈ X, ∀ y ∈ X, paperCommutator x y ∈ X

theorem paperCommutator_eq_one_iff (x y : G) :
    paperCommutator x y = 1 ↔ Commute x y := by
  have heq : paperCommutator x y = ⁅x⁻¹, y⁻¹⁆ := by
    simp only [paperCommutator, commutatorElement_def, inv_inv]
  rw [heq, commutatorElement_eq_one_iff_commute]
  exact ⟨fun h => by simpa only [inv_inv] using h.inv_left.inv_right,
    fun h => h.inv_left.inv_right⟩

theorem IsCommutatorClosed.image {X : Set G} (hX : IsCommutatorClosed X)
    (f : G →* H) : IsCommutatorClosed (f '' X) := by
  rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩
  exact ⟨paperCommutator x y, hX x hx y hy, by simp [paperCommutator]⟩

theorem IsCommutatorClosed.commutatorImage {X : Set G} (hX : IsCommutatorClosed X) :
    IsCommutatorClosed (commutatorImage X X) := by
  rintro a ⟨x, hx, y, hy, rfl⟩ b ⟨z, hz, t, ht, rfl⟩
  exact ⟨_, hX x hx y hy, _, hX z hz t ht, rfl⟩

theorem commutatorImage_subset {X : Set G} (hX : IsCommutatorClosed X) :
    commutatorImage X X ⊆ X := by
  rintro _ ⟨x, hx, y, hy, rfl⟩
  exact hX x hx y hy

/-- A finite group generated by a commutator-closed set has its derived
subgroup generated by commutators of members of that set. -/
theorem commutator_eq_closure_commutatorImage [Finite G] {X : Set G}
    (hX : IsCommutatorClosed X) (hgen : Subgroup.closure X = ⊤) :
    commutator G = Subgroup.closure (commutatorImage X X) := by
  let Y := commutatorImage X X
  let N := Subgroup.closure Y
  have hnorm (x : G) (hx : x ∈ X) : x ∈ Subgroup.normalizer N := by
    apply (Subgroup.normalizer (N : Set G)).inv_mem_iff.mp
    apply Subgroup.mem_normalizer_fintype
    intro y hy
    change x⁻¹ * y * (x⁻¹)⁻¹ ∈ N
    simp only [inv_inv]
    induction hy using Subgroup.closure_induction with
    | mem y hy =>
        have hyX : y ∈ X := commutatorImage_subset hX hy
        have hc : paperCommutator y x ∈ N :=
          Subgroup.subset_closure ⟨y, hyX, x, hx, rfl⟩
        have heq : x⁻¹ * y * x = y * paperCommutator y x := by
          simp [paperCommutator, mul_assoc]
        rw [heq]
        exact N.mul_mem (Subgroup.subset_closure hy) hc
    | one => simpa using N.one_mem
    | mul a b _ _ iha ihb =>
        simpa only [mul_assoc, mul_inv_cancel_left] using N.mul_mem iha ihb
    | inv a _ ih =>
        simpa only [mul_inv_rev, inv_inv, mul_assoc] using N.inv_mem ih
  have hle : Subgroup.closure X ≤ Subgroup.normalizer N :=
    (Subgroup.closure_le _).mpr hnorm
  have hN : N.Normal := Subgroup.normalizer_eq_top_iff.mp <| by
    rw [hgen] at hle
    exact top_le_iff.mp hle
  letI := hN
  apply le_antisymm
  · let f := QuotientGroup.mk' N
    have hbase (a : G) (ha : a ∈ X) (b : G) (hb : b ∈ X) :
        Commute (f a) (f b) := by
      apply (paperCommutator_eq_one_iff _ _).mp
      have heq : paperCommutator (f a) (f b) = f (paperCommutator a b) := by
        simp [paperCommutator]
      rw [heq]
      exact (QuotientGroup.eq_one_iff _).mpr
        (Subgroup.subset_closure ⟨a, ha, b, hb, rfl⟩)
    have hcomm (a b : G) : Commute (f a) (f b) := by
      have ha : a ∈ Subgroup.closure X := by rw [hgen]; trivial
      have hb : b ∈ Subgroup.closure X := by rw [hgen]; trivial
      induction ha using Subgroup.closure_induction with
      | mem a ha =>
          induction hb using Subgroup.closure_induction with
          | mem b hb => exact hbase a ha b hb
          | one => simp
          | mul b c _ _ ihb ihc => simpa only [map_mul] using ihb.mul_right ihc
          | inv b _ ih => simpa only [map_inv] using (Commute.inv_right ih)
      | one => simp
      | mul a c _ _ iha ihc => simpa only [map_mul] using iha.mul_left ihc
      | inv a _ ih => simpa only [map_inv] using (Commute.inv_left ih)
    apply Subgroup.commutator_le.mpr
    intro a _ b _
    apply (QuotientGroup.eq_one_iff _).mp
    change f ⁅a,b⁆ = 1
    rw [map_commutatorElement]
    exact (hcomm a b).commutator_eq
  · apply (Subgroup.closure_le _).mpr
    rintro _ ⟨a, _, b, _, rfl⟩
    change paperCommutator a b ∈ (⁅(⊤ : Subgroup G), ⊤⁆ : Subgroup G)
    simpa only [paperCommutator, commutatorElement_def, inv_inv] using
      Subgroup.commutator_mem_commutator (H₁ := (⊤ : Subgroup G))
        (H₂ := ⊤) (g₁ := a⁻¹) (g₂ := b⁻¹) (by trivial) (by trivial)

theorem image_commutatorImage (f : G →* H) (X Y : Set G) :
    f '' commutatorImage X Y = commutatorImage (f '' X) (f '' Y) := by
  ext z
  constructor
  · rintro ⟨_, ⟨x, hx, y, hy, rfl⟩, rfl⟩
    exact ⟨f x, ⟨x, hx, rfl⟩, f y, ⟨y, hy, rfl⟩, by simp [paperCommutator]⟩
  · rintro ⟨_, ⟨x, hx, rfl⟩, _, ⟨y, hy, rfl⟩, rfl⟩
    exact ⟨paperCommutator x y, ⟨x, hx, y, hy, rfl⟩, by simp [paperCommutator]⟩

/-- The same generation identity inside an arbitrary generated subgroup. -/
theorem commutator_closure_eq_closure_commutatorImage [Finite G] {X : Set G}
    (hX : IsCommutatorClosed X) :
    ⁅Subgroup.closure X, Subgroup.closure X⁆ =
      Subgroup.closure (commutatorImage X X) := by
  let K := Subgroup.closure X
  let Z : Set K := {x | (x : G) ∈ X}
  have himage : K.subtype '' Z = X := by
    ext x
    exact ⟨fun ⟨y, hy, heq⟩ => heq ▸ hy,
      fun hx => ⟨⟨x, Subgroup.subset_closure hx⟩, hx, rfl⟩⟩
  have hgen : Subgroup.closure Z = ⊤ := by
    apply Subgroup.map_injective K.subtype_injective
    rw [MonoidHom.map_closure, himage, ← MonoidHom.range_eq_map, K.range_subtype]
  have hZ : IsCommutatorClosed Z := by
    intro x hx y hy
    exact hX x hx y hy
  calc
    ⁅Subgroup.closure X, Subgroup.closure X⁆ = (commutator K).map K.subtype := by
      rw [_root_.commutator_def, Subgroup.map_commutator,
        ← MonoidHom.range_eq_map, K.range_subtype]
    _ = (Subgroup.closure (commutatorImage Z Z)).map K.subtype := by
      rw [commutator_eq_closure_commutatorImage hZ hgen]
    _ = Subgroup.closure (commutatorImage X X) := by
      rw [MonoidHom.map_closure, image_commutatorImage, himage]

/-- Derived evaluations with every leaf input in a specified generating set. -/
def derivedValuesOn (X : Set G) : ℕ → Set G
  | 0 => X
  | k + 1 => commutatorImage (derivedValuesOn X k) (derivedValuesOn X k)

theorem derivedValuesOn_commutatorClosed {X : Set G} (hX : IsCommutatorClosed X)
    (k : ℕ) : IsCommutatorClosed (derivedValuesOn X k) := by
  induction k with
  | zero => exact hX
  | succ k ih => exact ih.commutatorImage

theorem derivedValuesOn_subset {X : Set G} (hX : IsCommutatorClosed X) (k : ℕ) :
    derivedValuesOn X k ⊆ X := by
  induction k with
  | zero => exact Set.Subset.rfl
  | succ k ih => exact (commutatorImage_subset (derivedValuesOn_commutatorClosed hX k)).trans ih

theorem derivedValuesOn_subset_values (X : Set G) (k : ℕ) :
    derivedValuesOn X k ⊆ (OuterWord.derivedWord k).values G := by
  induction k with
  | zero => simp
  | succ k ih =>
      rintro _ ⟨x, hx, y, hy, rfl⟩
      exact (OuterWord.mem_values_bracket _ _ _).mpr ⟨x, ih hx, y, ih hy, rfl⟩

/-- Each derived subgroup is generated by the corresponding derived
commutators in a commutator-closed generating set. -/
theorem closure_derivedValuesOn [Finite G] {X : Set G}
    (hX : IsCommutatorClosed X) (hgen : Subgroup.closure X = ⊤) (k : ℕ) :
    Subgroup.closure (derivedValuesOn X k) = derivedSeries G k := by
  induction k with
  | zero => exact hgen
  | succ k ih =>
      rw [derivedValuesOn, ← commutator_closure_eq_closure_commutatorImage
        (derivedValuesOn_commutatorClosed hX k), ih, derivedSeries_succ]

namespace OuterWord

/-- The tree definition of the derived word gives mathlib's derived series. -/
theorem verbalSubgroup_derivedWord (k : ℕ) :
    (derivedWord k).verbalSubgroup G = derivedSeries G k := by
  induction k with
  | zero => simp
  | succ k ih => rw [derivedWord_succ, verbalSubgroup_bracket, ih, derivedSeries_succ]

/-- Single values of every derived word are commutator-closed. -/
theorem derivedWord_values_commutatorClosed (k : ℕ) :
    IsCommutatorClosed ((derivedWord k).values G) := by
  intro x hx y hy
  have hm : paperCommutator x y ∈ (derivedWord (k + 1)).values G :=
    (mem_values_bracket _ _ _).mpr ⟨x, hx, y, hy, rfl⟩
  exact (derivedWord k).derivedWord_values_subset (k + 1) (by simp) hm

end OuterWord
end Kourovka2135
