import Kourovka2135.NormalCoprimeCocycleVanishing
import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic

/-! Degree-one vanishing for a group generated by a normal coprime-order
subgroup and one element, when the whole group has no fixed vectors.
The generator acts on the normal-subgroup fixed space; its difference from
identity is injective, hence surjective. No semisimplicity of the cyclic
quotient, or invertibility of its order, is required. -/

set_option autoImplicit false
noncomputable section
universe u

namespace Kourovka2135.NormalCyclicCocycleVanishing
open groupCohomology CocycleGeneratorBounds CocycleGeneratorEvaluation

variable {K G V : Type u} [Field K] [Group G]
variable [AddCommGroup V] [Module K V]
variable (ρ : Representation K G V) (H : Subgroup G) (t : G)

theorem cocycle_eq_zero_of_generators
    (hgen : H ⊔ Subgroup.zpowers t = ⊤)
    (z : cocycles₁ (Rep.of ρ)) (hH : ∀ h : H, z h = 0) (ht : z t = 0) :
    z = 0 := by
  have hle : H ⊔ Subgroup.zpowers t ≤ zeroSubgroup ρ z := by
    apply sup_le
    · intro h hh
      exact hH ⟨h, hh⟩
    · exact Subgroup.zpowers_le.mpr ht
  rw [hgen] at hle
  apply cocycles₁_ext
  intro g
  exact hle (show g ∈ (⊤ : Subgroup G) from trivial)

theorem normalized_value_invariant [H.Normal]
    (z : cocycles₁ (Rep.of ρ)) (hH : ∀ h : H, z h = 0) (g : G) :
    z g ∈ Representation.invariants (ρ.comp H.subtype) := by
  intro h
  have hm : g⁻¹ * (h : G) * g ∈ H := by
    simpa only [inv_inv] using
      (inferInstance : H.Normal).conj_mem (h : G) h.property g⁻¹
  have he : g * (g⁻¹ * (h : G) * g) = (h : G) * g := by group
  have ha := (mem_cocycles₁_iff z).mp z.property g (g⁻¹ * (h : G) * g)
  have hb := (mem_cocycles₁_iff z).mp z.property (h : G) g
  rw [he, hH ⟨_, hm⟩, map_zero, zero_add] at ha
  rw [hH h, add_zero] at hb
  exact hb.symm.trans ha

theorem fixedSpace_difference_injective [H.Normal]
    (hgen : H ⊔ Subgroup.zpowers t = ⊤)
    (hfixed : ρ.invariants = ⊥) :
    Function.Injective ((Representation.toInvariants ρ H) t -
      (LinearMap.id : Representation.invariants (ρ.comp H.subtype) →ₗ[K]
        Representation.invariants (ρ.comp H.subtype))) := by
  apply LinearMap.ker_eq_bot.mp
  apply LinearMap.ker_eq_bot'.mpr
  intro v hv
  have ht : ρ t (v : V) = v := by
    have he : (Representation.toInvariants ρ H t) v - v = 0 := hv
    exact congrArg Subtype.val (sub_eq_zero.mp he)
  have hp : principal ρ (v : V) = 0 := by
    apply cocycle_eq_zero_of_generators ρ H t hgen
    · intro h
      change ρ h (v : V) - (v : V) = 0
      exact sub_eq_zero.mpr (v.property h)
    · change ρ t (v : V) - (v : V) = 0
      exact sub_eq_zero.mpr ht
  have hi : (v : V) ∈ ρ.invariants := by
    rw [← principal_ker]
    exact hp
  rw [hfixed] at hi
  exact Subtype.ext hi

/-- A normal coprime subgroup and a cyclic quotient suffice; the quotient
may have order divisible by the coefficient characteristic. -/
theorem subsingleton_H1 [H.Normal] [Fintype H] [FiniteDimensional K V]
    (hcard : (Fintype.card H : K) ≠ 0)
    (hgen : H ⊔ Subgroup.zpowers t = ⊤)
    (hfixed : ρ.invariants = ⊥) :
    Subsingleton (groupCohomology (Rep.of ρ) 1) := by
  have hsurj := LinearMap.surjective_of_injective
    (fixedSpace_difference_injective ρ H t hgen hfixed)
  have hzero : ∀ x : groupCohomology (Rep.of ρ) 1, x = 0 := by
    intro x
    induction x using H1_induction_on with
    | h z =>
      let zr : cocycles₁ (Rep.of (ρ.comp H.subtype)) :=
        ⟨fun h => z h, (mem_cocycles₁_iff _).mpr
          (fun a b => (mem_cocycles₁_iff z).mp z.property a b)⟩
      obtain ⟨v, hv⟩ := NormalCoprimeCocycleVanishing.exists_principal_of_card_ne_zero
        (ρ.comp H.subtype) hcard zr
      let zn := z - principal ρ v
      have hH : ∀ h : H, zn h = 0 := by
        intro h
        change z h - (ρ h v - v) = 0
        exact sub_eq_zero.mpr (hv h)
      obtain ⟨w, hw⟩ := hsurj ⟨zn t, normalized_value_invariant ρ H zn hH t⟩
      have hw' : ρ t (w : V) - (w : V) = zn t := congrArg Subtype.val hw
      have hn : zn = principal ρ (w : V) := by
        apply sub_eq_zero.mp
        apply cocycle_eq_zero_of_generators ρ H t hgen
        · intro h
          change zn h - (ρ h (w : V) - (w : V)) = 0
          have hwh : ρ (h : G) (w : V) = (w : V) := w.property h
          rw [hH h, hwh, sub_self, sub_self]
        · change zn t - (ρ t (w : V) - (w : V)) = 0
          exact sub_eq_zero.mpr hw'.symm
      have he : z = principal ρ (v + (w : V)) := by
        calc
          z = zn + principal ρ v := (sub_add_cancel z (principal ρ v)).symm
          _ = principal ρ (w : V) + principal ρ v := by rw [hn]
          _ = principal ρ (v + (w : V)) := by rw [map_add, add_comm]
      apply (H1π_eq_zero_iff (A := Rep.of ρ) z).mpr
      exact ⟨v + (w : V), congrArg Subtype.val he.symm⟩
  exact ⟨fun x y => (hzero x).trans (hzero y).symm⟩

end Kourovka2135.NormalCyclicCocycleVanishing
