import Kourovka2135.OddPSLTwoPermutationHeart
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic

/-! The actual Borel subgroup in the projective action of PSL2.

The stabilizer of infinity is generated by its root subgroup and diagonal
torus. The root subgroup is normal, and over a finite field one actual torus
element suffices. These are geometric statements over the parameter field;
no coefficient-field embedding or representation classification is used.
-/

set_option autoImplicit false
noncomputable section

namespace Kourovka2135.OddPSLTwoBorel

open OddPSLTwoProjectiveChart
open OddPSLTwoPermutationHeart
open scoped MatrixGroups LinearAlgebra.Projectivization Matrix

variable (F : Type*) [Field F]

def borel : Subgroup (Q F) := MulAction.stabilizer (Q F) (none : Option F)

def unipotentInBorel : Subgroup (borel F) := (unipotent F).subgroupOf (borel F)

def unipotentEquiv : unipotentInBorel F ≃* unipotent F :=
  Subgroup.subgroupOfEquivOfLe (unipotent_le_stabilizer F)

theorem card_unipotentInBorel : Nat.card (unipotentInBorel F) = Nat.card F :=
  (Nat.card_congr (unipotentEquiv F).toEquiv).trans (card_unipotent F)

/-- The genuine root homomorphism, with codomain restricted to the Borel. -/
def rootHom : Multiplicative F →* borel F where
  toFun t := ⟨unipotentHom F t, unipotent_le_stabilizer F ⟨t, rfl⟩⟩
  map_one' := Subtype.ext (map_one (unipotentHom F))
  map_mul' a b := Subtype.ext (map_mul (unipotentHom F) a b)

@[simp] theorem rootHom_coe (t : F) :
    (rootHom F (Multiplicative.ofAdd t) : Q F) = quotient F (SLTwo.uni t) := rfl

theorem rootHom_mem (t : Multiplicative F) : rootHom F t ∈ unipotentInBorel F :=
  ⟨t, rfl⟩

/-- The actual diagonal torus homomorphism inside the stabilizer. -/
def torusHom : Fˣ →* borel F where
  toFun r := ⟨quotient F (SLTwo.tor r), tor_smul_none F r⟩
  map_one' := by
    apply Subtype.ext
    change quotient F (SLTwo.torHom F 1) = 1
    rw [map_one, map_one]
  map_mul' r s := by
    apply Subtype.ext
    change quotient F (SLTwo.torHom F (r * s)) =
      quotient F (SLTwo.torHom F r) * quotient F (SLTwo.torHom F s)
    rw [map_mul, map_mul]

@[simp] theorem torusHom_coe (r : Fˣ) :
    (torusHom F r : Q F) = quotient F (SLTwo.tor r) := rfl

/-- Projective fixation of infinity forces the lower-left matrix entry to vanish. -/
theorem lowerLeft_eq_zero (g : SLTwo.SL2 F)
    (hg : quotient F g • (none : Option F) = none) : g.val 1 0 = 0 := by
  have he := congrArg (point F) hg
  rw [point_smul] at he
  change Projectivization.mk F (g.val.mulVec (representative F none)) _ =
    Projectivization.mk F (representative F none) _ at he
  obtain ⟨a, ha⟩ := (Projectivization.mk_eq_mk_iff' F _ _ _ _).mp he
  simpa [representative, Matrix.mulVec, dotProduct, Fin.sum_univ_two] using
    (congrFun ha 1).symm

/-- Every determinant-one upper triangular matrix has an actual root-torus factorization. -/
theorem exists_uni_tor_of_lowerLeft_zero (g : SLTwo.SL2 F) (h10 : g.val 1 0 = 0) :
    ∃ t : F, ∃ r : Fˣ, g = SLTwo.uni t * SLTwo.tor r := by
  have hd := g.property
  change g.val.det = 1 at hd
  rw [Matrix.det_fin_two, h10, mul_zero, sub_zero] at hd
  have ha : g.val 0 0 ≠ 0 := by
    intro hz
    rw [hz, zero_mul] at hd
    exact zero_ne_one hd
  have h11 : g.val 1 1 = (g.val 0 0)⁻¹ := by
    calc
      g.val 1 1 = (g.val 0 0)⁻¹ * (g.val 0 0 * g.val 1 1) := by
        rw [← mul_assoc, inv_mul_cancel₀ ha, one_mul]
      _ = (g.val 0 0)⁻¹ := by rw [hd, mul_one]
  refine ⟨g.val 0 1 * g.val 0 0, Units.mk0 (g.val 0 0) ha, ?_⟩
  apply Subtype.ext
  change g.val = (SLTwo.uni (g.val 0 1 * g.val 0 0)).val *
    (SLTwo.tor (Units.mk0 (g.val 0 0) ha)).val
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [SLTwo.uni, SLTwo.tor, Matrix.mul_apply, Fin.sum_univ_two,
      h10, h11, ha]

/-- Every actual projective Borel element is a root element times a torus element. -/
theorem exists_root_mul_torus (b : borel F) :
    ∃ t : F, ∃ r : Fˣ, b = rootHom F (Multiplicative.ofAdd t) * torusHom F r := by
  have hsurj : Function.Surjective (quotient F) :=
    QuotientGroup.mk'_surjective (Subgroup.center (SLTwo.SL2 F))
  obtain ⟨g, hg⟩ := hsurj b.val
  have hfixed : quotient F g • (none : Option F) = none := by
    rw [hg]
    exact b.property
  obtain ⟨t, r, hgr⟩ := exists_uni_tor_of_lowerLeft_zero F g (lowerLeft_eq_zero F g hfixed)
  refine ⟨t, r, Subtype.ext ?_⟩
  change b.val = quotient F (SLTwo.uni t) * quotient F (SLTwo.tor r)
  rw [← hg, hgr, map_mul]

/-- Conjugation in an upper triangular matrix acts on the root parameter by a square. -/
theorem uni_tor_conj_uni (t : F) (r : Fˣ) (s : F) :
    (SLTwo.uni t * SLTwo.tor r) * SLTwo.uni s * (SLTwo.uni t * SLTwo.tor r)⁻¹ =
      SLTwo.uni ((r : F) ^ 2 * s) := by
  have hc : Commute (SLTwo.uni t) (SLTwo.uni ((r : F) ^ 2 * s)) :=
    by
      have he := congrArg (SLTwo.uniHom F)
        (mul_comm (Multiplicative.ofAdd t) (Multiplicative.ofAdd ((r : F) ^ 2 * s)))
      rw [map_mul (SLTwo.uniHom F), map_mul (SLTwo.uniHom F)] at he
      exact he
  calc
    _ = SLTwo.uni t * (SLTwo.tor r * SLTwo.uni s * (SLTwo.tor r)⁻¹) *
        (SLTwo.uni t)⁻¹ := by group
    _ = SLTwo.uni t * SLTwo.uni ((r : F) ^ 2 * s) * (SLTwo.uni t)⁻¹ := by
      rw [SLTwo.tor_conj_uni]
    _ = SLTwo.uni ((r : F) ^ 2 * s) := by
      rw [hc.eq, mul_assoc, mul_inv_cancel, mul_one]

instance unipotentInBorel_normal : (unipotentInBorel F).Normal where
  conj_mem n hn b := by
    change (b : Q F) * (n : Q F) * (b : Q F)⁻¹ ∈ unipotent F
    change (n : Q F) ∈ unipotent F at hn
    obtain ⟨s, hs⟩ := hn
    change quotient F (SLTwo.uni s.toAdd) = (n : Q F) at hs
    obtain ⟨t, r, hb⟩ := exists_root_mul_torus F b
    have hb' : (b : Q F) = quotient F (SLTwo.uni t) * quotient F (SLTwo.tor r) :=
      congrArg Subtype.val hb
    refine ⟨Multiplicative.ofAdd ((r : F) ^ 2 * s.toAdd), ?_⟩
    change quotient F (SLTwo.uni ((r : F) ^ 2 * s.toAdd)) =
      (b : Q F) * (n : Q F) * (b : Q F)⁻¹
    rw [hb', ← hs]
    simpa only [map_mul, map_inv] using
      (congrArg (quotient F) (uni_tor_conj_uni F t r s.toAdd)).symm

theorem unipotent_sup_torus :
    unipotentInBorel F ⊔ (torusHom F).range = ⊤ := by
  apply top_unique
  intro b _
  obtain ⟨t, r, rfl⟩ := exists_root_mul_torus F b
  exact (unipotentInBorel F ⊔ (torusHom F).range).mul_mem
    ((show unipotentInBorel F ≤ unipotentInBorel F ⊔ (torusHom F).range from le_sup_left)
      (rootHom_mem F (Multiplicative.ofAdd t)))
    ((show (torusHom F).range ≤ unipotentInBorel F ⊔ (torusHom F).range from le_sup_right)
      ⟨r, rfl⟩)

instance torus_isCyclic [Finite F] : IsCyclic (torusHom F).range :=
  isCyclic_of_surjective (torusHom F).rangeRestrict (torusHom F).rangeRestrict_surjective

/-- One actual torus element generates the Borel together with its normal root subgroup. -/
theorem exists_torus_generator [Finite F] :
    ∃ r : Fˣ, unipotentInBorel F ⊔ Subgroup.zpowers (torusHom F r) = ⊤ := by
  obtain ⟨r, hr⟩ := IsCyclic.exists_generator (α := Fˣ)
  refine ⟨r, top_unique ?_⟩
  rw [← unipotent_sup_torus F]
  apply sup_le_sup_left
  rintro _ ⟨s, rfl⟩
  obtain ⟨n, hn⟩ := hr s
  change r ^ n = s at hn
  refine ⟨n, ?_⟩
  change (torusHom F r) ^ n = torusHom F s
  rw [← map_zpow, hn]

end Kourovka2135.OddPSLTwoBorel
