/-
The two Weyl matrix calculations are adapted from Qiuzhen-CFSG/CFSG,
commit 96b2a02085dc678f3e0a97b334c31ada599c55fd, Apache-2.0:
Glauberman/DicksonSplitTorusMatrices.lean, standardSplitWeylSL_inv and
standardSplitWeylSL_conj. See Vendor/CFSG/LICENSE.
No declaration from that repository's classification import closure is used.
-/
import Kourovka2135.OddPSLTwoBorel
import Kourovka2135.OddPSLTwoTorusMovingRank
import Mathlib.GroupTheory.GroupAction.SubMulAction.Combination
import Mathlib.GroupTheory.Index

/-! An actual odd-index split dihedral subgroup of odd PSL2.

The subgroup is the stabilizer of the unordered pair {infinity,0}. Its
elements are diagonal or Weyl times diagonal, hence it is generated by a
primitive diagonal and the actual Weyl reflection. Its index is obtained
from the actual action on two-element subsets, not from an assumed order
formula or subgroup classification.
-/

set_option autoImplicit false
noncomputable section

namespace Kourovka2135.OddPSLTwoSplitDihedral

open OddPSLTwoProjectiveChart OddPSLTwoBorel OddPSLTwoTorusMovingRank
open scoped Pointwise Matrix LinearAlgebra.Projectivization

variable (F : Type*) [Field F]

def weylSL : SLTwo.SL2 F := ⟨!![0, -1; 1, 0], by simp [Matrix.det_fin_two_of]⟩

theorem weylSL_inv :
    (weylSL F)⁻¹ = (⟨!![0, 1; -1, 0], by simp [Matrix.det_fin_two_of]⟩ : SLTwo.SL2 F) := by
  apply Subtype.ext
  rw [Matrix.SpecialLinearGroup.coe_inv]
  simp [weylSL, Matrix.adjugate_fin_two]

theorem weylSL_conj (r : Fˣ) :
    weylSL F * SLTwo.tor r * (weylSL F)⁻¹ = SLTwo.tor r⁻¹ := by
  rw [weylSL_inv]
  apply Subtype.ext
  change ((weylSL F).val * (SLTwo.tor r).val) *
    (!![0, 1; -1, 0] : Matrix (Fin 2) (Fin 2) F) = (SLTwo.tor r⁻¹).val
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [weylSL, SLTwo.tor, Matrix.mul_apply, Fin.sum_univ_two]

theorem weylSL_sq_center : weylSL F * weylSL F ∈ Subgroup.center (SLTwo.SL2 F) := by
  rw [Matrix.SpecialLinearGroup.mem_center_iff]
  refine ⟨-1, by simp, ?_⟩
  change Matrix.scalar (Fin 2) (-1 : F) = (weylSL F).val * (weylSL F).val
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [weylSL, Matrix.mul_apply, Fin.sum_univ_two]

def weyl : Q F := quotient F (weylSL F)

theorem weyl_sq : weyl F * weyl F = 1 := by
  change quotient F (weylSL F) * quotient F (weylSL F) = 1
  rw [← map_mul]
  exact (QuotientGroup.eq_one_iff _).mpr (weylSL_sq_center F)

theorem weyl_inv : (weyl F)⁻¹ = weyl F :=
  (eq_inv_of_mul_eq_one_left (weyl_sq F)).symm

theorem weyl_conj (r : Fˣ) :
    weyl F * projectiveTorusHom F r * (weyl F)⁻¹ = (projectiveTorusHom F r)⁻¹ := by
  change quotient F (weylSL F) * quotient F (SLTwo.tor r) *
    (quotient F (weylSL F))⁻¹ = (projectiveTorusHom F r)⁻¹
  rw [← map_inv, ← map_mul, ← map_mul, weylSL_conj]
  exact (projectiveTorusHom F).map_inv r

@[simp] theorem weyl_smul_none : weyl F • (none : Option F) = some 0 := by
  apply point_injective F
  rw [point_smul]
  change Projectivization.mk F ((weylSL F).val.mulVec (representative F none)) _ =
    Projectivization.mk F (representative F (some 0)) _
  apply (Projectivization.mk_eq_mk_iff' F _ _ _ _).mpr
  refine ⟨1, ?_⟩
  ext i
  fin_cases i <;> simp [weylSL, representative, Matrix.mulVec, dotProduct, Fin.sum_univ_two]

@[simp] theorem weyl_smul_zero : weyl F • (some (0 : F) : Option F) = none := by
  apply point_injective F
  rw [point_smul]
  change Projectivization.mk F ((weylSL F).val.mulVec (representative F (some 0))) _ =
    Projectivization.mk F (representative F none) _
  apply (Projectivization.mk_eq_mk_iff' F _ _ _ _).mpr
  refine ⟨-1, ?_⟩
  ext i
  fin_cases i <;> simp [weylSL, representative, Matrix.mulVec, dotProduct, Fin.sum_univ_two]

def subgroup : Subgroup (Q F) :=
  MulAction.stabilizer (Q F) ({none, some 0} : Set (Option F))

theorem mem_subgroup_iff (g : Q F) : g ∈ subgroup F ↔
    (g • (none : Option F) = none ∧ g • (some 0 : Option F) = some 0) ∨
    (g • (none : Option F) = some 0 ∧ g • (some 0 : Option F) = none) := by
  change g • ({none, some 0} : Set (Option F)) = {none, some 0} ↔ _
  rw [Set.smul_set_insert, Set.smul_set_singleton, Set.pair_eq_pair_iff]

theorem torus_mem (r : Fˣ) : projectiveTorusHom F r ∈ subgroup F := by
  apply (mem_subgroup_iff F _).mpr
  exact Or.inl ⟨tor_smul_none F r, by simp⟩

theorem weyl_mem : weyl F ∈ subgroup F :=
  (mem_subgroup_iff F _).mpr (Or.inr ⟨weyl_smul_none F, weyl_smul_zero F⟩)

/-- Fixing both points is exactly being an actual diagonal image. -/
theorem exists_torus_of_fixed (g : Q F)
    (hinfty : g • (none : Option F) = none) (h0 : g • (some 0 : Option F) = some 0) :
    ∃ r : Fˣ, g = projectiveTorusHom F r := by
  obtain ⟨t, r, he⟩ := exists_root_mul_torus F (⟨g, hinfty⟩ : borel F)
  have hg : g = quotient F (SLTwo.uni t) * projectiveTorusHom F r :=
    congrArg Subtype.val he
  have ht : t = 0 := by
    have hs : (some t : Option F) = some 0 := by
      simpa only [hg, mul_smul, projectiveTorusHom_apply, tor_smul_some,
        mul_zero, uni_smul_some, zero_add] using h0
    exact Option.some.inj hs
  refine ⟨r, ?_⟩
  rw [hg, ht, show SLTwo.uni (0 : F) = 1 from (SLTwo.uniHom F).map_one,
    map_one, one_mul]

theorem exists_torus_or_weyl_torus (g : subgroup F) :
    ∃ r : Fˣ, (g : Q F) = projectiveTorusHom F r ∨
      (g : Q F) = weyl F * projectiveTorusHom F r := by
  rcases (mem_subgroup_iff F g).mp g.property with hf | hs
  · obtain ⟨r, hr⟩ := exists_torus_of_fixed F g hf.1 hf.2
    exact ⟨r, Or.inl hr⟩
  · obtain ⟨r, hr⟩ := exists_torus_of_fixed F (weyl F * g)
      (by rw [mul_smul, hs.1, weyl_smul_zero])
      (by rw [mul_smul, hs.2, weyl_smul_none])
    refine ⟨r, Or.inr ?_⟩
    calc
      (g : Q F) = (weyl F)⁻¹ * (weyl F * g) := by group
      _ = weyl F * projectiveTorusHom F r := by rw [hr, weyl_inv]

theorem subgroup_eq_sup : subgroup F =
    (projectiveTorusHom F).range ⊔ Subgroup.zpowers (weyl F) := by
  apply le_antisymm
  · intro g hg
    obtain ⟨r, hr | hr⟩ := exists_torus_or_weyl_torus F ⟨g, hg⟩
    · change g = projectiveTorusHom F r at hr
      rw [hr]
      exact (show (projectiveTorusHom F).range ≤
        (projectiveTorusHom F).range ⊔ Subgroup.zpowers (weyl F) from le_sup_left) ⟨r, rfl⟩
    · change g = weyl F * projectiveTorusHom F r at hr
      rw [hr]
      exact Subgroup.mul_mem _
        ((show Subgroup.zpowers (weyl F) ≤ (projectiveTorusHom F).range ⊔
          Subgroup.zpowers (weyl F) from le_sup_right) (Subgroup.mem_zpowers _))
        ((show (projectiveTorusHom F).range ≤ (projectiveTorusHom F).range ⊔
          Subgroup.zpowers (weyl F) from le_sup_left) ⟨r, rfl⟩)
  · apply sup_le
    · rintro _ ⟨r, rfl⟩
      exact torus_mem F r
    · exact Subgroup.zpowers_le.mpr (weyl_mem F)

/-- Root translations normalize an arbitrary pair of distinct actual points. -/
theorem exists_pair_to_base {x y : Option F} (hxy : x ≠ y) :
    ∃ g : Q F, g • x = none ∧ g • y = some 0 := by
  obtain ⟨g, hg⟩ := MulAction.exists_smul_eq (Q F) x (none : Option F)
  have hne : g • y ≠ (none : Option F) := fun he =>
    hxy (MulAction.injective g (hg.trans he.symm))
  cases he : g • y with
  | none => exact (hne he).elim
  | some t =>
      refine ⟨quotient F (SLTwo.uni (-t)) * g, ?_, ?_⟩
      · rw [mul_smul, hg, uni_smul_none]
      · rw [mul_smul, he, uni_smul_some, add_neg_cancel]

theorem isTwoPretransitive : MulAction.IsMultiplyPretransitive (Q F) (Option F) 2 := by
  apply MulAction.is_two_pretransitive_iff.mpr
  intro a b c d hab hcd
  obtain ⟨g, hga, hgb⟩ := exists_pair_to_base F hab
  obtain ⟨h, hhc, hhd⟩ := exists_pair_to_base F hcd
  refine ⟨h⁻¹ * g, ?_, ?_⟩
  · rw [mul_smul, hga, ← hhc, inv_smul_smul]
  · rw [mul_smul, hgb, ← hhd, inv_smul_smul]

theorem subgroup_index [Finite F] :
    (subgroup F).index = ((Nat.card F + 1) * Nat.card F) / 2 := by
  classical
  let : Fintype F := Fintype.ofFinite F
  let pair : Set.powersetCard (Option F) 2 := ⟨{none, some 0}, by simp⟩
  let : MulAction.IsPretransitive (Q F) (Set.powersetCard (Option F) 2) :=
    Set.powersetCard.isPretransitive_of_isMultiplyPretransitive (Q F) (isTwoPretransitive F)
  have hs : MulAction.stabilizer (Q F) pair = subgroup F := by
    rw [Set.powersetCard.stabilizer_coe]
    change MulAction.stabilizer (Q F) (↑({none, some 0} : Finset (Option F)) : Set (Option F)) = _
    rw [Finset.coe_pair]
    rfl
  rw [← hs, MulAction.index_stabilizer_of_transitive, Set.powersetCard.card,
    Nat.card_eq_fintype_card, Fintype.card_option, Nat.choose_two_right]
  simp only [Nat.add_sub_cancel, Nat.card_eq_fintype_card]

theorem subgroup_index_odd [Finite F] (hmod : Nat.card F % 4 = 1) : Odd (subgroup F).index := by
  have hq : Odd (Nat.card F) := ⟨2 * (Nat.card F / 4), by omega⟩
  have hhalf : Odd ((Nat.card F + 1) / 2) := ⟨Nat.card F / 4, by omega⟩
  have hdiv : 2 ∣ Nat.card F + 1 := by omega
  rw [subgroup_index, mul_comm (Nat.card F + 1), Nat.mul_div_assoc _ hdiv]
  exact hq.mul hhalf

/-- The explicit diagonal generator and Weyl reflection generate the subgroup. -/
theorem exists_generators [Finite F] :
    ∃ r : Fˣ, Subgroup.closure ({projectiveTorusHom F r, weyl F} : Set (Q F)) = subgroup F := by
  classical
  obtain ⟨r, hr⟩ := IsCyclic.exists_generator (α := Fˣ)
  have hT : (projectiveTorusHom F).range = Subgroup.zpowers (projectiveTorusHom F r) := by
    apply le_antisymm
    · rintro _ ⟨s, rfl⟩
      obtain ⟨n, hn⟩ := hr s
      rw [← hn, map_zpow]
      exact Subgroup.zpow_mem _ (Subgroup.mem_zpowers _) n
    · exact Subgroup.zpowers_le.mpr ⟨r, rfl⟩
  refine ⟨r, ?_⟩
  rw [subgroup_eq_sup, hT, Subgroup.zpowers_eq_closure, Subgroup.zpowers_eq_closure,
    ← Subgroup.closure_union]
  congr 1

/-- The same generation and inversion statements on the actual subgroup type. -/
theorem exists_subgroup_generators [Finite F] :
    ∃ a b : subgroup F, Subgroup.closure ({a, b} : Set (subgroup F)) = ⊤ ∧
      b * a * b⁻¹ = a⁻¹ := by
  classical
  obtain ⟨r, hr⟩ := IsCyclic.exists_generator (α := Fˣ)
  let a : subgroup F := ⟨projectiveTorusHom F r, torus_mem F r⟩
  let b : subgroup F := ⟨weyl F, weyl_mem F⟩
  refine ⟨a, b, ?_, Subtype.ext (weyl_conj F r)⟩
  apply top_le_iff.mp
  intro g _
  obtain ⟨s, hs | hs⟩ := exists_torus_or_weyl_torus F g
  · obtain ⟨n, hn⟩ := hr s
    change r ^ n = s at hn
    have he : g = a ^ n := by
      apply Subtype.ext
      change (g : Q F) = (projectiveTorusHom F r) ^ n
      rw [← map_zpow, hn]
      exact hs
    rw [he]
    exact Subgroup.zpow_mem _ (Subgroup.subset_closure (by simp)) n
  · obtain ⟨n, hn⟩ := hr s
    change r ^ n = s at hn
    have he : g = b * a ^ n := by
      apply Subtype.ext
      change (g : Q F) = weyl F * (projectiveTorusHom F r) ^ n
      rw [← map_zpow, hn]
      exact hs
    rw [he]
    exact Subgroup.mul_mem _ (Subgroup.subset_closure (by simp))
      (Subgroup.zpow_mem _ (Subgroup.subset_closure (by simp)) n)

end Kourovka2135.OddPSLTwoSplitDihedral
