import Mathlib.Algebra.Group.Subgroup.Basic

/-!
# Outer commutator words and their single values

An input has a separate component for each leaf of the word tree. In particular,
the variables used by the two children of a bracket are disjoint. The commutator
convention in this file is `a⁻¹ * b⁻¹ * a * b`.
-/

set_option autoImplicit false

universe u v

namespace Kourovka2135

/-- A multilinear outer commutator word, represented by its binary tree. -/
inductive OuterWord where
  | leaf : OuterWord
  | bracket (left right : OuterWord) : OuterWord
  deriving DecidableEq

namespace OuterWord

/-- The largest number of brackets along a root-to-leaf path. -/
def height (w : OuterWord) : ℕ :=
  match w with
  | leaf => 0
  | bracket left right => max left.height right.height + 1

/-- The balanced derived word: `δ₀ = x` and `δₖ₊₁ = [δₖ, δₖ]`, with
independent inputs in its two copies. -/
def derivedWord : ℕ → OuterWord
  | 0 => leaf
  | k + 1 => bracket (derivedWord k) (derivedWord k)

@[simp]
theorem height_leaf : leaf.height = 0 := rfl

@[simp]
theorem height_bracket (left right : OuterWord) :
    (bracket left right).height = max left.height right.height + 1 := rfl

@[simp]
theorem derivedWord_zero : derivedWord 0 = leaf := rfl

@[simp]
theorem derivedWord_succ (k : ℕ) :
    derivedWord (k + 1) = bracket (derivedWord k) (derivedWord k) := rfl

@[simp]
theorem height_derivedWord (k : ℕ) : (derivedWord k).height = k := by
  induction k with
  | zero => rfl
  | succ k ih => simp only [derivedWord_succ, height_bracket, ih, Nat.max_self]

/-- Independent inputs at all leaves of a word. -/
def Input (w : OuterWord) (G : Type u) : Type u :=
  match w with
  | leaf => G
  | bracket left right => left.Input G × right.Input G

/-- Evaluate the word using the convention `[a,b] = a⁻¹ * b⁻¹ * a * b`. -/
def eval (w : OuterWord) {G : Type u} [Group G] : w.Input G → G :=
  match w with
  | leaf => fun x => x
  | bracket left right => fun x =>
      (left.eval x.1)⁻¹ * (right.eval x.2)⁻¹ * left.eval x.1 * right.eval x.2

/-- The set of single evaluations, rather than the subgroup that they generate. -/
def values (w : OuterWord) (G : Type u) [Group G] : Set G :=
  Set.range w.eval

/-- The subgroup generated by all single evaluations. -/
def verbalSubgroup (w : OuterWord) (G : Type u) [Group G] : Subgroup G :=
  Subgroup.closure (w.values G)

variable {G : Type u} {H : Type v} [Group G] [Group H]

@[simp]
theorem eval_leaf (x : G) : leaf.eval x = x := rfl

@[simp]
theorem eval_bracket (left right : OuterWord) (x : left.Input G) (y : right.Input G) :
    (bracket left right).eval (x, y) =
      (left.eval x)⁻¹ * (right.eval y)⁻¹ * left.eval x * right.eval y := rfl

@[simp]
theorem mem_values (w : OuterWord) (x : G) :
    x ∈ w.values G ↔ ∃ a : w.Input G, w.eval a = x := Iff.rfl

@[simp]
theorem values_leaf : leaf.values G = Set.univ := by
  ext x
  exact ⟨fun _ => Set.mem_univ x, fun _ => ⟨x, rfl⟩⟩

theorem mem_values_bracket (left right : OuterWord) (t : G) :
    t ∈ (bracket left right).values G ↔
      ∃ a ∈ left.values G, ∃ b ∈ right.values G, a⁻¹ * b⁻¹ * a * b = t := by
  constructor
  · rintro ⟨⟨x, y⟩, rfl⟩
    exact ⟨left.eval x, ⟨x, rfl⟩, right.eval y, ⟨y, rfl⟩, rfl⟩
  · rintro ⟨a, ⟨x, rfl⟩, b, ⟨y, rfl⟩, h⟩
    exact ⟨(x, y), h⟩

/-- Every single value of a sufficiently deep derived word is a single value
of the given outer word, including when its two branches have unequal heights. -/
theorem derivedWord_values_subset (w : OuterWord) (k : ℕ) (h : w.height ≤ k) :
    (derivedWord k).values G ⊆ w.values G := by
  induction k generalizing w with
  | zero =>
      cases w with
      | leaf => exact Set.Subset.rfl
      | bracket left right => simp [height] at h
  | succ k ih =>
      cases w with
      | leaf =>
          intro t _
          exact ⟨t, rfl⟩
      | bracket left right =>
          have hmax : max left.height right.height ≤ k := Nat.le_of_succ_le_succ h
          have hLeft : left.height ≤ k := (Nat.le_max_left _ _).trans hmax
          have hRight : right.height ≤ k := (Nat.le_max_right _ _).trans hmax
          intro t ht
          obtain ⟨a, ha, b, hb, hab⟩ :=
            (mem_values_bracket (derivedWord k) (derivedWord k) t).1 ht
          exact (mem_values_bracket left right t).2
            ⟨a, ih left hLeft ha, b, ih right hRight hb, hab⟩

theorem mem_values_of_mem_derivedWord_values (w : OuterWord) (k : ℕ)
    (h : w.height ≤ k) {x : G} (hx : x ∈ (derivedWord k).values G) :
    x ∈ w.values G :=
  w.derivedWord_values_subset k h hx

@[simp]
theorem one_mem_values (w : OuterWord) : (1 : G) ∈ w.values G := by
  induction w with
  | leaf => exact ⟨(1 : G), rfl⟩
  | bracket left right ihLeft ihRight =>
      exact (mem_values_bracket left right 1).2 ⟨1, ihLeft, 1, ihRight, by simp⟩

theorem values_nonempty (w : OuterWord) : (w.values G).Nonempty :=
  ⟨1, w.one_mem_values⟩

theorem mem_verbalSubgroup_of_mem_values (w : OuterWord) {x : G}
    (hx : x ∈ w.values G) : x ∈ w.verbalSubgroup G :=
  Subgroup.subset_closure hx

theorem eval_mem_verbalSubgroup (w : OuterWord) (x : w.Input G) :
    w.eval x ∈ w.verbalSubgroup G :=
  w.mem_verbalSubgroup_of_mem_values ⟨x, rfl⟩

@[simp]
theorem verbalSubgroup_leaf : leaf.verbalSubgroup G = ⊤ := by
  simp [verbalSubgroup]

/-- A set whose members can each be expressed as a commutator of two members
is contained in the single-value set of every outer commutator word. -/
theorem subset_values_of_commutator_closed (B : Set G)
    (hB : ∀ t ∈ B, ∃ a ∈ B, ∃ b ∈ B, a⁻¹ * b⁻¹ * a * b = t)
    (w : OuterWord) : B ⊆ w.values G := by
  induction w with
  | leaf =>
      intro t _
      exact ⟨t, rfl⟩
  | bracket left right ihLeft ihRight =>
      intro t ht
      obtain ⟨a, ha, b, hb, hab⟩ := hB t ht
      exact (mem_values_bracket left right t).2 ⟨a, ihLeft ha, b, ihRight hb, hab⟩

/-- Apply a function independently to all leaf inputs. -/
def mapInput (w : OuterWord) {A : Type u} {B : Type v} (f : A → B) :
    w.Input A → w.Input B :=
  match w with
  | leaf => f
  | bracket left right => fun x => (left.mapInput f x.1, right.mapInput f x.2)

theorem mapInput_surjective (w : OuterWord) {A : Type u} {B : Type v}
    (f : A → B) (hf : Function.Surjective f) : Function.Surjective (w.mapInput f) := by
  induction w with
  | leaf => exact hf
  | bracket left right ihLeft ihRight =>
      rintro ⟨x, y⟩
      obtain ⟨a, ha⟩ := ihLeft x
      obtain ⟨b, hb⟩ := ihRight y
      exact ⟨(a, b), Prod.ext ha hb⟩

/-- Evaluation commutes with a group homomorphism. -/
@[simp]
theorem eval_mapInput (w : OuterWord) (f : G →* H) (x : w.Input G) :
    w.eval (w.mapInput f x) = f (w.eval x) := by
  induction w with
  | leaf => rfl
  | bracket left right ihLeft ihRight =>
      rcases x with ⟨x, y⟩
      simp only [mapInput, eval, ihLeft, ihRight, map_mul, map_inv]

theorem map_mem_values (w : OuterWord) (f : G →* H) {x : G}
    (hx : x ∈ w.values G) : f x ∈ w.values H := by
  obtain ⟨a, rfl⟩ := hx
  exact ⟨w.mapInput f a, w.eval_mapInput f a⟩

theorem image_values_subset (w : OuterWord) (f : G →* H) :
    f '' w.values G ⊆ w.values H := by
  rintro y ⟨x, hx, rfl⟩
  exact w.map_mem_values f hx

/-- Under an epimorphism, every single quotient value lifts to a single value. -/
theorem image_values_eq (w : OuterWord) (f : G →* H) (hf : Function.Surjective f) :
    f '' w.values G = w.values H := by
  apply Set.Subset.antisymm (w.image_values_subset f)
  rintro y ⟨b, rfl⟩
  obtain ⟨a, ha⟩ := w.mapInput_surjective f hf b
  refine ⟨w.eval a, ⟨a, rfl⟩, ?_⟩
  rw [← w.eval_mapInput f a, ha]

theorem map_verbalSubgroup_le (w : OuterWord) (f : G →* H) :
    (w.verbalSubgroup G).map f ≤ w.verbalSubgroup H := by
  change (Subgroup.closure (w.values G)).map f ≤ Subgroup.closure (w.values H)
  rw [MonoidHom.map_closure, Subgroup.closure_le]
  intro y hy
  exact Subgroup.subset_closure (w.image_values_subset f hy)

theorem map_verbalSubgroup_eq (w : OuterWord) (f : G →* H)
    (hf : Function.Surjective f) :
    (w.verbalSubgroup G).map f = w.verbalSubgroup H := by
  change (Subgroup.closure (w.values G)).map f = Subgroup.closure (w.values H)
  rw [MonoidHom.map_closure, w.image_values_eq f hf]

/-- Single-value sets are invariant under right conjugation. -/
theorem conj_mem_values (w : OuterWord) {x : G} (hx : x ∈ w.values G) (g : G) :
    g⁻¹ * x * g ∈ w.values G := by
  simpa [MulAut.conj_apply] using
    w.map_mem_values (MulAut.conj g⁻¹).toMonoidHom hx

instance verbalSubgroup_characteristic (w : OuterWord) :
    (w.verbalSubgroup G).Characteristic := by
  apply Subgroup.characteristic_iff_map_eq.mpr
  intro f
  exact w.map_verbalSubgroup_eq f.toMonoidHom f.surjective

instance verbalSubgroup_normal (w : OuterWord) : (w.verbalSubgroup G).Normal := by
  apply Subgroup.normal_iff_map_conj_eq.mpr
  intro g
  exact w.map_verbalSubgroup_eq (MulAut.conj g).toMonoidHom (MulAut.conj g).surjective

/-- Inverses of single outer-word values are again single values. This theorem
does not assert closure under arbitrary powers. -/
theorem inv_mem_values (w : OuterWord) {x : G} (hx : x ∈ w.values G) :
    x⁻¹ ∈ w.values G := by
  induction w generalizing x with
  | leaf => exact ⟨(x⁻¹ : G), rfl⟩
  | bracket left right ihLeft _ =>
      obtain ⟨a, ha, b, hb, rfl⟩ := (mem_values_bracket left right x).1 hx
      have hcomm : (a⁻¹)⁻¹ * b⁻¹ * a⁻¹ * b ∈ (bracket left right).values G :=
        (mem_values_bracket left right _).2 ⟨a⁻¹, ihLeft ha, b, hb, rfl⟩
      simpa only [inv_inv, mul_inv_rev, mul_assoc, inv_mul_cancel_left] using
        (bracket left right).conj_mem_values hcomm a

@[simp]
theorem inv_mem_values_iff (w : OuterWord) (x : G) :
    x⁻¹ ∈ w.values G ↔ x ∈ w.values G := by
  constructor
  · intro hx
    simpa only [inv_inv] using w.inv_mem_values hx
  · exact w.inv_mem_values

end OuterWord

end Kourovka2135
