import Kourovka2135.SolubleFocal
import Kourovka2135.Vendor.CFSG.PCore.PCore

/-!
# Generation by prime-to-p single values

The focal theorem implies that killing all prime-to-p values leaves a p-group.
This is applied to actual single values, not powers of word values.
-/

set_option autoImplicit false
universe u v
namespace Kourovka2135
variable {G : Type u} [Group G] [Finite G]

theorem ValueGeneratedSylows.isPGroup_quotient
    {V : Set G} (hV : ValueGeneratedSylows V) (p : ℕ) (hp : p.Prime)
    (N : Subgroup G) [N.Normal]
    (hN : ∀ x ∈ V, ¬ p ∣ orderOf x → x ∈ N) : IsPGroup p (G ⧸ N) := by
  classical
  apply (isPGroup_iff_primeFactors_card_subset hp.ne_zero).mpr
  intro q hq
  obtain ⟨hqprime, hqdvd, _⟩ := Nat.mem_primeFactors.mp hq
  rw [hp.primeFactors, Finset.mem_singleton]
  by_contra hqp
  let : Fact q.Prime := ⟨hqprime⟩
  let S : Sylow q G := Sylow.nonempty.some
  obtain ⟨X, hX, hgen⟩ := hV q hqprime S
  have hSN : (S : Subgroup G) ≤ N := by
    rw [← hgen]
    apply (Subgroup.closure_le _).mpr
    intro x hx
    have hxS : x ∈ (S : Subgroup G) := hgen ▸ Subgroup.subset_closure hx
    apply hN x (hX hx)
    obtain ⟨k, hk⟩ := S.isPGroup'.exists_orderOf_eq_pow (⟨x, hxS⟩ : S)
    have horder : orderOf x = q ^ k := by simpa only [Subgroup.orderOf_mk] using hk
    rw [horder]
    exact fun hd => hqp ((Nat.prime_dvd_prime_iff_eq hp hqprime).mp
      (hp.dvd_of_dvd_pow hd)).symm
  exact S.not_dvd_index ((N.index_eq_card.symm ▸ hqdvd).trans
    (Subgroup.index_dvd_of_le hSN))

theorem ValueGeneratedSylows.isPGroup_of_surjective
    {V : Set G} (hV : ValueGeneratedSylows V) (p : ℕ) (hp : p.Prime)
    {H : Type v} [Group H] (f : G →* H) (hf : Function.Surjective f)
    (hkill : ∀ x ∈ V, ¬ p ∣ orderOf x → f x = 1) : IsPGroup p H := by
  have hQ := hV.isPGroup_quotient p hp f.ker hkill
  exact hQ.of_equiv (QuotientGroup.quotientKerEquivOfSurjective f hf)

omit [Finite G] in
theorem mem_of_not_dvd_orderOf_of_isPGroup_quotient
    (p : ℕ) (hp : p.Prime) (N : Subgroup G) [N.Normal]
    (hQ : IsPGroup p (G ⧸ N)) {x : G} (hx : ¬ p ∣ orderOf x) : x ∈ N := by
  let : Fact p.Prime := ⟨hp⟩
  apply (QuotientGroup.eq_one_iff x).mp
  by_contra hne
  exact hx ((hQ.dvd_orderOf hne).trans (orderOf_map_dvd (QuotientGroup.mk' N) x))

namespace OuterWord

/-- The subgroup generated by the prime-to-p single values in the original group. -/
def primeToPValueSubgroup (w : OuterWord) (p : ℕ) (G : Type u) [Group G] : Subgroup G :=
  Subgroup.closure {x | x ∈ w.values G ∧ ¬ p ∣ orderOf x}

instance primeToPValueSubgroup_normal (w : OuterWord) (p : ℕ) :
    (w.primeToPValueSubgroup p G).Normal := by
  apply Subgroup.normalizer_eq_top_iff.mp
  apply top_le_iff.mp
  apply Subgroup.le_normalizer_closure_iff.mpr
  intro g _ x hx
  apply Subgroup.subset_closure
  refine ⟨?_, ?_⟩
  · simpa only [inv_inv] using w.conj_mem_values hx.1 g⁻¹
  · change ¬ p ∣ orderOf ((MulAut.conj g) x)
    simpa only [MulEquiv.orderOf_eq] using hx.2

omit [Finite G] in
theorem primeToPValueSubgroup_le (w : OuterWord) (p : ℕ) :
    w.primeToPValueSubgroup p G ≤ w.verbalSubgroup G :=
  Subgroup.closure_mono (fun _ hx => hx.1)

/-- Prime-to-p elements of a soluble verbal subgroup are generated by its
prime-to-p single values. -/
theorem mem_primeToPValueSubgroup (w : OuterWord) (p : ℕ) (hp : p.Prime)
    (hsolv : Group.IsSolvable G) {x : G} (hx : x ∈ w.verbalSubgroup G)
    (hxp : ¬ p ∣ orderOf x) : x ∈ w.primeToPValueSubgroup p G := by
  let N := (w.primeToPValueSubgroup p G).subgroupOf (w.verbalSubgroup G)
  have hQ : IsPGroup p ((w.verbalSubgroup G) ⧸ N) :=
    (w.valueGeneratedSylows_of_isSolvable hsolv).isPGroup_quotient p hp N (by
      intro y hy hyp
      apply Subgroup.subset_closure
      refine ⟨hy, ?_⟩
      change ¬ p ∣ orderOf (y : G)
      simpa only [Subgroup.orderOf_coe] using hyp)
  exact mem_of_not_dvd_orderOf_of_isPGroup_quotient p hp N hQ
    (x := ⟨x, hx⟩) (by simpa only [Subgroup.orderOf_mk] using hxp)

/-- If all prime-to-p single values are trivial, the whole verbal subgroup
of a finite soluble group is a p-group. -/
theorem verbalSubgroup_isPGroup_of_primeToP_values_eq_one
    (w : OuterWord) (p : ℕ) (hp : p.Prime) (hsolv : Group.IsSolvable G)
    (hvalues : ∀ x ∈ w.values G, ¬ p ∣ orderOf x → x = 1) :
    IsPGroup p (w.verbalSubgroup G) := by
  have hQ := (w.valueGeneratedSylows_of_isSolvable hsolv).isPGroup_quotient p hp
    (⊥ : Subgroup (w.verbalSubgroup G)) (by
      intro x hx hxp
      apply Subgroup.mem_bot.mpr
      apply Subtype.ext
      exact hvalues x hx (by simpa only [Subgroup.orderOf_coe] using hxp))
  exact hQ.of_injective (QuotientGroup.mk' ⊥)
    ((MonoidHom.ker_eq_bot_iff _).mp (QuotientGroup.ker_mk' _))

/-- Prime-to-p values of every word in a family, taken together. -/
def familyPrimeToPValueSubgroup (W : Set OuterWord) (p : ℕ)
    (G : Type u) [Group G] : Subgroup G :=
  Subgroup.closure {x | ∃ w ∈ W, x ∈ w.values G ∧ ¬ p ∣ orderOf x}

instance familyPrimeToPValueSubgroup_normal (W : Set OuterWord) (p : ℕ) :
    (familyPrimeToPValueSubgroup W p G).Normal := by
  apply Subgroup.normalizer_eq_top_iff.mp
  apply top_le_iff.mp
  apply Subgroup.le_normalizer_closure_iff.mpr
  rintro g _ x ⟨w, hw, hx, hxp⟩
  apply Subgroup.subset_closure
  refine ⟨w, hw, ?_, ?_⟩
  · simpa only [inv_inv] using w.conj_mem_values hx g⁻¹
  · change ¬ p ∣ orderOf ((MulAut.conj g) x)
    simpa only [MulEquiv.orderOf_eq] using hxp

/-- A prime-to-p element of a join of soluble verbal subgroups is generated
by prime-to-p single values of the words in that family. -/
theorem mem_familyPrimeToPValueSubgroup (W : Set OuterWord) (p : ℕ)
    (hp : p.Prime) (hsolv : Group.IsSolvable G) {x : G}
    (hx : x ∈ ⨆ w ∈ W, w.verbalSubgroup G) (hxp : ¬ p ∣ orderOf x) :
    x ∈ familyPrimeToPValueSubgroup W p G := by
  let : Fact p.Prime := ⟨hp⟩
  let N := familyPrimeToPValueSubgroup W p G
  let q : G →* G ⧸ N := QuotientGroup.mk' N
  have hwmap (w : OuterWord) (hw : w ∈ W) :
      IsPGroup p ((w.verbalSubgroup G).map q) := by
    apply (w.valueGeneratedSylows_of_isSolvable hsolv).isPGroup_of_surjective
      p hp (q.subgroupMap (w.verbalSubgroup G)) (q.subgroupMap_surjective _)
    intro y hy hyp
    apply Subtype.ext
    change q (y : G) = 1
    apply (QuotientGroup.eq_one_iff _).mpr
    apply Subgroup.subset_closure
    exact ⟨w, hw, hy, by simpa only [Subgroup.orderOf_coe] using hyp⟩
  have hle : (⨆ w ∈ W, w.verbalSubgroup G).map q ≤ pCore p (G ⧸ N) := by
    rw [Subgroup.map_iSup]
    apply iSup_le
    intro w
    rw [Subgroup.map_iSup]
    apply iSup_le
    intro hw
    apply le_sSup
    exact ⟨Subgroup.Normal.map inferInstance q (QuotientGroup.mk'_surjective N),
      hwmap w hw⟩
  have hqx : q x ∈ pCore p (G ⧸ N) := hle ⟨x, hx, rfl⟩
  apply (QuotientGroup.eq_one_iff x).mp
  by_contra hne
  have hne' : (⟨q x, hqx⟩ : pCore p (G ⧸ N)) ≠ 1 := by
    intro heq
    exact hne (congrArg Subtype.val heq)
  have hdiv : p ∣ orderOf (q x) := by
    simpa only [Subgroup.orderOf_mk] using pCore_isPGroup.dvd_orderOf hne'
  exact hxp (hdiv.trans (orderOf_map_dvd q x))

end OuterWord
end Kourovka2135
