import Kourovka2135.AbelianCommutatorFiber

/-! The exact commutator image on two cosets of an abelian normal subgroup.
The correction subgroup is [N, closure {a,b}], with no full-moving or ambient
generation hypothesis. All actors and corrections are actual group elements.
-/

set_option autoImplicit false
universe u v

namespace Kourovka2135.RelativeAbelianCommutatorFiber

open AbelianDifference
open scoped IsMulCommutative commutatorElement

section Moving
variable {V : Type u} [CommGroup V] {G : Type v} [Group G]

/-- The subgroup generated by the differences of the actual actors in H. -/
def movingSubgroupOn (ρ : G →* MulAut V) (H : Subgroup G) : Subgroup V :=
  ⨆ g : H, movingSubgroup (ρ g)

/-- The two original difference ranges generate exactly the differences of
the subgroup they generate, even when that subgroup is proper. -/
theorem movingSubgroupOn_closure_pair (ρ : G →* MulAut V) (a b : G) :
    movingSubgroupOn ρ (Subgroup.closure ({a, b} : Set G)) =
      movingSubgroup (ρ a) ⊔ movingSubgroup (ρ b) := by
  let U := movingSubgroup (ρ a) ⊔ movingSubgroup (ρ b)
  have hoperators : Subgroup.closure ({a, b} : Set G) ≤ (modFixer ⊤ U).comap ρ := by
    apply (Subgroup.closure_le _).mpr
    intro g hg
    refine ⟨fun _ => iff_of_true (Subgroup.mem_top _) (Subgroup.mem_top _), ?_⟩
    intro x _
    rcases Set.mem_insert_iff.mp hg with hga | hg
    · subst g
      exact Subgroup.mem_sup_left (show delta (ρ a) x ∈ movingSubgroup (ρ a) from ⟨x, rfl⟩)
    · have heq : g = b := Set.mem_singleton_iff.mp hg
      subst g
      exact Subgroup.mem_sup_right (show delta (ρ b) x ∈ movingSubgroup (ρ b) from ⟨x, rfl⟩)
  apply le_antisymm
  · apply iSup_le
    intro g x hx
    obtain ⟨y, rfl⟩ := hx
    exact (hoperators g.property).2 y (Subgroup.mem_top y)
  · refine sup_le ?_ ?_
    · exact le_iSup (fun g : Subgroup.closure ({a, b} : Set G) => movingSubgroup (ρ g))
        ⟨a, Subgroup.subset_closure (Set.mem_insert _ _)⟩
    · exact le_iSup (fun g : Subgroup.closure ({a, b} : Set G) => movingSubgroup (ρ g))
        ⟨b, Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _))⟩

/-- Membership in the relative moving subgroup has an exact two-difference witness. -/
theorem exists_delta_mul_delta_of_mem_closure_pair
    (ρ : G →* MulAut V) (a b : G) (t : V)
    (ht : t ∈ movingSubgroupOn ρ (Subgroup.closure ({a, b} : Set G))) :
    ∃ x y : V, delta (ρ a) x * delta (ρ b) y = t := by
  rw [movingSubgroupOn_closure_pair] at ht
  obtain ⟨x, ⟨s, rfl⟩, y, ⟨z, rfl⟩, hsz⟩ := Subgroup.mem_sup_of_normal_right.mp ht
  exact ⟨s, z, hsz⟩

end Moving

section Conjugation
variable {G : Type u} [Group G]
variable (N : Subgroup G) [N.Normal] [IsMulCommutative N]

/-- The relative differences of actual conjugation map to the actual subgroup commutator. -/
theorem movingSubgroupOn_conj_map (H : Subgroup G) :
    (movingSubgroupOn (MulAut.conjNormal : G →* MulAut N) H).map N.subtype = ⁅N, H⁆ := by
  let ρ : G →* MulAut N := MulAut.conjNormal
  apply le_antisymm
  · apply Subgroup.map_le_iff_le_comap.mpr
    apply iSup_le
    intro g x hx
    obtain ⟨y, rfl⟩ := hx
    have h := Subgroup.commutator_mem_commutator (H₁ := N) (H₂ := H)
      (g₁ := (y : G)⁻¹) (g₂ := (g : G)) (N.inv_mem y.property) g.property
    change (y : G)⁻¹ * ((g : G) * (y : G) * (g : G)⁻¹) ∈ ⁅N, H⁆
    simpa only [commutatorElement_def, inv_inv, mul_assoc] using h
  · apply Subgroup.commutator_le.mpr
    intro a ha g hg
    refine ⟨delta (ρ g) (⟨a⁻¹, N.inv_mem ha⟩ : N), ?_, ?_⟩
    · exact (le_iSup (fun g : H => movingSubgroup (ρ g)) ⟨g, hg⟩)
        (show delta (ρ g) (⟨a⁻¹, N.inv_mem ha⟩ : N) ∈ movingSubgroup (ρ g) from ⟨_, rfl⟩)
    · change (a⁻¹)⁻¹ * (g * a⁻¹ * g⁻¹) = a * g * a⁻¹ * g⁻¹
      simp only [inv_inv, mul_assoc]

theorem mem_movingSubgroupOn_conj_iff (H : Subgroup G) (t : N) :
    t ∈ movingSubgroupOn (MulAut.conjNormal : G →* MulAut N) H ↔ (t : G) ∈ ⁅N, H⁆ := by
  rw [← movingSubgroupOn_conj_map N H]
  constructor
  · exact fun ht => Subgroup.mem_map_of_mem N.subtype ht
  · rintro ⟨s, hs, hst⟩
    exact (show s = t from Subtype.ext hst) ▸ hs

/-- Every element of the relative subgroup commutator is an actual correction. -/
theorem exists_correction_eq_of_mem_commutator (a b : G) (t : N)
    (ht : (t : G) ∈ ⁅N, Subgroup.closure ({a, b} : Set G)⁆) :
    ∃ u v : N, abelianCorrection N a b u v = t := by
  let ρ : G →* MulAut N := MulAut.conjNormal
  let c := paperCommutator a b
  have hpair : Subgroup.closure ({(c⁻¹ * b)⁻¹, (a * c)⁻¹} : Set G) =
      Subgroup.closure ({a, b} : Set G) := by
    rw [closure_inverse_pair, closure_commutator_correction_pair]
  have ht' : t ∈ movingSubgroupOn ρ
      (Subgroup.closure ({(c⁻¹ * b)⁻¹, (a * c)⁻¹} : Set G)) := by
    rw [hpair]
    exact (mem_movingSubgroupOn_conj_iff N _ t).mpr ht
  obtain ⟨s, z, hsz⟩ := exists_delta_mul_delta_of_mem_closure_pair ρ
    (c⁻¹ * b)⁻¹ (a * c)⁻¹ t ht'
  refine ⟨ρ c s, z⁻¹, ?_⟩
  rw [abelianCorrection_eq_deltas]
  change delta (ρ (c⁻¹ * b)⁻¹) (ρ c⁻¹ (ρ c s)) *
    delta (ρ (a * c)⁻¹) (z⁻¹)⁻¹ = t
  rw [show ρ c⁻¹ (ρ c s) = s by rw [map_inv]; exact (ρ c).symm_apply_apply s, inv_inv]
  exact hsz

/-- Every actual correction lies in the same relative subgroup commutator. -/
theorem correction_mem_commutator (a b : G) (u v : N) :
    (abelianCorrection N a b u v : G) ∈ ⁅N, Subgroup.closure ({a, b} : Set G)⁆ := by
  let ρ : G →* MulAut N := MulAut.conjNormal
  let c := paperCommutator a b
  have hpair : Subgroup.closure ({(c⁻¹ * b)⁻¹, (a * c)⁻¹} : Set G) =
      Subgroup.closure ({a, b} : Set G) := by
    rw [closure_inverse_pair, closure_commutator_correction_pair]
  apply (mem_movingSubgroupOn_conj_iff N _ _).mp
  rw [← hpair, movingSubgroupOn_closure_pair, abelianCorrection_eq_deltas]
  exact (movingSubgroup (ρ (c⁻¹ * b)⁻¹) ⊔ movingSubgroup (ρ (a * c)⁻¹)).mul_mem
    (Subgroup.mem_sup_left ⟨_, rfl⟩) (Subgroup.mem_sup_right ⟨_, rfl⟩)

/-- Exact correction range, including all relative fibers and only those fibers. -/
theorem correction_range_eq (a b : G) :
    Set.range (fun uv : N × N => (abelianCorrection N a b uv.1 uv.2 : G)) =
      ((⁅N, Subgroup.closure ({a, b} : Set G)⁆ : Subgroup G) : Set G) := by
  ext x
  constructor
  · rintro ⟨⟨u, v⟩, rfl⟩
    exact correction_mem_commutator N a b u v
  · intro hx
    have hxN : x ∈ N :=
      Subgroup.commutator_le_left N (Subgroup.closure ({a, b} : Set G)) hx
    obtain ⟨u, v, huv⟩ := exists_correction_eq_of_mem_commutator N a b ⟨x, hxN⟩ hx
    exact ⟨(u, v), congrArg Subtype.val huv⟩

/-- The requested relative lifting theorem, with no generation or full-moving premise. -/
theorem exists_paperCommutator_mul_eq_of_mem_commutator (a b : G) (t : N)
    (ht : (t : G) ∈ ⁅N, Subgroup.closure ({a, b} : Set G)⁆) :
    ∃ u v : N, paperCommutator (a * u) (b * v) = paperCommutator a b * t := by
  obtain ⟨u, v, huv⟩ := exists_correction_eq_of_mem_commutator N a b t ht
  exact ⟨u, v, (paperCommutator_mul_eq_correction N a b u v).trans
    (congrArg (fun z : N => paperCommutator a b * (z : G)) huv)⟩

/-- A single deviation by the right actor already lies in the correction
range. This is the pointwise form of the module difference rho(b)x - x. -/
theorem exists_paperCommutator_mul_eq_conj_difference_right (a b : G) (x : N) :
    ∃ u v : N, paperCommutator (a * u) (b * v) = paperCommutator a b *
      (((MulAut.conjNormal b : MulAut N) x * x⁻¹ : N) : G) := by
  let ρ : G →* MulAut N := MulAut.conjNormal
  have hdelta : ρ b x * x⁻¹ ∈ movingSubgroup (ρ b) := by
    refine ⟨x, ?_⟩
    rw [delta_apply, mul_comm]
  have hmove : ρ b x * x⁻¹ ∈ movingSubgroupOn ρ
      (Subgroup.closure ({a, b} : Set G)) := by
    rw [movingSubgroupOn_closure_pair]
    exact Subgroup.mem_sup_right hdelta
  exact exists_paperCommutator_mul_eq_of_mem_commutator N a b (ρ b x * x⁻¹)
    ((mem_movingSubgroupOn_conj_iff N _ _).mp hmove)

/-- The commutator image on two actual N-cosets is exactly the corresponding
coset of [N, closure {a,b}]. -/
theorem paperCommutator_range_eq (a b : G) :
    Set.range (fun uv : N × N => paperCommutator (a * uv.1) (b * uv.2)) =
      (fun z : G => paperCommutator a b * z) ''
        ((⁅N, Subgroup.closure ({a, b} : Set G)⁆ : Subgroup G) : Set G) := by
  ext x
  constructor
  · rintro ⟨⟨u, v⟩, rfl⟩
    exact ⟨abelianCorrection N a b u v, correction_mem_commutator N a b u v,
      (paperCommutator_mul_eq_correction N a b u v).symm⟩
  · rintro ⟨z, hz, rfl⟩
    have hzN : z ∈ N :=
      Subgroup.commutator_le_left N (Subgroup.closure ({a, b} : Set G)) hz
    obtain ⟨u, v, huv⟩ := exists_paperCommutator_mul_eq_of_mem_commutator N a b ⟨z, hzN⟩ hz
    exact ⟨(u, v), huv⟩

/-- Membership form useful for intersecting the correction fiber with a
normalizer-preserving coset. -/
theorem exists_paperCommutator_eq_iff (a b x : G) :
    (∃ u v : N, paperCommutator (a * u) (b * v) = x) ↔
      (paperCommutator a b)⁻¹ * x ∈ ⁅N, Subgroup.closure ({a, b} : Set G)⁆ := by
  constructor
  · rintro ⟨u, v, rfl⟩
    rw [paperCommutator_mul_eq_correction, inv_mul_cancel_left]
    exact correction_mem_commutator N a b u v
  · intro hx
    have htN : (paperCommutator a b)⁻¹ * x ∈ N :=
      Subgroup.commutator_le_left N (Subgroup.closure ({a, b} : Set G)) hx
    obtain ⟨u, v, huv⟩ := exists_paperCommutator_mul_eq_of_mem_commutator N a b
      ⟨(paperCommutator a b)⁻¹ * x, htN⟩ hx
    exact ⟨u, v, huv.trans (mul_inv_cancel_left _ _)⟩

end Conjugation
end Kourovka2135.RelativeAbelianCommutatorFiber
