import Kourovka2135.RelativeVerbal

/-!
# Outer-word evaluation modulo the relative verbal subgroup

For a normal subgroup P, multiplying any leaf inputs by elements of P changes
the evaluated word by an element of the subgroup generated by mixed values.
-/

set_option autoImplicit false
universe u v
namespace Kourovka2135
variable {G : Type u} {H : Type v} [Group G] [Group H]
open scoped commutatorElement

@[simp]
theorem map_paperCommutator (f : G →* H) (a b : G) :
    f (paperCommutator a b) = paperCommutator (f a) (f b) := by
  simp only [paperCommutator, map_mul, map_inv]

/-- The exact three cross-commutation relations needed for relative evaluation. -/
theorem paperCommutator_mul_of_cross_commute (a b c d : G)
    (hcb : Commute c b) (hcd : Commute c d) (had : Commute a d) :
    paperCommutator (c * a) (d * b) = paperCommutator a b := by
  have hcdc : c⁻¹ * d⁻¹ * c = d⁻¹ := by
    rw [hcd.inv_inv.eq]
    simp only [mul_assoc, inv_mul_cancel, mul_one]
  have hdad : d⁻¹ * a * d = a := by
    rw [had.symm.inv_left.eq]
    simp only [mul_assoc, inv_mul_cancel, mul_one]
  calc
    paperCommutator (c * a) (d * b) =
        a⁻¹ * (c⁻¹ * b⁻¹) * d⁻¹ * c * a * d * b := by
      simp only [paperCommutator, mul_inv_rev, mul_assoc]
    _ = a⁻¹ * (b⁻¹ * c⁻¹) * d⁻¹ * c * a * d * b := by rw [hcb.inv_inv.eq]
    _ = a⁻¹ * b⁻¹ * (c⁻¹ * d⁻¹ * c) * a * d * b := by simp only [mul_assoc]
    _ = a⁻¹ * b⁻¹ * d⁻¹ * a * d * b := by rw [hcdc]
    _ = a⁻¹ * b⁻¹ * (d⁻¹ * a * d) * b := by simp only [mul_assoc]
    _ = paperCommutator a b := by rw [hdad]; rfl

theorem commute_quotient_of_commutator_le
    {A B N : Subgroup G} [N.Normal] (h : ⁅A, B⁆ ≤ N)
    {a b : G} (ha : a ∈ A) (hb : b ∈ B) :
    Commute (QuotientGroup.mk' N a) (QuotientGroup.mk' N b) := by
  apply commutatorElement_eq_one_iff_commute.mp
  rw [← map_commutatorElement]
  exact (QuotientGroup.eq_one_iff _).mpr (h (Subgroup.commutator_mem_commutator ha hb))

namespace OuterWord

/-- Congruent inputs modulo P give congruent outputs modulo the relative
verbal subgroup. This is the multilinearity assertion used in the new focal proof. -/
theorem eval_mul_inv_mem_mixedSubgroup (w : OuterWord) (P : Subgroup G) [P.Normal]
    (x y : w.Input G)
    (hxy : w.mapInput (QuotientGroup.mk' P) x = w.mapInput (QuotientGroup.mk' P) y) :
    w.eval x * (w.eval y)⁻¹ ∈ w.mixedSubgroup P := by
  induction w with
  | leaf =>
      change G at x y
      change (QuotientGroup.mk' P) x = (QuotientGroup.mk' P) y at hxy
      rw [mixedSubgroup_leaf]
      apply (QuotientGroup.eq_one_iff _).mp
      change (QuotientGroup.mk' P) (x * y⁻¹) = 1
      rw [map_mul, map_inv, hxy, mul_inv_cancel]
  | bracket l r ihl ihr =>
      rcases x with ⟨xl, xr⟩
      rcases y with ⟨yl, yr⟩
      have hl := ihl xl yl (congrArg Prod.fst hxy)
      have hr := ihr xr yr (congrArg Prod.snd hxy)
      let N := (bracket l r).mixedSubgroup P
      let f := QuotientGroup.mk' N
      let c := l.eval xl * (l.eval yl)⁻¹
      let d := r.eval xr * (r.eval yr)⁻¹
      have hc : c ∈ l.mixedSubgroup P := hl
      have hd : d ∈ r.mixedSubgroup P := hr
      have hL : ⁅l.mixedSubgroup P, r.verbalSubgroup G⁆ ≤ N := by
        change _ ≤ (bracket l r).mixedSubgroup P
        rw [mixedSubgroup_bracket]
        exact le_sup_left
      have hR : ⁅l.verbalSubgroup G, r.mixedSubgroup P⁆ ≤ N := by
        change _ ≤ (bracket l r).mixedSubgroup P
        rw [mixedSubgroup_bracket]
        exact le_sup_right
      have hcb : Commute (f c) (f (r.eval yr)) :=
        commute_quotient_of_commutator_le hL hc (r.eval_mem_verbalSubgroup yr)
      have hcd : Commute (f c) (f d) :=
        commute_quotient_of_commutator_le hL hc (r.mixedSubgroup_le_verbal P hd)
      have had : Commute (f (l.eval yl)) (f d) :=
        commute_quotient_of_commutator_le hR (l.eval_mem_verbalSubgroup yl) hd
      have hleft : f (l.eval xl) = f c * f (l.eval yl) := by
        simp only [c, map_mul, map_inv, mul_assoc, inv_mul_cancel, mul_one]
      have hright : f (r.eval xr) = f d * f (r.eval yr) := by
        simp only [d, map_mul, map_inv, mul_assoc, inv_mul_cancel, mul_one]
      have heq : f ((bracket l r).eval (xl, xr)) = f ((bracket l r).eval (yl, yr)) := by
        change f (paperCommutator (l.eval xl) (r.eval xr)) =
          f (paperCommutator (l.eval yl) (r.eval yr))
        rw [map_paperCommutator, map_paperCommutator, hleft, hright,
          paperCommutator_mul_of_cross_commute _ _ _ _ hcb hcd had]
      apply (QuotientGroup.eq_one_iff _).mp
      change f ((bracket l r).eval (xl, xr) * ((bracket l r).eval (yl, yr))⁻¹) = 1
      rw [map_mul, map_inv, heq, mul_inv_cancel]

end OuterWord
end Kourovka2135
