import Kourovka2135.GeneratingSets

/-!
# Relative verbal subgroups of outer commutator words

Mixed values have at least one input in a specified normal subgroup; the
remaining leaf inputs are arbitrary. Their generated subgroup remains inside
that normal subgroup and is generated by actual single word values.
-/

set_option autoImplicit false
universe u
namespace Kourovka2135
open scoped commutatorElement
variable {G : Type u} [Group G]

/-- Commutation modulo a normal subgroup extends from generators to closures. -/
theorem commutator_closure_le_of_paperCommutators
    (X Y : Set G) (N : Subgroup G) [N.Normal]
    (h : ∀ x ∈ X, ∀ y ∈ Y, paperCommutator x y ∈ N) :
    ⁅Subgroup.closure X, Subgroup.closure Y⁆ ≤ N := by
  let f := QuotientGroup.mk' N
  have hbase (x : G) (hx : x ∈ X) (y : G) (hy : y ∈ Y) : Commute (f x) (f y) := by
    apply (paperCommutator_eq_one_iff _ _).mp
    have heq : paperCommutator (f x) (f y) = f (paperCommutator x y) := by
      simp [paperCommutator]
    rw [heq]
    exact (QuotientGroup.eq_one_iff _).mpr (h x hx y hy)
  have hc (x : G) (hx : x ∈ Subgroup.closure X)
      (y : G) (hy : y ∈ Subgroup.closure Y) : Commute (f x) (f y) := by
    induction hx using Subgroup.closure_induction with
    | mem x hx =>
        induction hy using Subgroup.closure_induction with
        | mem y hy => exact hbase x hx y hy
        | one => simp
        | mul y z _ _ ihy ihz => simpa only [map_mul] using ihy.mul_right ihz
        | inv y _ ih => simpa only [map_inv] using (Commute.inv_right ih)
    | one => simp
    | mul x z _ _ ihx ihz => simpa only [map_mul] using ihx.mul_left ihz
    | inv x _ ih => simpa only [map_inv] using (Commute.inv_left ih)
  apply Subgroup.commutator_le.mpr
  intro x hx y hy
  apply (QuotientGroup.eq_one_iff _).mp
  change f ⁅x,y⁆ = 1
  rw [map_commutatorElement]
  exact (hc x hx y hy).commutator_eq

namespace OuterWord

def mixedValues (w : OuterWord) (P : Subgroup G) : Set G :=
  match w with
  | leaf => P
  | bracket l r =>
      commutatorImage (mixedValues l P) (r.values G) ∪
      commutatorImage (l.values G) (mixedValues r P)

def mixedSubgroup (w : OuterWord) (P : Subgroup G) : Subgroup G :=
  Subgroup.closure (w.mixedValues P)

theorem mixedValues_subset_values (w : OuterWord) (P : Subgroup G) :
    w.mixedValues P ⊆ w.values G := by
  induction w with
  | leaf => simp
  | bracket l r ihl ihr =>
      rintro x (hx | hx)
      · obtain ⟨a, ha, b, hb, rfl⟩ := hx
        exact (mem_values_bracket _ _ _).mpr ⟨a, ihl ha, b, hb, rfl⟩
      · obtain ⟨a, ha, b, hb, rfl⟩ := hx
        exact (mem_values_bracket _ _ _).mpr ⟨a, ha, b, ihr hb, rfl⟩

theorem mixedValues_conj_mem (w : OuterWord) (P : Subgroup G) [P.Normal]
    {x : G} (hx : x ∈ w.mixedValues P) (g : G) : g * x * g⁻¹ ∈ w.mixedValues P := by
  induction w generalizing x with
  | leaf => exact (inferInstance : P.Normal).conj_mem x hx g
  | bracket l r ihl ihr =>
      rcases hx with hx | hx
      · obtain ⟨a, ha, b, hb, rfl⟩ := hx
        refine Or.inl ⟨g * a * g⁻¹, ihl ha, g * b * g⁻¹, ?_, ?_⟩
        · simpa only [inv_inv] using r.conj_mem_values hb g⁻¹
        · simp [paperCommutator, mul_assoc]
      · obtain ⟨a, ha, b, hb, rfl⟩ := hx
        refine Or.inr ⟨g * a * g⁻¹, ?_, g * b * g⁻¹, ihr hb, ?_⟩
        · simpa only [inv_inv] using l.conj_mem_values ha g⁻¹
        · simp [paperCommutator, mul_assoc]

instance mixedSubgroup_normal (w : OuterWord) (P : Subgroup G) [P.Normal] :
    (w.mixedSubgroup P).Normal := by
  change (Subgroup.closure (w.mixedValues P)).Normal
  apply Subgroup.normalizer_eq_top_iff.mp
  apply top_le_iff.mp
  apply Subgroup.le_normalizer_closure_iff.mpr
  intro g _ x hx
  exact Subgroup.subset_closure (w.mixedValues_conj_mem P hx g)

theorem mixedValues_subset_normal (w : OuterWord) (P : Subgroup G) [P.Normal] :
    w.mixedValues P ⊆ P := by
  induction w with
  | leaf => exact Set.Subset.rfl
  | bracket l r ihl ihr =>
      rintro x (hx | hx)
      · obtain ⟨a, ha, b, _, rfl⟩ := hx
        change paperCommutator a b ∈ P
        have hconj := (inferInstance : P.Normal).conj_mem a (ihl ha) b⁻¹
        simpa only [paperCommutator, inv_inv, mul_assoc] using P.mul_mem (P.inv_mem (ihl ha)) hconj
      · obtain ⟨a, _, b, hb, rfl⟩ := hx
        change paperCommutator a b ∈ P
        have hconj := (inferInstance : P.Normal).conj_mem b⁻¹ (P.inv_mem (ihr hb)) a⁻¹
        simpa only [paperCommutator, inv_inv, mul_assoc] using P.mul_mem hconj (ihr hb)

theorem mixedSubgroup_le (w : OuterWord) (P : Subgroup G) [P.Normal] :
    w.mixedSubgroup P ≤ P :=
  (Subgroup.closure_le _).mpr (w.mixedValues_subset_normal P)

theorem mixedSubgroup_le_verbal (w : OuterWord) (P : Subgroup G) :
    w.mixedSubgroup P ≤ w.verbalSubgroup G :=
  Subgroup.closure_mono (w.mixedValues_subset_values P)

@[simp]
theorem mixedSubgroup_leaf (P : Subgroup G) : leaf.mixedSubgroup P = P :=
  Subgroup.closure_eq P

/-- The recursive subgroup identity for relative values. -/
theorem mixedSubgroup_bracket (l r : OuterWord) (P : Subgroup G) [P.Normal] :
    (bracket l r).mixedSubgroup P =
      ⁅l.mixedSubgroup P, r.verbalSubgroup G⁆ ⊔
      ⁅l.verbalSubgroup G, r.mixedSubgroup P⁆ := by
  apply le_antisymm
  · apply (Subgroup.closure_le _).mpr
    rintro x (hx | hx)
    · obtain ⟨a, ha, b, hb, rfl⟩ := hx
      change paperCommutator a b ∈ (⁅l.mixedSubgroup P, r.verbalSubgroup G⁆ ⊔
        ⁅l.verbalSubgroup G, r.mixedSubgroup P⁆ : Subgroup G)
      apply (show ⁅l.mixedSubgroup P, r.verbalSubgroup G⁆ ≤
        ⁅l.mixedSubgroup P, r.verbalSubgroup G⁆ ⊔ ⁅l.verbalSubgroup G, r.mixedSubgroup P⁆ from le_sup_left)
      change paperCommutator a b ∈ (⁅l.mixedSubgroup P, r.verbalSubgroup G⁆ : Subgroup G)
      simpa only [paperCommutator, commutatorElement_def, inv_inv] using
        Subgroup.commutator_mem_commutator
          ((l.mixedSubgroup P).inv_mem (Subgroup.subset_closure ha))
          ((r.verbalSubgroup G).inv_mem (Subgroup.subset_closure hb))
    · obtain ⟨a, ha, b, hb, rfl⟩ := hx
      change paperCommutator a b ∈ (⁅l.mixedSubgroup P, r.verbalSubgroup G⁆ ⊔
        ⁅l.verbalSubgroup G, r.mixedSubgroup P⁆ : Subgroup G)
      apply (show ⁅l.verbalSubgroup G, r.mixedSubgroup P⁆ ≤
        ⁅l.mixedSubgroup P, r.verbalSubgroup G⁆ ⊔ ⁅l.verbalSubgroup G, r.mixedSubgroup P⁆ from le_sup_right)
      change paperCommutator a b ∈ (⁅l.verbalSubgroup G, r.mixedSubgroup P⁆ : Subgroup G)
      simpa only [paperCommutator, commutatorElement_def, inv_inv] using
        Subgroup.commutator_mem_commutator
          ((l.verbalSubgroup G).inv_mem (Subgroup.subset_closure ha))
          ((r.mixedSubgroup P).inv_mem (Subgroup.subset_closure hb))
  · apply sup_le
    · apply commutator_closure_le_of_paperCommutators
      intro a ha b hb
      exact Subgroup.subset_closure (Or.inl ⟨a, ha, b, hb, rfl⟩)
    · apply commutator_closure_le_of_paperCommutators
      intro a ha b hb
      exact Subgroup.subset_closure (Or.inr ⟨a, ha, b, hb, rfl⟩)

end OuterWord
end Kourovka2135
