import Kourovka2135.RelativeVerbal
import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic

/-! The derived subgroup of a central extension of the semidihedral group of
order sixteen meets its kernel trivially. This uses the actual defining
relations and exact order eight; no multiplier theorem is assumed. -/

set_option autoImplicit false
noncomputable section
namespace Kourovka2135.SemidihedralCentralStem

variable {E Q : Type*} [Group E] [Group Q]

private theorem closure_lifts_kernel (π : E →* Q) (a b : E)
    (hgen : Subgroup.closure ({π a, π b} : Set Q) = ⊤) :
    Subgroup.closure (({a, b} : Set E) ∪ π.ker) = ⊤ := by
  let H := Subgroup.closure (({a, b} : Set E) ∪ π.ker)
  have hker : π.ker ≤ H := fun _ h => Subgroup.subset_closure (Or.inr h)
  have ha : a ∈ H := Subgroup.subset_closure (Or.inl (by simp))
  have hb : b ∈ H := Subgroup.subset_closure (Or.inl (by simp))
  have hm : H.map π = ⊤ := by
    apply top_le_iff.mp
    rw [← hgen]
    apply (Subgroup.closure_le _).2
    intro q hq
    rcases Set.mem_insert_iff.mp hq with rfl | hq
    · exact Subgroup.mem_map_of_mem π ha
    · have : q = π b := Set.mem_singleton_iff.mp hq
      subst q
      exact Subgroup.mem_map_of_mem π hb
  apply top_le_iff.mp
  intro e _
  obtain ⟨h, hh, he⟩ := (show π e ∈ H.map π by rw [hm]; trivial)
  have hk : e * h⁻¹ ∈ π.ker := by simp [MonoidHom.mem_ker, he]
  simpa using H.mul_mem (hker hk) hh

/-- Exact order four survives under the projection, so its cyclic subgroup
has trivial intersection with the kernel. -/
theorem zpowers_inf_ker_eq_bot (π : E →* Q) (d : E)
    (hd : d ^ 4 = 1) (horder : orderOf (π d) = 4) :
    Subgroup.zpowers d ⊓ π.ker = ⊥ := by
  have ho : orderOf d = 4 := Nat.dvd_antisymm
    (orderOf_dvd_of_pow_eq_one hd) (horder ▸ orderOf_map_dvd π d)
  apply bot_unique
  intro e he
  obtain ⟨n, rfl⟩ := he.1
  apply Subgroup.mem_bot.mpr
  apply orderOf_dvd_iff_zpow_eq_one.mp
  rw [ho, ← horder]
  apply orderOf_dvd_iff_zpow_eq_one.mpr
  have heq : π (d ^ n) = 1 := he.2
  simpa only [map_zpow] using heq

/-- A central extension of a group generated by semidihedral generators
cannot have any nonidentity kernel element in its derived subgroup. -/
theorem ker_inf_commutator_eq_bot (π : E →* Q)
    (hcentral : π.ker ≤ Subgroup.center E) (a b : E)
    (hgen : Subgroup.closure ({π a, π b} : Set Q) = ⊤)
    (hb : (π b) ^ 2 = 1)
    (hconj : π b * π a * (π b)⁻¹ = (π a) ^ 3)
    (horder : orderOf (π a) = 8) :
    π.ker ⊓ commutator E = ⊥ := by
  let z := (a ^ 3)⁻¹ * (b * a * b⁻¹)
  have hzker : z ∈ π.ker := by
    simp only [z, MonoidHom.mem_ker, map_mul, map_inv, map_pow, hconj,
      inv_mul_cancel]
  have hz := hcentral hzker
  have haz : Commute a z := Subgroup.mem_center_iff.mp hz a
  have hbz : Commute b z := Subgroup.mem_center_iff.mp hz b
  have hrel : b * a * b⁻¹ = a ^ 3 * z := by dsimp [z]; group
  have hb2 : b ^ 2 ∈ Subgroup.center E :=
    hcentral (by simpa only [MonoidHom.mem_ker, map_pow] using hb)
  let θ : E ≃* E := MulAut.conj b
  have hzθ : θ z = z := by
    change b * z * b⁻¹ = z
    rw [hbz.eq, mul_inv_cancel_right]
  have haθ : θ a = a ^ 3 * z := hrel
  have hθ2 : θ (θ a) = a := by
    change b * (b * a * b⁻¹) * b⁻¹ = a
    calc
      _ = b ^ 2 * a * (b ^ 2)⁻¹ := by simp only [pow_two]; group
      _ = a := by rw [← Subgroup.mem_center_iff.mp hb2 a]; group
  have h9 : a = a ^ 9 * z ^ 4 := by
    calc
      a = θ (θ a) := hθ2.symm
      _ = (a ^ 3 * z) ^ 3 * z := by rw [haθ, map_mul, map_pow, hzθ, haθ]
      _ = a ^ 9 * z ^ 4 := by rw [(haz.pow_left 3).mul_pow]; group
  have h8 : a ^ 8 * z ^ 4 = 1 := by
    have h := congrArg (fun t => a⁻¹ * t) h9
    calc
      a ^ 8 * z ^ 4 = a⁻¹ * (a ^ 9 * z ^ 4) := by group
      _ = 1 := by rw [← h]; group
  let d := a ^ 2 * z
  have hd : d ^ 4 = 1 := by
    dsimp [d]
    rw [(haz.pow_left 2).mul_pow]
    simpa only [← pow_mul] using h8
  have had : Commute a d := (Commute.refl a).pow_right 2 |>.mul_right haz
  have hbd : b * d * b⁻¹ = d⁻¹ := by
    have he : θ d = d ^ 3 := by
      dsimp only [d]
      rw [map_mul, map_pow, hzθ, haθ, (haz.pow_left 3).mul_pow,
        (haz.pow_left 2).mul_pow]
      group
    have hi : d ^ 3 = d⁻¹ := by
      apply eq_inv_iff_mul_eq_one.mpr
      simpa only [← pow_succ] using hd
    exact he.trans hi
  let D := Subgroup.zpowers d
  have haD : a ∈ Subgroup.normalizer (D : Set E) := by
    rw [Subgroup.mem_normalizer_iff_map_conj_eq, MonoidHom.map_zpowers]
    change Subgroup.zpowers (a * d * a⁻¹) = Subgroup.zpowers d
    rw [had.eq, mul_inv_cancel_right]
  have hbD : b ∈ Subgroup.normalizer (D : Set E) := by
    rw [Subgroup.mem_normalizer_iff_map_conj_eq, MonoidHom.map_zpowers]
    change Subgroup.zpowers (b * d * b⁻¹) = Subgroup.zpowers d
    rw [hbd, Subgroup.zpowers_inv]
  have hRD : π.ker ≤ Subgroup.normalizer (D : Set E) := by
    intro r hr
    rw [Subgroup.mem_normalizer_iff_map_conj_eq, MonoidHom.map_zpowers]
    change Subgroup.zpowers (r * d * r⁻¹) = Subgroup.zpowers d
    rw [← Subgroup.mem_center_iff.mp (hcentral hr) d, mul_inv_cancel_right]
  have hDnormal : D.Normal := by
    apply Subgroup.normalizer_eq_top_iff.mp
    apply top_le_iff.mp
    rw [← closure_lifts_kernel π a b hgen]
    apply (Subgroup.closure_le _).2
    intro r hr
    rcases hr with hr | hr
    · rcases Set.mem_insert_iff.mp hr with rfl | hr
      · exact haD
      · exact Set.mem_singleton_iff.mp hr ▸ hbD
    · exact hRD hr
  let : D.Normal := hDnormal
  have habD : paperCommutator a b ∈ D := by
    have he : b * a * b⁻¹ * a⁻¹ = d := by
      rw [hrel]
      dsimp [d]
      calc
        a ^ 3 * z * a⁻¹ = a ^ 3 * a⁻¹ * z := by rw [mul_assoc, ← haz.inv_left.eq, ← mul_assoc]
        _ = a ^ 2 * z := by group
    have hf : Commute ((QuotientGroup.mk' D) b) ((QuotientGroup.mk' D) a) := by
      apply commutatorElement_eq_one_iff_mul_comm.mp
      change (QuotientGroup.mk' D) (b * a * b⁻¹ * a⁻¹) = 1
      rw [he]
      exact (QuotientGroup.eq_one_iff _).mpr (Subgroup.mem_zpowers d)
    apply (QuotientGroup.eq_one_iff _).mp
    change paperCommutator ((QuotientGroup.mk' D) a) ((QuotientGroup.mk' D) b) = 1
    exact (paperCommutator_eq_one_iff _ _).mpr hf.symm
  have hbaD : paperCommutator b a ∈ D := by
    have : paperCommutator b a = (paperCommutator a b)⁻¹ := by
      simp only [paperCommutator]; group
    rw [this]
    exact D.inv_mem habD
  have hderived : commutator E ≤ D := by
    have h := commutator_closure_le_of_paperCommutators
      (({a, b} : Set E) ∪ π.ker) (({a, b} : Set E) ∪ π.ker) D ?_
    · simpa only [closure_lifts_kernel π a b hgen, commutator_def] using h
    intro s hs t ht
    rcases hs with hs | hs <;> rcases ht with ht | ht
    · simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hs ht
      rcases hs with rfl | rfl <;> rcases ht with rfl | rfl
      · simp [paperCommutator]
      · exact habD
      · exact hbaD
      · simp [paperCommutator]
    · have hc : Commute s t := Subgroup.mem_center_iff.mp (hcentral ht) s
      rw [(paperCommutator_eq_one_iff _ _).mpr hc]
      exact D.one_mem
    · have hc : Commute s t := (Subgroup.mem_center_iff.mp (hcentral hs) t).symm
      rw [(paperCommutator_eq_one_iff _ _).mpr hc]
      exact D.one_mem
    · have hc : Commute s t := Subgroup.mem_center_iff.mp (hcentral ht) s
      rw [(paperCommutator_eq_one_iff _ _).mpr hc]
      exact D.one_mem
  have hπd : π d = (π a) ^ 2 := by simp [d, MonoidHom.mem_ker.mp hzker]
  have hdo : orderOf (π d) = 4 := by rw [hπd, orderOf_pow' _ (by decide : 2 ≠ 0), horder]; decide
  have hdis := zpowers_inf_ker_eq_bot π d hd hdo
  apply bot_unique
  intro r hr
  exact hdis.le ⟨hderived hr.2, hr.1⟩

/-- In particular, a central stem extension with the actual semidihedral
relations and an order-eight generator has trivial kernel. -/
theorem ker_eq_bot (π : E →* Q)
    (hcentral : π.ker ≤ Subgroup.center E) (a b : E)
    (hgen : Subgroup.closure ({π a, π b} : Set Q) = ⊤)
    (hb : (π b) ^ 2 = 1)
    (hconj : π b * π a * (π b)⁻¹ = (π a) ^ 3)
    (horder : orderOf (π a) = 8) (hstem : π.ker ≤ commutator E) :
    π.ker = ⊥ := by
  simpa only [inf_eq_left.mpr hstem] using
    ker_inf_commutator_eq_bot π hcentral a b hgen hb hconj horder

end Kourovka2135.SemidihedralCentralStem
