import Kourovka2135.SLTwoFiveGenerationData
import Kourovka2135.GoodSetLifting

/-! The certified finite set of all elements of orders six and ten is an
actual generating good set in SL2(F5). Generator words prove generation;
no finite-search conclusion is assumed. -/

set_option autoImplicit false
set_option maxHeartbeats 2000000
set_option maxRecDepth 4096
namespace Kourovka2135.SLTwoFiveGoodSet
open SLTwoFiveGoodSetData

def Y : Set S := targets

/-- The short words are evaluated inside the actual subgroup generated by their inputs. -/
theorem eval_mem (H : Subgroup S) (a b : S) (ha : a ∈ H) (hb : b ∈ H)
    (w : List (Fin 4)) : eval a b w ∈ H := by
  have hletter (k : Fin 4) : letter a b k ∈ H := by
    fin_cases k
    · exact ha
    · exact hb
    · exact H.inv_mem ha
    · exact H.inv_mem hb
  induction w with
  | nil => exact H.one_mem
  | cons k w ih => exact H.mul_mem (hletter k) ih

/-- Membership of both elementary generators forces a subgroup to be the whole group. -/
theorem eq_top_of_upper_lower (H : Subgroup S) (hu : upper ∈ H) (hl : lower ∈ H) : H = ⊤ := by
  apply top_le_iff.mp
  intro g _
  obtain ⟨i, hi⟩ := SLTwoFiveGenerationData.exists_word g
  rw [← hi]
  exact eval_mem H upper lower hu hl _

/-- Every persistent target is an actual commutator of two persistent inputs generating SL2(F5). -/
theorem isGeneratingGoodSet : IsGeneratingGoodSet Y := by
  intro g hg
  obtain ⟨i, _, hi⟩ := Finset.mem_image.mp hg
  subst g
  have h := all_witnesses i
  refine ⟨(witness i).left, h.1, (witness i).right, h.2.1, h.2.2.1, ?_⟩
  let H := Subgroup.closure ({(witness i).left, (witness i).right} : Set S)
  have ha : (witness i).left ∈ H := Subgroup.subset_closure (Set.mem_insert _ _)
  have hb : (witness i).right ∈ H :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _))
  apply eq_top_of_upper_lower H
  · rw [← h.2.2.2.1]
    exact eval_mem H _ _ ha hb _
  · rw [← h.2.2.2.2]
    exact eval_mem H _ _ ha hb _

/-- In particular every actual element of order six lies in the persistent set. -/
theorem mem_of_order_six (g : S) (hg : orderOf g = 6) : g ∈ Y := by
  apply (targets_iff_powers g).mpr
  left
  refine ⟨?_, ?_, ?_⟩
  · simpa only [hg] using pow_orderOf_eq_one g
  · intro h
    have hd := orderOf_dvd_of_pow_eq_one h
    rw [hg] at hd
    exact (by decide : ¬ 6 ∣ 3) hd
  · intro h
    have hd := orderOf_dvd_of_pow_eq_one h
    rw [hg] at hd
    exact (by decide : ¬ 6 ∣ 2) hd

theorem mem_of_order_ten (g : S) (hg : orderOf g = 10) : g ∈ Y := by
  apply (targets_iff_powers g).mpr
  right
  refine ⟨?_, ?_, ?_⟩
  · simpa only [hg] using pow_orderOf_eq_one g
  · intro h
    have hd := orderOf_dvd_of_pow_eq_one h
    rw [hg] at hd
    exact (by decide : ¬ 10 ∣ 5) hd
  · intro h
    have hd := orderOf_dvd_of_pow_eq_one h
    rw [hg] at hd
    exact (by decide : ¬ 10 ∣ 2) hd

end Kourovka2135.SLTwoFiveGoodSet
