import Kourovka2135.SLTwoPrincipalSeriesAugmentation
import Kourovka2135.SLTwoUnipotentInvariants
import Mathlib.Tactic.Module

/-! The actual augmentation kernel
is generated by the affine indicator and has no proper nonzero SL2-stable
subspace. The proof uses the existing unipotent fixed-vector theorem and
explicit delta differences, without a tensor identification or dimension count.
-/

set_option autoImplicit false
noncomputable section
universe u v

namespace Kourovka2135.SLTwoPrincipalSeries

open SLTwoHomogeneousFunctions

variable (k : Type u) [Field k] {F : Type v} [Field F] (σ : F →+* k)

/-- At weight zero the affine indicator is constant one minus infinity delta. -/
theorem affineIndicator_eq_constants_sub_infinityDelta :
    affineIndicator k σ 0 = constants k σ 1 - infinityDelta k σ 0 := by
  apply (coordinates k σ 0).injective
  rw [map_sub, coordinates_affineIndicator, coordinates_infinityDelta]
  apply Prod.ext
  · change (0 : k) = 1 - 1
    simp
  · funext t
    change (1 : k) = 1 - 0
    simp

section Finite
variable [Fintype F]

@[simp] theorem augmentation_affineIndicator :
    augmentation k σ (affineIndicator k σ 0) = 0 := by
  have hq : (Fintype.card F : k) = 0 := by
    simpa only [map_natCast, map_zero] using congrArg σ (Nat.cast_card_eq_zero F)
  rw [augmentation_coordinates, coordinates_affineIndicator]
  simp [hq]

@[simp] theorem augmentation_infinityDelta :
    augmentation k σ (infinityDelta k σ 0) = 1 := by
  rw [augmentation_coordinates, coordinates_infinityDelta]
  simp

@[simp] theorem augmentation_affineDelta (t : F) :
    augmentation k σ (affineDelta k σ 0 t) = 1 := by
  classical
  rw [augmentation_coordinates, coordinates_affineDelta]
  simp [Pi.single_apply]

/-- The actual augmentation kernel is nonzero, since it contains the affine indicator. -/
theorem augmentation_ker_ne_bot : LinearMap.ker (augmentation k σ) ≠ ⊥ := by
  intro h
  apply affineIndicator_ne_zero k σ 0
  have hA : affineIndicator k σ 0 ∈ LinearMap.ker (augmentation k σ) :=
    augmentation_affineIndicator k σ
  simpa only [h, Submodule.mem_bot] using hA

/-- Infinity delta shows that the actual augmentation kernel is proper. -/
theorem augmentation_ker_ne_top : LinearMap.ker (augmentation k σ) ≠ ⊤ := by
  intro h
  have hD : infinityDelta k σ 0 ∈ LinearMap.ker (augmentation k σ) := by
    rw [h]
    trivial
  change augmentation k σ (infinityDelta k σ 0) = 0 at hD
  rw [augmentation_infinityDelta] at hD
  exact one_ne_zero hD

/-- All actual kernel vectors are linear combinations of the projective delta differences. -/
theorem augmentation_ker_expansion (h : Carrier k σ 0)
    (hh : h ∈ LinearMap.ker (augmentation k σ)) :
    h = ∑ t : F, (coordinates k σ 0 h).2 t •
      (affineDelta k σ 0 t - infinityDelta k σ 0) := by
  have hsum : (coordinates k σ 0 h).1 + ∑ t : F, (coordinates k σ 0 h).2 t = 0 := by
    rw [← augmentation_coordinates]
    exact hh
  have hb : (coordinates k σ 0 h).1 = -(∑ t : F, (coordinates k σ 0 h).2 t) := by
    exact eq_neg_of_add_eq_zero_left hsum
  conv_lhs => rw [coordinate_expansion k σ 0 h]
  rw [hb]
  simp only [smul_sub, Finset.sum_sub_distrib, ← Finset.sum_smul]
  module

end Finite

section CharTwo
variable [CharP k 2]

/-- The Weyl translate of the affine indicator differs at affine zero. -/
theorem weyl_affineIndicator_weightZero :
    representation k σ 0 (SLTwo.weyl F) (affineIndicator k σ 0) =
      constants k σ 1 - affineDelta k σ 0 0 := by
  rw [affineIndicator_eq_constants_sub_infinityDelta, map_sub,
    representation_constants, weyl_infinityDelta]

/-- Subtracting the original vector produces the first projective delta difference. -/
theorem weyl_affineIndicator_sub_weightZero :
    representation k σ 0 (SLTwo.weyl F) (affineIndicator k σ 0) -
      affineIndicator k σ 0 = infinityDelta k σ 0 - affineDelta k σ 0 0 := by
  rw [weyl_affineIndicator_weightZero, affineIndicator_eq_constants_sub_infinityDelta]
  abel

variable [Fintype F]

/-- A stable subspace containing the affine indicator contains the entire augmentation kernel. -/
theorem augmentation_ker_le_of_affineIndicator_mem
    (W : Submodule k (Carrier k σ 0))
    (hstable : ∀ (g : SLTwo.SL2 F) (h : Carrier k σ 0), h ∈ W →
      representation k σ 0 g h ∈ W)
    (hA : affineIndicator k σ 0 ∈ W) :
    LinearMap.ker (augmentation k σ) ≤ W := by
  have hzero : infinityDelta k σ 0 - affineDelta k σ 0 0 ∈ W := by
    have h := W.sub_mem (hstable (SLTwo.weyl F) _ hA) hA
    rwa [weyl_affineIndicator_sub_weightZero] at h
  have hdelta (t : F) : affineDelta k σ 0 t - infinityDelta k σ 0 ∈ W := by
    have h := hstable (SLTwo.uni (-t)) _ hzero
    rw [map_sub, unipotent_infinityDelta, unipotent_affineDelta,
      zero_sub, neg_neg] at h
    simpa only [neg_sub] using W.neg_mem h
  intro h hh
  rw [augmentation_ker_expansion k σ h hh]
  exact W.sum_mem (fun t _ => W.smul_mem _ (hdelta t))

/-- The actual augmentation kernel has no proper nonzero SL2-stable subspace. -/
theorem eq_augmentation_ker_of_ne_bot
    (W : Submodule k (Carrier k σ 0)) (hW : W ≠ ⊥)
    (hWker : W ≤ LinearMap.ker (augmentation k σ))
    (hstable : ∀ (g : SLTwo.SL2 F) (h : Carrier k σ 0), h ∈ W →
      representation k σ 0 g h ∈ W) :
    W = LinearMap.ker (augmentation k σ) := by
  have : CharP F 2 := σ.charP σ.injective 2
  obtain ⟨v, hvW, hv, hfix⟩ :=
    SLTwoUnipotentInvariants.exists_nonzero_unipotent_fixed_mem
      (representation k σ 0) W hW (fun t h hh => hstable (SLTwo.uni t) h hh)
  obtain ⟨a, b, hvab⟩ := (unipotent_fixed_iff k σ 0 v).mp hfix
  have hb : b = 0 := by
    have haug : augmentation k σ v = 0 := hWker hvW
    rw [hvab, map_add, map_smul, map_smul,
      augmentation_affineIndicator, augmentation_infinityDelta] at haug
    simpa using haug
  rw [hb, zero_smul, add_zero] at hvab
  have ha : a ≠ 0 := by
    intro ha
    apply hv
    simpa [ha] using hvab
  have hA : affineIndicator k σ 0 ∈ W := by
    rw [hvab] at hvW
    exact (W.smul_mem_iff ha).mp hvW
  exact le_antisymm hWker
    (augmentation_ker_le_of_affineIndicator_mem k σ W hstable hA)

end CharTwo
end Kourovka2135.SLTwoPrincipalSeries
