import Kourovka2135.GeneratingSets
import Kourovka2135.ClassTwoCommutators
import Mathlib.GroupTheory.SpecificGroups.ZGroup

/-! A finite soluble group generated by p-elements, with a cyclic Sylow
p-subgroup, has p-prime commutator subgroup. This uses the existing cyclic
Sylow commutator-index dichotomy, not a new Hall-Higman assumption.
-/

set_option autoImplicit false
noncomputable section

namespace Kourovka2135.SolubleCyclicSylowCommutator

variable {H : Type*} [Group H] [Finite H]
variable {p : ℕ} [Fact p.Prime]

omit [Finite H] in
/-- If p does not divide the abelianization order, every actual p-element
already lies in the commutator subgroup. -/
theorem mem_commutator_of_pow_prime_pow
    (hindex : ¬ p ∣ (commutator H).index) (x : H) (n : ℕ)
    (hx : x ^ (p ^ n) = 1) : x ∈ commutator H := by
  let q : H →* H ⧸ commutator H := QuotientGroup.mk' (commutator H)
  have hcard : ¬ p ∣ Nat.card (H ⧸ commutator H) := by
    rwa [← Subgroup.index_eq_card]
  have hpow : q x ^ (p ^ n) = 1 := by rw [← map_pow, hx, map_one]
  have horder : orderOf (q x) = 1 :=
    Nat.eq_one_of_dvd_coprimes
      ((Fact.out : p.Prime).coprime_pow_of_not_dvd hcard)
      (orderOf_dvd_natCard (q x)) (orderOf_dvd_iff_pow_eq_one.mpr hpow)
  exact (QuotientGroup.eq_one_iff x).mp (orderOf_eq_one_iff.mp horder)

omit [Finite H] in
/-- A nontrivial soluble group generated by two actual p-elements
has abelianization order divisible by p. -/
theorem prime_dvd_commutator_index [Group.IsSolvable H] [Nontrivial H]
    (a b : H) (m n : ℕ) (ha : a ^ (p ^ m) = 1) (hb : b ^ (p ^ n) = 1)
    (hgen : Subgroup.closure ({a, b} : Set H) = ⊤) : p ∣ (commutator H).index := by
  by_contra hindex
  have ha' := mem_commutator_of_pow_prime_pow hindex a m ha
  have hb' := mem_commutator_of_pow_prime_pow hindex b n hb
  have hle : Subgroup.closure ({a, b} : Set H) ≤ commutator H := by
    apply (Subgroup.closure_le _).mpr
    intro x hx
    rcases Set.mem_insert_iff.mp hx with rfl | hx
    · exact ha'
    · have heq := Set.mem_singleton_iff.mp hx
      subst x
      exact hb'
  rw [hgen] at hle
  exact (ne_of_lt (Group.IsSolvable.commutator_lt_top_of_nontrivial H))
    (top_le_iff.mp hle)

/-- Cyclicity of an actual Sylow subgroup excludes p from the commutator
order once the generating-p-elements force p into the abelianization order. -/
theorem not_dvd_card_commutator [Group.IsSolvable H] [Nontrivial H]
    (P : Sylow p H) [IsCyclic P]
    (a b : H) (m n : ℕ) (ha : a ^ (p ^ m) = 1) (hb : b ^ (p ^ n) = 1)
    (hgen : Subgroup.closure ({a, b} : Set H) = ⊤) :
    ¬ p ∣ Nat.card (commutator H) := by
  rcases P.not_dvd_card_commutator_or_not_dvd_index_commutator with hcard | hindex
  · exact hcard
  · exact False.elim (hindex (prime_dvd_commutator_index a b m n ha hb hgen))

/-- The actual paper commutator of the given generators has p-prime order. -/
theorem not_dvd_orderOf_paperCommutator [Group.IsSolvable H] [Nontrivial H]
    (P : Sylow p H) [IsCyclic P]
    (a b : H) (m n : ℕ) (ha : a ^ (p ^ m) = 1) (hb : b ^ (p ^ n) = 1)
    (hgen : Subgroup.closure ({a, b} : Set H) = ⊤) :
    ¬ p ∣ orderOf (paperCommutator a b) := by
  intro hdiv
  apply not_dvd_card_commutator P a b m n ha hb hgen
  exact hdiv.trans ((commutator H).orderOf_dvd_natCard
    (paperCommutator_mem_commutator a b))

/-- A prime-power commutator of those generators must actually be the identity. -/
theorem paperCommutator_eq_one_of_prime_power [Group.IsSolvable H] [Nontrivial H]
    (P : Sylow p H) [IsCyclic P]
    (a b : H) (m n l : ℕ) (ha : a ^ (p ^ m) = 1) (hb : b ^ (p ^ n) = 1)
    (hgen : Subgroup.closure ({a, b} : Set H) = ⊤)
    (hc : paperCommutator a b ^ (p ^ l) = 1) : paperCommutator a b = 1 := by
  have hcop := (Fact.out : p.Prime).coprime_pow_of_not_dvd (m := l)
    (not_dvd_orderOf_paperCommutator P a b m n ha hb hgen)
  have horder : orderOf (paperCommutator a b) = 1 :=
    Nat.eq_one_of_dvd_coprimes hcop (dvd_refl _)
      (orderOf_dvd_iff_pow_eq_one.mpr hc)
  exact orderOf_eq_one_iff.mp horder

/-- In particular a finite soluble group with a cyclic p-Sylow cannot be
generated by two order-p elements whose actual commutator also has order p. -/
theorem false_of_three_prime_orders [Group.IsSolvable H]
    (P : Sylow p H) [IsCyclic P]
    (a b : H) (ha : orderOf a = p) (hb : orderOf b = p)
    (hgen : Subgroup.closure ({a, b} : Set H) = ⊤)
    (hc : orderOf (paperCommutator a b) = p) : False := by
  have hane : a ≠ 1 := by
    intro h
    have hp1 : p = 1 := by simpa only [h, orderOf_one] using ha.symm
    exact (Fact.out : p.Prime).ne_one hp1
  let : Nontrivial H := ⟨⟨a, 1, hane⟩⟩
  have ha' : a ^ (p ^ 1) = 1 := by
    simpa only [pow_one, ha] using pow_orderOf_eq_one a
  have hb' : b ^ (p ^ 1) = 1 := by
    simpa only [pow_one, hb] using pow_orderOf_eq_one b
  exact not_dvd_orderOf_paperCommutator P a b 1 1 ha' hb' hgen
    (by rw [hc])

end Kourovka2135.SolubleCyclicSylowCommutator
