import Kourovka2135.VerbalSupplement
import Kourovka2135.SylowGeneration
import Kourovka2135.SolubleSupplement

/-!
# Single-value focal generation in finite soluble groups

This proof uses a normal prime-power subgroup with a proper supplement, the
relative verbal decomposition, and Sylow decomposition. It applies to arbitrary
outer commutator words and keeps actual single values throughout.
-/

set_option autoImplicit false
universe u
namespace Kourovka2135
namespace OuterWord

/-- Single word values, viewed as elements of their verbal subgroup. -/
def verbalValues (w : OuterWord) (G : Type u) [Group G] : Set (w.verbalSubgroup G) :=
  {x | (x : G) ∈ w.values G}

/-- Every Sylow subgroup of an outer-word subgroup of a finite soluble group
is generated by single word values in it. -/
theorem valueGeneratedSylows_of_isSolvable (w : OuterWord)
    {G : Type u} [Group G] [Finite G] (hsolv : Group.IsSolvable G) :
    ValueGeneratedSylows (w.verbalValues G) := by
  classical
  let T : ℕ → Prop := fun n =>
    ∀ (K : Type u) [Group K] [Finite K], Nat.card K = n → Group.IsSolvable K →
      ValueGeneratedSylows (w.verbalValues K)
  have main : ∀ n, T n := by
    intro n
    refine Nat.strong_induction_on n ?_
    intro n ih K _ _ hcard hK
    have : Group.IsSolvable K := hK
    rcases subsingleton_or_nontrivial K with htriv | hnontriv
    · let := htriv
      intro q hq S
      exact ⟨∅, Set.empty_subset _, by simp [Subgroup.eq_bot_of_subsingleton]⟩
    · let := hnontriv
      obtain ⟨r, hr, P, M, hPnormal, hP, hM, hsup⟩ :=
        Soluble.exists_normal_pSubgroup_proper_supplement hK
      let : P.Normal := hPnormal
      have hlt : Nat.card M < n := by
        rw [← hcard]
        simpa only [Subgroup.card_top] using
          (Subgroup.card_lt_of_lt (lt_top_iff_ne_top.mpr hM))
      have hMvalues := ih (Nat.card M) hlt M rfl (by infer_instance)
      let D := w.verbalSubgroup K
      let A₀ := w.mixedSubgroup P
      let A : Subgroup D := A₀.subgroupOf D
      let f : w.verbalSubgroup M →* D := {
        toFun := fun x => ⟨M.subtype (x : M),
          w.map_verbalSubgroup_le M.subtype ⟨(x : M), x.property, rfl⟩⟩
        map_one' := rfl
        map_mul' := fun _ _ => rfl }
      let B : Subgroup D := f.range
      have hAD : A₀ ≤ D := w.mixedSubgroup_le_verbal P
      have hAmap : A.map D.subtype = A₀ := Subgroup.map_subgroupOf_eq_of_le hAD
      have hBmap : B.map D.subtype = (w.verbalSubgroup M).map M.subtype := by
        ext x
        constructor
        · rintro ⟨b, ⟨y, rfl⟩, rfl⟩
          exact ⟨(y : M), y.property, rfl⟩
        · rintro ⟨y, hy, rfl⟩
          exact ⟨f ⟨y, hy⟩, ⟨⟨y, hy⟩, rfl⟩, rfl⟩
      have hjoin : A ⊔ B = ⊤ := by
        apply Subgroup.map_injective D.subtype_injective
        rw [Subgroup.map_sup, hAmap, hBmap,
          ← MonoidHom.range_eq_map, D.range_subtype]
        exact (w.verbalSubgroup_eq_mixed_sup P M hsup).symm
      have hAr : IsPGroup r A := (hP.to_le (w.mixedSubgroup_le P)).comap_subtype
      let U : Set D := {x | (x : K) ∈ w.mixedValues P}
      have hUimage : D.subtype '' U = w.mixedValues P := by
        ext x
        refine ⟨fun ⟨y, hy, heq⟩ => heq ▸ hy, fun hx => ?_⟩
        exact ⟨⟨x, w.mem_verbalSubgroup_of_mem_values (w.mixedValues_subset_values P hx)⟩,
          hx, rfl⟩
      have hUgen : Subgroup.closure U = A := by
        apply Subgroup.map_injective D.subtype_injective
        rw [MonoidHom.map_closure, hUimage, hAmap]
        rfl
      have hUsub : U ⊆ w.verbalValues K := by
        intro x hx
        exact w.mixedValues_subset_values P hx
      have hBvalues : ValueGeneratedSylows (B.subtype ⁻¹' w.verbalValues K) := by
        apply (hMvalues.map_surjective f.rangeRestrict f.rangeRestrict_surjective).mono
        rintro _ ⟨x, hx, rfl⟩
        exact w.map_mem_values M.subtype hx
      have hconj : ∀ x ∈ w.verbalValues K, ∀ g : D,
          g * x * g⁻¹ ∈ w.verbalValues K := by
        intro x hx g
        change (g : K) * (x : K) * (g : K)⁻¹ ∈ w.values K
        simpa only [inv_inv] using w.conj_mem_values hx (g : K)⁻¹
      exact valueGeneratedSylows_of_normal_prime_supplement r hr A B hAr hjoin
        hconj ⟨U, hUsub, hUgen⟩ hBvalues
  exact main (Nat.card G) G rfl hsolv

/-- Equality form of the soluble single-value focal theorem. -/
theorem sylow_eq_closure_single_values
    (w : OuterWord) {G : Type u} [Group G] [Finite G]
    (hsolv : Group.IsSolvable G) (p : ℕ) (hp : p.Prime)
    (S : Sylow p (w.verbalSubgroup G)) :
    Subgroup.closure (w.verbalValues G ∩ (S : Set (w.verbalSubgroup G))) =
      (S : Subgroup (w.verbalSubgroup G)) := by
  obtain ⟨X, hX, hgen⟩ := w.valueGeneratedSylows_of_isSolvable hsolv p hp S
  apply le_antisymm
  · apply (Subgroup.closure_le _).mpr
    intro x hx
    exact hx.2
  · rw [← hgen]
    apply Subgroup.closure_mono
    intro x hx
    refine ⟨hX hx, ?_⟩
    change x ∈ (S : Subgroup (w.verbalSubgroup G))
    rw [← hgen]
    exact Subgroup.subset_closure hx

end OuterWord
end Kourovka2135
