import Kourovka2135.SuzukiEightPairedPcData

/-! Actual paired matrix certificate. Generated by generate_paired_upper.py.
Finite data are checked by ordinary kernel proofs, never used as assumptions. -/
set_option autoImplicit false
set_option maxRecDepth 16384
set_option maxHeartbeats 8000000
noncomputable section
namespace Kourovka2135.SuzukiEightPairedPcRelations
open SuzukiEightPairedPcData SuzukiEightCodeField

private theorem square0_codeStep1 : SuzukiEightCoverCodeMatrices.pc0Matrix * SuzukiEightCoverCodeMatrices.pc0Matrix = SuzukiEightCoverCodeForms.raw 13 := by decide +kernel
private theorem square0_coverStep1 : SuzukiEightCoverPcMatrices.pc0Matrix * SuzukiEightCoverPcMatrices.pc0Matrix = SuzukiEightCoverPcForms.raw 13 := by decide +kernel

theorem square0 : pc0 * pc0 = form 13 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc0Matrix * SuzukiEightCoverCodeMatrices.pc0Matrix = (SuzukiEightCoverCodeForms.form 13).val
    rw [SuzukiEightCoverCodeForms.form_val, square0_codeStep1]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc0Matrix * SuzukiEightCoverPcMatrices.pc0Matrix = (SuzukiEightCoverPcForms.form 13).val
    rw [SuzukiEightCoverPcForms.form_val, square0_coverStep1]

private theorem square1_codeStep1 : SuzukiEightCoverCodeMatrices.pc1Matrix * SuzukiEightCoverCodeMatrices.pc1Matrix = SuzukiEightCoverCodeForms.raw 31 := by decide +kernel
private theorem square1_coverStep1 : SuzukiEightCoverPcMatrices.pc1Matrix * SuzukiEightCoverPcMatrices.pc1Matrix = SuzukiEightCoverPcForms.raw 31 := by decide +kernel

theorem square1 : pc1 * pc1 = form 31 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc1Matrix * SuzukiEightCoverCodeMatrices.pc1Matrix = (SuzukiEightCoverCodeForms.form 31).val
    rw [SuzukiEightCoverCodeForms.form_val, square1_codeStep1]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc1Matrix * SuzukiEightCoverPcMatrices.pc1Matrix = (SuzukiEightCoverPcForms.form 31).val
    rw [SuzukiEightCoverPcForms.form_val, square1_coverStep1]

private theorem square2_codeStep1 : SuzukiEightCoverCodeMatrices.pc2Matrix * SuzukiEightCoverCodeMatrices.pc2Matrix = SuzukiEightCoverCodeForms.raw 5 := by decide +kernel
private theorem square2_coverStep1 : SuzukiEightCoverPcMatrices.pc2Matrix * SuzukiEightCoverPcMatrices.pc2Matrix = SuzukiEightCoverPcForms.raw 5 := by decide +kernel

theorem square2 : pc2 * pc2 = form 5 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc2Matrix * SuzukiEightCoverCodeMatrices.pc2Matrix = (SuzukiEightCoverCodeForms.form 5).val
    rw [SuzukiEightCoverCodeForms.form_val, square2_codeStep1]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc2Matrix * SuzukiEightCoverPcMatrices.pc2Matrix = (SuzukiEightCoverPcForms.form 5).val
    rw [SuzukiEightCoverPcForms.form_val, square2_coverStep1]

private theorem square3_codeStep1 : SuzukiEightCoverCodeMatrices.pc3Matrix * SuzukiEightCoverCodeMatrices.pc3Matrix = SuzukiEightCoverCodeForms.raw 0 := by decide +kernel
private theorem square3_coverStep1 : SuzukiEightCoverPcMatrices.pc3Matrix * SuzukiEightCoverPcMatrices.pc3Matrix = SuzukiEightCoverPcForms.raw 0 := by decide +kernel

theorem square3 : pc3 * pc3 = form 0 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc3Matrix * SuzukiEightCoverCodeMatrices.pc3Matrix = (SuzukiEightCoverCodeForms.form 0).val
    rw [SuzukiEightCoverCodeForms.form_val, square3_codeStep1]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc3Matrix * SuzukiEightCoverPcMatrices.pc3Matrix = (SuzukiEightCoverPcForms.form 0).val
    rw [SuzukiEightCoverPcForms.form_val, square3_coverStep1]

private theorem square4_codeStep1 : SuzukiEightCoverCodeMatrices.pc4Matrix * SuzukiEightCoverCodeMatrices.pc4Matrix = SuzukiEightCoverCodeForms.raw 0 := by decide +kernel
private theorem square4_coverStep1 : SuzukiEightCoverPcMatrices.pc4Matrix * SuzukiEightCoverPcMatrices.pc4Matrix = SuzukiEightCoverPcForms.raw 0 := by decide +kernel

theorem square4 : pc4 * pc4 = form 0 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc4Matrix * SuzukiEightCoverCodeMatrices.pc4Matrix = (SuzukiEightCoverCodeForms.form 0).val
    rw [SuzukiEightCoverCodeForms.form_val, square4_codeStep1]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc4Matrix * SuzukiEightCoverPcMatrices.pc4Matrix = (SuzukiEightCoverPcForms.form 0).val
    rw [SuzukiEightCoverPcForms.form_val, square4_coverStep1]

private theorem square5_codeStep1 : SuzukiEightCoverCodeMatrices.pc5Matrix * SuzukiEightCoverCodeMatrices.pc5Matrix = SuzukiEightCoverCodeForms.raw 0 := by decide +kernel
private theorem square5_coverStep1 : SuzukiEightCoverPcMatrices.pc5Matrix * SuzukiEightCoverPcMatrices.pc5Matrix = SuzukiEightCoverPcForms.raw 0 := by decide +kernel

theorem square5 : pc5 * pc5 = form 0 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc5Matrix * SuzukiEightCoverCodeMatrices.pc5Matrix = (SuzukiEightCoverCodeForms.form 0).val
    rw [SuzukiEightCoverCodeForms.form_val, square5_codeStep1]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc5Matrix * SuzukiEightCoverPcMatrices.pc5Matrix = (SuzukiEightCoverPcForms.form 0).val
    rw [SuzukiEightCoverPcForms.form_val, square5_coverStep1]

private theorem square6_codeStep1 : SuzukiEightCoverCodeMatrices.pc6Matrix * SuzukiEightCoverCodeMatrices.pc6Matrix = SuzukiEightCoverCodeForms.raw 0 := by decide +kernel
private theorem square6_coverStep1 : SuzukiEightCoverPcMatrices.pc6Matrix * SuzukiEightCoverPcMatrices.pc6Matrix = SuzukiEightCoverPcForms.raw 0 := by decide +kernel

theorem square6 : pc6 * pc6 = form 0 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc6Matrix * SuzukiEightCoverCodeMatrices.pc6Matrix = (SuzukiEightCoverCodeForms.form 0).val
    rw [SuzukiEightCoverCodeForms.form_val, square6_codeStep1]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc6Matrix * SuzukiEightCoverPcMatrices.pc6Matrix = (SuzukiEightCoverPcForms.form 0).val
    rw [SuzukiEightCoverPcForms.form_val, square6_coverStep1]

private theorem square7_codeStep1 : SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.pc7Matrix = SuzukiEightCoverCodeForms.raw 0 := by decide +kernel
private theorem square7_coverStep1 : SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.pc7Matrix = SuzukiEightCoverPcForms.raw 0 := by decide +kernel

theorem square7 : pc7 * pc7 = form 0 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.pc7Matrix = (SuzukiEightCoverCodeForms.form 0).val
    rw [SuzukiEightCoverCodeForms.form_val, square7_codeStep1]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.pc7Matrix = (SuzukiEightCoverPcForms.form 0).val
    rw [SuzukiEightCoverPcForms.form_val, square7_coverStep1]

private def conjugate0_1_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 6, ofCode 6, ofCode 5; ofCode 0, ofCode 1, ofCode 4, ofCode 3; ofCode 0, ofCode 0, ofCode 1, ofCode 6; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate0_1_codeStep1 : SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc1Matrix = conjugate0_1_codePrefix1 := by decide +kernel
private theorem conjugate0_1_codeStep2 : conjugate0_1_codePrefix1 * SuzukiEightCoverCodeMatrices.pc0Matrix = SuzukiEightCoverCodeForms.raw 70 := by decide +kernel
private def conjugate0_1_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8167052518801806263779495976174674753955999227679944576052435979598149212301772737328488807911757329057923133517574985966037151567673819964616475515776625041677156960669114657963060447730805587650243390901114540062667615285512653179014760407032055940146736251274614412356939156844178524235318996412846623985817363907286223734960995758294881547932818932726393686232655941305194612801872336426780338187267696492560381695610719594026947242542141249736695706527152867758161707599657105341804347504645171507327679566987692120
private theorem conjugate0_1_coverStep1 : SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc1Matrix = conjugate0_1_coverPrefix1 := by decide +kernel
private theorem conjugate0_1_coverStep2 : conjugate0_1_coverPrefix1 * SuzukiEightCoverPcMatrices.pc0Matrix = SuzukiEightCoverPcForms.raw 70 := by decide +kernel

theorem conjugate0_1 : pc0⁻¹ * pc1 * pc0 = form 70 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc1Matrix * SuzukiEightCoverCodeMatrices.pc0Matrix = (SuzukiEightCoverCodeForms.form 70).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate0_1_codeStep1, conjugate0_1_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc1Matrix * SuzukiEightCoverPcMatrices.pc0Matrix = (SuzukiEightCoverPcForms.form 70).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate0_1_coverStep1, conjugate0_1_coverStep2]

private def conjugate0_2_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 5, ofCode 7, ofCode 1; ofCode 0, ofCode 1, ofCode 3, ofCode 3; ofCode 0, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate0_2_codeStep1 : SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc2Matrix = conjugate0_2_codePrefix1 := by decide +kernel
private theorem conjugate0_2_codeStep2 : conjugate0_2_codePrefix1 * SuzukiEightCoverCodeMatrices.pc0Matrix = SuzukiEightCoverCodeForms.raw 59 := by decide +kernel
private def conjugate0_2_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6177595977593437285715357644046824015033783961858581032551298230298180867265816248159087790468527418447665516230432498899766557925072880839071903076829860646726347398125785815013214920060599639542266462057857684848064838675234511175900089736947873754458445994080361000578479610781472294016465066446855056796013817310607171723176897459162320683135711222814816018842579777679448047129352138709996588510752363277340313745267703716391173947223842877163207491801217541008719051887417732944511337537375227925938032257999976073
private theorem conjugate0_2_coverStep1 : SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc2Matrix = conjugate0_2_coverPrefix1 := by decide +kernel
private theorem conjugate0_2_coverStep2 : conjugate0_2_coverPrefix1 * SuzukiEightCoverPcMatrices.pc0Matrix = SuzukiEightCoverPcForms.raw 59 := by decide +kernel

theorem conjugate0_2 : pc0⁻¹ * pc2 * pc0 = form 59 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc2Matrix * SuzukiEightCoverCodeMatrices.pc0Matrix = (SuzukiEightCoverCodeForms.form 59).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate0_2_codeStep1, conjugate0_2_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc2Matrix * SuzukiEightCoverPcMatrices.pc0Matrix = (SuzukiEightCoverPcForms.form 59).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate0_2_coverStep1, conjugate0_2_coverStep2]

private def conjugate0_3_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 4, ofCode 7, ofCode 3; ofCode 0, ofCode 1, ofCode 2, ofCode 4; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate0_3_codeStep1 : SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc3Matrix = conjugate0_3_codePrefix1 := by decide +kernel
private theorem conjugate0_3_codeStep2 : conjugate0_3_codePrefix1 * SuzukiEightCoverCodeMatrices.pc0Matrix = SuzukiEightCoverCodeForms.raw 19 := by decide +kernel
private def conjugate0_3_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 3872740473758270626867915784510740838237504180284483547243314364459688222033185732657731276310707925860915173294600016956148437199296686638271020545970298829694809424844894369143236160374695115156125961277477694316638588765560547165715834483643866592825003399627168263550835173867621608298909764052322151471455594528788248078118536162052756184212703242897578726573823835856636801782058544840381104793773627249009061757973086484910835937594299274996861541095027846663688588952770298773994835768401897233650270144093759203
private theorem conjugate0_3_coverStep1 : SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc3Matrix = conjugate0_3_coverPrefix1 := by decide +kernel
private theorem conjugate0_3_coverStep2 : conjugate0_3_coverPrefix1 * SuzukiEightCoverPcMatrices.pc0Matrix = SuzukiEightCoverPcForms.raw 19 := by decide +kernel

theorem conjugate0_3 : pc0⁻¹ * pc3 * pc0 = form 19 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc3Matrix * SuzukiEightCoverCodeMatrices.pc0Matrix = (SuzukiEightCoverCodeForms.form 19).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate0_3_codeStep1, conjugate0_3_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc3Matrix * SuzukiEightCoverPcMatrices.pc0Matrix = (SuzukiEightCoverPcForms.form 19).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate0_3_coverStep1, conjugate0_3_coverStep2]

private def conjugate0_4_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 4, ofCode 1, ofCode 2; ofCode 0, ofCode 1, ofCode 2, ofCode 2; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate0_4_codeStep1 : SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc4Matrix = conjugate0_4_codePrefix1 := by decide +kernel
private theorem conjugate0_4_codeStep2 : conjugate0_4_codePrefix1 * SuzukiEightCoverCodeMatrices.pc0Matrix = SuzukiEightCoverCodeForms.raw 9 := by decide +kernel
private def conjugate0_4_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4315043358443532237662778304932546960553150744730592943150320982074137352723872879498287976662692187159317330776820552748624155453049067307903711382932506202544247274914446949455452074714903299218147826130920138225754733636343491432080351299160201776120075355988933693749724178292740608861061533119176130434764846699685660153979507850669054448243542608575228165338186695897032634514069753295162293470030855106238906559104295360719436433304706924022583033284043521720932307026238847334156524763373261887524013597222081115
private theorem conjugate0_4_coverStep1 : SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc4Matrix = conjugate0_4_coverPrefix1 := by decide +kernel
private theorem conjugate0_4_coverStep2 : conjugate0_4_coverPrefix1 * SuzukiEightCoverPcMatrices.pc0Matrix = SuzukiEightCoverPcForms.raw 9 := by decide +kernel

theorem conjugate0_4 : pc0⁻¹ * pc4 * pc0 = form 9 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc4Matrix * SuzukiEightCoverCodeMatrices.pc0Matrix = (SuzukiEightCoverCodeForms.form 9).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate0_4_codeStep1, conjugate0_4_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc4Matrix * SuzukiEightCoverPcMatrices.pc0Matrix = (SuzukiEightCoverPcForms.form 9).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate0_4_coverStep1, conjugate0_4_coverStep2]

private def conjugate0_5_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 4, ofCode 2, ofCode 2; ofCode 0, ofCode 1, ofCode 2, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate0_5_codeStep1 : SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix = conjugate0_5_codePrefix1 := by decide +kernel
private theorem conjugate0_5_codeStep2 : conjugate0_5_codePrefix1 * SuzukiEightCoverCodeMatrices.pc0Matrix = SuzukiEightCoverCodeForms.raw 5 := by decide +kernel
private def conjugate0_5_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 3872539820446241143138565307621646544219692285569226298503730363570083627989262866544273380766763525909673968247432019609292900833116597394687027445104842023453133682128601661852680919048760962213498391112594878980850618746935711533717745370545833626719865581674197943655670386311605953533937089720843829592655282949520734793579141501520171549650604977727963783618988871799936945423850239139416016117636140533309991417384968058188443688936490715504704794109468136218537849541094652898407850013277403302951352023501518360
private theorem conjugate0_5_coverStep1 : SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc5Matrix = conjugate0_5_coverPrefix1 := by decide +kernel
private theorem conjugate0_5_coverStep2 : conjugate0_5_coverPrefix1 * SuzukiEightCoverPcMatrices.pc0Matrix = SuzukiEightCoverPcForms.raw 5 := by decide +kernel

theorem conjugate0_5 : pc0⁻¹ * pc5 * pc0 = form 5 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix * SuzukiEightCoverCodeMatrices.pc0Matrix = (SuzukiEightCoverCodeForms.form 5).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate0_5_codeStep1, conjugate0_5_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc5Matrix * SuzukiEightCoverPcMatrices.pc0Matrix = (SuzukiEightCoverPcForms.form 5).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate0_5_coverStep1, conjugate0_5_coverStep2]

private def conjugate0_6_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 4, ofCode 3, ofCode 7; ofCode 0, ofCode 1, ofCode 2, ofCode 0; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate0_6_codeStep1 : SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix = conjugate0_6_codePrefix1 := by decide +kernel
private theorem conjugate0_6_codeStep2 : conjugate0_6_codePrefix1 * SuzukiEightCoverCodeMatrices.pc0Matrix = SuzukiEightCoverCodeForms.raw 2 := by decide +kernel
private def conjugate0_6_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 808955476134381437091033666055308391442121117305708070900036829242825888449954834705076374341105821086077605627831967344134805703167391727562787922367473727398047745292216432526834410581038128767668197843060106024815513382655787088807265263136066882101165524448895301110259520058214004871969164592678973839312092830371325930520420813845387885354027674128317417913475442601068164036397874190171221470561870314702164345690856606011335636109196309176652345641157204776948569203426808035065450206228304460887340806706612322
private theorem conjugate0_6_coverStep1 : SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc6Matrix = conjugate0_6_coverPrefix1 := by decide +kernel
private theorem conjugate0_6_coverStep2 : conjugate0_6_coverPrefix1 * SuzukiEightCoverPcMatrices.pc0Matrix = SuzukiEightCoverPcForms.raw 2 := by decide +kernel

theorem conjugate0_6 : pc0⁻¹ * pc6 * pc0 = form 2 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix * SuzukiEightCoverCodeMatrices.pc0Matrix = (SuzukiEightCoverCodeForms.form 2).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate0_6_codeStep1, conjugate0_6_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc6Matrix * SuzukiEightCoverPcMatrices.pc0Matrix = (SuzukiEightCoverPcForms.form 2).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate0_6_coverStep1, conjugate0_6_coverStep2]

private def conjugate0_7_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 4, ofCode 3, ofCode 7; ofCode 0, ofCode 1, ofCode 2, ofCode 0; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate0_7_codeStep1 : SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix = conjugate0_7_codePrefix1 := by decide +kernel
private theorem conjugate0_7_codeStep2 : conjugate0_7_codePrefix1 * SuzukiEightCoverCodeMatrices.pc0Matrix = SuzukiEightCoverCodeForms.raw 1 := by decide +kernel
private def conjugate0_7_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 1049679648467924921048276479210339725177007082992371822119498394584716450654743296711444310742795878860380601294280979168044926808947678953160394076122476982142868828427974815577936895234468964028794411283368427069177349368805256105410562730537022360745284553188090673078273257676851972823679044089845572480621290625876104997048389577740282286603887438645338997381668890961341750478571518644901162609262534822917691536089402295534631430011127586933362577336452840770389735626675510333076972851902279274854587941626888412
private theorem conjugate0_7_coverStep1 : SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc7Matrix = conjugate0_7_coverPrefix1 := by decide +kernel
private theorem conjugate0_7_coverStep2 : conjugate0_7_coverPrefix1 * SuzukiEightCoverPcMatrices.pc0Matrix = SuzukiEightCoverPcForms.raw 1 := by decide +kernel

theorem conjugate0_7 : pc0⁻¹ * pc7 * pc0 = form 1 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc0Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.pc0Matrix = (SuzukiEightCoverCodeForms.form 1).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate0_7_codeStep1, conjugate0_7_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc0Inverse * SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.pc0Matrix = (SuzukiEightCoverPcForms.form 1).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate0_7_coverStep1, conjugate0_7_coverStep2]

private def conjugate1_2_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 3, ofCode 5, ofCode 1; ofCode 0, ofCode 1, ofCode 7, ofCode 7; ofCode 0, ofCode 0, ofCode 1, ofCode 3; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate1_2_codeStep1 : SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc2Matrix = conjugate1_2_codePrefix1 := by decide +kernel
private theorem conjugate1_2_codeStep2 : conjugate1_2_codePrefix1 * SuzukiEightCoverCodeMatrices.pc1Matrix = SuzukiEightCoverCodeForms.raw 49 := by decide +kernel
private def conjugate1_2_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8289522282733556018450269918769236408529057185319820037367656748679388866478021738793878420840350095851410922826272180447256562662640026658730793080217876301521681675808329731458581025576231993868290951410878106646729089419117105926448010418274706210453234065855171428376769281701516469289503981427114833648840896049999585384173878426557959160903947052360841391521095873743888409201162925279502115594117502757564274233209195407667764494454782433743205513374549464973384189367772123677562716506832583221231980410210161163
private theorem conjugate1_2_coverStep1 : SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc2Matrix = conjugate1_2_coverPrefix1 := by decide +kernel
private theorem conjugate1_2_coverStep2 : conjugate1_2_coverPrefix1 * SuzukiEightCoverPcMatrices.pc1Matrix = SuzukiEightCoverPcForms.raw 49 := by decide +kernel

theorem conjugate1_2 : pc1⁻¹ * pc2 * pc1 = form 49 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc2Matrix * SuzukiEightCoverCodeMatrices.pc1Matrix = (SuzukiEightCoverCodeForms.form 49).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate1_2_codeStep1, conjugate1_2_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc2Matrix * SuzukiEightCoverPcMatrices.pc1Matrix = (SuzukiEightCoverPcForms.form 49).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate1_2_coverStep1, conjugate1_2_coverStep2]

private def conjugate1_3_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 2, ofCode 3, ofCode 4; ofCode 0, ofCode 1, ofCode 6, ofCode 4; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate1_3_codeStep1 : SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc3Matrix = conjugate1_3_codePrefix1 := by decide +kernel
private theorem conjugate1_3_codeStep2 : conjugate1_3_codePrefix1 * SuzukiEightCoverCodeMatrices.pc1Matrix = SuzukiEightCoverCodeForms.raw 17 := by decide +kernel
private def conjugate1_3_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7506192943034629168851640473996261025560779080658173402140116670333625161815280865938264591326512741873319855956737744137943716682348844851135120192224490753892761119794713551437484101118455577344278954278101441059722483493105002502715095227497599741085915737100665612665446477409909085278946437215093615207388908870540293933566722578650368852966184796411524062342353875911669338769796139948402853765311777108385560098862159540781610807891678653953674807917240877619462064019894797552092362423066303747889157393953282
private theorem conjugate1_3_coverStep1 : SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc3Matrix = conjugate1_3_coverPrefix1 := by decide +kernel
private theorem conjugate1_3_coverStep2 : conjugate1_3_coverPrefix1 * SuzukiEightCoverPcMatrices.pc1Matrix = SuzukiEightCoverPcForms.raw 17 := by decide +kernel

theorem conjugate1_3 : pc1⁻¹ * pc3 * pc1 = form 17 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc3Matrix * SuzukiEightCoverCodeMatrices.pc1Matrix = (SuzukiEightCoverCodeForms.form 17).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate1_3_codeStep1, conjugate1_3_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc3Matrix * SuzukiEightCoverPcMatrices.pc1Matrix = (SuzukiEightCoverPcForms.form 17).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate1_3_coverStep1, conjugate1_3_coverStep2]

private def conjugate1_4_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 2, ofCode 5, ofCode 7; ofCode 0, ofCode 1, ofCode 6, ofCode 2; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate1_4_codeStep1 : SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc4Matrix = conjugate1_4_codePrefix1 := by decide +kernel
private theorem conjugate1_4_codeStep2 : conjugate1_4_codePrefix1 * SuzukiEightCoverCodeMatrices.pc1Matrix = SuzukiEightCoverCodeForms.raw 10 := by decide +kernel
private def conjugate1_4_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6746265862868519898578627790758613037229905600683108780243885726386608109905677755996556921736447788224931864484442147137256861534743819275448449381727291519292398861424454501531951177160156844267641329910490712157346542468087858708479021198782520692269243020342624009290937674797711797502728755894687175625492331483166400753319887504834100131884672710409807597978476034563120457904908690227264230237902155008136065212210721401786081515716807973742837510200964427973378037832895536458403481106499310684285185270567552154
private theorem conjugate1_4_coverStep1 : SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc4Matrix = conjugate1_4_coverPrefix1 := by decide +kernel
private theorem conjugate1_4_coverStep2 : conjugate1_4_coverPrefix1 * SuzukiEightCoverPcMatrices.pc1Matrix = SuzukiEightCoverPcForms.raw 10 := by decide +kernel

theorem conjugate1_4 : pc1⁻¹ * pc4 * pc1 = form 10 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc4Matrix * SuzukiEightCoverCodeMatrices.pc1Matrix = (SuzukiEightCoverCodeForms.form 10).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate1_4_codeStep1, conjugate1_4_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc4Matrix * SuzukiEightCoverPcMatrices.pc1Matrix = (SuzukiEightCoverPcForms.form 10).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate1_4_coverStep1, conjugate1_4_coverStep2]

private def conjugate1_5_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 2, ofCode 6, ofCode 6; ofCode 0, ofCode 1, ofCode 6, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate1_5_codeStep1 : SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix = conjugate1_5_codePrefix1 := by decide +kernel
private theorem conjugate1_5_codeStep2 : conjugate1_5_codePrefix1 * SuzukiEightCoverCodeMatrices.pc1Matrix = SuzukiEightCoverCodeForms.raw 7 := by decide +kernel
private def conjugate1_5_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 1063871381035803703899634156756562011803227984548955720486441696181024946445479597780817599479636608565052118237783688836512311919720644539054969362024383710597858236369164220072161678633502969474728275651699170900173175871379828152222913098221623427944249863300968019856335351461321035448135918745371801110717020488995035665219527781332198467901466743390735746205196602336921784557881156306248232252033180114454999106993506891121012058704140253606336489395736305963859887715536432511663153632314955116924850969686840929
private theorem conjugate1_5_coverStep1 : SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc5Matrix = conjugate1_5_coverPrefix1 := by decide +kernel
private theorem conjugate1_5_coverStep2 : conjugate1_5_coverPrefix1 * SuzukiEightCoverPcMatrices.pc1Matrix = SuzukiEightCoverPcForms.raw 7 := by decide +kernel

theorem conjugate1_5 : pc1⁻¹ * pc5 * pc1 = form 7 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix * SuzukiEightCoverCodeMatrices.pc1Matrix = (SuzukiEightCoverCodeForms.form 7).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate1_5_codeStep1, conjugate1_5_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc5Matrix * SuzukiEightCoverPcMatrices.pc1Matrix = (SuzukiEightCoverPcForms.form 7).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate1_5_coverStep1, conjugate1_5_coverStep2]

private def conjugate1_6_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 2, ofCode 7, ofCode 5; ofCode 0, ofCode 1, ofCode 6, ofCode 0; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate1_6_codeStep1 : SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix = conjugate1_6_codePrefix1 := by decide +kernel
private theorem conjugate1_6_codeStep2 : conjugate1_6_codePrefix1 * SuzukiEightCoverCodeMatrices.pc1Matrix = SuzukiEightCoverCodeForms.raw 2 := by decide +kernel
private def conjugate1_6_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4584230787604600315503502660351285578233946909011688131311846459170668298156046724195868736908444810684487668519176949446590359961814511094656695888392068293712217965739441808559146248217473782801484531602117066374459354962883811498363161268450798021636065354736567382431323548610057870199478985151142433996564337877611744979759157554438123986553798827968358238429285722910565560250768489755625326277041844950052161199262222760367540091476771402814982870620427620933986198591461989794106683965869900604244701589812314636
private theorem conjugate1_6_coverStep1 : SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc6Matrix = conjugate1_6_coverPrefix1 := by decide +kernel
private theorem conjugate1_6_coverStep2 : conjugate1_6_coverPrefix1 * SuzukiEightCoverPcMatrices.pc1Matrix = SuzukiEightCoverPcForms.raw 2 := by decide +kernel

theorem conjugate1_6 : pc1⁻¹ * pc6 * pc1 = form 2 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix * SuzukiEightCoverCodeMatrices.pc1Matrix = (SuzukiEightCoverCodeForms.form 2).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate1_6_codeStep1, conjugate1_6_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc6Matrix * SuzukiEightCoverPcMatrices.pc1Matrix = (SuzukiEightCoverPcForms.form 2).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate1_6_coverStep1, conjugate1_6_coverStep2]

private def conjugate1_7_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 2, ofCode 7, ofCode 5; ofCode 0, ofCode 1, ofCode 6, ofCode 0; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate1_7_codeStep1 : SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix = conjugate1_7_codePrefix1 := by decide +kernel
private theorem conjugate1_7_codeStep2 : conjugate1_7_codePrefix1 * SuzukiEightCoverCodeMatrices.pc1Matrix = SuzukiEightCoverCodeForms.raw 1 := by decide +kernel
private def conjugate1_7_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6416320880624394402548842211853028376936941969067492745708396969606350391250938111168051083598844184955345896852829803932023410353180340028058343413015960304588993347089672051747364442236517913045089291646349821935536221267510767210506308436770354932751448386126495138744459324742503181052566458252606994182385796851629778858786822711303068660101825328932089806831811891712914038492322685633589756129201102816044091935099980315739802247455322123533992550162097314820803980999570726396968836203177114596007725271762605080
private theorem conjugate1_7_coverStep1 : SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc7Matrix = conjugate1_7_coverPrefix1 := by decide +kernel
private theorem conjugate1_7_coverStep2 : conjugate1_7_coverPrefix1 * SuzukiEightCoverPcMatrices.pc1Matrix = SuzukiEightCoverPcForms.raw 1 := by decide +kernel

theorem conjugate1_7 : pc1⁻¹ * pc7 * pc1 = form 1 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc1Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.pc1Matrix = (SuzukiEightCoverCodeForms.form 1).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate1_7_codeStep1, conjugate1_7_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc1Inverse * SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.pc1Matrix = (SuzukiEightCoverPcForms.form 1).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate1_7_coverStep1, conjugate1_7_coverStep2]

private def conjugate2_3_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 1, ofCode 5, ofCode 7; ofCode 0, ofCode 1, ofCode 1, ofCode 4; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate2_3_codeStep1 : SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc3Matrix = conjugate2_3_codePrefix1 := by decide +kernel
private theorem conjugate2_3_codeStep2 : conjugate2_3_codePrefix1 * SuzukiEightCoverCodeMatrices.pc2Matrix = SuzukiEightCoverCodeForms.raw 19 := by decide +kernel
private def conjugate2_3_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 1906706157501355257188586668324903877626938805222532169156419444317006449301890385860134373080966397032843523690925686772925828306288810691270861531096268625039104454773598974037979578548665931868328922038699632416461316362598654681914881420726350761958080364019706517970058668890459391267526938679832301460026072460210701142653991066178152229545959700071175449339459771388548944480868746189706040132963203588240178510795487429981433656998749082299011562572022362188579752888260846254701408305905421043086594005412123292
private theorem conjugate2_3_coverStep1 : SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc3Matrix = conjugate2_3_coverPrefix1 := by decide +kernel
private theorem conjugate2_3_coverStep2 : conjugate2_3_coverPrefix1 * SuzukiEightCoverPcMatrices.pc2Matrix = SuzukiEightCoverPcForms.raw 19 := by decide +kernel

theorem conjugate2_3 : pc2⁻¹ * pc3 * pc2 = form 19 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc3Matrix * SuzukiEightCoverCodeMatrices.pc2Matrix = (SuzukiEightCoverCodeForms.form 19).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate2_3_codeStep1, conjugate2_3_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc3Matrix * SuzukiEightCoverPcMatrices.pc2Matrix = (SuzukiEightCoverPcForms.form 19).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate2_3_coverStep1, conjugate2_3_coverStep2]

private def conjugate2_4_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 1, ofCode 3, ofCode 5; ofCode 0, ofCode 1, ofCode 1, ofCode 2; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate2_4_codeStep1 : SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc4Matrix = conjugate2_4_codePrefix1 := by decide +kernel
private theorem conjugate2_4_codeStep2 : conjugate2_4_codePrefix1 * SuzukiEightCoverCodeMatrices.pc2Matrix = SuzukiEightCoverCodeForms.raw 10 := by decide +kernel
private def conjugate2_4_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8076031487726270296300697530669011423283870862615408620662481542638789556961323477186646036137531059780047741559047521278981201263719514317882363536498743449126130309406400598730198135298946185383943706116983494430752536183270275797608582432012373856319997909987183048123686470452200526946384684494193612938508832850770846051038585165335195958867495118226802656989001442212105236275148370131626790863018567421574408672493465610977774445074278387153291794732207851389996461391221192365552181265132585801688408814935607504
private theorem conjugate2_4_coverStep1 : SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc4Matrix = conjugate2_4_coverPrefix1 := by decide +kernel
private theorem conjugate2_4_coverStep2 : conjugate2_4_coverPrefix1 * SuzukiEightCoverPcMatrices.pc2Matrix = SuzukiEightCoverPcForms.raw 10 := by decide +kernel

theorem conjugate2_4 : pc2⁻¹ * pc4 * pc2 = form 10 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc4Matrix * SuzukiEightCoverCodeMatrices.pc2Matrix = (SuzukiEightCoverCodeForms.form 10).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate2_4_codeStep1, conjugate2_4_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc4Matrix * SuzukiEightCoverPcMatrices.pc2Matrix = (SuzukiEightCoverPcForms.form 10).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate2_4_coverStep1, conjugate2_4_coverStep2]

private def conjugate2_5_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 1, ofCode 0, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate2_5_codeStep1 : SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix = conjugate2_5_codePrefix1 := by decide +kernel
private theorem conjugate2_5_codeStep2 : conjugate2_5_codePrefix1 * SuzukiEightCoverCodeMatrices.pc2Matrix = SuzukiEightCoverCodeForms.raw 4 := by decide +kernel
private def conjugate2_5_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7806834468180618769810332288530306503859122918450609072190199617833083034284707968245005280505842022527764526277871636293905685455838333713816605740366388513930812581879445476928938647846931628089634396054035770375131171975409856220229128671796120941042183023936376449442151817209828861235612943669155145224208747566214806490376560526842105289674383123097113572565936125297291767665179786094040649659078903561520305059191950943184028855267265056461623679045819643927819477015697302846064749919350237536708418766104728859
private theorem conjugate2_5_coverStep1 : SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc5Matrix = conjugate2_5_coverPrefix1 := by decide +kernel
private theorem conjugate2_5_coverStep2 : conjugate2_5_coverPrefix1 * SuzukiEightCoverPcMatrices.pc2Matrix = SuzukiEightCoverPcForms.raw 4 := by decide +kernel

theorem conjugate2_5 : pc2⁻¹ * pc5 * pc2 = form 4 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix * SuzukiEightCoverCodeMatrices.pc2Matrix = (SuzukiEightCoverCodeForms.form 4).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate2_5_codeStep1, conjugate2_5_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc5Matrix * SuzukiEightCoverPcMatrices.pc2Matrix = (SuzukiEightCoverPcForms.form 4).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate2_5_coverStep1, conjugate2_5_coverStep2]

private def conjugate2_6_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 1, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate2_6_codeStep1 : SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix = conjugate2_6_codePrefix1 := by decide +kernel
private theorem conjugate2_6_codeStep2 : conjugate2_6_codePrefix1 * SuzukiEightCoverCodeMatrices.pc2Matrix = SuzukiEightCoverCodeForms.raw 2 := by decide +kernel
private def conjugate2_6_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 813759944787513087807388642357571605165496881424449293267433036973285409885873582547247504922464888286909519767268039451710545440855043894669883593198116711666389768030720294009415306600891563291241839100603151836351062825294242723084065856375197271221145017448532548729006265303116595916208728024494478634709020869285127928571003554360090301605446949678203285629836455396077418669050027422289486733859950944165139040533062201250092432174662426120840019079928811828760901058134922607741799149539243440311068710595006548
private theorem conjugate2_6_coverStep1 : SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc6Matrix = conjugate2_6_coverPrefix1 := by decide +kernel
private theorem conjugate2_6_coverStep2 : conjugate2_6_coverPrefix1 * SuzukiEightCoverPcMatrices.pc2Matrix = SuzukiEightCoverPcForms.raw 2 := by decide +kernel

theorem conjugate2_6 : pc2⁻¹ * pc6 * pc2 = form 2 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix * SuzukiEightCoverCodeMatrices.pc2Matrix = (SuzukiEightCoverCodeForms.form 2).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate2_6_codeStep1, conjugate2_6_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc6Matrix * SuzukiEightCoverPcMatrices.pc2Matrix = (SuzukiEightCoverPcForms.form 2).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate2_6_coverStep1, conjugate2_6_coverStep2]

private def conjugate2_7_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 1, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate2_7_codeStep1 : SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix = conjugate2_7_codePrefix1 := by decide +kernel
private theorem conjugate2_7_codeStep2 : conjugate2_7_codePrefix1 * SuzukiEightCoverCodeMatrices.pc2Matrix = SuzukiEightCoverCodeForms.raw 1 := by decide +kernel
private def conjugate2_7_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 502832925036724755271518195981540006552951487879809331097534052423843811408807916625454706001835767460012646902514289522418387821648960103395473355874025240443337474090914865529193108125160592437655758226656974947311059924554503268773608615475461679871830279490630962122754414475669929550855228803426222993349482078577268540832498936088222708505110453974688551003280654424722968767227310060767604747816250050607387583376352321659362325987388372007225658099784852255873715975406219542749337211154062659667264112135911650
private theorem conjugate2_7_coverStep1 : SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc7Matrix = conjugate2_7_coverPrefix1 := by decide +kernel
private theorem conjugate2_7_coverStep2 : conjugate2_7_coverPrefix1 * SuzukiEightCoverPcMatrices.pc2Matrix = SuzukiEightCoverPcForms.raw 1 := by decide +kernel

theorem conjugate2_7 : pc2⁻¹ * pc7 * pc2 = form 1 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc2Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.pc2Matrix = (SuzukiEightCoverCodeForms.form 1).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate2_7_codeStep1, conjugate2_7_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc2Inverse * SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.pc2Matrix = (SuzukiEightCoverPcForms.form 1).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate2_7_coverStep1, conjugate2_7_coverStep2]

private def conjugate3_4_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 6, ofCode 4; ofCode 0, ofCode 1, ofCode 0, ofCode 6; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate3_4_codeStep1 : SuzukiEightCoverCodeMatrices.pc3Inverse * SuzukiEightCoverCodeMatrices.pc4Matrix = conjugate3_4_codePrefix1 := by decide +kernel
private theorem conjugate3_4_codeStep2 : conjugate3_4_codePrefix1 * SuzukiEightCoverCodeMatrices.pc3Matrix = SuzukiEightCoverCodeForms.raw 8 := by decide +kernel
private def conjugate3_4_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 3872250373254238702143579266966375851939730107680799143864150377944616407637441681232846670433585610549013875070997560424366428393361561334451451960375439006933591297685009859186007651258710674580739419100572864042535101689314736991536378476485768089292528167852409288896220516394290075045629942052872082670332304441731075006973860724966911703393304817508606739649710840115712622646487009002430525234931388040918132557728765533296367031937286312049686520323190233019304809777551444322090505243884826108707529886047455257
private theorem conjugate3_4_coverStep1 : SuzukiEightCoverPcMatrices.pc3Inverse * SuzukiEightCoverPcMatrices.pc4Matrix = conjugate3_4_coverPrefix1 := by decide +kernel
private theorem conjugate3_4_coverStep2 : conjugate3_4_coverPrefix1 * SuzukiEightCoverPcMatrices.pc3Matrix = SuzukiEightCoverPcForms.raw 8 := by decide +kernel

theorem conjugate3_4 : pc3⁻¹ * pc4 * pc3 = form 8 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc3Inverse * SuzukiEightCoverCodeMatrices.pc4Matrix * SuzukiEightCoverCodeMatrices.pc3Matrix = (SuzukiEightCoverCodeForms.form 8).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate3_4_codeStep1, conjugate3_4_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc3Inverse * SuzukiEightCoverPcMatrices.pc4Matrix * SuzukiEightCoverPcMatrices.pc3Matrix = (SuzukiEightCoverPcForms.form 8).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate3_4_coverStep1, conjugate3_4_coverStep2]

private def conjugate3_5_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 5, ofCode 3; ofCode 0, ofCode 1, ofCode 0, ofCode 5; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate3_5_codeStep1 : SuzukiEightCoverCodeMatrices.pc3Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix = conjugate3_5_codePrefix1 := by decide +kernel
private theorem conjugate3_5_codeStep2 : conjugate3_5_codePrefix1 * SuzukiEightCoverCodeMatrices.pc3Matrix = SuzukiEightCoverCodeForms.raw 4 := by decide +kernel
private def conjugate3_5_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4057697524973959106181758919787427671786304703866084413863449300173487808972343342054769881387561190422115986058135078164900561573325820199350599841526612834698329908161040542712953188506357999766758855797899902926474287252744104506966811417107315013248775559784610056013900245252250939066624058200592650531178253530846444291498350870587459018648043363746645645001271538440932442604565407206563564046116807240894665878900181781896776763694925734543801855488626415301794314797917529827316863710421961402174074973166645256
private theorem conjugate3_5_coverStep1 : SuzukiEightCoverPcMatrices.pc3Inverse * SuzukiEightCoverPcMatrices.pc5Matrix = conjugate3_5_coverPrefix1 := by decide +kernel
private theorem conjugate3_5_coverStep2 : conjugate3_5_coverPrefix1 * SuzukiEightCoverPcMatrices.pc3Matrix = SuzukiEightCoverPcForms.raw 4 := by decide +kernel

theorem conjugate3_5 : pc3⁻¹ * pc5 * pc3 = form 4 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc3Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix * SuzukiEightCoverCodeMatrices.pc3Matrix = (SuzukiEightCoverCodeForms.form 4).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate3_5_codeStep1, conjugate3_5_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc3Inverse * SuzukiEightCoverPcMatrices.pc5Matrix * SuzukiEightCoverPcMatrices.pc3Matrix = (SuzukiEightCoverPcForms.form 4).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate3_5_coverStep1, conjugate3_5_coverStep2]

private def conjugate3_6_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 4, ofCode 2; ofCode 0, ofCode 1, ofCode 0, ofCode 4; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate3_6_codeStep1 : SuzukiEightCoverCodeMatrices.pc3Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix = conjugate3_6_codePrefix1 := by decide +kernel
private theorem conjugate3_6_codeStep2 : conjugate3_6_codePrefix1 * SuzukiEightCoverCodeMatrices.pc3Matrix = SuzukiEightCoverCodeForms.raw 2 := by decide +kernel
private def conjugate3_6_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7599694225153705448322000705710084047240864414538137319560858364665737216538811739718882206672060832934701574591566849535322195394328639288076056662304963598450995686005699870394596632049169516693536635872934934902520802437851124759486429140354631150639650034460790133040220168582018427849389375269363036922614601649911948882888444755202800511773673161244953463671457575650324479743288307943119503000738632508961256621139002662954752571583040468528717845431982061981546187043820833285941375095359230248473491796649910305
private theorem conjugate3_6_coverStep1 : SuzukiEightCoverPcMatrices.pc3Inverse * SuzukiEightCoverPcMatrices.pc6Matrix = conjugate3_6_coverPrefix1 := by decide +kernel
private theorem conjugate3_6_coverStep2 : conjugate3_6_coverPrefix1 * SuzukiEightCoverPcMatrices.pc3Matrix = SuzukiEightCoverPcForms.raw 2 := by decide +kernel

theorem conjugate3_6 : pc3⁻¹ * pc6 * pc3 = form 2 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc3Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix * SuzukiEightCoverCodeMatrices.pc3Matrix = (SuzukiEightCoverCodeForms.form 2).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate3_6_codeStep1, conjugate3_6_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc3Inverse * SuzukiEightCoverPcMatrices.pc6Matrix * SuzukiEightCoverPcMatrices.pc3Matrix = (SuzukiEightCoverPcForms.form 2).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate3_6_coverStep1, conjugate3_6_coverStep2]

private def conjugate3_7_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 4, ofCode 2; ofCode 0, ofCode 1, ofCode 0, ofCode 4; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate3_7_codeStep1 : SuzukiEightCoverCodeMatrices.pc3Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix = conjugate3_7_codePrefix1 := by decide +kernel
private theorem conjugate3_7_codeStep2 : conjugate3_7_codePrefix1 * SuzukiEightCoverCodeMatrices.pc3Matrix = SuzukiEightCoverCodeForms.raw 1 := by decide +kernel
private def conjugate3_7_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 1981519942166193259453490135451677711303399182557062187660176192214422789875175887602985978193997113782253760340558908227745264969189064723912927593366330435441921496722724224217972502178037429854992437827817568500423925950137171842953635977884101628983897343616382863882964175184575349254524400736862457182710731085828722021445630167981202318428289311699851902760815901482350259467739185179140955163834645966321826440769504613981100734223936885668144268046853887117857322174283193495328077554458597560767933154284868811
private theorem conjugate3_7_coverStep1 : SuzukiEightCoverPcMatrices.pc3Inverse * SuzukiEightCoverPcMatrices.pc7Matrix = conjugate3_7_coverPrefix1 := by decide +kernel
private theorem conjugate3_7_coverStep2 : conjugate3_7_coverPrefix1 * SuzukiEightCoverPcMatrices.pc3Matrix = SuzukiEightCoverPcForms.raw 1 := by decide +kernel

theorem conjugate3_7 : pc3⁻¹ * pc7 * pc3 = form 1 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc3Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.pc3Matrix = (SuzukiEightCoverCodeForms.form 1).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate3_7_codeStep1, conjugate3_7_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc3Inverse * SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.pc3Matrix = (SuzukiEightCoverPcForms.form 1).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate3_7_coverStep1, conjugate3_7_coverStep2]

private def conjugate4_5_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 3, ofCode 7; ofCode 0, ofCode 1, ofCode 0, ofCode 3; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate4_5_codeStep1 : SuzukiEightCoverCodeMatrices.pc4Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix = conjugate4_5_codePrefix1 := by decide +kernel
private theorem conjugate4_5_codeStep2 : conjugate4_5_codePrefix1 * SuzukiEightCoverCodeMatrices.pc4Matrix = SuzukiEightCoverCodeForms.raw 4 := by decide +kernel
private def conjugate4_5_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2430979481353808232903414021118752960337979389827413284744112462163815357084486589692402400580339080015295532432923342597138384928381683178490290478798719705579250305555902453620120362233333333911238140604832818074816156326215629356047235345811854374716325550370456623740509305900481625527014227397863846718954844247585862268318085225231224007027412914041541114294305966650279274605773240561914861908728704921745380811634380096791876235779194753525824727575348818983218477137627366743948610117161311462693467071806215328
private theorem conjugate4_5_coverStep1 : SuzukiEightCoverPcMatrices.pc4Inverse * SuzukiEightCoverPcMatrices.pc5Matrix = conjugate4_5_coverPrefix1 := by decide +kernel
private theorem conjugate4_5_coverStep2 : conjugate4_5_coverPrefix1 * SuzukiEightCoverPcMatrices.pc4Matrix = SuzukiEightCoverPcForms.raw 4 := by decide +kernel

theorem conjugate4_5 : pc4⁻¹ * pc5 * pc4 = form 4 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc4Inverse * SuzukiEightCoverCodeMatrices.pc5Matrix * SuzukiEightCoverCodeMatrices.pc4Matrix = (SuzukiEightCoverCodeForms.form 4).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate4_5_codeStep1, conjugate4_5_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc4Inverse * SuzukiEightCoverPcMatrices.pc5Matrix * SuzukiEightCoverPcMatrices.pc4Matrix = (SuzukiEightCoverPcForms.form 4).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate4_5_coverStep1, conjugate4_5_coverStep2]

private def conjugate4_6_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 2, ofCode 6; ofCode 0, ofCode 1, ofCode 0, ofCode 2; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate4_6_codeStep1 : SuzukiEightCoverCodeMatrices.pc4Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix = conjugate4_6_codePrefix1 := by decide +kernel
private theorem conjugate4_6_codeStep2 : conjugate4_6_codePrefix1 * SuzukiEightCoverCodeMatrices.pc4Matrix = SuzukiEightCoverCodeForms.raw 2 := by decide +kernel
private def conjugate4_6_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4795482287909380944980013573776806246641634304202891359123626913761495974170952402676384342133725063442442557870713216857116290280623712171677314349362070229818588903495291117543762644333449786276364914221146954265085533445660687445511906157344606514036728891985366651317656170465127627453390848809839409847055842094863385579035624506030021655121119640208216549191251469905020454097754813749320342363061879844101734106889581256004606432952100837280021278428826404841110867613967071637743886586853450971720836261683479619
private theorem conjugate4_6_coverStep1 : SuzukiEightCoverPcMatrices.pc4Inverse * SuzukiEightCoverPcMatrices.pc6Matrix = conjugate4_6_coverPrefix1 := by decide +kernel
private theorem conjugate4_6_coverStep2 : conjugate4_6_coverPrefix1 * SuzukiEightCoverPcMatrices.pc4Matrix = SuzukiEightCoverPcForms.raw 2 := by decide +kernel

theorem conjugate4_6 : pc4⁻¹ * pc6 * pc4 = form 2 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc4Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix * SuzukiEightCoverCodeMatrices.pc4Matrix = (SuzukiEightCoverCodeForms.form 2).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate4_6_codeStep1, conjugate4_6_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc4Inverse * SuzukiEightCoverPcMatrices.pc6Matrix * SuzukiEightCoverPcMatrices.pc4Matrix = (SuzukiEightCoverPcForms.form 2).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate4_6_coverStep1, conjugate4_6_coverStep2]

private def conjugate4_7_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 2, ofCode 6; ofCode 0, ofCode 1, ofCode 0, ofCode 2; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate4_7_codeStep1 : SuzukiEightCoverCodeMatrices.pc4Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix = conjugate4_7_codePrefix1 := by decide +kernel
private theorem conjugate4_7_codeStep2 : conjugate4_7_codePrefix1 * SuzukiEightCoverCodeMatrices.pc4Matrix = SuzukiEightCoverCodeForms.raw 1 := by decide +kernel
private def conjugate4_7_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6512765917406410541128673553044364336199153505759397590987059792572873699707726249641634164554465034262975648352607936721090497794852275175219266974604131299362538101061881614412633917370995977107808546020720370495847867644604664511594076132373960240252710418695756459922625027950538141313880457479883784793262639755548785720027290277787985746151687335366843043536485187032012629742643875716971120662507274198153527596551375843710592733979202009240470000081839112685426780942030359121636992455921706722340696912487388163
private theorem conjugate4_7_coverStep1 : SuzukiEightCoverPcMatrices.pc4Inverse * SuzukiEightCoverPcMatrices.pc7Matrix = conjugate4_7_coverPrefix1 := by decide +kernel
private theorem conjugate4_7_coverStep2 : conjugate4_7_coverPrefix1 * SuzukiEightCoverPcMatrices.pc4Matrix = SuzukiEightCoverPcForms.raw 1 := by decide +kernel

theorem conjugate4_7 : pc4⁻¹ * pc7 * pc4 = form 1 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc4Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.pc4Matrix = (SuzukiEightCoverCodeForms.form 1).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate4_7_codeStep1, conjugate4_7_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc4Inverse * SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.pc4Matrix = (SuzukiEightCoverPcForms.form 1).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate4_7_coverStep1, conjugate4_7_coverStep2]

private def conjugate5_6_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate5_6_codeStep1 : SuzukiEightCoverCodeMatrices.pc5Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix = conjugate5_6_codePrefix1 := by decide +kernel
private theorem conjugate5_6_codeStep2 : conjugate5_6_codePrefix1 * SuzukiEightCoverCodeMatrices.pc5Matrix = SuzukiEightCoverCodeForms.raw 2 := by decide +kernel
private def conjugate5_6_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2671617337728130434779338159456277698497926834990780891828518612347720196669997119577884239771392079435895291994874779559723767258837946700139716847479684733886893391868849752684400910800611004629225238314990758973926257475641247480008930137210785870318621227486743427975988982485077800949672580138507023782135656309854345026602383130154512976459070894715940004503707903199354273224538118725571680369334173154812677797192060641952189871216482794389177456640408636707172998274474102393805119037042730743083650624650555979
private theorem conjugate5_6_coverStep1 : SuzukiEightCoverPcMatrices.pc5Inverse * SuzukiEightCoverPcMatrices.pc6Matrix = conjugate5_6_coverPrefix1 := by decide +kernel
private theorem conjugate5_6_coverStep2 : conjugate5_6_coverPrefix1 * SuzukiEightCoverPcMatrices.pc5Matrix = SuzukiEightCoverPcForms.raw 2 := by decide +kernel

theorem conjugate5_6 : pc5⁻¹ * pc6 * pc5 = form 2 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc5Inverse * SuzukiEightCoverCodeMatrices.pc6Matrix * SuzukiEightCoverCodeMatrices.pc5Matrix = (SuzukiEightCoverCodeForms.form 2).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate5_6_codeStep1, conjugate5_6_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc5Inverse * SuzukiEightCoverPcMatrices.pc6Matrix * SuzukiEightCoverPcMatrices.pc5Matrix = (SuzukiEightCoverPcForms.form 2).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate5_6_coverStep1, conjugate5_6_coverStep2]

private def conjugate5_7_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate5_7_codeStep1 : SuzukiEightCoverCodeMatrices.pc5Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix = conjugate5_7_codePrefix1 := by decide +kernel
private theorem conjugate5_7_codeStep2 : conjugate5_7_codePrefix1 * SuzukiEightCoverCodeMatrices.pc5Matrix = SuzukiEightCoverCodeForms.raw 1 := by decide +kernel
private def conjugate5_7_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8104200225595879235278365370537069762638206804319355722016658800820441276802006377821369909727583000918407159298219610789757274152419683643862233738259257064304477218341809958008193126519774053530299528210570222266287137221192916387126887859875183664756153642369417209395882542810046053404771546159378198231889519742573184190826613914475515172187261984921923524149955864661950899099494440365005140211799703312911307122450057517263497867438357516544486306667416218819108038294572381740877950883852511765451629864120321281
private theorem conjugate5_7_coverStep1 : SuzukiEightCoverPcMatrices.pc5Inverse * SuzukiEightCoverPcMatrices.pc7Matrix = conjugate5_7_coverPrefix1 := by decide +kernel
private theorem conjugate5_7_coverStep2 : conjugate5_7_coverPrefix1 * SuzukiEightCoverPcMatrices.pc5Matrix = SuzukiEightCoverPcForms.raw 1 := by decide +kernel

theorem conjugate5_7 : pc5⁻¹ * pc7 * pc5 = form 1 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc5Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.pc5Matrix = (SuzukiEightCoverCodeForms.form 1).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate5_7_codeStep1, conjugate5_7_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc5Inverse * SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.pc5Matrix = (SuzukiEightCoverPcForms.form 1).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate5_7_coverStep1, conjugate5_7_coverStep2]

private def conjugate6_7_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 1, ofCode 0, ofCode 0, ofCode 0; ofCode 0, ofCode 1, ofCode 0, ofCode 0; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 1]
private theorem conjugate6_7_codeStep1 : SuzukiEightCoverCodeMatrices.pc6Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix = conjugate6_7_codePrefix1 := by decide +kernel
private theorem conjugate6_7_codeStep2 : conjugate6_7_codePrefix1 * SuzukiEightCoverCodeMatrices.pc6Matrix = SuzukiEightCoverCodeForms.raw 1 := by decide +kernel
private def conjugate6_7_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4497395536819381563561988845645687119764415541981108395758795623907787172267636791660200699771887252613348547109620310019804612481196597918420807008382659341475527651657469150135373498078851012038259027635924359010982079881543455030080747254589696605091608197238021704162158069472806899101415108669362109270005283225136300244999418186412560136294525733882895194413543182115417068627152815884924797953362616264963154735325767954928211252544033570661124230077287253350029332225533850623099221294560483338880502518954928404
private theorem conjugate6_7_coverStep1 : SuzukiEightCoverPcMatrices.pc6Inverse * SuzukiEightCoverPcMatrices.pc7Matrix = conjugate6_7_coverPrefix1 := by decide +kernel
private theorem conjugate6_7_coverStep2 : conjugate6_7_coverPrefix1 * SuzukiEightCoverPcMatrices.pc6Matrix = SuzukiEightCoverPcForms.raw 1 := by decide +kernel

theorem conjugate6_7 : pc6⁻¹ * pc7 * pc6 = form 1 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.pc6Inverse * SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.pc6Matrix = (SuzukiEightCoverCodeForms.form 1).val
    rw [SuzukiEightCoverCodeForms.form_val, conjugate6_7_codeStep1, conjugate6_7_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.pc6Inverse * SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.pc6Matrix = (SuzukiEightCoverPcForms.form 1).val
    rw [SuzukiEightCoverPcForms.form_val, conjugate6_7_coverStep1, conjugate6_7_coverStep2]

private def torusConjugate0_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 7, ofCode 1, ofCode 0, ofCode 3; ofCode 0, ofCode 2, ofCode 4, ofCode 6; ofCode 0, ofCode 0, ofCode 5, ofCode 2; ofCode 0, ofCode 0, ofCode 0, ofCode 4]
private theorem torusConjugate0_codeStep1 : SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc0Matrix = torusConjugate0_codePrefix1 := by decide +kernel
private theorem torusConjugate0_codeStep2 : torusConjugate0_codePrefix1 * SuzukiEightCoverCodeMatrices.torusMatrix = SuzukiEightCoverCodeForms.raw 177 := by decide +kernel
private def torusConjugate0_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 1928415427802813437986753327276449301112419496199027585081986970626927563206971988696277511724702467967009371493620996221602618593257006459893766764060530842247617904369022608796143762235561695281182421713576461594643366130925682473608870143336009471372083436948828837049904378044663757654043783765292262716915787806816634161655997852760814730027385137074638173548507480178172500270834895214625073632352215633179562979579737298672268836649820667942844667820118100409662732026078341120104304516373610338613338215952254105
private theorem torusConjugate0_coverStep1 : SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc0Matrix = torusConjugate0_coverPrefix1 := by decide +kernel
private theorem torusConjugate0_coverStep2 : torusConjugate0_coverPrefix1 * SuzukiEightCoverPcMatrices.torusMatrix = SuzukiEightCoverPcForms.raw 177 := by decide +kernel

theorem torusConjugate0 : torus⁻¹ * pc0 * torus = form 177 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc0Matrix * SuzukiEightCoverCodeMatrices.torusMatrix = (SuzukiEightCoverCodeForms.form 177).val
    rw [SuzukiEightCoverCodeForms.form_val, torusConjugate0_codeStep1, torusConjugate0_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc0Matrix * SuzukiEightCoverPcMatrices.torusMatrix = (SuzukiEightCoverPcForms.form 177).val
    rw [SuzukiEightCoverPcForms.form_val, torusConjugate0_coverStep1, torusConjugate0_coverStep2]

private def torusConjugate1_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 7, ofCode 5, ofCode 0, ofCode 6; ofCode 0, ofCode 2, ofCode 7, ofCode 5; ofCode 0, ofCode 0, ofCode 5, ofCode 1; ofCode 0, ofCode 0, ofCode 0, ofCode 4]
private theorem torusConjugate1_codeStep1 : SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc1Matrix = torusConjugate1_codePrefix1 := by decide +kernel
private theorem torusConjugate1_codeStep2 : torusConjugate1_codePrefix1 * SuzukiEightCoverCodeMatrices.torusMatrix = SuzukiEightCoverCodeForms.raw 238 := by decide +kernel
private def torusConjugate1_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6658236412780310839989506530505960653406108364927120940979030214949792362717468844444103791275277387748695116439553708939873148206987997343532302566174276420982501940059121947859639472786269790546595381258651088510370729238874057524620957177780099402719894873527919868262283895400936867913647591800661472360992102188985581940584976929984567776055057905679502394281529339409752063503390243269416127746966405696695532164586067573384465983738173058696184091996350777661843685498874532507859957612149047546379024066175902299
private theorem torusConjugate1_coverStep1 : SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc1Matrix = torusConjugate1_coverPrefix1 := by decide +kernel
private theorem torusConjugate1_coverStep2 : torusConjugate1_coverPrefix1 * SuzukiEightCoverPcMatrices.torusMatrix = SuzukiEightCoverPcForms.raw 238 := by decide +kernel

theorem torusConjugate1 : torus⁻¹ * pc1 * torus = form 238 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc1Matrix * SuzukiEightCoverCodeMatrices.torusMatrix = (SuzukiEightCoverCodeForms.form 238).val
    rw [SuzukiEightCoverCodeForms.form_val, torusConjugate1_codeStep1, torusConjugate1_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc1Matrix * SuzukiEightCoverPcMatrices.torusMatrix = (SuzukiEightCoverPcForms.form 238).val
    rw [SuzukiEightCoverPcForms.form_val, torusConjugate1_coverStep1, torusConjugate1_coverStep2]

private def torusConjugate2_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 7, ofCode 7, ofCode 0, ofCode 7; ofCode 0, ofCode 2, ofCode 2, ofCode 2; ofCode 0, ofCode 0, ofCode 5, ofCode 5; ofCode 0, ofCode 0, ofCode 0, ofCode 4]
private theorem torusConjugate2_codeStep1 : SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc2Matrix = torusConjugate2_codePrefix1 := by decide +kernel
private theorem torusConjugate2_codeStep2 : torusConjugate2_codePrefix1 * SuzukiEightCoverCodeMatrices.torusMatrix = SuzukiEightCoverCodeForms.raw 213 := by decide +kernel
private def torusConjugate2_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4060636029991035549823392695996641932953098573347236526059961801026501970160298118198415890910199406176792632108231192662412651378787802614895778523292993391676773364818846152259679770838021935518746117717309828444881991540155262496608789465784572017743336200429347397884484628959429549204031532020660282440147674879222003307417694071792596261268521880855542309953113923895406147765430523541648482895068018041302992558935787406802756887835194525452072335525126168292566718843242003805715052982594452927405465023281902674
private theorem torusConjugate2_coverStep1 : SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc2Matrix = torusConjugate2_coverPrefix1 := by decide +kernel
private theorem torusConjugate2_coverStep2 : torusConjugate2_coverPrefix1 * SuzukiEightCoverPcMatrices.torusMatrix = SuzukiEightCoverPcForms.raw 213 := by decide +kernel

theorem torusConjugate2 : torus⁻¹ * pc2 * torus = form 213 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc2Matrix * SuzukiEightCoverCodeMatrices.torusMatrix = (SuzukiEightCoverCodeForms.form 213).val
    rw [SuzukiEightCoverCodeForms.form_val, torusConjugate2_codeStep1, torusConjugate2_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc2Matrix * SuzukiEightCoverPcMatrices.torusMatrix = (SuzukiEightCoverPcForms.form 213).val
    rw [SuzukiEightCoverPcForms.form_val, torusConjugate2_coverStep1, torusConjugate2_coverStep2]

private def torusConjugate3_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 7, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 2, ofCode 0, ofCode 3; ofCode 0, ofCode 0, ofCode 5, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 4]
private theorem torusConjugate3_codeStep1 : SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc3Matrix = torusConjugate3_codePrefix1 := by decide +kernel
private theorem torusConjugate3_codeStep2 : torusConjugate3_codePrefix1 * SuzukiEightCoverCodeMatrices.torusMatrix = SuzukiEightCoverCodeForms.raw 10 := by decide +kernel
private def torusConjugate3_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6619739249268669740748564973807690144381242988909881378546227561632505217130085518400169527957808908078787191832348354283664906065356499284272999977455386989150572247263081644516504421327685563071421697264164974980355305210166905491251082404093875281495421406875844616872981951635473370076795417096960813480710670605879954965555512602721172928370425540070719161975559116118651126663210532508052916045394408603489990861911136425221771863779094317027676265768748070021451895609088572104347139259888235770113523537725096136
private theorem torusConjugate3_coverStep1 : SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc3Matrix = torusConjugate3_coverPrefix1 := by decide +kernel
private theorem torusConjugate3_coverStep2 : torusConjugate3_coverPrefix1 * SuzukiEightCoverPcMatrices.torusMatrix = SuzukiEightCoverPcForms.raw 10 := by decide +kernel

theorem torusConjugate3 : torus⁻¹ * pc3 * torus = form 10 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc3Matrix * SuzukiEightCoverCodeMatrices.torusMatrix = (SuzukiEightCoverCodeForms.form 10).val
    rw [SuzukiEightCoverCodeForms.form_val, torusConjugate3_codeStep1, torusConjugate3_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc3Matrix * SuzukiEightCoverPcMatrices.torusMatrix = (SuzukiEightCoverPcForms.form 10).val
    rw [SuzukiEightCoverPcForms.form_val, torusConjugate3_coverStep1, torusConjugate3_coverStep2]

private def torusConjugate4_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 7, ofCode 0, ofCode 5, ofCode 4; ofCode 0, ofCode 2, ofCode 0, ofCode 4; ofCode 0, ofCode 0, ofCode 5, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 4]
private theorem torusConjugate4_codeStep1 : SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc4Matrix = torusConjugate4_codePrefix1 := by decide +kernel
private theorem torusConjugate4_codeStep2 : torusConjugate4_codePrefix1 * SuzukiEightCoverCodeMatrices.torusMatrix = SuzukiEightCoverCodeForms.raw 5 := by decide +kernel
private def torusConjugate4_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6029368107889369137492679205700216510742731724171620246684114961461567767405190348172538066527371308276289278721215659324931495809502977143536001311789338041368675670764690673558074590041941835032411928295559767375549565144966105492791189101201113788763291124701190465055282864392046819643903623199528507515235097430220844429116237074533064066525689971851186160514485730849851552460113217886505053400190014396429120253963883118504257822482694722509078411819379216633080100807885001498987679113676311425194427274490852380
private theorem torusConjugate4_coverStep1 : SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc4Matrix = torusConjugate4_coverPrefix1 := by decide +kernel
private theorem torusConjugate4_coverStep2 : torusConjugate4_coverPrefix1 * SuzukiEightCoverPcMatrices.torusMatrix = SuzukiEightCoverPcForms.raw 5 := by decide +kernel

theorem torusConjugate4 : torus⁻¹ * pc4 * torus = form 5 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc4Matrix * SuzukiEightCoverCodeMatrices.torusMatrix = (SuzukiEightCoverCodeForms.form 5).val
    rw [SuzukiEightCoverCodeForms.form_val, torusConjugate4_codeStep1, torusConjugate4_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc4Matrix * SuzukiEightCoverPcMatrices.torusMatrix = (SuzukiEightCoverPcForms.form 5).val
    rw [SuzukiEightCoverPcForms.form_val, torusConjugate4_coverStep1, torusConjugate4_coverStep2]

private def torusConjugate5_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 7, ofCode 0, ofCode 7, ofCode 7; ofCode 0, ofCode 2, ofCode 0, ofCode 2; ofCode 0, ofCode 0, ofCode 5, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 4]
private theorem torusConjugate5_codeStep1 : SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc5Matrix = torusConjugate5_codePrefix1 := by decide +kernel
private theorem torusConjugate5_codeStep2 : torusConjugate5_codePrefix1 * SuzukiEightCoverCodeMatrices.torusMatrix = SuzukiEightCoverCodeForms.raw 22 := by decide +kernel
private def torusConjugate5_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6162230024163143428136729006071754221859117348214494678082052422091029676733869916181501842567354259499994468071096599192413988785122728066469134187921975694661278969003825917579272927550799547221877892707229483121341548899761885155986367619243148944556581048625253423758951293049346341983718984923791899279330736502784997358877038742127693232304862906365014503115401434202044469636843680201973620998302692071096769914826865525017739496457964129800562617376081787925810306264828645193521242288408494444823022948661068291
private theorem torusConjugate5_coverStep1 : SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc5Matrix = torusConjugate5_coverPrefix1 := by decide +kernel
private theorem torusConjugate5_coverStep2 : torusConjugate5_coverPrefix1 * SuzukiEightCoverPcMatrices.torusMatrix = SuzukiEightCoverPcForms.raw 22 := by decide +kernel

theorem torusConjugate5 : torus⁻¹ * pc5 * torus = form 22 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc5Matrix * SuzukiEightCoverCodeMatrices.torusMatrix = (SuzukiEightCoverCodeForms.form 22).val
    rw [SuzukiEightCoverCodeForms.form_val, torusConjugate5_codeStep1, torusConjugate5_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc5Matrix * SuzukiEightCoverPcMatrices.torusMatrix = (SuzukiEightCoverPcForms.form 22).val
    rw [SuzukiEightCoverPcForms.form_val, torusConjugate5_coverStep1, torusConjugate5_coverStep2]

private def torusConjugate6_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 7, ofCode 0, ofCode 0, ofCode 0; ofCode 0, ofCode 2, ofCode 0, ofCode 0; ofCode 0, ofCode 0, ofCode 5, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 4]
private theorem torusConjugate6_codeStep1 : SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc6Matrix = torusConjugate6_codePrefix1 := by decide +kernel
private theorem torusConjugate6_codeStep2 : torusConjugate6_codePrefix1 * SuzukiEightCoverCodeMatrices.torusMatrix = SuzukiEightCoverCodeForms.raw 2 := by decide +kernel
private def torusConjugate6_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7632877490795734897330292605581874961271161625983109945178466040935446461137243942488020103347274385125540489076791557638845573778898413462268834333235021303597369690318607234079238560811927104071578733556029552713017661461602274592811240834216347896182777218998804848269646781969971004907567015595508900664047323740667186512264157899229672145561128133312644841742343651242589071166594285150871110723530521546334968076611653912971083147503735778922778238878069139418867388504110149742515741628762381790603488871299723266
private theorem torusConjugate6_coverStep1 : SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc6Matrix = torusConjugate6_coverPrefix1 := by decide +kernel
private theorem torusConjugate6_coverStep2 : torusConjugate6_coverPrefix1 * SuzukiEightCoverPcMatrices.torusMatrix = SuzukiEightCoverPcForms.raw 2 := by decide +kernel

theorem torusConjugate6 : torus⁻¹ * pc6 * torus = form 2 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc6Matrix * SuzukiEightCoverCodeMatrices.torusMatrix = (SuzukiEightCoverCodeForms.form 2).val
    rw [SuzukiEightCoverCodeForms.form_val, torusConjugate6_codeStep1, torusConjugate6_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc6Matrix * SuzukiEightCoverPcMatrices.torusMatrix = (SuzukiEightCoverPcForms.form 2).val
    rw [SuzukiEightCoverPcForms.form_val, torusConjugate6_coverStep1, torusConjugate6_coverStep2]

private def torusConjugate7_codePrefix1 : SuzukiEightCoverCodeMatrices.M := !![ofCode 7, ofCode 0, ofCode 0, ofCode 0; ofCode 0, ofCode 2, ofCode 0, ofCode 0; ofCode 0, ofCode 0, ofCode 5, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 4]
private theorem torusConjugate7_codeStep1 : SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc7Matrix = torusConjugate7_codePrefix1 := by decide +kernel
private theorem torusConjugate7_codeStep2 : torusConjugate7_codePrefix1 * SuzukiEightCoverCodeMatrices.torusMatrix = SuzukiEightCoverCodeForms.raw 1 := by decide +kernel
private def torusConjugate7_coverPrefix1 : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7861809712381005179651687698268544400928744408897753523710515774365441695186297702895819943571010460970465503832365259646815248807914683471999448607317612950271883240881167296006915896984753439960023548108466223561781423499819130278359747636684415220603356747894322053019399324909977214819585911155128942984790775915897897437599273483974186516717232485031947694538534100737261979802702620523161274251768885865276525723418299525389478474338765399304484424124517860066732001709210538031589439013133590542588588852978648153
private theorem torusConjugate7_coverStep1 : SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc7Matrix = torusConjugate7_coverPrefix1 := by decide +kernel
private theorem torusConjugate7_coverStep2 : torusConjugate7_coverPrefix1 * SuzukiEightCoverPcMatrices.torusMatrix = SuzukiEightCoverPcForms.raw 1 := by decide +kernel

theorem torusConjugate7 : torus⁻¹ * pc7 * torus = form 1 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    change SuzukiEightCoverCodeMatrices.torusInverse * SuzukiEightCoverCodeMatrices.pc7Matrix * SuzukiEightCoverCodeMatrices.torusMatrix = (SuzukiEightCoverCodeForms.form 1).val
    rw [SuzukiEightCoverCodeForms.form_val, torusConjugate7_codeStep1, torusConjugate7_codeStep2]
  · apply Units.ext
    change SuzukiEightCoverPcMatrices.torusInverse * SuzukiEightCoverPcMatrices.pc7Matrix * SuzukiEightCoverPcMatrices.torusMatrix = (SuzukiEightCoverPcForms.form 1).val
    rw [SuzukiEightCoverPcForms.form_val, torusConjugate7_coverStep1, torusConjugate7_coverStep2]

def torusPower0_code : SuzukiEightCoverCodeMatrices.M := 1
theorem torusPower0_code_val : ((SuzukiEightCoverCodeMatrices.torus ^ 0 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) = torusPower0_code := by
  rfl

def torusPower1_code : SuzukiEightCoverCodeMatrices.M := SuzukiEightCoverCodeMatrices.torusMatrix
theorem torusPower1_code_val : ((SuzukiEightCoverCodeMatrices.torus ^ 1 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) = torusPower1_code := by
  simp only [pow_one]
  rfl

def torusPower2_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 6, ofCode 0, ofCode 0, ofCode 0; ofCode 0, ofCode 7, ofCode 0, ofCode 0; ofCode 0, ofCode 0, ofCode 4, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 3]
private theorem torusPower2_code_step : torusPower1_code * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower2_code := by decide +kernel
theorem torusPower2_code_val : ((SuzukiEightCoverCodeMatrices.torus ^ 2 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) = torusPower2_code := by
  rw [pow_succ]
  change ((SuzukiEightCoverCodeMatrices.torus ^ 1 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower2_code
  rw [torusPower1_code_val]
  exact torusPower2_code_step

def torusPower3_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 5, ofCode 0, ofCode 0, ofCode 0; ofCode 0, ofCode 6, ofCode 0, ofCode 0; ofCode 0, ofCode 0, ofCode 3, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 2]
private theorem torusPower3_code_step : torusPower2_code * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower3_code := by decide +kernel
theorem torusPower3_code_val : ((SuzukiEightCoverCodeMatrices.torus ^ 3 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) = torusPower3_code := by
  rw [pow_succ]
  change ((SuzukiEightCoverCodeMatrices.torus ^ 2 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower3_code
  rw [torusPower2_code_val]
  exact torusPower3_code_step

def torusPower4_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 2, ofCode 0, ofCode 0, ofCode 0; ofCode 0, ofCode 3, ofCode 0, ofCode 0; ofCode 0, ofCode 0, ofCode 6, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 5]
private theorem torusPower4_code_step : torusPower3_code * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower4_code := by decide +kernel
theorem torusPower4_code_val : ((SuzukiEightCoverCodeMatrices.torus ^ 4 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) = torusPower4_code := by
  rw [pow_succ]
  change ((SuzukiEightCoverCodeMatrices.torus ^ 3 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower4_code
  rw [torusPower3_code_val]
  exact torusPower4_code_step

def torusPower5_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 3, ofCode 0, ofCode 0, ofCode 0; ofCode 0, ofCode 4, ofCode 0, ofCode 0; ofCode 0, ofCode 0, ofCode 7, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 6]
private theorem torusPower5_code_step : torusPower4_code * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower5_code := by decide +kernel
theorem torusPower5_code_val : ((SuzukiEightCoverCodeMatrices.torus ^ 5 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) = torusPower5_code := by
  rw [pow_succ]
  change ((SuzukiEightCoverCodeMatrices.torus ^ 4 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower5_code
  rw [torusPower4_code_val]
  exact torusPower5_code_step

def torusPower6_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 7, ofCode 0, ofCode 0, ofCode 0; ofCode 0, ofCode 2, ofCode 0, ofCode 0; ofCode 0, ofCode 0, ofCode 5, ofCode 0; ofCode 0, ofCode 0, ofCode 0, ofCode 4]
private theorem torusPower6_code_step : torusPower5_code * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower6_code := by decide +kernel
theorem torusPower6_code_val : ((SuzukiEightCoverCodeMatrices.torus ^ 6 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) = torusPower6_code := by
  rw [pow_succ]
  change ((SuzukiEightCoverCodeMatrices.torus ^ 5 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower6_code
  rw [torusPower5_code_val]
  exact torusPower6_code_step

def torusPower7_code : SuzukiEightCoverCodeMatrices.M := 1
private theorem torusPower7_code_step : torusPower6_code * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower7_code := by decide +kernel
theorem torusPower7_code_val : ((SuzukiEightCoverCodeMatrices.torus ^ 7 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) = torusPower7_code := by
  rw [pow_succ]
  change ((SuzukiEightCoverCodeMatrices.torus ^ 6 : SuzukiEightCoverCodeMatrices.UnitMatrix) : SuzukiEightCoverCodeMatrices.M) * SuzukiEightCoverCodeMatrices.torusMatrix = torusPower7_code
  rw [torusPower6_code_val]
  exact torusPower7_code_step

def torusRaw_code : Fin 7 → SuzukiEightCoverCodeMatrices.M := ![torusPower0_code, torusPower1_code, torusPower2_code, torusPower3_code, torusPower4_code, torusPower5_code, torusPower6_code]

theorem torus_power_val_code (i : Fin 7) :
    ((torus ^ i.val).val.1 : SuzukiEightCoverCodeMatrices.M) = torusRaw_code i := by
  fin_cases i
  · exact torusPower0_code_val
  · exact torusPower1_code_val
  · exact torusPower2_code_val
  · exact torusPower3_code_val
  · exact torusPower4_code_val
  · exact torusPower5_code_val
  · exact torusPower6_code_val

def torusPower0_cover : SuzukiEightCoverMatrices.M := 1
theorem torusPower0_cover_val : ((SuzukiEightCoverPcMatrices.torus ^ 0 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) = torusPower0_cover := by
  rfl

def torusPower1_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverPcMatrices.torusMatrix
theorem torusPower1_cover_val : ((SuzukiEightCoverPcMatrices.torus ^ 1 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) = torusPower1_cover := by
  simp only [pow_one]
  rfl

def torusPower2_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4851944287848161618857429941772018814498338511228690814497084054746870763922167885871677552602384816209024094224276427275648850945394599347670819942242022528222878426842698936297637208895434001036927755663287657162077558432532930119829895603119395465708415077449915436256345206792500030716301135660359315534069493873215287252812191462393604027392539486385395842997627813783705782468306683276817058570733091801958410726898481899465646040562535651722154714210472335030485261468159193968375380117849917880036447329437712538
private theorem torusPower2_cover_step : torusPower1_cover * SuzukiEightCoverPcMatrices.torusMatrix = torusPower2_cover := by decide +kernel
theorem torusPower2_cover_val : ((SuzukiEightCoverPcMatrices.torus ^ 2 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) = torusPower2_cover := by
  rw [pow_succ]
  change ((SuzukiEightCoverPcMatrices.torus ^ 1 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) * SuzukiEightCoverPcMatrices.torusMatrix = torusPower2_cover
  rw [torusPower1_cover_val]
  exact torusPower2_cover_step

def torusPower3_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6207551350702435873426406291947981425399094244663216899615682682517423852084765082102248730399129760176603465257026502983673739712089104141589558841216542074596240439831709557808449747614325538249441605560398928910534912622193973733097040638124882527473550808819215805849745989023377326207401729585359658386742192235508389721716588472392139816662868024402776568523336746454000182670134881681898143148033349998491805915996662028442235144448437835613886085423487411076821781328030841031041605424320099737071572580102350404
private theorem torusPower3_cover_step : torusPower2_cover * SuzukiEightCoverPcMatrices.torusMatrix = torusPower3_cover := by decide +kernel
theorem torusPower3_cover_val : ((SuzukiEightCoverPcMatrices.torus ^ 3 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) = torusPower3_cover := by
  rw [pow_succ]
  change ((SuzukiEightCoverPcMatrices.torus ^ 2 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) * SuzukiEightCoverPcMatrices.torusMatrix = torusPower3_cover
  rw [torusPower2_cover_val]
  exact torusPower3_cover_step

def torusPower4_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7865672971161316071476874587206928944475035795974556737913122317200364015139468781330459526624931014027469828122347953307593972033032531365587084358865162843324280225339421206708308158173693570067764152234034185159763087083380403618410172327748415805437200921242900625443171280650553069120487029047363044647155483827481666363868386029555259424397154561610220244870062651132367896137764016986926236389497663182426624839665349300920169573589760026348607560999255463698953880958315478539611723394995105961405510526027506305
private theorem torusPower4_cover_step : torusPower3_cover * SuzukiEightCoverPcMatrices.torusMatrix = torusPower4_cover := by decide +kernel
theorem torusPower4_cover_val : ((SuzukiEightCoverPcMatrices.torus ^ 4 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) = torusPower4_cover := by
  rw [pow_succ]
  change ((SuzukiEightCoverPcMatrices.torus ^ 3 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) * SuzukiEightCoverPcMatrices.torusMatrix = torusPower4_cover
  rw [torusPower3_cover_val]
  exact torusPower4_cover_step

def torusPower5_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7898254785193382477551356931763665213314463542113859471068538842339038996522512673057666222664103260983058451185668886012707571610988148113052116163823926212309267564157735681160374955417211592891309402723394640496482771381647020956101920468561725361899396077025680176656031610541742748817029757745648032581114681655499964709669589900431508958628787848619645436848267588218932999752133013555960333761375654240689194376732891605911972841718394272231344348005644616338963794744225444021645439079624754164299564855276742656
private theorem torusPower5_cover_step : torusPower4_cover * SuzukiEightCoverPcMatrices.torusMatrix = torusPower5_cover := by decide +kernel
theorem torusPower5_cover_val : ((SuzukiEightCoverPcMatrices.torus ^ 5 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) = torusPower5_cover := by
  rw [pow_succ]
  change ((SuzukiEightCoverPcMatrices.torus ^ 4 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) * SuzukiEightCoverPcMatrices.torusMatrix = torusPower5_cover
  rw [torusPower4_cover_val]
  exact torusPower5_cover_step

def torusPower6_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7580703457734733789683573805000479999546965554153571285343093194987296994100815429271583092811533467373486513203752634048476051328565500336294554610352640036246896927628534050955570208087866334595695532907402814162592050676848984466689965345213933740513399690647977392137763515989254470920781040936367779004997022900946475023700607842119809254589670662391153071959803439213602243896808088254740680128032173793903714926104757115553966838451460349556957021114126789328630947239919664488896555309524808184299289434770965603
private theorem torusPower6_cover_step : torusPower5_cover * SuzukiEightCoverPcMatrices.torusMatrix = torusPower6_cover := by decide +kernel
theorem torusPower6_cover_val : ((SuzukiEightCoverPcMatrices.torus ^ 6 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) = torusPower6_cover := by
  rw [pow_succ]
  change ((SuzukiEightCoverPcMatrices.torus ^ 5 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) * SuzukiEightCoverPcMatrices.torusMatrix = torusPower6_cover
  rw [torusPower5_cover_val]
  exact torusPower6_cover_step

def torusPower7_cover : SuzukiEightCoverMatrices.M := 1
private theorem torusPower7_cover_step : torusPower6_cover * SuzukiEightCoverPcMatrices.torusMatrix = torusPower7_cover := by decide +kernel
theorem torusPower7_cover_val : ((SuzukiEightCoverPcMatrices.torus ^ 7 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) = torusPower7_cover := by
  rw [pow_succ]
  change ((SuzukiEightCoverPcMatrices.torus ^ 6 : SuzukiEightCoverMatrices.UnitMatrix) : SuzukiEightCoverMatrices.M) * SuzukiEightCoverPcMatrices.torusMatrix = torusPower7_cover
  rw [torusPower6_cover_val]
  exact torusPower7_cover_step

def torusRaw_cover : Fin 7 → SuzukiEightCoverMatrices.M := ![torusPower0_cover, torusPower1_cover, torusPower2_cover, torusPower3_cover, torusPower4_cover, torusPower5_cover, torusPower6_cover]

theorem torus_power_val_cover (i : Fin 7) :
    ((torus ^ i.val).val.2 : SuzukiEightCoverMatrices.M) = torusRaw_cover i := by
  fin_cases i
  · exact torusPower0_cover_val
  · exact torusPower1_cover_val
  · exact torusPower2_cover_val
  · exact torusPower3_cover_val
  · exact torusPower4_cover_val
  · exact torusPower5_cover_val
  · exact torusPower6_cover_val

theorem torus_seventh : torus ^ 7 = 1 := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    exact torusPower7_code_val
  · apply Units.ext
    exact torusPower7_cover_val

end Kourovka2135.SuzukiEightPairedPcRelations
