import Kourovka2135.SuzukiEightPairedTransitions1
import Kourovka2135.SuzukiEightPairedTransitions2
import Kourovka2135.SuzukiEightPairedTransitions3
import Kourovka2135.SuzukiEightPairedTransitions4
import Kourovka2135.SuzukiEightPairedTransitions5
import Kourovka2135.SuzukiEightPairedTransitions6
import Kourovka2135.SuzukiEightPairedTransitions7

/-! Actual paired matrix certificate. Generated by generate_paired_upper.py.
Finite data are checked by ordinary kernel proofs, never used as assumptions. -/
set_option autoImplicit false
set_option maxRecDepth 16384
set_option maxHeartbeats 8000000
noncomputable section
namespace Kourovka2135.SuzukiEightPairedCosets
open SuzukiEightPairedGoodSet SuzukiEightPairedPcData SuzukiEightPairedPc SuzukiEightPairedCosetData
open SuzukiEightPairedTransitions1 SuzukiEightPairedTransitions2 SuzukiEightPairedTransitions3 SuzukiEightPairedTransitions4 SuzukiEightPairedTransitions5 SuzukiEightPairedTransitions6 SuzukiEightPairedTransitions7

theorem transition_mem {i j : Fin 65} {s : E} (a : Fin 256) (e : ℕ)
    (h : rep i * s = form a * torus ^ e * rep j) : rep i * s * (rep j)⁻¹ ∈ H := by
  rw [h]
  simp only [mul_assoc, mul_inv_cancel, mul_one]
  exact H.mul_mem (form_mem_H a) (H.pow_mem torus_mem_H e)

theorem step_C (i : Fin 65) : ∃ j : Fin 65, rep i * C * (rep j)⁻¹ ∈ H := by
  fin_cases i
  · exact ⟨1, transition_mem 0 0 transition0⟩
  · exact ⟨0, transition_mem 0 0 transition4⟩
  · exact ⟨9, transition_mem 37 0 transition8⟩
  · exact ⟨54, transition_mem 194 5 transition12⟩
  · exact ⟨60, transition_mem 246 1 transition16⟩
  · exact ⟨17, transition_mem 92 3 transition20⟩
  · exact ⟨27, transition_mem 98 2 transition24⟩
  · exact ⟨33, transition_mem 142 6 transition28⟩
  · exact ⟨45, transition_mem 160 4 transition32⟩
  · exact ⟨2, transition_mem 32 0 transition36⟩
  · exact ⟨10, transition_mem 4 0 transition40⟩
  · exact ⟨35, transition_mem 202 4 transition44⟩
  · exact ⟨56, transition_mem 133 4 transition48⟩
  · exact ⟨50, transition_mem 76 1 transition52⟩
  · exact ⟨21, transition_mem 209 1 transition56⟩
  · exact ⟨23, transition_mem 149 2 transition60⟩
  · exact ⟨39, transition_mem 70 2 transition64⟩
  · exact ⟨5, transition_mem 179 4 transition68⟩
  · exact ⟨29, transition_mem 62 5 transition72⟩
  · exact ⟨26, transition_mem 81 1 transition76⟩
  · exact ⟨22, transition_mem 51 6 transition80⟩
  · exact ⟨14, transition_mem 74 6 transition84⟩
  · exact ⟨20, transition_mem 109 1 transition88⟩
  · exact ⟨15, transition_mem 120 5 transition92⟩
  · exact ⟨41, transition_mem 18 4 transition96⟩
  · exact ⟨49, transition_mem 22 5 transition100⟩
  · exact ⟨19, transition_mem 254 6 transition104⟩
  · exact ⟨6, transition_mem 213 5 transition108⟩
  · exact ⟨58, transition_mem 87 6 transition112⟩
  · exact ⟨18, transition_mem 166 2 transition116⟩
  · exact ⟨57, transition_mem 174 0 transition120⟩
  · exact ⟨46, transition_mem 91 2 transition124⟩
  · exact ⟨48, transition_mem 250 0 transition128⟩
  · exact ⟨7, transition_mem 236 1 transition132⟩
  · exact ⟨47, transition_mem 46 3 transition136⟩
  · exact ⟨11, transition_mem 168 3 transition140⟩
  · exact ⟨62, transition_mem 27 1 transition144⟩
  · exact ⟨42, transition_mem 155 2 transition148⟩
  · exact ⟨40, transition_mem 58 5 transition152⟩
  · exact ⟨16, transition_mem 147 5 transition156⟩
  · exact ⟨38, transition_mem 181 2 transition160⟩
  · exact ⟨24, transition_mem 31 3 transition164⟩
  · exact ⟨37, transition_mem 115 5 transition168⟩
  · exact ⟨59, transition_mem 136 4 transition172⟩
  · exact ⟨63, transition_mem 119 0 transition176⟩
  · exact ⟨8, transition_mem 66 3 transition180⟩
  · exact ⟨31, transition_mem 156 5 transition184⟩
  · exact ⟨34, transition_mem 241 4 transition188⟩
  · exact ⟨32, transition_mem 227 0 transition192⟩
  · exact ⟨25, transition_mem 9 2 transition196⟩
  · exact ⟨13, transition_mem 230 6 transition200⟩
  · exact ⟨55, transition_mem 43 3 transition204⟩
  · exact ⟨61, transition_mem 221 4 transition208⟩
  · exact ⟨64, transition_mem 54 6 transition212⟩
  · exact ⟨3, transition_mem 106 2 transition216⟩
  · exact ⟨51, transition_mem 235 4 transition220⟩
  · exact ⟨12, transition_mem 206 3 transition224⟩
  · exact ⟨30, transition_mem 190 0 transition228⟩
  · exact ⟨28, transition_mem 196 1 transition232⟩
  · exact ⟨43, transition_mem 217 3 transition236⟩
  · exact ⟨4, transition_mem 131 6 transition240⟩
  · exact ⟨52, transition_mem 186 3 transition244⟩
  · exact ⟨36, transition_mem 12 6 transition248⟩
  · exact ⟨44, transition_mem 126 0 transition252⟩
  · exact ⟨53, transition_mem 101 1 transition256⟩

theorem step_B (i : Fin 65) : ∃ j : Fin 65, rep i * B * (rep j)⁻¹ ∈ H := by
  fin_cases i
  · exact ⟨0, transition_mem 107 0 transition1⟩
  · exact ⟨27, transition_mem 3 0 transition5⟩
  · exact ⟨28, transition_mem 0 0 transition9⟩
  · exact ⟨25, transition_mem 3 0 transition13⟩
  · exact ⟨26, transition_mem 0 0 transition17⟩
  · exact ⟨31, transition_mem 1 0 transition21⟩
  · exact ⟨32, transition_mem 2 0 transition25⟩
  · exact ⟨29, transition_mem 1 0 transition29⟩
  · exact ⟨30, transition_mem 2 0 transition33⟩
  · exact ⟨24, transition_mem 0 0 transition37⟩
  · exact ⟨23, transition_mem 3 0 transition41⟩
  · exact ⟨22, transition_mem 0 0 transition45⟩
  · exact ⟨21, transition_mem 3 0 transition49⟩
  · exact ⟨20, transition_mem 2 0 transition53⟩
  · exact ⟨19, transition_mem 1 0 transition57⟩
  · exact ⟨18, transition_mem 2 0 transition61⟩
  · exact ⟨17, transition_mem 1 0 transition65⟩
  · exact ⟨14, transition_mem 1 0 transition69⟩
  · exact ⟨13, transition_mem 2 0 transition73⟩
  · exact ⟨16, transition_mem 1 0 transition77⟩
  · exact ⟨15, transition_mem 2 0 transition81⟩
  · exact ⟨10, transition_mem 3 0 transition85⟩
  · exact ⟨9, transition_mem 0 0 transition89⟩
  · exact ⟨12, transition_mem 3 0 transition93⟩
  · exact ⟨11, transition_mem 0 0 transition97⟩
  · exact ⟨1, transition_mem 3 0 transition101⟩
  · exact ⟨2, transition_mem 0 0 transition105⟩
  · exact ⟨3, transition_mem 3 0 transition109⟩
  · exact ⟨4, transition_mem 0 0 transition113⟩
  · exact ⟨5, transition_mem 1 0 transition117⟩
  · exact ⟨6, transition_mem 2 0 transition121⟩
  · exact ⟨7, transition_mem 1 0 transition125⟩
  · exact ⟨8, transition_mem 2 0 transition129⟩
  · exact ⟨59, transition_mem 3 0 transition133⟩
  · exact ⟨60, transition_mem 0 0 transition137⟩
  · exact ⟨57, transition_mem 3 0 transition141⟩
  · exact ⟨58, transition_mem 0 0 transition145⟩
  · exact ⟨63, transition_mem 1 0 transition149⟩
  · exact ⟨64, transition_mem 2 0 transition153⟩
  · exact ⟨61, transition_mem 1 0 transition157⟩
  · exact ⟨62, transition_mem 2 0 transition161⟩
  · exact ⟨56, transition_mem 0 0 transition165⟩
  · exact ⟨55, transition_mem 3 0 transition169⟩
  · exact ⟨54, transition_mem 0 0 transition173⟩
  · exact ⟨53, transition_mem 3 0 transition177⟩
  · exact ⟨52, transition_mem 2 0 transition181⟩
  · exact ⟨51, transition_mem 1 0 transition185⟩
  · exact ⟨50, transition_mem 2 0 transition189⟩
  · exact ⟨49, transition_mem 1 0 transition193⟩
  · exact ⟨46, transition_mem 1 0 transition197⟩
  · exact ⟨45, transition_mem 2 0 transition201⟩
  · exact ⟨48, transition_mem 1 0 transition205⟩
  · exact ⟨47, transition_mem 2 0 transition209⟩
  · exact ⟨42, transition_mem 3 0 transition213⟩
  · exact ⟨41, transition_mem 0 0 transition217⟩
  · exact ⟨44, transition_mem 3 0 transition221⟩
  · exact ⟨43, transition_mem 0 0 transition225⟩
  · exact ⟨33, transition_mem 3 0 transition229⟩
  · exact ⟨34, transition_mem 0 0 transition233⟩
  · exact ⟨35, transition_mem 3 0 transition237⟩
  · exact ⟨36, transition_mem 0 0 transition241⟩
  · exact ⟨37, transition_mem 1 0 transition245⟩
  · exact ⟨38, transition_mem 2 0 transition249⟩
  · exact ⟨39, transition_mem 1 0 transition253⟩
  · exact ⟨40, transition_mem 2 0 transition257⟩

theorem step_B_inv (i : Fin 65) : ∃ j : Fin 65, rep i * B⁻¹ * (rep j)⁻¹ ∈ H := by
  fin_cases i
  · exact ⟨0, transition_mem 99 0 transition3⟩
  · exact ⟨25, transition_mem 3 0 transition7⟩
  · exact ⟨26, transition_mem 0 0 transition11⟩
  · exact ⟨27, transition_mem 3 0 transition15⟩
  · exact ⟨28, transition_mem 0 0 transition19⟩
  · exact ⟨29, transition_mem 1 0 transition23⟩
  · exact ⟨30, transition_mem 2 0 transition27⟩
  · exact ⟨31, transition_mem 1 0 transition31⟩
  · exact ⟨32, transition_mem 2 0 transition35⟩
  · exact ⟨22, transition_mem 0 0 transition39⟩
  · exact ⟨21, transition_mem 3 0 transition43⟩
  · exact ⟨24, transition_mem 0 0 transition47⟩
  · exact ⟨23, transition_mem 3 0 transition51⟩
  · exact ⟨18, transition_mem 2 0 transition55⟩
  · exact ⟨17, transition_mem 1 0 transition59⟩
  · exact ⟨20, transition_mem 2 0 transition63⟩
  · exact ⟨19, transition_mem 1 0 transition67⟩
  · exact ⟨16, transition_mem 1 0 transition71⟩
  · exact ⟨15, transition_mem 2 0 transition75⟩
  · exact ⟨14, transition_mem 1 0 transition79⟩
  · exact ⟨13, transition_mem 2 0 transition83⟩
  · exact ⟨12, transition_mem 3 0 transition87⟩
  · exact ⟨11, transition_mem 0 0 transition91⟩
  · exact ⟨10, transition_mem 3 0 transition95⟩
  · exact ⟨9, transition_mem 0 0 transition99⟩
  · exact ⟨3, transition_mem 3 0 transition103⟩
  · exact ⟨4, transition_mem 0 0 transition107⟩
  · exact ⟨1, transition_mem 3 0 transition111⟩
  · exact ⟨2, transition_mem 0 0 transition115⟩
  · exact ⟨7, transition_mem 1 0 transition119⟩
  · exact ⟨8, transition_mem 2 0 transition123⟩
  · exact ⟨5, transition_mem 1 0 transition127⟩
  · exact ⟨6, transition_mem 2 0 transition131⟩
  · exact ⟨57, transition_mem 3 0 transition135⟩
  · exact ⟨58, transition_mem 0 0 transition139⟩
  · exact ⟨59, transition_mem 3 0 transition143⟩
  · exact ⟨60, transition_mem 0 0 transition147⟩
  · exact ⟨61, transition_mem 1 0 transition151⟩
  · exact ⟨62, transition_mem 2 0 transition155⟩
  · exact ⟨63, transition_mem 1 0 transition159⟩
  · exact ⟨64, transition_mem 2 0 transition163⟩
  · exact ⟨54, transition_mem 0 0 transition167⟩
  · exact ⟨53, transition_mem 3 0 transition171⟩
  · exact ⟨56, transition_mem 0 0 transition175⟩
  · exact ⟨55, transition_mem 3 0 transition179⟩
  · exact ⟨50, transition_mem 2 0 transition183⟩
  · exact ⟨49, transition_mem 1 0 transition187⟩
  · exact ⟨52, transition_mem 2 0 transition191⟩
  · exact ⟨51, transition_mem 1 0 transition195⟩
  · exact ⟨48, transition_mem 1 0 transition199⟩
  · exact ⟨47, transition_mem 2 0 transition203⟩
  · exact ⟨46, transition_mem 1 0 transition207⟩
  · exact ⟨45, transition_mem 2 0 transition211⟩
  · exact ⟨44, transition_mem 3 0 transition215⟩
  · exact ⟨43, transition_mem 0 0 transition219⟩
  · exact ⟨42, transition_mem 3 0 transition223⟩
  · exact ⟨41, transition_mem 0 0 transition227⟩
  · exact ⟨35, transition_mem 3 0 transition231⟩
  · exact ⟨36, transition_mem 0 0 transition235⟩
  · exact ⟨33, transition_mem 3 0 transition239⟩
  · exact ⟨34, transition_mem 0 0 transition243⟩
  · exact ⟨39, transition_mem 1 0 transition247⟩
  · exact ⟨40, transition_mem 2 0 transition251⟩
  · exact ⟨37, transition_mem 1 0 transition255⟩
  · exact ⟨38, transition_mem 2 0 transition259⟩

theorem step_C_inv (i : Fin 65) : ∃ j : Fin 65, rep i * C⁻¹ * (rep j)⁻¹ ∈ H := by
  rw [C_inv]
  exact step_C i

theorem step (i : Fin 65) (s : E) (hs : s ∈ ({C, B} : Set E)) :
    ∃ j : Fin 65, rep i * s * (rep j)⁻¹ ∈ H := by
  rcases Set.mem_insert_iff.mp hs with rfl | hs
  · exact step_C i
  · obtain rfl := Set.mem_singleton_iff.mp hs
    exact step_B i

theorem stepInv (i : Fin 65) (s : E) (hs : s ∈ ({C, B} : Set E)) :
    ∃ j : Fin 65, rep i * s⁻¹ * (rep j)⁻¹ ∈ H := by
  rcases Set.mem_insert_iff.mp hs with rfl | hs
  · exact step_C_inv i
  · obtain rfl := Set.mem_singleton_iff.mp hs
    exact step_B_inv i

end Kourovka2135.SuzukiEightPairedCosets
