import Kourovka2135.SuzukiEightPairedGoodSet
import Kourovka2135.SuzukiEightCoverPcWords
import Kourovka2135.SuzukiEightCoverPcForms
import Kourovka2135.SuzukiEightCoverCodeForms
import Kourovka2135.FiniteEightPcWords

/-! Actual paired matrix certificate. Generated by generate_paired_upper.py.
Finite data are checked by ordinary kernel proofs, never used as assumptions. -/
set_option autoImplicit false
set_option maxRecDepth 16384
set_option maxHeartbeats 8000000
noncomputable section
namespace Kourovka2135.SuzukiEightPairedPcData
open SuzukiEightPairedGoodSet

def pc0Ambient : Ambient := (SuzukiEightCoverCodeMatrices.pc0, SuzukiEightCoverPcMatrices.pc0)

theorem pc0Ambient_from_cb : b * c * b * c * b * b * c * b * b * c * b⁻¹ * c * b * b * c * b * b * c * b * c * b⁻¹ * c * b * c * b = pc0Ambient :=
  Prod.ext SuzukiEightCoverCodeMatrices.pc0_from_cb SuzukiEightCoverPcWords.pc0_from_cb

theorem pc0Ambient_mem : pc0Ambient ∈ coverGroup := by
  rw [← pc0Ambient_from_cb]
  exact (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem b_mem c_mem) b_mem) c_mem) b_mem) b_mem) c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem) c_mem) b_mem) b_mem) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) b_mem)

def pc0 : E := ⟨pc0Ambient, pc0Ambient_mem⟩
theorem pc0_val : pc0.val = (SuzukiEightCoverCodeMatrices.pc0, SuzukiEightCoverPcMatrices.pc0) := rfl

def pc1Ambient : Ambient := (SuzukiEightCoverCodeMatrices.pc1, SuzukiEightCoverPcMatrices.pc1)

theorem pc1Ambient_from_cb : b * c * b * b * c * b⁻¹ * c * b * b * c * b * c * b⁻¹ * c * b⁻¹ * c * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b⁻¹ * c * b * c * b = pc1Ambient :=
  Prod.ext SuzukiEightCoverCodeMatrices.pc1_from_cb SuzukiEightCoverPcWords.pc1_from_cb

theorem pc1Ambient_mem : pc1Ambient ∈ coverGroup := by
  rw [← pc1Ambient_from_cb]
  exact (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem b_mem c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) b_mem)

def pc1 : E := ⟨pc1Ambient, pc1Ambient_mem⟩
theorem pc1_val : pc1.val = (SuzukiEightCoverCodeMatrices.pc1, SuzukiEightCoverPcMatrices.pc1) := rfl

def pc2Ambient : Ambient := (SuzukiEightCoverCodeMatrices.pc2, SuzukiEightCoverPcMatrices.pc2)

theorem pc2Ambient_from_cb : b * b * c * b * b * c * b * b * c * b * c * b * b * c * b * b * c * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b * c * b⁻¹ * c = pc2Ambient :=
  Prod.ext SuzukiEightCoverCodeMatrices.pc2_from_cb SuzukiEightCoverPcWords.pc2_from_cb

theorem pc2Ambient_mem : pc2Ambient ∈ coverGroup := by
  rw [← pc2Ambient_from_cb]
  exact (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem b_mem b_mem) c_mem) b_mem) b_mem) c_mem) b_mem) b_mem) c_mem) b_mem) c_mem) b_mem) b_mem) c_mem) b_mem) b_mem) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem)

def pc2 : E := ⟨pc2Ambient, pc2Ambient_mem⟩
theorem pc2_val : pc2.val = (SuzukiEightCoverCodeMatrices.pc2, SuzukiEightCoverPcMatrices.pc2) := rfl

def pc3Ambient : Ambient := (SuzukiEightCoverCodeMatrices.pc3, SuzukiEightCoverPcMatrices.pc3)

theorem pc3Ambient_from_cb : b * c * b * c * b⁻¹ * c * b * b * c * b⁻¹ * c * b * b * c * b * c * b⁻¹ * c * b * b * c * b⁻¹ * c * b * b * c * b = pc3Ambient :=
  Prod.ext SuzukiEightCoverCodeMatrices.pc3_from_cb SuzukiEightCoverPcWords.pc3_from_cb

theorem pc3Ambient_mem : pc3Ambient ∈ coverGroup := by
  rw [← pc3Ambient_from_cb]
  exact (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem b_mem c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem) c_mem) b_mem)

def pc3 : E := ⟨pc3Ambient, pc3Ambient_mem⟩
theorem pc3_val : pc3.val = (SuzukiEightCoverCodeMatrices.pc3, SuzukiEightCoverPcMatrices.pc3) := rfl

def pc4Ambient : Ambient := (SuzukiEightCoverCodeMatrices.pc4, SuzukiEightCoverPcMatrices.pc4)

theorem pc4Ambient_from_cb : b * b = pc4Ambient :=
  Prod.ext SuzukiEightCoverCodeMatrices.pc4_from_cb SuzukiEightCoverPcWords.pc4_from_cb

theorem pc4Ambient_mem : pc4Ambient ∈ coverGroup := by
  rw [← pc4Ambient_from_cb]
  exact (coverGroup.mul_mem b_mem b_mem)

def pc4 : E := ⟨pc4Ambient, pc4Ambient_mem⟩
theorem pc4_val : pc4.val = (SuzukiEightCoverCodeMatrices.pc4, SuzukiEightCoverPcMatrices.pc4) := rfl

def pc5Ambient : Ambient := (SuzukiEightCoverCodeMatrices.pc5, SuzukiEightCoverPcMatrices.pc5)

theorem pc5Ambient_from_cb : c * b⁻¹ * c * b * c * b * b * c * b⁻¹ * c * b * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b * c = pc5Ambient :=
  Prod.ext SuzukiEightCoverCodeMatrices.pc5_from_cb SuzukiEightCoverPcWords.pc5_from_cb

theorem pc5Ambient_mem : pc5Ambient ∈ coverGroup := by
  rw [← pc5Ambient_from_cb]
  exact (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem c_mem (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem)

def pc5 : E := ⟨pc5Ambient, pc5Ambient_mem⟩
theorem pc5_val : pc5.val = (SuzukiEightCoverCodeMatrices.pc5, SuzukiEightCoverPcMatrices.pc5) := rfl

def pc6Ambient : Ambient := (SuzukiEightCoverCodeMatrices.pc6, SuzukiEightCoverPcMatrices.pc6)

theorem pc6Ambient_from_cb : b⁻¹ * c * b * c * b * b * c * b⁻¹ * c * b * c * b * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b * b * c * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b * b * c * b * c = pc6Ambient :=
  Prod.ext SuzukiEightCoverCodeMatrices.pc6_from_cb SuzukiEightCoverPcWords.pc6_from_cb

theorem pc6Ambient_mem : pc6Ambient ∈ coverGroup := by
  rw [← pc6Ambient_from_cb]
  exact (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.inv_mem b_mem) c_mem) b_mem) c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem) c_mem) b_mem) c_mem)

def pc6 : E := ⟨pc6Ambient, pc6Ambient_mem⟩
theorem pc6_val : pc6.val = (SuzukiEightCoverCodeMatrices.pc6, SuzukiEightCoverPcMatrices.pc6) := rfl

def pc7Ambient : Ambient := (SuzukiEightCoverCodeMatrices.pc7, SuzukiEightCoverPcMatrices.pc7)

theorem pc7Ambient_from_cb : b⁻¹ * c * b * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b⁻¹ * c * b * c * b * c * b⁻¹ * c * b⁻¹ * c * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b * c * b⁻¹ * c * b * c * b * c = pc7Ambient :=
  Prod.ext SuzukiEightCoverCodeMatrices.pc7_from_cb SuzukiEightCoverPcWords.pc7_from_cb

theorem pc7Ambient_mem : pc7Ambient ∈ coverGroup := by
  rw [← pc7Ambient_from_cb]
  exact (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.inv_mem b_mem) c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) b_mem) c_mem)

def pc7 : E := ⟨pc7Ambient, pc7Ambient_mem⟩
theorem pc7_val : pc7.val = (SuzukiEightCoverCodeMatrices.pc7, SuzukiEightCoverPcMatrices.pc7) := rfl

def torusAmbient : Ambient := (SuzukiEightCoverCodeMatrices.torus, SuzukiEightCoverPcMatrices.torus)

theorem torusAmbient_from_cb : c * b * c * b⁻¹ * c * b⁻¹ * c * b * c * b⁻¹ * c * b * c * b * b * c * b⁻¹ * c * b * b = torusAmbient :=
  Prod.ext SuzukiEightCoverCodeMatrices.torus_from_cb SuzukiEightCoverPcWords.torus_from_cb

theorem torusAmbient_mem : torusAmbient ∈ coverGroup := by
  rw [← torusAmbient_from_cb]
  exact (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem (coverGroup.mul_mem c_mem b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) c_mem) b_mem) b_mem) c_mem) (coverGroup.inv_mem b_mem)) c_mem) b_mem) b_mem)

def torus : E := ⟨torusAmbient, torusAmbient_mem⟩
theorem torus_val : torus.val = (SuzukiEightCoverCodeMatrices.torus, SuzukiEightCoverPcMatrices.torus) := rfl

def pcAmbient : Fin 8 → Ambient := ![pc0Ambient, pc1Ambient, pc2Ambient, pc3Ambient, pc4Ambient, pc5Ambient, pc6Ambient, pc7Ambient]
def pc : Fin 8 → E := ![pc0, pc1, pc2, pc3, pc4, pc5, pc6, pc7]

theorem pc_val (i : Fin 8) : (pc i).val = pcAmbient i := by
  fin_cases i <;> rfl

theorem pcAmbient_mem (i : Fin 8) : pcAmbient i ∈ coverGroup := by
  fin_cases i
  · exact pc0Ambient_mem
  · exact pc1Ambient_mem
  · exact pc2Ambient_mem
  · exact pc3Ambient_mem
  · exact pc4Ambient_mem
  · exact pc5Ambient_mem
  · exact pc6Ambient_mem
  · exact pc7Ambient_mem

def formAmbient (i : Fin 256) : Ambient := (SuzukiEightCoverCodeForms.form i, SuzukiEightCoverPcForms.form i)

def codePc : Fin 8 → SuzukiEightCoverCodeMatrices.UnitMatrix :=
  ![SuzukiEightCoverCodeMatrices.pc0, SuzukiEightCoverCodeMatrices.pc1,
    SuzukiEightCoverCodeMatrices.pc2, SuzukiEightCoverCodeMatrices.pc3,
    SuzukiEightCoverCodeMatrices.pc4, SuzukiEightCoverCodeMatrices.pc5,
    SuzukiEightCoverCodeMatrices.pc6, SuzukiEightCoverCodeMatrices.pc7]

def coverPc : Fin 8 → SuzukiEightCoverMatrices.UnitMatrix :=
  ![SuzukiEightCoverPcMatrices.pc0, SuzukiEightCoverPcMatrices.pc1,
    SuzukiEightCoverPcMatrices.pc2, SuzukiEightCoverPcMatrices.pc3,
    SuzukiEightCoverPcMatrices.pc4, SuzukiEightCoverPcMatrices.pc5,
    SuzukiEightCoverPcMatrices.pc6, SuzukiEightCoverPcMatrices.pc7]

theorem code_form_eq_word (i : Fin 256) :
    SuzukiEightCoverCodeForms.form i = FiniteEightPcWords.word (G := SuzukiEightCoverCodeMatrices.UnitMatrix) codePc i := by
  fin_cases i <;> rfl

theorem cover_form_eq_word (i : Fin 256) :
    SuzukiEightCoverPcForms.form i = FiniteEightPcWords.word (G := SuzukiEightCoverMatrices.UnitMatrix) coverPc i := by
  fin_cases i <;> rfl

theorem pcAmbient_eq_pair (j : Fin 8) :
    pcAmbient j = (codePc j, coverPc j) := by
  fin_cases j <;> rfl

theorem formAmbient_eq_word (i : Fin 256) :
    formAmbient i = FiniteEightPcWords.word (G := Ambient) pcAmbient i := by
  have hpc : (fun j => (codePc j, coverPc j)) = pcAmbient := by
    funext j
    exact (pcAmbient_eq_pair j).symm
  calc
    formAmbient i = (FiniteEightPcWords.word (G := SuzukiEightCoverCodeMatrices.UnitMatrix) codePc i,
        FiniteEightPcWords.word (G := SuzukiEightCoverMatrices.UnitMatrix) coverPc i) :=
      Prod.ext (code_form_eq_word i) (cover_form_eq_word i)
    _ = FiniteEightPcWords.word (G := Ambient) (fun j => (codePc j, coverPc j)) i :=
      FiniteEightPcWords.word_prod (A := SuzukiEightCoverCodeMatrices.UnitMatrix)
        (B := SuzukiEightCoverMatrices.UnitMatrix) codePc coverPc i
    _ = FiniteEightPcWords.word (G := Ambient) pcAmbient i :=
      congrArg (fun p : Fin 8 → Ambient => FiniteEightPcWords.word (G := Ambient) p i) hpc

theorem formAmbient_mem (H : Subgroup Ambient) (hp : ∀ j, pcAmbient j ∈ H)
    (i : Fin 256) : formAmbient i ∈ H := by
  rw [formAmbient_eq_word]
  exact FiniteEightPcWords.word_mem (G := Ambient) H pcAmbient hp i

def form (i : Fin 256) : E := ⟨formAmbient i, formAmbient_mem coverGroup pcAmbient_mem i⟩

theorem form_val (i : Fin 256) : (form i).val = (SuzukiEightCoverCodeForms.form i, SuzukiEightCoverPcForms.form i) := rfl

theorem form_code_val (i : Fin 256) : ((form i).val.1 : SuzukiEightCoverCodeMatrices.M) = SuzukiEightCoverCodeForms.raw i :=
  SuzukiEightCoverCodeForms.form_val i

theorem form_cover_val (i : Fin 256) : ((form i).val.2 : SuzukiEightCoverMatrices.M) = SuzukiEightCoverPcForms.raw i :=
  SuzukiEightCoverPcForms.form_val i

theorem form_mem (H : Subgroup E) (hp : ∀ j, pc j ∈ H)
    (i : Fin 256) : form i ∈ H := by
  have ha : ∀ j, pcAmbient j ∈ H.map coverGroup.subtype := by
    intro j
    exact Subgroup.mem_map.mpr ⟨pc j, hp j, pc_val j⟩
  obtain ⟨g, hg, he⟩ := formAmbient_mem (H.map coverGroup.subtype) ha i
  have he' : g = form i := Subtype.ext he
  exact he' ▸ hg

def C : E := ⟨c, c_mem⟩
def B : E := ⟨b, b_mem⟩

theorem generates : Subgroup.closure ({C, B} : Set E) = ⊤ :=
  closure_pair_eq_top_of_subtype_closure coverGroup C B rfl

theorem C_inv : C⁻¹ = C := by
  apply Subtype.ext
  apply Prod.ext
  · apply Units.ext
    rfl
  · apply Units.ext
    rfl

end Kourovka2135.SuzukiEightPairedPcData
