import Kourovka2135.SuzukiEightPairedCosets
import Kourovka2135.FiniteCosetCertificate

/-! Actual paired matrix certificate. Generated by generate_paired_upper.py.
Finite data are checked by ordinary kernel proofs, never used as assumptions. -/
set_option autoImplicit false
set_option maxRecDepth 16384
set_option maxHeartbeats 8000000
noncomputable section
namespace Kourovka2135.SuzukiEightPairedUpperBound
open SuzukiEightPairedGoodSet SuzukiEightPairedPcData SuzukiEightPairedPc SuzukiEightPairedCosetData SuzukiEightPairedCosets

/-- The bound concerns the actual paired subgroup generated by c,b. -/
theorem card_le : Nat.card E ≤ 116480 := by
  have h := FiniteCosetCertificate.card_le H ({C, B} : Set E)
    SuzukiEightPairedPcData.generates rep 0 rep_zero step stepInv
  have h' : Nat.card E ≤ Nat.card H * 65 := by
    simpa only [Nat.card_fin] using h
  exact h'.trans (Nat.mul_le_mul_right 65 card_H_le)

end Kourovka2135.SuzukiEightPairedUpperBound
