import Kourovka2135.SuzukiEightPairedPc

/-! Actual paired matrix certificate. Generated by generate_paired_upper.py.
Finite data are checked by ordinary kernel proofs, never used as assumptions. -/
set_option autoImplicit false
set_option maxRecDepth 16384
set_option maxHeartbeats 8000000
noncomputable section
namespace Kourovka2135.SuzukiEightPairedCosetData
open SuzukiEightPairedGoodSet SuzukiEightPairedPcData SuzukiEightCodeField

def rep : Fin 65 → E := ![1, C * form 0, C * form 4, C * form 8, C * form 12, C * form 16, C * form 20, C * form 24, C * form 28, C * form 32, C * form 36, C * form 40, C * form 44, C * form 48, C * form 52, C * form 56, C * form 60, C * form 64, C * form 68, C * form 72, C * form 76, C * form 80, C * form 84, C * form 88, C * form 92, C * form 96, C * form 100, C * form 104, C * form 108, C * form 112, C * form 116, C * form 120, C * form 124, C * form 128, C * form 132, C * form 136, C * form 140, C * form 144, C * form 148, C * form 152, C * form 156, C * form 160, C * form 164, C * form 168, C * form 172, C * form 176, C * form 180, C * form 184, C * form 188, C * form 192, C * form 196, C * form 200, C * form 204, C * form 208, C * form 212, C * form 216, C * form 220, C * form 224, C * form 228, C * form 232, C * form 236, C * form 240, C * form 244, C * form 248, C * form 252]

theorem rep_zero : rep 0 = 1 := rfl

def rep0_code : SuzukiEightCoverCodeMatrices.M := 1
def rep1_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 1, ofCode 0, ofCode 0; ofCode 1, ofCode 0, ofCode 0, ofCode 0]
private theorem rep1_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 0 = rep1_code := by decide +kernel
def rep2_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 1, ofCode 0, ofCode 1; ofCode 1, ofCode 0, ofCode 1, ofCode 1]
private theorem rep2_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 4 = rep2_code := by decide +kernel
def rep3_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 1, ofCode 0, ofCode 2; ofCode 1, ofCode 0, ofCode 2, ofCode 6]
private theorem rep3_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 8 = rep3_code := by decide +kernel
def rep4_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 1, ofCode 0, ofCode 3; ofCode 1, ofCode 0, ofCode 3, ofCode 7]
private theorem rep4_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 12 = rep4_code := by decide +kernel
def rep5_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 1, ofCode 0, ofCode 4; ofCode 1, ofCode 0, ofCode 4, ofCode 2]
private theorem rep5_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 16 = rep5_code := by decide +kernel
def rep6_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 1, ofCode 0, ofCode 5; ofCode 1, ofCode 0, ofCode 5, ofCode 3]
private theorem rep6_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 20 = rep6_code := by decide +kernel
def rep7_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 1, ofCode 0, ofCode 6; ofCode 1, ofCode 0, ofCode 6, ofCode 4]
private theorem rep7_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 24 = rep7_code := by decide +kernel
def rep8_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 0; ofCode 0, ofCode 1, ofCode 0, ofCode 7; ofCode 1, ofCode 0, ofCode 7, ofCode 5]
private theorem rep8_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 28 = rep8_code := by decide +kernel
def rep9_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 1; ofCode 1, ofCode 1, ofCode 0, ofCode 1]
private theorem rep9_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 32 = rep9_code := by decide +kernel
def rep10_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 0; ofCode 1, ofCode 1, ofCode 1, ofCode 1]
private theorem rep10_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 36 = rep10_code := by decide +kernel
def rep11_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 3; ofCode 1, ofCode 1, ofCode 2, ofCode 5]
private theorem rep11_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 40 = rep11_code := by decide +kernel
def rep12_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 2; ofCode 1, ofCode 1, ofCode 3, ofCode 5]
private theorem rep12_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 44 = rep12_code := by decide +kernel
def rep13_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 5; ofCode 1, ofCode 1, ofCode 4, ofCode 7]
private theorem rep13_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 48 = rep13_code := by decide +kernel
def rep14_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 4; ofCode 1, ofCode 1, ofCode 5, ofCode 7]
private theorem rep14_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 52 = rep14_code := by decide +kernel
def rep15_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 7; ofCode 1, ofCode 1, ofCode 6, ofCode 3]
private theorem rep15_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 56 = rep15_code := by decide +kernel
def rep16_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 1; ofCode 0, ofCode 1, ofCode 1, ofCode 6; ofCode 1, ofCode 1, ofCode 7, ofCode 3]
private theorem rep16_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 60 = rep16_code := by decide +kernel
def rep17_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 1, ofCode 6, ofCode 7; ofCode 1, ofCode 2, ofCode 0, ofCode 5]
private theorem rep17_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 64 = rep17_code := by decide +kernel
def rep18_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 1, ofCode 6, ofCode 6; ofCode 1, ofCode 2, ofCode 1, ofCode 6]
private theorem rep18_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 68 = rep18_code := by decide +kernel
def rep19_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 1, ofCode 6, ofCode 5; ofCode 1, ofCode 2, ofCode 2, ofCode 7]
private theorem rep19_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 72 = rep19_code := by decide +kernel
def rep20_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 1, ofCode 6, ofCode 4; ofCode 1, ofCode 2, ofCode 3, ofCode 4]
private theorem rep20_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 76 = rep20_code := by decide +kernel
def rep21_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 1, ofCode 6, ofCode 3; ofCode 1, ofCode 2, ofCode 4, ofCode 4]
private theorem rep21_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 80 = rep21_code := by decide +kernel
def rep22_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 1, ofCode 6, ofCode 2; ofCode 1, ofCode 2, ofCode 5, ofCode 7]
private theorem rep22_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 84 = rep22_code := by decide +kernel
def rep23_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 1, ofCode 6, ofCode 1; ofCode 1, ofCode 2, ofCode 6, ofCode 6]
private theorem rep23_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 88 = rep23_code := by decide +kernel
def rep24_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 2; ofCode 0, ofCode 1, ofCode 6, ofCode 0; ofCode 1, ofCode 2, ofCode 7, ofCode 5]
private theorem rep24_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 92 = rep24_code := by decide +kernel
def rep25_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 3; ofCode 0, ofCode 1, ofCode 7, ofCode 0; ofCode 1, ofCode 3, ofCode 2, ofCode 6]
private theorem rep25_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 96 = rep25_code := by decide +kernel
def rep26_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 3; ofCode 0, ofCode 1, ofCode 7, ofCode 1; ofCode 1, ofCode 3, ofCode 3, ofCode 4]
private theorem rep26_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 100 = rep26_code := by decide +kernel
def rep27_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 3; ofCode 0, ofCode 1, ofCode 7, ofCode 2; ofCode 1, ofCode 3, ofCode 0, ofCode 6]
private theorem rep27_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 104 = rep27_code := by decide +kernel
def rep28_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 3; ofCode 0, ofCode 1, ofCode 7, ofCode 3; ofCode 1, ofCode 3, ofCode 1, ofCode 4]
private theorem rep28_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 108 = rep28_code := by decide +kernel
def rep29_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 3; ofCode 0, ofCode 1, ofCode 7, ofCode 4; ofCode 1, ofCode 3, ofCode 6, ofCode 3]
private theorem rep29_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 112 = rep29_code := by decide +kernel
def rep30_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 3; ofCode 0, ofCode 1, ofCode 7, ofCode 5; ofCode 1, ofCode 3, ofCode 7, ofCode 1]
private theorem rep30_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 116 = rep30_code := by decide +kernel
def rep31_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 3; ofCode 0, ofCode 1, ofCode 7, ofCode 6; ofCode 1, ofCode 3, ofCode 4, ofCode 3]
private theorem rep31_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 120 = rep31_code := by decide +kernel
def rep32_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 3; ofCode 0, ofCode 1, ofCode 7, ofCode 7; ofCode 1, ofCode 3, ofCode 5, ofCode 1]
private theorem rep32_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 124 = rep32_code := by decide +kernel
def rep33_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 1, ofCode 2, ofCode 3; ofCode 1, ofCode 4, ofCode 0, ofCode 7]
private theorem rep33_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 128 = rep33_code := by decide +kernel
def rep34_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 1, ofCode 2, ofCode 2; ofCode 1, ofCode 4, ofCode 1, ofCode 2]
private theorem rep34_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 132 = rep34_code := by decide +kernel
def rep35_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 1, ofCode 2, ofCode 1; ofCode 1, ofCode 4, ofCode 2, ofCode 2]
private theorem rep35_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 136 = rep35_code := by decide +kernel
def rep36_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 1, ofCode 2, ofCode 0; ofCode 1, ofCode 4, ofCode 3, ofCode 7]
private theorem rep36_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 140 = rep36_code := by decide +kernel
def rep37_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 1, ofCode 2, ofCode 7; ofCode 1, ofCode 4, ofCode 4, ofCode 3]
private theorem rep37_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 144 = rep37_code := by decide +kernel
def rep38_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 1, ofCode 2, ofCode 6; ofCode 1, ofCode 4, ofCode 5, ofCode 6]
private theorem rep38_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 148 = rep38_code := by decide +kernel
def rep39_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 1, ofCode 2, ofCode 5; ofCode 1, ofCode 4, ofCode 6, ofCode 6]
private theorem rep39_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 152 = rep39_code := by decide +kernel
def rep40_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 4; ofCode 0, ofCode 1, ofCode 2, ofCode 4; ofCode 1, ofCode 4, ofCode 7, ofCode 3]
private theorem rep40_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 156 = rep40_code := by decide +kernel
def rep41_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 1, ofCode 3, ofCode 0; ofCode 1, ofCode 5, ofCode 4, ofCode 2]
private theorem rep41_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 160 = rep41_code := by decide +kernel
def rep42_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 1, ofCode 3, ofCode 1; ofCode 1, ofCode 5, ofCode 5, ofCode 6]
private theorem rep42_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 164 = rep42_code := by decide +kernel
def rep43_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 1, ofCode 3, ofCode 2; ofCode 1, ofCode 5, ofCode 6, ofCode 5]
private theorem rep43_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 168 = rep43_code := by decide +kernel
def rep44_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 1, ofCode 3, ofCode 3; ofCode 1, ofCode 5, ofCode 7, ofCode 1]
private theorem rep44_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 172 = rep44_code := by decide +kernel
def rep45_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 1, ofCode 3, ofCode 4; ofCode 1, ofCode 5, ofCode 0, ofCode 2]
private theorem rep45_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 176 = rep45_code := by decide +kernel
def rep46_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 1, ofCode 3, ofCode 5; ofCode 1, ofCode 5, ofCode 1, ofCode 6]
private theorem rep46_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 180 = rep46_code := by decide +kernel
def rep47_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 1, ofCode 3, ofCode 6; ofCode 1, ofCode 5, ofCode 2, ofCode 5]
private theorem rep47_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 184 = rep47_code := by decide +kernel
def rep48_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 5; ofCode 0, ofCode 1, ofCode 3, ofCode 7; ofCode 1, ofCode 5, ofCode 3, ofCode 1]
private theorem rep48_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 188 = rep48_code := by decide +kernel
def rep49_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 6; ofCode 0, ofCode 1, ofCode 4, ofCode 0; ofCode 1, ofCode 6, ofCode 5, ofCode 3]
private theorem rep49_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 192 = rep49_code := by decide +kernel
def rep50_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 6; ofCode 0, ofCode 1, ofCode 4, ofCode 1; ofCode 1, ofCode 6, ofCode 4, ofCode 4]
private theorem rep50_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 196 = rep50_code := by decide +kernel
def rep51_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 6; ofCode 0, ofCode 1, ofCode 4, ofCode 2; ofCode 1, ofCode 6, ofCode 7, ofCode 2]
private theorem rep51_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 200 = rep51_code := by decide +kernel
def rep52_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 6; ofCode 0, ofCode 1, ofCode 4, ofCode 3; ofCode 1, ofCode 6, ofCode 6, ofCode 5]
private theorem rep52_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 204 = rep52_code := by decide +kernel
def rep53_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 6; ofCode 0, ofCode 1, ofCode 4, ofCode 4; ofCode 1, ofCode 6, ofCode 1, ofCode 4]
private theorem rep53_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 208 = rep53_code := by decide +kernel
def rep54_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 6; ofCode 0, ofCode 1, ofCode 4, ofCode 5; ofCode 1, ofCode 6, ofCode 0, ofCode 3]
private theorem rep54_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 212 = rep54_code := by decide +kernel
def rep55_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 6; ofCode 0, ofCode 1, ofCode 4, ofCode 6; ofCode 1, ofCode 6, ofCode 3, ofCode 5]
private theorem rep55_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 216 = rep55_code := by decide +kernel
def rep56_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 6; ofCode 0, ofCode 1, ofCode 4, ofCode 7; ofCode 1, ofCode 6, ofCode 2, ofCode 2]
private theorem rep56_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 220 = rep56_code := by decide +kernel
def rep57_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 7; ofCode 0, ofCode 1, ofCode 5, ofCode 5; ofCode 1, ofCode 7, ofCode 3, ofCode 1]
private theorem rep57_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 224 = rep57_code := by decide +kernel
def rep58_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 7; ofCode 0, ofCode 1, ofCode 5, ofCode 4; ofCode 1, ofCode 7, ofCode 2, ofCode 7]
private theorem rep58_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 228 = rep58_code := by decide +kernel
def rep59_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 7; ofCode 0, ofCode 1, ofCode 5, ofCode 7; ofCode 1, ofCode 7, ofCode 1, ofCode 2]
private theorem rep59_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 232 = rep59_code := by decide +kernel
def rep60_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 7; ofCode 0, ofCode 1, ofCode 5, ofCode 6; ofCode 1, ofCode 7, ofCode 0, ofCode 4]
private theorem rep60_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 236 = rep60_code := by decide +kernel
def rep61_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 7; ofCode 0, ofCode 1, ofCode 5, ofCode 1; ofCode 1, ofCode 7, ofCode 7, ofCode 2]
private theorem rep61_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 240 = rep61_code := by decide +kernel
def rep62_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 7; ofCode 0, ofCode 1, ofCode 5, ofCode 0; ofCode 1, ofCode 7, ofCode 6, ofCode 4]
private theorem rep62_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 244 = rep62_code := by decide +kernel
def rep63_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 7; ofCode 0, ofCode 1, ofCode 5, ofCode 3; ofCode 1, ofCode 7, ofCode 5, ofCode 1]
private theorem rep63_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 248 = rep63_code := by decide +kernel
def rep64_code : SuzukiEightCoverCodeMatrices.M := !![ofCode 0, ofCode 0, ofCode 0, ofCode 1; ofCode 0, ofCode 0, ofCode 1, ofCode 7; ofCode 0, ofCode 1, ofCode 5, ofCode 2; ofCode 1, ofCode 7, ofCode 4, ofCode 7]
private theorem rep64_code_step : SuzukiEightCoverCodeMatrices.cMatrix * SuzukiEightCoverCodeForms.raw 252 = rep64_code := by decide +kernel

def repRaw_code : Fin 65 → SuzukiEightCoverCodeMatrices.M := ![rep0_code, rep1_code, rep2_code, rep3_code, rep4_code, rep5_code, rep6_code, rep7_code, rep8_code, rep9_code, rep10_code, rep11_code, rep12_code, rep13_code, rep14_code, rep15_code, rep16_code, rep17_code, rep18_code, rep19_code, rep20_code, rep21_code, rep22_code, rep23_code, rep24_code, rep25_code, rep26_code, rep27_code, rep28_code, rep29_code, rep30_code, rep31_code, rep32_code, rep33_code, rep34_code, rep35_code, rep36_code, rep37_code, rep38_code, rep39_code, rep40_code, rep41_code, rep42_code, rep43_code, rep44_code, rep45_code, rep46_code, rep47_code, rep48_code, rep49_code, rep50_code, rep51_code, rep52_code, rep53_code, rep54_code, rep55_code, rep56_code, rep57_code, rep58_code, rep59_code, rep60_code, rep61_code, rep62_code, rep63_code, rep64_code]

theorem rep_code_val (i : Fin 65) : ((rep i).val.1 : SuzukiEightCoverCodeMatrices.M) = repRaw_code i := by
  fin_cases i
  · rfl
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 0).val = rep1_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep1_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 4).val = rep2_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep2_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 8).val = rep3_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep3_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 12).val = rep4_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep4_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 16).val = rep5_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep5_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 20).val = rep6_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep6_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 24).val = rep7_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep7_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 28).val = rep8_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep8_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 32).val = rep9_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep9_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 36).val = rep10_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep10_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 40).val = rep11_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep11_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 44).val = rep12_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep12_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 48).val = rep13_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep13_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 52).val = rep14_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep14_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 56).val = rep15_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep15_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 60).val = rep16_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep16_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 64).val = rep17_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep17_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 68).val = rep18_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep18_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 72).val = rep19_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep19_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 76).val = rep20_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep20_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 80).val = rep21_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep21_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 84).val = rep22_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep22_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 88).val = rep23_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep23_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 92).val = rep24_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep24_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 96).val = rep25_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep25_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 100).val = rep26_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep26_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 104).val = rep27_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep27_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 108).val = rep28_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep28_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 112).val = rep29_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep29_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 116).val = rep30_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep30_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 120).val = rep31_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep31_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 124).val = rep32_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep32_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 128).val = rep33_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep33_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 132).val = rep34_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep34_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 136).val = rep35_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep35_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 140).val = rep36_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep36_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 144).val = rep37_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep37_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 148).val = rep38_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep38_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 152).val = rep39_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep39_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 156).val = rep40_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep40_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 160).val = rep41_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep41_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 164).val = rep42_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep42_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 168).val = rep43_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep43_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 172).val = rep44_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep44_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 176).val = rep45_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep45_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 180).val = rep46_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep46_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 184).val = rep47_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep47_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 188).val = rep48_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep48_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 192).val = rep49_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep49_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 196).val = rep50_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep50_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 200).val = rep51_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep51_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 204).val = rep52_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep52_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 208).val = rep53_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep53_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 212).val = rep54_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep54_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 216).val = rep55_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep55_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 220).val = rep56_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep56_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 224).val = rep57_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep57_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 228).val = rep58_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep58_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 232).val = rep59_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep59_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 236).val = rep60_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep60_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 240).val = rep61_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep61_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 244).val = rep62_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep62_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 248).val = rep63_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep63_code_step
  · change SuzukiEightCoverCodeMatrices.cMatrix * (SuzukiEightCoverCodeForms.form 252).val = rep64_code
    rw [SuzukiEightCoverCodeForms.form_val]
    exact rep64_code_step

def rep0_cover : SuzukiEightCoverMatrices.M := 1
def rep1_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 57715516349220641403552672848487180539787327883306810864806786229133686534553590235253726720322281248304696396407678163996423539030539514420434047150794533445996911222042140830280374970866658086254804689812692867296416052193614038169741897694115186028675210803390942302216698784549514502586745722098562693806901898226763405414194130822058360661504615544353350121749289366482079997437184769749960227204173432737652444838288261870650905031915673825511698060438674621236455525824613797588721148170802786565743242641416
private theorem rep1_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 0 = rep1_cover := by decide +kernel
def rep2_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7809626666861617798050507446327563168368492652562676202802092790450245279930031603642292857599351900293370913906305715570065889890016360990299175256132181487397358502246797485168954664629237560069838161358642351155140316804134278439577430142033680167164532068608998326650690008073656722652644340965382436230100882448266233529584172859540202273005050077719720545164292837249737101994913632639138650903487173266349657845776540270428365122317676571870261870212593702744096303385905924096013235441096699133028010139303557379
private theorem rep2_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 4 = rep2_cover := by decide +kernel
def rep3_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6398654540388483017394395403327451800997725030660861020311870056880602771427437922391144633730299986151075345959498808226979022806833991595322240027840311174581248670073774745375893194057244347953986312412802882414183878394796432680821414408883049459348723005433010948955580401427283659522199562837777416170162591652984670320371828869870186720949946753109986584333455305231019017001818891549295100136291136695492398481498897851275686710525185093019904175467329759453971266358139827528076659213013510779106235887405900035
private theorem rep3_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 8 = rep3_cover := by decide +kernel
def rep4_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 5940611252302700369516048361453787277049154173021665078911588944803121821650292429435470528695446110637420071545253151775497389019839470323458837195431468018471887515378121255819237108833136077709630927973687975048922330813109797213117628358538618234004552602833999303304546046729632450720887103423046581075919804949370601177971232856376995037274022654872111897899328769754603692975611457863609471822335000950983709582822265175971883584171174937646326783762661823943639820908195551542534075631878997567618114408191464100
private theorem rep4_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 12 = rep4_cover := by decide +kernel
def rep5_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2693295931179929669103795919226743459080929469685482182395156898807644141631593886523627524926871662051825375469755299964399640915882491783452865014100327757583467152806653029578890154532987731529391363900645804425731086879140717247157745557478912672520581891325234091645325354595673158779512535260952124932964927450981249717105550745122297785131812113948793083990369665307438954660319777325371731606524615583336896130647009161382985991535321012440700441663836283083121154783339943298940199560060115602019876767959721504
private theorem rep5_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 16 = rep5_cover := by decide +kernel
def rep6_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 784094528117706243531774438418076705666034757703618732197128330338050691620977792748896591584108367406343816264015005847261888675333140990572175904162094612330206302052727053551078340832904921379196342165647265237405304589134370786203191984215510015229001380458338075207481235249801010404710259865282738419211978709627550174144556804058779357302305622937185975564701765270272728156406760143378657206630085571194218417743957997029786570951413435899517382881685884128791296241499152888491024625074546638125021462434726116
private theorem rep6_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 20 = rep6_cover := by decide +kernel
def rep7_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6690096022357955795080754835769714440261410025970063552960342914066863872952011859380515110868765567124855554575960280208563210139937536235926141997163433855759558812451301096703386515620113323308901997278038825061952224344301879473991714634786898008052346299893025069789917675817657952868173653010962445274905848624572191151324716859402129201246457628051757000744606853678634223997490754734068598936764101822395049408391757183571071998712318504057091683123225065211424045007372728787340899262906972862866349644846339660
private theorem rep7_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 24 = rep7_cover := by decide +kernel
def rep8_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2911863587117139757998684846653374719471442320701898394842936642052147085996393303889180336490781920714552899526576527364500194078507008228487698538073209157191708212496309265650419943981196466819307169974962365995359102545324434992417254726915313955387670991471254095970676950875741680911882608981702876712815164849048414900321687339477066466149559788727945049357132427460888064564401785761307029327231771172803271609330696437223684539451723490704289289338208854345347905447191390511315651381262329999352050295398086684
private theorem rep8_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 28 = rep8_cover := by decide +kernel
def rep9_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2142425345212812293673121521839206369461331891916532220089415672199554016089414077000697605170423675499296200010440132469921815326050786907751107603948066583529810498535154448551376238602582488084325984920424250913405468054591964955460944102948995857668558174174617230871837903065087291753774245697121818615192987956448516543878837857041248283093915708729949598336338494897205008622858203077392448147113002541964294296940521661305230000877985464341262593428251830015066730556925377425187569705891879848159868775457507458
private theorem rep9_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 32 = rep9_cover := by decide +kernel
def rep10_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2661407993415120438412273558188260901596238501505163300697646510638663684703788532877561838196452235983911076114427283822137928849068927592054026746823296451351808971920936366543800587590990119270512108177786844748839365694999851047317265886260008252148956037561092318826345519113031046350336787994632236127137248805313820135551424346492456908072609196506218525932942112287486457731961170625016666772372218611679851872486809570199935265732222721260974356095511512013711009955978737558114721412784906195457646649579780320
private theorem rep10_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 36 = rep10_cover := by decide +kernel
def rep11_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8042899016505501465135244973417231683622002032979629247771542638399048424373673727653155691292256400339686781262453783143988853843363228417587414992071871680839148346919221020008271557824703522795212513044622865356468900105850874191195535991562599503556775941928012711491428400954164706904688210090702389639460926204495721939759523959697860921515112241147396142364429214939617625607698456414811746619817157373658371456527505770497267712090000638532890119389788389612240423835622000840734067713239661881136662723089180929
private theorem rep11_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 40 = rep11_cover := by decide +kernel
def rep12_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 40870055475210641610140611141530274432506303201609162098950865979924978428851327959666715818241414492222916898334591963041131157056451414970537550757979373081728765000400922180640469972128829071081803276744999959433625219448192472763052404069234472933749036047778896443466464998682897674698635669377638705180816115006673899061779179933415360827623969384658614274374260956188854110486192646334630357735728343116992869184591789094002764442276820558789959170905480961339794960261390738350618925951373071193966916305006874
private theorem rep12_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 44 = rep12_cover := by decide +kernel
def rep13_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6147005640847640306188712442610355342361492545775690087005146520522804100608351423591696631720578180153986149421491293950746827798321855401767464587512809355848438811120401472186700437570051701502402481172924160681948545002690586042257395675185537470115095887619921068591235852426824769375408975923107768702474706288902569783434331372159205878773812702386946555055748630232075856546613259657243010724163853405327570514111284153110411289544965309254607528177147474534803711801686548712790537572437501121301245248427341404
private theorem rep13_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 48 = rep13_cover := by decide +kernel
def rep14_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4345416952125069218768349980073340726856682797560464209266196103994223598511550305384389927213024675423909629124784143925619900307466127760161740110790078250923532831525324580698012410483145578329015715715812261077497443725110648332217912869958840637638097253818003618613099470758979809609675914622083460678117640033636474878140491106804326195236400021191348840726548027780136302962506240811533172252785453798897018927581414481046495937022906698052579009096934382535999126609041694698848848972179495988918764640410048666
private theorem rep14_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 52 = rep14_cover := by decide +kernel
def rep15_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6682218888567490624562806216270701264635263853536103097744345827853787967877200972243472250596067730745483427285934178490669300488126850514651709108284344621517121771718038841025229890863630188920791694360465687940148881817995327141869601910538987336746911239844639616440508366523860521717918047510283949383037033464288053244395095021605132302538102548018925458026799745411590333690075130660741877051303307061446831063075150848861077753346667271884407930359312268275338688991355469236728606872971558997125216856285755472
private theorem rep15_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 56 = rep15_cover := by decide +kernel
def rep16_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2872000076797768268992644797683700226412371601373860488129216360332485047573696637878789933523949972746026764990418179759883400258799251020340321854250324104746258807437485771318803112483154253161494352890511490427402116892693413818310130295427519483505569562813935084562482248626334951601735701417928973472699480848459729333362506848309611589430510774806123153053410676926487177744737565992690369866880401623451626616879523442882746810927134351975257268880972361978030534107310841775006104668228441494526025414258526488
private theorem rep16_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 60 = rep16_cover := by decide +kernel
def rep17_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 3826887092113932870443201756191171078277450548264544772520136375032414429569721469198921708746804589941328335767288142229485442839278166172298618104595439700971005626715687100296560685106537297493513136565481387223363609177088920648174748209169693404038964444924658275340307522929014205964231171707118526065690624871840995467290848937587734773739564641495040338627051644504835658331018852101340440631006307719279564288433699433994373759067021493429686930187521811244985688907995644167983320217466779947084805948857726028
private theorem rep17_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 64 = rep17_cover := by decide +kernel
def rep18_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 983734417840898058300562462514793351790965426198736761085330365771352542996982605925840676405853006683045124437339225551649366202684545664982015637260829149259789685491781769398001352146050586552094763343312688618014419561895929594089240547201382138175741623901820051944239702180398831780895279155388228003390968207088362165476853519692816545635864464110844423701124335048118340829435072471107122690500505236575808796295289445051138756911151329542238990017920744870386498075369720527099123481054664600395652173128278106
private theorem rep18_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 68 = rep18_cover := by decide +kernel
def rep19_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6684051308455662523190706209271292110696802328818628762188029413444874791535345691901746797457508974262328059858347442444712826571125467214625791706908419451454205866899733036336612357487796165525345194394948851658516735875793281167976845591833122873319571173315319787373072188045377132802326891826513074711223633968327090596991751578028995414755973504399198389320083266248156866209582920373785263068784263783703869486976156428948259062247123046997648271601129325389334360238670966196651179316144778949312306316835603104
private theorem rep19_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 72 = rep19_cover := by decide +kernel
def rep20_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 1933935285905300374441934474142500658481284789240575483840902190050770943515245896802239848042262899769151469116096399460975979949915193590099876813163124216614230938049997500957641270197504361138546590752946921886491764882922329697672995585741733409465480280250442127178684569142201006028752707906680487887965665769624579788270421546859092261836143521706006285965164615083069315143058721324666538396464523083366796221118157185243052323667420349672105179837708005300317490835782148551429248515354775264432260599473508888
private theorem rep20_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 76 = rep20_cover := by decide +kernel
def rep21_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6428840763207066018527932900165588006391737355998149939863162204339436397204939919178229284205750169821226148684796146296109217503728887571554962626249333300834133749175587022202715995354190221202986056220594371052552408906495947580188440608390914703093341196894929243307840034611546017250662100106056384986687005942555862838974040063916577447281465497368653664554177956840087925422952015374707998213108452082336125339653897892755701459751917754155427218734598036811142338113613661059074693320867946499445226032000140952
private theorem rep21_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 80 = rep21_cover := by decide +kernel
def rep22_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8333899652994042498316073469737261305917833295754233387988377973617951373798873955630626433969477686346565837300858495784795269812077493203636454221948822339764686330919161285490344906100654985461233509922322904646172897424963060668595990425010215947468820920828616092857743384745764832164921229689429170816007220682389870354895749816736955821768639688692768003630164925483881127778304987933781783586538147206289409660985441918317149996770022334049321551955425197472811412706683484947066593704771057835276339634013308556
private theorem rep22_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 84 = rep22_cover := by decide +kernel
def rep23_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6236581945182277919286610729109253884027180357942595888713265357319308568929121661666660641792089940808839922294012073105787478154602509517956180341108103898437901840196297728524246202888281724781080951001218062423262395238916847421535519538231612121191661229502414090109580542737783940795918666799126613355593051683010530624697746157098934592583670290244109213237240205392562890545306524587208058539368056435495045056321485017856652726034360955165173079804389601629110118159848738141842195353743774815520069764792764064
private theorem rep23_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 88 = rep23_cover := by decide +kernel
def rep24_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8515666916591131882408400297251773160809191958362776889257663623464291245829588017024874776708390858002505697546127223405721126172191820970245929095652540002110815473939882295104608590605854702167194383134493860831142694403214915004593866229252370778092626689764950118699521063440637290530358706888094078326521289621870098076502293951062322975801535700676654463700203704895058675676567265994245420701267927354544821783141971503112439363117662619354139749446421520846749713664413152801896767771358021587841879909422118428
private theorem rep24_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 92 = rep24_cover := by decide +kernel
def rep25_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4116851899229521445685524578751860257888815004140118036433101779140569583188684947172225146732221402887625434771149415216105391848986428169031462013240651960236631164769047783091906822632805076168772891596358125200633949674155016312936084984946086525777444072433504336464722929682727984854110508150427357076091492823600833465849958279831943822997271575155712389782457867562722023322593401237231743460981204957295142979897548188483708344705916551464192408882992770963133384374947330919248247681830079431777397612935921937
private theorem rep25_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 96 = rep25_cover := by decide +kernel
def rep26_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6657673640644847536623514122937966759578891860049828258525379593690568300455588122656893252796364957141320929965474990442454773483044086374686056605255385428463508496801003385259618391873379863498050352785758994680704815440608309956963577656331574447949398596026460648860363763002759939927153627195069988768516933059396795999739854773671847113342821804560214286297334921078369682315842335226701880768097769416609511919533692376717555812897158138468726356638333067064382897436416353430519802319786401605881353805497411353
private theorem rep26_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 100 = rep26_cover := by decide +kernel
def rep27_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 1955477826867789991155185011790208076264682802095659161093810718861481057421737200420173898739232191775033650579663050425776464275598978672509821273883841760962981840060765857955412772842147437261878173304838662796350529244381143536346970224345328848658033988631111357796680446464191890375069833729938052279104380644170115367853490355581514498124982812583259506369722266647770143056630183202771151113811913423215763138345125114561812773689548895440125814255062687613386318339571985410438325262730446783348240382404956180
private theorem rep27_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 104 = rep27_cover := by decide +kernel
def rep28_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4529536290046744563666607811341230313492358317256729872278211994447204908452293322627442296240628765956465783802901049186739713680443134019135364556449211699381281353267561185861367667548416564591789743153799259032297621937016843192852220766565724164400117244754550967078467629510327339698934998254026947675167683321457283040606278613026938080652997577724932435125130503318840281393719106000142457826982936205202478000554289982955810163365324373812837811854145962751141351817469336565754448029550215431328664200535605468
private theorem rep28_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 108 = rep28_cover := by decide +kernel
def rep29_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4772409930518942438801638923290829201928820904778714886025335123210943657990858561843133578075393077981524970944445422182895180348694129931060314101829482134711625327492395993368824782930093979111265437195558380911961086606893298613121958989770685356547187227439665275037204778730151792121618288772713952590199615159108482181873636407448495172942887899424808103070732334410334731113050649819238341271002441217097299192438005725267419972215879093195259314294535448116186837636717351911069311727350367297617398193359798556
private theorem rep29_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 112 = rep29_cover := by decide +kernel
def rep30_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8582262174870381704545410116480881180045871928000445222391662743696166122142683509350022121307437753239036881569852926976278772373302371418958920258112634976502295189571567549589919865759479405394072824561547355354508653633694704676816066605340823163549336367371120384248165100574788026352920302676458882635126078387617475137344509547010671825575779212436861754802053543787424138177013456859548119083658968469365851107154899148625452989466000447902124888520869029689173783459577591623861594790314256359542830392733212804
private theorem rep30_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 116 = rep30_cover := by decide +kernel
def rep31_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4296115796948560478326514670201479673737996970006763330250407462893510451689939285739448518407147469757159113439712330294732742763466311560580878239069487040199957024049904192353952816153256106939115759631566059115248981115784356139583017088766442722175567612264485857251928900478678395408386891486461894063648068890991171127488364388927803615770231244445305209832757007898392177796894530616554355413344346712135251426090497720240270485684576823203969043862603969688647017309582077804459546513476599763806539065374868121
private theorem rep31_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 120 = rep31_cover := by decide +kernel
def rep32_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8349999897062628903679428280884593227891288319502588783237426364194258783041041221045645485744250240321033393735540918573660254024568419822486975738698877427700019497013328689654113357531823565301544662533797801811111772217769337893629892172885267564250733451998397938374652984180289993724947151122407932238590542331242984847895514107322861385752553086425743987164740142421037834774777448746649775950714319359729211105861815551950234596071975917402846521081507837561085557356331534254863799879332020569285259223225336971
private theorem rep32_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 124 = rep32_cover := by decide +kernel
def rep33_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2010138695004093392010415493079640515406155805590151602257041738299307369557488560823148992929744786825181676555193930329534786132851862848177068798892287275677438662418614178129087101223581615871300043172921835945327627081303522644003125336465295353391096188666238653151459929525479854313577576469347991368141300253044030271413622811736360792371598603919746234701446516814598169604258020818004103485809245107802734198910787985216462646669178671103136639083786552945042914837631123577003582266850252384116281526815565458
private theorem rep33_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 128 = rep33_cover := by decide +kernel
def rep34_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 602573568078516858106583011725545418611906825218561093361838769168682549063683429178087259055186934539453867599395070964109092780412404272372204186199522900559265109795934656493213481322796228443932616012269627591507574891647692688385793442224375870901883382394914970486691217173349142323665389948043500057833449723276150808616928512546207613728769581977181341319309974565288371340957051866673818853457571524508024385055368095413951132704801217818224089989037391628727125701019845357979668804097497264611295527533289482
private theorem rep34_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 132 = rep34_cover := by decide +kernel
def rep35_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 5737618111994199963379422216210923805000066032706743707031855895313291187645299358467820851071057230588543670035091697479481942119723835825590386194240707690557784927733959092084917117541726092083099436632410898697532796941990654498020115589910376301932081622130621370728924645812948256450030001619007413862231188487527444480438313412169661960230487688824562072029724322661964971480355445549546309906300054134570053083027853450083774894469720414252145790653271512952187865104723662478599082932249156914138430741212897368
private theorem rep35_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 136 = rep35_cover := by decide +kernel
def rep36_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4355100634851946342801568402295382608874048377257183731268114600881057897027501538315040921347333185780089704341567497543640538912927052019507682233519722446101182643113246297021854629847713486667386066278367682649889699717258950256817180511086099685109983653077250383155873922004035960194317167309910448257055798825951511735764009333812019932114668518299621638662305964857675868833434397947565324147680122750302756169423525674069865811096796410198195245045066620277535950498884294043046933754927412543670059607693494466
private theorem rep36_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 140 = rep36_cover := by decide +kernel
def rep37_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 3795444870103777850893846641677608038414437038257136947680532177881435433805500000657647828286639255717578128841841532271185706900540579781603681157309813220024715314494274029265547326603178077677351911312050656528419981595422050974819945490131118402284843636366038333288966752864169845175046568494344902965912371070491733588890269884536330330238049952276337541972470911657136037560931871530060603303359405802914411863834985956502740483971996281580281073710891293681790385079687005544007834790375167877852226760509303010
private theorem rep37_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 144 = rep37_cover := by decide +kernel
def rep38_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8525737109982909999541001397713851712909355154263248138017629860973293880334622683935865053656305480413005715525067705130123393003683245567123367014737054140562112828417966470558452005171054268866571313058163471420925798028764436490427515824336106095867181881733459946945122624284459444419128438464180107757432373147294392936851923941839434513387388707460523649047216286647495949639705786060293767159894817281926090076108840508785811071648354644366860802032767354125345222815689510610680583620078180348121033447528044636
private theorem rep38_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 148 = rep38_cover := by decide +kernel
def rep39_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 5807638601741469650111861964001716931815574765838297555510861456409042317605528597151055718639134713581183705999678396011928343785026408716258525163041550825417632706427697742267486037084815128319398838105267111578571574473140435170439934105730792472069257835046848250130236616003479236930632133858487252115680273360211256274645284105341688832885179428266381566158536241612861683151729225471118149213239186715050907336615789301049329649763823336255888313299417315700744632116842851388528765388136156471064277712135786642
private theorem rep39_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 152 = rep39_cover := by decide +kernel
def rep40_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 1005292533360356350481017603086072525206733917508444161601977581035983659964046365707318016154156194877523407403493500717837570045311477666154323312385030855095710637897796987674527287466312536062114530961719035502891993765443437153244924430456347403687699640517303564583128287555716098099280705134725226447383379012111944486189393985520157500504995469257480724413105606444946964491605705733027845949448069431019775547778115581143326050394581464046983177651642235958615914268382997117839150189215666194991601620393769025
private theorem rep40_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 156 = rep40_cover := by decide +kernel
def rep41_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 711115646214353179975069388429365064623995222151561391679353137166762634035009561998913061284131873976719365500894237665228801022779072083408451375559833461755019999615886964233912132105224506640441834226366359824809460815273519827461105361486725187217538977593952303237602257411882828606823810055165891206935642601736074105071216838050850303421851889883297328049757698760521869085107760905781471331144692079197690194816147503307688709742252720453195673704047916793432232890041049436571653118328169627767937236122051786
private theorem rep41_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 160 = rep41_cover := by decide +kernel
def rep42_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4347617220286294576583985618758166279165302004848611019108763100700002914327067292797244655943144363318857985623190410308555002310091016042144816697809030433834297743190182174119282357176490345080837005875794713404137116093004598831342602435462596088704154243367977139203946701268263460110693573722492426948510222919196977922217107988724880163428268861093402929474905966578100592776070200027946774622259233758100309170925536439971431648938845192570015130969973900660883048937453237175646847424826349838108698400889611906
private theorem rep42_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 164 = rep42_cover := by decide +kernel
def rep43_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2464289434391232782808831581070144245478791838971040415492581757969495561132435092800921320244556652061267755080420222634139903000440358756498312730797326942687390659059330451578388606324607642614665700511173096445422272683562250959088830087235714830249187576107482153368485992241159453478402046014572949142990842575587131527783348458680641524906254802897283549855970632708506055435664650090782116944754831213299305546503314746667614449726972408682739575974940656525392195697950177765750066074418387853570906910150394506
private theorem rep43_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 168 = rep43_cover := by decide +kernel
def rep44_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6723628627062494341750673585170854488328325597676518127937169453349170415002870427895566451112800111338556968985019255448996538976528984177023276881975770052468153043315733256109618981699239340951336181963994885642694397104705453790417868778386177676620967561754616807117139582343709979642998454790735370598730553368579329144385974822755091016344383255859706206637379425109402790835718254178793942755466740578673986032393026746649295944185871747423884920995075157751279736857095016514537651317893203442812984236691501323
private theorem rep44_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 172 = rep44_cover := by decide +kernel
def rep45_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8401153667664429752354625169565915708528292973555761949852838072531159018928754437625886364277389896277406657538660837778897009260981374755615333980585261146771753100377199106428293645384663874963883865130156582956036119648324008680982218214579690910268267000499726917304860905864152275097779230920860194156625945245304467357114791711666129342675409309105264006503374811205234650938092661148347949010965841110805163658778645042816242780951120596057115404935992767023267967437287419718820115729999597703610628451063629984
private theorem rep45_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 176 = rep45_cover := by decide +kernel
def rep46_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 813616654725365984422113779457056755529167953502874144091605380002378533218738978634031073580323465329256484738152107012568425015083780518234632737626305159237616678750602208954163871967787236876285219508570505198216962409298904819741767394831028093209317614133494123807739689904428839939245114080580499746257933314507833309503162710931460575644654214659976212922314557400351403698067555413258653675679358845169673916824395031933447318670908032305873214903744685362227802468401638769705350475150204474395112505466521236
private theorem rep46_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 180 = rep46_cover := by decide +kernel
def rep47_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4057757366772095494332646946695288396041347355400637646131554702143677649859631111289575763730306728512182545373272376349478559317907877301567681002373146099452020514099867363549448015504931282156427013429286181413495784852283507928232515272521902624156665948994382811190274175792370757895150298086815627746384760906155081742852038811920186227753786390749395409928840678080445536299271880344599953357818078671999638786378922444280308584001389025492028628125892092332813111130574817734849926691601462397273848407650801938
private theorem rep47_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 184 = rep47_cover := by decide +kernel
def rep48_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 6187125140674352681618975234975019986141133114006970955060587230216899261714108026664296073931833830469501152143069558530072287778781211117300775086741675279866924972929076656888692577542282859226532874048854868106914485152646050476498314256846921547643256692089806491588351858745514743158287867355356624956070246894720718156258424088129389182410490317254440787279563773906783635491397783533239045972753612910717580924328423221350928728165578415492502432211202488712431111399143972695023903246540438790257276574230393356
private theorem rep48_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 188 = rep48_cover := by decide +kernel
def rep49_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 5982236992178217309736370701620533340257923346333738895634904129424762928864811331426900307343478920866888895214657790813080473124136565751790320083130560897836549481408286869666290672475684296722719076305473751333424237479532462453072270733507947753833152506059869784455105557093836380063371436306387623448908209617103629635181912633182765787833556925297596715344332601613499798045411640613330278830016987795167979235057834584982329345604680828654633874548819860307975069757827028854397640220666468413283630190487159588
private theorem rep49_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 192 = rep49_cover := by decide +kernel
def rep50_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4056941928808092038530449543338326409430582650636774364435685875534707122438188423333239965711596126530266466194323348127303280152727390280216989327813201351942337736151981517497385190848265488859257772431903108513212408091493350560858122825936787951485561640355007873628316257550148886369962778880765609815530264423404283476149228122762006092427098632413621788200691106868432759146402752731345299571684924298256818764283356956770210959531692990115163715360383574617766812470925178590276635664343587768338309298621876484
private theorem rep50_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 196 = rep50_cover := by decide +kernel
def rep51_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 7810088986627551964855934519467009287322564723319742208647337940528217606759898991488834027316071416762962021508991893313150029410397225404860936070075910533466262026656720305199077836699055113908992280488898899623951892759979135234636248661723473953081402328021563551287081065294848733106581108172923376914221618597099948048306906077484609801108348007699672059059842595588738319694479313622506089426605973458182901071020528311654932269504494418263770749434843439543164804467624304756553996088353046653051589081353467538
private theorem rep51_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 200 = rep51_cover := by decide +kernel
def rep52_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 3821369704996241357234344140177771227667025392305438384051556509860623699196807018316544040442857229587002360526165653262686956842785005231030901627276552363665690383447770552069069159155162492849240805639506471789134085064041075663648805793360533088666666791587859365475739012274236126610248198819805791294346332212450417289724536334036067591401682338816750901185238545676579852661798341781272402419533593782717639922881545450620393669806352059978984862844013764592385801184154970020980016206295583063972108368616129569
private theorem rep52_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 204 = rep52_cover := by decide +kernel
def rep53_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 130742934567487343794080615650565628318424035981528970586521342594437284602991030770506225985950097825857585809368454360147278649911177436481182383236974898556742901182662345323767161281566695971201454093097762864132498749902249671059332747016208889439453246890893877916418620243877492677731227153687026140435593630711302483140951800575676033587989953783597620504678556135438918181060826017278857966662272916648465720942855469146318475910004244900092565826778456188637811136666394180915579534192673182396006736694747236
private theorem rep53_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 208 = rep53_cover := by decide +kernel
def rep54_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8404854921602891726384081452500452725906156658728886611020938591551336995635629031129512539659347071280812298466458541916374201954323765608728219365328049027371653474053370925907713567427330587894137417720338117986168233016878537808382790261540544468895073532110794070489509266951228492481074647654307182772008139867023127183827061397791273362603540363729520468767264172629846541993428690944088957707034694143400788439282702190610451048587442701472065112031137873597145899907222430819892722612710735544226642381112385800
private theorem rep54_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 212 = rep54_cover := by decide +kernel
def rep55_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 783621098330221131964904093131652665848527770551088518951171133931056666412593195533421638046349526686267552568751351326581185210050225993728184103516942482344030664660324190648412323627948197578576844064775441435213809560995134950933905177104995980285589452892677919497339536431271246511756146716968821758376460533231696773630516435990868910481161656435521398157674785526426728614368466424949253742781576054394913373301213475923092265329253072160035528738407591264252289130593537086363119788211864659122190321679701516
private theorem rep55_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 216 = rep55_cover := by decide +kernel
def rep56_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 363861421129160988583542451753101000821185419199848671507453471265432960339942327794795751251303790161600950388897185863053754610098968674345582765058328411886429518004551406287929537633808309576797203649691278236860647752813839716979387928586241364509274863090298618331880669847676282233266759826299187939946290055262798319642746127996554526869768435120987134011751796232972496582007984144208007548314931497000052039322632988509727965236074874012635598478065894607150710011003756231044913190961598590090046835851309656
private theorem rep56_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 220 = rep56_cover := by decide +kernel
def rep57_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 4034549449602173980265151895660631271810440308248065662034351550570138781125786286911341111936761658877415704832954427233116379685656523118605867337909051438217583189819959785430597025429658289244816726065807719381696059565561232521950652069415929618800121046375788995295268599191171411451786087045898266097643140018419775982609034473609170726629946933441922631904296958109638573854707266726438364256072482875233263292776458659911373933915135746302395412210065083915114809609327477276423168176617197974459209520728113408
private theorem rep57_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 224 = rep57_cover := by decide +kernel
def rep58_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 595245488744571727891645052323241380113138136931716666640359878173712097327407497233189932109374237824032416534196583531241118101503079311083932514941848284941260390411370494746826928521964229369202749821692138546807239741873671422725977400886805806284640356787085344001345934102906883136768997981595438855154786003615274459150253051565486143807311756913900282005461292437532482108101429157628176834057196440585442749506502218095459078826056470721828352167571347885863981116703847786761278040961674224689689388942762764
private theorem rep58_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 228 = rep58_cover := by decide +kernel
def rep59_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 769373443014466372532692667279704570614807237672641509364226235987624754058162054150330616302597112016356607521357300458317292013191885729781418149782794130573699285395789830642726956113690272633747451629283616825423700402151711293965759317183784855607503685069807165199664695722548713869767155917174667016342732324745777023413124625708699966920467596887251063819833844499761345308221002699123560382983596726666475247171256738739444771247934455486728192114176659445559211331838181806627976422150147012743244730231271706
private theorem rep59_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 232 = rep59_cover := by decide +kernel
def rep60_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 3826885043688314361484945233483363853015377122829513576021182000791995440263187959868019584146950040523020438175953677529136834892803342352479959590736070390667056868039619603143750072964743483926763603924874783749180335794595350868931034680137165552558265191465818605977617115074887339551092180618075214388100803634781573908058977996545253622074331989622492823707089401126164211687915921773438712741329296703322707276132338520975263201901256194535010411723424974912844230897090646233297537790856421721230063612507788368
private theorem rep60_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 236 = rep60_cover := by decide +kernel
def rep61_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 561574285861343933942987665677493516674992991398794291137222327256433239537498425485897557916951674857007041506760054048987561566811857592277445487844610699751301367220050630519704907944115113744386555040839535686717473292629832488746800766213175095894741022607003905667381832953509901746691332523475949852584537286468916951181200097174544204921781847396678397383588811401019839607513029623576510970081947239983156512498207283067310685697486062544381430267435439948099191242161773840880872534930385749652485672743863458
private theorem rep61_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 240 = rep61_cover := by decide +kernel
def rep62_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 2162443530308022895582772784027090051657291209516467398567438521560847187379556955067054993550550900221780806232013973232619112626199979942609768642169991637664168272422476636117769318189058252071938311021822242022533257820824896839479261287995700768199844263448983437145942625349739049140773554197340127275856531879282579722416855772958901286483658552580745680026819897220094280047095448959871902262653575251273539122670311103573371050629372134615414168847491067156169632676785561461319177048570619905219957533145146385
private theorem rep62_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 244 = rep62_cover := by decide +kernel
def rep63_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 8525810192326196183830830097695709819273056515741497699451979367753662107991902623719601078291198441689616469906444296479808190439537613509838335848378452290186670450464707655851778537250689492817720814679053264494528438281310342353410951694880042960674419194278207344625933218071893281371872582611247665111840621013201288937327179911117499533560219552568613498486041028554439394071297645080018413055783352433977362114352818298815641404245824826838549146386959955121726337931938272558810229872953681622386328873482617859
private theorem rep63_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 248 = rep63_cover := by decide +kernel
def rep64_cover : SuzukiEightCoverMatrices.M := SuzukiEightCoverMatrices.unpackMatrix 1892174367418281908719091096106357742480108208422040367745778224626174442156879748992122443353951819565331785284589209435359302436215782350193184568186102891421399954996907933669561637808585654741189472587596245081823055604468440477776570557484517577103275258011159390774489489001036716360680392940582055049823533137323553972981640968885482509785656420261075615073187819277825821255071464732504659248340130706635889439772065909797173594903813939775826003593946157794650787425682844391485838000902796571416037361856816420
private theorem rep64_cover_step : SuzukiEightCoverMatrices.cMatrix * SuzukiEightCoverPcForms.raw 252 = rep64_cover := by decide +kernel

def repRaw_cover : Fin 65 → SuzukiEightCoverMatrices.M := ![rep0_cover, rep1_cover, rep2_cover, rep3_cover, rep4_cover, rep5_cover, rep6_cover, rep7_cover, rep8_cover, rep9_cover, rep10_cover, rep11_cover, rep12_cover, rep13_cover, rep14_cover, rep15_cover, rep16_cover, rep17_cover, rep18_cover, rep19_cover, rep20_cover, rep21_cover, rep22_cover, rep23_cover, rep24_cover, rep25_cover, rep26_cover, rep27_cover, rep28_cover, rep29_cover, rep30_cover, rep31_cover, rep32_cover, rep33_cover, rep34_cover, rep35_cover, rep36_cover, rep37_cover, rep38_cover, rep39_cover, rep40_cover, rep41_cover, rep42_cover, rep43_cover, rep44_cover, rep45_cover, rep46_cover, rep47_cover, rep48_cover, rep49_cover, rep50_cover, rep51_cover, rep52_cover, rep53_cover, rep54_cover, rep55_cover, rep56_cover, rep57_cover, rep58_cover, rep59_cover, rep60_cover, rep61_cover, rep62_cover, rep63_cover, rep64_cover]

theorem rep_cover_val (i : Fin 65) : ((rep i).val.2 : SuzukiEightCoverMatrices.M) = repRaw_cover i := by
  fin_cases i
  · rfl
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 0).val = rep1_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep1_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 4).val = rep2_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep2_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 8).val = rep3_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep3_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 12).val = rep4_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep4_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 16).val = rep5_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep5_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 20).val = rep6_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep6_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 24).val = rep7_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep7_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 28).val = rep8_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep8_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 32).val = rep9_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep9_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 36).val = rep10_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep10_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 40).val = rep11_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep11_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 44).val = rep12_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep12_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 48).val = rep13_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep13_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 52).val = rep14_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep14_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 56).val = rep15_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep15_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 60).val = rep16_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep16_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 64).val = rep17_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep17_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 68).val = rep18_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep18_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 72).val = rep19_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep19_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 76).val = rep20_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep20_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 80).val = rep21_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep21_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 84).val = rep22_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep22_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 88).val = rep23_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep23_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 92).val = rep24_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep24_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 96).val = rep25_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep25_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 100).val = rep26_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep26_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 104).val = rep27_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep27_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 108).val = rep28_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep28_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 112).val = rep29_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep29_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 116).val = rep30_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep30_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 120).val = rep31_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep31_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 124).val = rep32_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep32_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 128).val = rep33_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep33_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 132).val = rep34_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep34_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 136).val = rep35_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep35_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 140).val = rep36_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep36_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 144).val = rep37_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep37_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 148).val = rep38_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep38_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 152).val = rep39_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep39_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 156).val = rep40_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep40_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 160).val = rep41_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep41_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 164).val = rep42_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep42_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 168).val = rep43_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep43_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 172).val = rep44_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep44_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 176).val = rep45_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep45_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 180).val = rep46_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep46_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 184).val = rep47_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep47_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 188).val = rep48_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep48_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 192).val = rep49_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep49_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 196).val = rep50_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep50_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 200).val = rep51_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep51_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 204).val = rep52_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep52_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 208).val = rep53_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep53_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 212).val = rep54_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep54_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 216).val = rep55_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep55_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 220).val = rep56_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep56_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 224).val = rep57_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep57_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 228).val = rep58_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep58_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 232).val = rep59_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep59_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 236).val = rep60_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep60_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 240).val = rep61_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep61_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 244).val = rep62_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep62_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 248).val = rep63_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep63_cover_step
  · change SuzukiEightCoverMatrices.cMatrix * (SuzukiEightCoverPcForms.form 252).val = rep64_cover
    rw [SuzukiEightCoverPcForms.form_val]
    exact rep64_cover_step


end Kourovka2135.SuzukiEightPairedCosetData
