import Kourovka2135.SylowSupplement

/-!
# Sylow generation by a specified set of values

The generating elements remain members of the specified set. Generation passes
through surjective homomorphisms and through a normal prime-power subgroup with
a supplement. No closure of the value set under multiplication is assumed.
-/

set_option autoImplicit false
universe u v

namespace Kourovka2135

variable {G : Type u} {H : Type v} [Group G] [Group H]

/-- Every Sylow subgroup is generated by a subset of the specified value set. -/
def ValueGeneratedSylows (V : Set G) : Prop :=
  ∀ q : ℕ, q.Prime → ∀ P : Sylow q G,
    ∃ X : Set G, X ⊆ V ∧ Subgroup.closure X = (P : Subgroup G)

theorem ValueGeneratedSylows.mono {V W : Set G}
    (hV : ValueGeneratedSylows V) (hVW : V ⊆ W) : ValueGeneratedSylows W := by
  intro q hq P
  obtain ⟨X, hX, hgen⟩ := hV q hq P
  exact ⟨X, hX.trans hVW, hgen⟩

/-- Surjective images preserve generation of Sylow subgroups by the specified values. -/
theorem ValueGeneratedSylows.map_surjective [Finite G] {V : Set G}
    (hV : ValueGeneratedSylows V) (f : G →* H) (hf : Function.Surjective f) :
    ValueGeneratedSylows (f '' V) := by
  intro q hq P
  let : Fact q.Prime := ⟨hq⟩
  obtain ⟨Q, hQ⟩ := Sylow.mapSurjective_surjective hf q P
  obtain ⟨X, hX, hgen⟩ := hV q hq Q
  refine ⟨f '' X, Set.image_mono hX, ?_⟩
  rw [← MonoidHom.map_closure, hgen]
  exact congrArg Sylow.toSubgroup hQ

/-- Sylow generation passes from a normal prime-power subgroup and its supplement.
The supplement need not be normal or disjoint from the normal subgroup. -/
theorem valueGeneratedSylows_of_normal_prime_supplement [Finite G] {V : Set G}
    (r : ℕ) (hr : r.Prime) (A B : Subgroup G) [A.Normal]
    (hA : IsPGroup r A) (hsup : A ⊔ B = ⊤)
    (hconj : ∀ x ∈ V, ∀ g : G, g * x * g⁻¹ ∈ V)
    (hAgen : ∃ U : Set G, U ⊆ V ∧ Subgroup.closure U = A)
    (hB : ValueGeneratedSylows (B.subtype ⁻¹' V)) : ValueGeneratedSylows V := by
  classical
  let : Fact r.Prime := ⟨hr⟩
  intro q hq P
  let : Fact q.Prime := ⟨hq⟩
  let Q : Sylow q B := Sylow.nonempty.some
  obtain ⟨X, hX, hXgen⟩ := hB q hq Q
  obtain ⟨g, hP⟩ := exists_sylow_conjugate_decomposition A B hA hsup Q P
  let f : B →* G := (MulAut.conj g).toMonoidHom.comp B.subtype
  let Y : Set G := f '' X
  have hY : Y ⊆ V := by
    rintro _ ⟨x, hx, rfl⟩
    change g * (x : G) * g⁻¹ ∈ V
    exact hconj x (hX hx) g
  have hYgen : Subgroup.closure Y =
      ((Q : Subgroup B).map B.subtype).map (MulAut.conj g).toMonoidHom := by
    change Subgroup.closure (f '' X) = _
    rw [← MonoidHom.map_closure, hXgen, Subgroup.map_map]
  by_cases hqr : q = r
  · obtain ⟨U, hU, hUgen⟩ := hAgen
    refine ⟨U ∪ Y, Set.union_subset hU hY, ?_⟩
    rw [Subgroup.closure_union, hUgen, hYgen]
    simpa only [ite_eq_left hqr] using hP.symm
  · refine ⟨Y, hY, ?_⟩
    rw [ite_eq_right hqr, bot_sup_eq] at hP
    exact hYgen.trans hP.symm

end Kourovka2135
