import Kourovka2135.RelativeCongruence

/-!
# Verbal subgroups over a normal subgroup and a supplement

If G=P*M with P normal, then w(G) is generated by the mixed w-values involving
P together with the image of w(M). The supplement need not be normal or disjoint
from P. This identity is valid for every outer commutator word.
-/

set_option autoImplicit false
universe u v z
namespace Kourovka2135

variable {G : Type u} [Group G]

theorem quotient_restrict_surjective_of_sup_eq_top
    (P M : Subgroup G) [P.Normal] (hsup : P ⊔ M = ⊤) :
    Function.Surjective ((QuotientGroup.mk' P).comp M.subtype) := by
  intro y
  obtain ⟨x, rfl⟩ := QuotientGroup.mk'_surjective P y
  have hx : x ∈ P ⊔ M := by rw [hsup]; trivial
  obtain ⟨p, hp, m, hm, heq⟩ := Subgroup.mem_sup_of_normal_left.mp hx
  refine ⟨⟨m, hm⟩, ?_⟩
  change (QuotientGroup.mk' P) m = (QuotientGroup.mk' P) x
  have hqp : (QuotientGroup.mk' P) p = 1 := (QuotientGroup.eq_one_iff p).mpr hp
  rw [← heq, map_mul, hqp, one_mul]

namespace OuterWord

theorem mapInput_comp (w : OuterWord) {A : Type u} {B : Type v} {C : Type z}
    (f : A → B) (g : B → C) (x : w.Input A) :
    w.mapInput g (w.mapInput f x) = w.mapInput (g ∘ f) x := by
  induction w with
  | leaf => rfl
  | bracket l r ihl ihr =>
      rcases x with ⟨xl, xr⟩
      exact Prod.ext (ihl xl) (ihr xr)

/-- The exact mixed-value/supplement decomposition for an arbitrary outer word. -/
theorem verbalSubgroup_eq_mixed_sup (w : OuterWord)
    (P M : Subgroup G) [P.Normal] (hsup : P ⊔ M = ⊤) :
    w.verbalSubgroup G = w.mixedSubgroup P ⊔ (w.verbalSubgroup M).map M.subtype := by
  apply le_antisymm
  · apply (Subgroup.closure_le _).mpr
    rintro _ ⟨x, rfl⟩
    let q : G →* G ⧸ P := QuotientGroup.mk' P
    let f : M →* G ⧸ P := q.comp M.subtype
    have hf : Function.Surjective f := quotient_restrict_surjective_of_sup_eq_top P M hsup
    obtain ⟨y, hy⟩ := w.mapInput_surjective f hf (w.mapInput q x)
    have hinputs : w.mapInput q x = w.mapInput q (w.mapInput M.subtype y) := by
      rw [mapInput_comp]
      exact hy.symm
    have hdiff := w.eval_mul_inv_mem_mixedSubgroup P x (w.mapInput M.subtype y) hinputs
    rw [w.eval_mapInput M.subtype] at hdiff
    have hyB : M.subtype (w.eval y) ∈ (w.verbalSubgroup M).map M.subtype :=
      ⟨w.eval y, w.eval_mem_verbalSubgroup y, rfl⟩
    change w.eval x ∈ (w.mixedSubgroup P ⊔ (w.verbalSubgroup M).map M.subtype : Subgroup G)
    have ha : w.eval x * (M.subtype (w.eval y))⁻¹ ∈
        w.mixedSubgroup P ⊔ (w.verbalSubgroup M).map M.subtype :=
      (show w.mixedSubgroup P ≤ _ from le_sup_left) hdiff
    have hb : M.subtype (w.eval y) ∈
        w.mixedSubgroup P ⊔ (w.verbalSubgroup M).map M.subtype :=
      (show (w.verbalSubgroup M).map M.subtype ≤ _ from le_sup_right) hyB
    simpa only [mul_assoc, inv_mul_cancel, mul_one] using
      (w.mixedSubgroup P ⊔ (w.verbalSubgroup M).map M.subtype).mul_mem ha hb
  · exact sup_le (w.mixedSubgroup_le_verbal P) (w.map_verbalSubgroup_le M.subtype)

end OuterWord
end Kourovka2135
