import Kourovka.Problems.P21_40.Proof.DeepRoots
import Kourovka.Problems.P21_40.Proof.Orbits
import Mathlib.RingTheory.Adjoin.Polynomial.Basic
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.FieldTheory.IsAlgClosed.Spectrum
import Mathlib.LinearAlgebra.Matrix.Charpoly.Eigs
import Mathlib.LinearAlgebra.Matrix.Charpoly.Minpoly
import Mathlib.Analysis.Normed.Ring.Finite
import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed

namespace Kourovka.P21_40

open Polynomial

/-- A coherent chain of roots in a finite-dimensional algebra lies in a single
singly generated subalgebra. -/
theorem exists_stable_adjoin_of_root_chain {A : Type*} [Ring A] [Algebra ℚ A]
    [FiniteDimensional ℚ A] (p : ℕ) (b : ℕ → A)
    (hb : ∀ k : ℕ, b (k + 1) ^ p = b k) :
    ∃ N : ℕ, ∀ k : ℕ, b k ∈ Algebra.adjoin ℚ {b N} := by
  let S (k : ℕ) : Subalgebra ℚ A := Algebra.adjoin ℚ {b k}
  have hS : Monotone S := by
    apply monotone_nat_of_le_succ
    intro k
    apply Algebra.adjoin_le
    intro x hx
    obtain rfl := Set.mem_singleton_iff.mp hx
    rw [← hb k]
    exact (S (k + 1)).pow_mem (Algebra.self_mem_adjoin_singleton ℚ (b (k + 1))) p
  let f : ℕ →o Submodule ℚ A :=
    ⟨fun k => (S k).toSubmodule, fun i j hij => hS hij⟩
  obtain ⟨N, hN⟩ := monotone_stabilizes_iff_noetherian.mpr
    (inferInstance : IsNoetherian ℚ A) f
  refine ⟨N, fun k => ?_⟩
  have hk : b k ∈ S k := Algebra.self_mem_adjoin_singleton ℚ (b k)
  rcases le_total k N with h | h
  · exact hS h hk
  · have he : (S N).toSubmodule = (S k).toSubmodule := hN k h
    change b k ∈ (S N).toSubmodule
    rw [he]
    exact hk

/-- Polynomial relations transfer deep roots in a singly generated algebra to
roots in the number field generated by a scalar. -/
theorem exists_pow_eq_one_of_deep_roots_in_adjoin {A : Type*} [Ring A] [Algebra ℚ A]
    {a : A} {z : ℂ} (hz : z ≠ 0) (hzi : IsIntegral ℚ z)
    (hrel : ∀ f : ℚ[X], aeval a f = 0 → aeval z f = 0)
    {p : ℕ} (hp : 2 ≤ p)
    (hr : ∀ k : ℕ, ∃ b : A, b ∈ Algebra.adjoin ℚ {a} ∧ b ^ (p ^ k) = a) :
    ∃ m : ℕ, 0 < m ∧ z ^ m = 1 := by
  let K := IntermediateField.adjoin ℚ ({z} : Set ℂ)
  let : NumberField K :=
    { to_charZero := K.charZero
      to_finiteDimensional := IntermediateField.adjoin.finiteDimensional hzi }
  let y : K := ⟨z, IntermediateField.mem_adjoin_simple_self ℚ z⟩
  have hy : y ≠ 0 := by
    intro h
    exact hz (congrArg (fun t : K => (t : ℂ)) h)
  have hroots : ∀ k : ℕ, ∃ w : K, w ^ (p ^ k) = y := by
    intro k
    obtain ⟨b, hb, hbp⟩ := hr k
    obtain ⟨q, hq⟩ := Algebra.adjoin_mem_exists_aeval ℚ a hb
    refine ⟨aeval y q, ?_⟩
    apply Subtype.ext
    have hqa : aeval a (q ^ (p ^ k) - X) = 0 := by
      simp only [map_sub, map_pow, aeval_X, hq, hbp, sub_self]
    have hqz := hrel (q ^ (p ^ k) - X) hqa
    change (K.val (aeval y q)) ^ (p ^ k) = z
    have hcoe : K.val (aeval y q) = aeval z q :=
      (aeval_algHom_apply K.val y q).symm
    rw [hcoe]
    simpa only [map_sub, map_pow, aeval_X, sub_eq_zero] using hqz
  obtain ⟨m, hm, hpow⟩ := exists_pow_eq_one_of_deep_roots hp hy hroots
  exact ⟨m, hm, congrArg (fun t : K => (t : ℂ)) hpow⟩

/-- A scalar in the complex spectrum satisfies every rational polynomial relation
of the original matrix. -/
theorem aeval_eq_zero_of_mem_spectrum_map {ι : Type*} [Fintype ι] [DecidableEq ι]
    [Nonempty ι] {a : Matrix ι ι ℚ} {z : ℂ}
    (hz : z ∈ spectrum ℂ (a.map (algebraMap ℚ ℂ))) (q : ℚ[X])
    (hq : aeval a q = 0) : aeval z q = 0 := by
  let φ : Matrix ι ι ℚ →ₐ[ℚ] Matrix ι ι ℂ := (Algebra.ofId ℚ ℂ).mapMatrix
  have hqC : aeval (φ a) (q.map (algebraMap ℚ ℂ)) = 0 := by
    rw [← aeval_eq_aeval_map (IsScalarTower.algebraMap_eq ℚ ℂ (Matrix ι ι ℂ)).symm]
    rw [aeval_algHom_apply, hq, map_zero]
  have hm := spectrum.subset_polynomial_aeval (φ a) (q.map (algebraMap ℚ ℂ))
    ⟨z, hz, rfl⟩
  rw [hqC, spectrum.zero_eq] at hm
  simpa only [Set.mem_singleton_iff, eval_map_algebraMap] using hm

/-- Every complex spectral value of a rational matrix is algebraic over the rationals. -/
theorem isIntegral_of_mem_spectrum_map {ι : Type*} [Fintype ι] [DecidableEq ι]
    [Nonempty ι] {a : Matrix ι ι ℚ} {z : ℂ}
    (hz : z ∈ spectrum ℂ (a.map (algebraMap ℚ ℂ))) : IsIntegral ℚ z := by
  exact ⟨minpoly ℚ a, minpoly.monic (Matrix.isIntegral a),
    aeval_eq_zero_of_mem_spectrum_map hz _ (minpoly.aeval ℚ a)⟩

/-- A coherent chain of invertible rational matrix roots forces every complex
spectral value of its first term to have finite multiplicative order. -/
theorem isOfFinOrder_spectrum_of_root_chain {ι : Type*} [Fintype ι] [DecidableEq ι]
    [Nonempty ι] {p : ℕ} (hp : 2 ≤ p) (b : ℕ → Matrix ι ι ℚ)
    (hb : ∀ k : ℕ, b (k + 1) ^ p = b k) (hunit : ∀ k : ℕ, IsUnit (b k))
    {z : ℂ} (hz : z ∈ spectrum ℂ ((b 0).map (algebraMap ℚ ℂ))) : IsOfFinOrder z := by
  let φ : Matrix ι ι ℚ →ₐ[ℚ] Matrix ι ι ℂ := (Algebra.ofId ℚ ℂ).mapMatrix
  obtain ⟨N, hN⟩ := exists_stable_adjoin_of_root_chain p b hb
  have hpow : (φ (b N)) ^ (p ^ N) = φ (b 0) := by
    rw [← map_pow]
    simpa only [Nat.zero_add] using congrArg φ (root_chain_pow hb 0 N)
  have hzpow : z ∈ spectrum ℂ ((φ (b N)) ^ (p ^ N)) := by
    rw [hpow]
    exact hz
  rw [spectrum.map_pow_of_pos _ (pow_pos (by omega : 0 < p) N)] at hzpow
  obtain ⟨w, hw, rfl⟩ := hzpow
  have hw0 : w ≠ 0 := by
    intro h
    exact spectrum.zero_notMem ℂ ((hunit N).map φ) (h ▸ hw)
  have hwi : IsIntegral ℚ w := isIntegral_of_mem_spectrum_map hw
  have hrel : ∀ q : ℚ[X], aeval (b N) q = 0 → aeval w q = 0 :=
    fun q hq => aeval_eq_zero_of_mem_spectrum_map hw q hq
  have hr : ∀ k : ℕ, ∃ c : Matrix ι ι ℚ,
      c ∈ Algebra.adjoin ℚ {b N} ∧ c ^ (p ^ k) = b N := by
    intro k
    exact ⟨b (N + k), hN _, root_chain_pow hb N k⟩
  exact (isOfFinOrder_iff_pow_eq_one.mpr
    (exists_pow_eq_one_of_deep_roots_in_adjoin hw0 hwi hrel hp hr)).pow

/-- A rational matrix whose complex spectral values have finite order has an
integer trace bounded by its dimension. -/
theorem trace_int_bound_of_spectrum_finite_order {ι : Type*} [Fintype ι] [DecidableEq ι]
    (a : Matrix ι ι ℚ)
    (h : ∀ z : ℂ, z ∈ spectrum ℂ (a.map (algebraMap ℚ ℂ)) → IsOfFinOrder z) :
    ∃ t : ℤ, (t : ℚ) = a.trace ∧ |t| ≤ Fintype.card ι := by
  let c := a.map (algebraMap ℚ ℂ)
  have hr (z : ℂ) (hz : z ∈ c.charpoly.roots) : IsOfFinOrder z :=
    h z (Matrix.mem_spectrum_of_isRoot_charpoly (Polynomial.isRoot_of_mem_roots hz))
  have htrace : (algebraMap ℚ ℂ) a.trace = c.trace := by
    simp [c, Matrix.trace, map_sum]
  have hiC : IsIntegral ℤ c.trace := by
    rw [Matrix.trace_eq_sum_roots_charpoly]
    apply IsIntegral.multiset_sum
    intro z hz
    obtain ⟨m, hm, hzm⟩ := (hr z hz).exists_pow_eq_one
    exact IsIntegral.of_pow hm (hzm ▸ isIntegral_one)
  have hiQ : IsIntegral ℤ a.trace := by
    apply (isIntegral_algebraMap_iff (B := ℂ)).mp
    rwa [htrace]
  obtain ⟨t, ht⟩ := IsIntegrallyClosed.algebraMap_eq_of_integral hiQ
  refine ⟨t, ht, ?_⟩
  have hnorm : ‖c.trace‖ ≤ (Fintype.card ι : ℝ) := by
    rw [Matrix.trace_eq_sum_roots_charpoly]
    calc
      ‖c.charpoly.roots.sum‖ ≤ (c.charpoly.roots.map (fun z : ℂ => ‖z‖)).sum :=
        norm_multiset_sum_le _
      _ = (c.charpoly.roots.card : ℝ) := by
        have he : c.charpoly.roots.map (fun z : ℂ => ‖z‖) =
            c.charpoly.roots.map (fun _ : ℂ => (1 : ℝ)) :=
          Multiset.map_congr rfl (fun z hz => (hr z hz).norm_eq_one)
        rw [he]
        simp
      _ ≤ c.charpoly.natDegree := by exact_mod_cast c.charpoly.card_roots'
      _ = Fintype.card ι := by rw [Matrix.charpoly_natDegree_eq_dim]
  have htC : (t : ℂ) = c.trace := by
    rw [← htrace, ← ht]
    simp
  rw [← htC, Complex.norm_intCast] at hnorm
  exact_mod_cast hnorm

/-- Trace bounds in the signed form used by the finite-trace quotient argument.
This includes the empty matrix case. -/
theorem trace_bounds_of_root_chain {ι : Type*} [Fintype ι] [DecidableEq ι]
    {p : ℕ} (hp : 2 ≤ p) (b : ℕ → Matrix ι ι ℚ)
    (hb : ∀ k : ℕ, b (k + 1) ^ p = b k) (hunit : ∀ k : ℕ, IsUnit (b k)) :
    ∃ t : ℤ, (b 0).trace = (t : ℚ) ∧
      -(Fintype.card ι : ℤ) ≤ t ∧ t ≤ (Fintype.card ι : ℤ) := by
  cases isEmpty_or_nonempty ι with
  | inl hi =>
    let := hi
    exact ⟨0, by simp, by simp, by simp⟩
  | inr hi =>
    let := hi
    obtain ⟨t, ht, htbound⟩ := trace_int_bound_of_spectrum_finite_order (b 0)
      (fun z hz => isOfFinOrder_spectrum_of_root_chain hp b hb hunit hz)
    exact ⟨t, ht.symm, (abs_le.mp htbound).1, (abs_le.mp htbound).2⟩

end Kourovka.P21_40
