import Kourovka.Problems.P21_99.Proof.DataPredicates

/-! Generated by scripts/generate_21_99.py; checked by Lean's kernel. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kourovka.P21_99.Data

set_option maxRecDepth 100000
set_option maxHeartbeats 0

theorem identity_checked :
    (∀ i j : Fin 18, entry (matrixRows 0) i j = identityEntry i j) ∧
    (∀ i : Fin 6, blockMap 0 i = i) := by decide +kernel

theorem section_checked : ∀ b : Fin 6, ∀ i j : Fin 14,
    compEntry (projectionRows b) (sectionRows b) i j = identityEntry i j := by
  decide +kernel

theorem target_coverage_checked : ∀ q : Fin 384,
    blockMap q 0 = 2 → targetIndex (targetSlot q) = q := by decide +kernel

theorem representative_checked : ∀ b : Fin 6,
    wordIndex (representativeWord b) = representativeIndex b ∧
      blockMap (representativeIndex b) 0 = b := by decide +kernel


end Kourovka.P21_99.Data
