import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows000
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows001
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows002
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows003
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows004
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows005
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows006
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows007
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows008
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows009
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows010
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows011
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows012
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows013
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows014
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows015
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows016
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows017
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows018
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows019
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows020
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows021
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows022
import Kourovka.Problems.P21_99.Proof.Certificates.MatrixRows023

/-! Generated by scripts/generate_21_99.py; checked by Lean's kernel. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kourovka.P21_99.Data

def matrixRowsChunks : Fin 24 → Fin 16 → Rows 18 18 :=
  ![matrixRowsChunk000, matrixRowsChunk001, matrixRowsChunk002, matrixRowsChunk003, matrixRowsChunk004, matrixRowsChunk005, matrixRowsChunk006, matrixRowsChunk007, matrixRowsChunk008, matrixRowsChunk009, matrixRowsChunk010, matrixRowsChunk011, matrixRowsChunk012, matrixRowsChunk013, matrixRowsChunk014, matrixRowsChunk015, matrixRowsChunk016, matrixRowsChunk017, matrixRowsChunk018, matrixRowsChunk019, matrixRowsChunk020, matrixRowsChunk021, matrixRowsChunk022, matrixRowsChunk023]

def matrixRows (q : Fin 384) : Rows 18 18 :=
  matrixRowsChunks ⟨q.val / 16, by omega⟩ ⟨q.val % 16, by omega⟩

end Kourovka.P21_99.Data
