import Kourovka.Problems.P21_99.Proof.Certificates.FixedCheck000
import Kourovka.Problems.P21_99.Proof.Certificates.FixedCheck001
import Kourovka.Problems.P21_99.Proof.Certificates.FixedCheck002
import Kourovka.Problems.P21_99.Proof.Certificates.FixedCheck003
import Kourovka.Problems.P21_99.Proof.Certificates.FixedCheck004
import Kourovka.Problems.P21_99.Proof.Certificates.FixedCheck005
import Kourovka.Problems.P21_99.Proof.Certificates.FixedCheck006
import Kourovka.Problems.P21_99.Proof.Certificates.FixedCheck007

/-! Generated by scripts/generate_21_99.py; checked by Lean's kernel. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kourovka.P21_99.Data

theorem fixedChecks (q : Fin 64) : fixedCheck q := by
  by_cases h0 : q.val < 8
  · let k : Fin 8 := ⟨q.val - 0, by omega⟩
    have he : (⟨0 + k.val, by omega⟩ : Fin 64) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using fixedCheckChunk000 k
  by_cases h1 : q.val < 16
  · let k : Fin 8 := ⟨q.val - 8, by omega⟩
    have he : (⟨8 + k.val, by omega⟩ : Fin 64) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using fixedCheckChunk001 k
  by_cases h2 : q.val < 24
  · let k : Fin 8 := ⟨q.val - 16, by omega⟩
    have he : (⟨16 + k.val, by omega⟩ : Fin 64) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using fixedCheckChunk002 k
  by_cases h3 : q.val < 32
  · let k : Fin 8 := ⟨q.val - 24, by omega⟩
    have he : (⟨24 + k.val, by omega⟩ : Fin 64) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using fixedCheckChunk003 k
  by_cases h4 : q.val < 40
  · let k : Fin 8 := ⟨q.val - 32, by omega⟩
    have he : (⟨32 + k.val, by omega⟩ : Fin 64) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using fixedCheckChunk004 k
  by_cases h5 : q.val < 48
  · let k : Fin 8 := ⟨q.val - 40, by omega⟩
    have he : (⟨40 + k.val, by omega⟩ : Fin 64) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using fixedCheckChunk005 k
  by_cases h6 : q.val < 56
  · let k : Fin 8 := ⟨q.val - 48, by omega⟩
    have he : (⟨48 + k.val, by omega⟩ : Fin 64) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using fixedCheckChunk006 k
  by_cases h7 : q.val < 64
  · let k : Fin 8 := ⟨q.val - 56, by omega⟩
    have he : (⟨56 + k.val, by omega⟩ : Fin 64) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using fixedCheckChunk007 k
  omega


end Kourovka.P21_99.Data
