import Kourovka.Problems.P21_99.Proof.Certificates.RegularInverseRows000
import Kourovka.Problems.P21_99.Proof.Certificates.RegularInverseRows001
import Kourovka.Problems.P21_99.Proof.Certificates.RegularInverseRows002
import Kourovka.Problems.P21_99.Proof.Certificates.RegularInverseRows003

/-! Generated by scripts/generate_21_99.py; checked by Lean's kernel. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kourovka.P21_99.Data

def regularInverseRowsChunks : Fin 4 → Fin 16 → Rows 14 14 :=
  ![regularInverseRowsChunk000, regularInverseRowsChunk001, regularInverseRowsChunk002, regularInverseRowsChunk003]

def regularInverseRows (q : Fin 64) : Rows 14 14 :=
  regularInverseRowsChunks ⟨q.val / 16, by omega⟩ ⟨q.val % 16, by omega⟩

end Kourovka.P21_99.Data
