import Kourovka.Problems.P21_99.Proof.DataRaw

/-! Generated by scripts/generate_21_99.py; checked by Lean's kernel. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kourovka.P21_99.Data

abbrev inverseCheck (q : Fin 384) : Prop :=
  (∀ i j : Fin 18, compEntry (matrixRows q) (matrixRows (inverseIndex q)) i j = identityEntry i j) ∧
  (∀ i j : Fin 18, compEntry (matrixRows (inverseIndex q)) (matrixRows q) i j = identityEntry i j) ∧
  (∀ i : Fin 6, blockMap q (blockMap (inverseIndex q) i) = i) ∧
  (∀ i : Fin 6, blockMap (inverseIndex q) (blockMap q i) = i)

abbrev stepCheck (q : Fin 384) : Prop :=
  ∀ g : Fin 8,
    (∀ i j : Fin 18, compEntry (matrixRows q) (matrixRows (generatorIndex g)) i j = entry (matrixRows (step q g)) i j) ∧
    (∀ i : Fin 6, blockMap q (blockMap (generatorIndex g) i) = blockMap (step q g) i)

abbrev covarianceCheck (q : Fin 384) : Prop :=
  ∀ b : Fin 6, ∀ i : Fin 14, ∀ j : Fin 18,
    linear (projectionRows (blockMap q b)) (linear (matrixRows q) (basisVector j)) i =
      quotientLinear q b (linear (projectionRows b) (basisVector j)) i

abbrev fixedCheck (t : Fin 64) : Prop :=
  (blockMap (targetIndex t) 0 = 2) ∧
  (regularBlock t ≠ singularBlock t) ∧
  (∀ i : Fin 6, blockMap (targetIndex t) i = i ↔ i = regularBlock t ∨ i = singularBlock t) ∧
  (∀ i j : Fin 14,
    linear (regularInverseRows t) (basisVector j - quotientLinear (targetIndex t) (regularBlock t) (basisVector j)) i = identityEntry i j) ∧
  (∀ i j : Fin 14,
    (linear (regularInverseRows t) (basisVector j) - quotientLinear (targetIndex t) (regularBlock t) (linear (regularInverseRows t) (basisVector j))) i = identityEntry i j) ∧
  (∀ j : Fin 14, rowLinear (singularFunctional t) (quotientLinear (targetIndex t) (singularBlock t) (basisVector j)) = rowLinear (singularFunctional t) (basisVector j)) ∧
  (∀ j : Fin 18, rowLinear (singularFunctional t) (linear (projectionRows (singularBlock t)) (basisVector j)) = rowLinear (targetFunctional t) (linear (projectionRows 2) (basisVector j))) ∧
  (rowLinear (targetFunctional t) (linear (projectionRows 2) translation) ≠ 0)


end Kourovka.P21_99.Data
