import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck000
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck001
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck002
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck003
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck004
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck005
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck006
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck007
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck008
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck009
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck010
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck011
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck012
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck013
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck014
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck015
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck016
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck017
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck018
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck019
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck020
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck021
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck022
import Kourovka.Problems.P21_99.Proof.Certificates.CovarianceCheck023

/-! Generated by scripts/generate_21_99.py; checked by Lean's kernel. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kourovka.P21_99.Data

theorem covarianceChecks (q : Fin 384) : covarianceCheck q := by
  by_cases h0 : q.val < 16
  · let k : Fin 16 := ⟨q.val - 0, by omega⟩
    have he : (⟨0 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk000 k
  by_cases h1 : q.val < 32
  · let k : Fin 16 := ⟨q.val - 16, by omega⟩
    have he : (⟨16 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk001 k
  by_cases h2 : q.val < 48
  · let k : Fin 16 := ⟨q.val - 32, by omega⟩
    have he : (⟨32 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk002 k
  by_cases h3 : q.val < 64
  · let k : Fin 16 := ⟨q.val - 48, by omega⟩
    have he : (⟨48 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk003 k
  by_cases h4 : q.val < 80
  · let k : Fin 16 := ⟨q.val - 64, by omega⟩
    have he : (⟨64 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk004 k
  by_cases h5 : q.val < 96
  · let k : Fin 16 := ⟨q.val - 80, by omega⟩
    have he : (⟨80 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk005 k
  by_cases h6 : q.val < 112
  · let k : Fin 16 := ⟨q.val - 96, by omega⟩
    have he : (⟨96 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk006 k
  by_cases h7 : q.val < 128
  · let k : Fin 16 := ⟨q.val - 112, by omega⟩
    have he : (⟨112 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk007 k
  by_cases h8 : q.val < 144
  · let k : Fin 16 := ⟨q.val - 128, by omega⟩
    have he : (⟨128 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk008 k
  by_cases h9 : q.val < 160
  · let k : Fin 16 := ⟨q.val - 144, by omega⟩
    have he : (⟨144 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk009 k
  by_cases h10 : q.val < 176
  · let k : Fin 16 := ⟨q.val - 160, by omega⟩
    have he : (⟨160 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk010 k
  by_cases h11 : q.val < 192
  · let k : Fin 16 := ⟨q.val - 176, by omega⟩
    have he : (⟨176 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk011 k
  by_cases h12 : q.val < 208
  · let k : Fin 16 := ⟨q.val - 192, by omega⟩
    have he : (⟨192 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk012 k
  by_cases h13 : q.val < 224
  · let k : Fin 16 := ⟨q.val - 208, by omega⟩
    have he : (⟨208 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk013 k
  by_cases h14 : q.val < 240
  · let k : Fin 16 := ⟨q.val - 224, by omega⟩
    have he : (⟨224 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk014 k
  by_cases h15 : q.val < 256
  · let k : Fin 16 := ⟨q.val - 240, by omega⟩
    have he : (⟨240 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk015 k
  by_cases h16 : q.val < 272
  · let k : Fin 16 := ⟨q.val - 256, by omega⟩
    have he : (⟨256 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk016 k
  by_cases h17 : q.val < 288
  · let k : Fin 16 := ⟨q.val - 272, by omega⟩
    have he : (⟨272 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk017 k
  by_cases h18 : q.val < 304
  · let k : Fin 16 := ⟨q.val - 288, by omega⟩
    have he : (⟨288 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk018 k
  by_cases h19 : q.val < 320
  · let k : Fin 16 := ⟨q.val - 304, by omega⟩
    have he : (⟨304 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk019 k
  by_cases h20 : q.val < 336
  · let k : Fin 16 := ⟨q.val - 320, by omega⟩
    have he : (⟨320 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk020 k
  by_cases h21 : q.val < 352
  · let k : Fin 16 := ⟨q.val - 336, by omega⟩
    have he : (⟨336 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk021 k
  by_cases h22 : q.val < 368
  · let k : Fin 16 := ⟨q.val - 352, by omega⟩
    have he : (⟨352 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk022 k
  by_cases h23 : q.val < 384
  · let k : Fin 16 := ⟨q.val - 368, by omega⟩
    have he : (⟨368 + k.val, by omega⟩ : Fin 384) = q := by
      apply Fin.ext
      dsimp [k]
      omega
    simpa only [he] using covarianceCheckChunk023 k
  omega


end Kourovka.P21_99.Data
