import Kourovka.Problems.P21_44.Proof.WreathGeneration
import Kourovka.Problems.P21_44.Proof.InverseLimit

/-!
# A fixed pair is dense in the full alternating inverse limit

The generators here are the single compatible automorphisms `a` and `b` from
`InverseLimit`. Their images generate every finite-level wreath quotient.
-/

namespace Kourovka.P21_44

/-- Every finite wreath quotient is perfect. -/
instance level_isPerfect : (n : ℕ) → Group.IsPerfect (Level n)
  | 0 => inferInstanceAs (Group.IsPerfect PUnit)
  | n + 1 =>
      let := level_isPerfect n
      inferInstanceAs (Group.IsPerfect (Wreath (Level n)))

/-- Restrictions of the fixed pair generate the entire finite wreath group. -/
theorem levels_generate (n : ℕ) :
    Subgroup.closure ({levelA n, levelB n} : Set (Level n)) = ⊤ := by
  induction n with
  | zero => exact Subsingleton.elim _ _
  | succ n ih =>
      exact Wreath.generates (levelA n) (levelB n) ih (levelA_cube n) (levelB_cube n)

/-- The same two infinite automorphisms surject onto every finite level. -/
theorem generated_pair_surjective (n : ℕ) :
    Function.Surjective ((levelEval n).comp
      (Subgroup.closure ({a, b} : Set AutTree)).subtype) := by
  have hmap : (Subgroup.closure ({a, b} : Set AutTree)).map (levelEval n) = ⊤ := by
    rw [MonoidHom.map_closure, Set.image_pair, eval_a, eval_b]
    exact levels_generate n
  intro x
  have hx : x ∈ (Subgroup.closure ({a, b} : Set AutTree)).map (levelEval n) := by
    rw [hmap]
    trivial
  obtain ⟨g, hg, hge⟩ := hx
  exact ⟨⟨g, hg⟩, hge⟩

/-- The subgroup generated by the fixed pair is dense in the entire inverse limit. -/
theorem dense_generated_pair :
    Dense (Subgroup.closure ({a, b} : Set AutTree) : Set AutTree) :=
  dense_of_surjective_levels _ generated_pair_surjective

end Kourovka.P21_44
