import Mathlib.GroupTheory.IsPerfect
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.GroupTheory.Subgroup.Centralizer

/-!
# Pairwise surjectivity for powers of a perfect group

A subgroup of a finite power of a perfect group is the whole power if its
projection onto every pair of distinct coordinates is surjective. The proof
isolates one coordinate using intersections of normal coordinate kernels.
-/

namespace Kourovka.P21_44

open scoped commutatorElement

/-- Two normal subgroups surjecting onto a perfect group have a surjective
intersection: their commutator already has full image. -/
theorem map_inf_eq_top_of_perfect
    {G P : Type*} [Group G] [Group P] [Group.IsPerfect P]
    (f : G →* P) (H J : Subgroup G) [H.Normal] [J.Normal]
    (hH : H.map f = ⊤) (hJ : J.map f = ⊤) :
    (H ⊓ J).map f = ⊤ := by
  apply top_unique
  calc
    ⊤ = ⁅(⊤ : Subgroup P), ⊤⁆ := by
      rw [← commutator_def, Group.IsPerfect.commutator_eq_top]
    _ = ⁅H, J⁆.map f := by rw [Subgroup.map_commutator, hH, hJ]
    _ ≤ (H ⊓ J).map f := Subgroup.map_mono (Subgroup.commutator_le_inf H J)

/-- A finite intersection of normal subgroups with full image in a perfect
group still has full image. -/
theorem map_finset_iInf_eq_top_of_perfect
    {G P ι : Type*} [Group G] [Group P] [Group.IsPerfect P]
    (f : G →* P) (hf : Function.Surjective f)
    (N : ι → Subgroup G) (hN : ∀ i, (N i).Normal)
    (s : Finset ι) (hs : ∀ i ∈ s, (N i).map f = ⊤) :
    (⨅ i ∈ s, N i).map f = ⊤ := by
  classical
  induction s using Finset.induction_on with
  | empty =>
      simpa [← MonoidHom.range_eq_map] using (MonoidHom.range_eq_top_of_surjective f hf)
  | @insert a s ha ih =>
      rw [Finset.iInf_insert]
      let : (N a).Normal := hN a
      let : (⨅ i ∈ s, N i).Normal :=
        Subgroup.normal_iInf_normal fun i =>
          Subgroup.normal_iInf_normal fun _ => hN i
      exact map_inf_eq_top_of_perfect f _ _
        (hs a (Finset.mem_insert_self a s))
        (ih fun i hi => hs i (Finset.mem_insert_of_mem hi))

/-- Pairwise surjectivity for a subgroup of a finite power of a perfect group
forces that subgroup to be the whole power. -/
theorem eq_top_of_pairwise_surjective
    {P ι : Type*} [Group P] [Group.IsPerfect P] [Finite ι] [Nontrivial ι]
    (K : Subgroup (ι → P))
    (hpair : ∀ i j : ι, i ≠ j → ∀ p q : P,
      ∃ k ∈ K, k i = p ∧ k j = q) :
    K = ⊤ := by
  classical
  let := Fintype.ofFinite ι
  let ev (i : ι) : K →* P := (Pi.evalMonoidHom (fun _ : ι => P) i).comp K.subtype
  have hev (i : ι) : Function.Surjective (ev i) := by
    intro p
    obtain ⟨j, hj⟩ := exists_ne i
    obtain ⟨k, hk, hi, _⟩ := hpair i j hj.symm p 1
    exact ⟨⟨k, hk⟩, hi⟩
  have hker (i j : ι) (hij : i ≠ j) : (ev j).ker.map (ev i) = ⊤ := by
    apply top_unique
    intro p _
    obtain ⟨k, hk, hi, hj⟩ := hpair i j hij p 1
    exact ⟨⟨k, hk⟩, hj, hi⟩
  have hsingle (i : ι) (p : P) : Pi.mulSingle i p ∈ K := by
    let s := Finset.univ.erase i
    have hfull : (⨅ j ∈ s, (ev j).ker).map (ev i) = ⊤ :=
      map_finset_iInf_eq_top_of_perfect (ev i) (hev i)
        (fun j => (ev j).ker) (fun _ => inferInstance) s
        (fun j hj => hker i j (Finset.ne_of_mem_erase hj).symm)
    have hp : p ∈ (⨅ j ∈ s, (ev j).ker).map (ev i) := by rw [hfull]; trivial
    obtain ⟨k, hk, hp⟩ := hp
    have heq : (k : ι → P) = Pi.mulSingle i p := by
      funext j
      by_cases hji : j = i
      · subst j
        simpa [ev] using hp
      · have hj : j ∈ s := Finset.mem_erase.mpr ⟨hji, Finset.mem_univ _⟩
        have hk' : k ∈ (ev j).ker :=
          (Subgroup.mem_iInf.mp (Subgroup.mem_iInf.mp hk j)) hj
        simpa [ev, Pi.mulSingle_eq_of_ne hji] using hk'
    exact heq ▸ k.property
  apply top_unique
  intro k _
  exact Subgroup.pi_mem_of_mulSingle_mem k fun i => hsingle i (k i)

/-- In a perfect group generated by two elements, a normal subgroup containing
their commutator is the whole group. -/
theorem normal_eq_top_of_pair_commutator
    {P : Type*} [Group P] [Group.IsPerfect P]
    (u v : P) (hgen : Subgroup.closure ({u, v} : Set P) = ⊤)
    (N : Subgroup P) [N.Normal] (hcomm : ⁅u, v⁆ ∈ N) : N = ⊤ := by
  let f := QuotientGroup.mk' N
  have hfg : Subgroup.closure ({f u, f v} : Set (P ⧸ N)) = ⊤ := by
    rw [← Set.image_pair, ← MonoidHom.map_closure, hgen,
      ← MonoidHom.range_eq_map]
    exact MonoidHom.range_eq_top_of_surjective f (QuotientGroup.mk'_surjective N)
  have hc : f u * f v = f v * f u := by
    rw [← commutatorElement_eq_one_iff_mul_comm, ← map_commutatorElement]
    exact (QuotientGroup.eq_one_iff _).mpr hcomm
  have hcl : IsMulCommutative
      (Subgroup.closure ({f u, f v} : Set (P ⧸ N))) :=
    Subgroup.isMulCommutative_closure (by
      intro x hx y hy
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy
      rcases hx with rfl | rfl <;> rcases hy with rfl | rfl
      · rfl
      · exact hc
      · exact hc.symm
      · rfl)
  have : IsMulCommutative (P ⧸ N) := by
    have htop : IsMulCommutative (⊤ : Subgroup (P ⧸ N)) := hfg ▸ hcl
    exact Function.Surjective.isMulCommutative
      (f := (⊤ : Subgroup (P ⧸ N)).subtype) (by intro x; exact ⟨⟨x, trivial⟩, rfl⟩) htop
  have : Subsingleton (P ⧸ N) := inferInstance
  apply top_unique
  intro p _
  exact (QuotientGroup.eq_one_iff p).mp (Subsingleton.elim (f p) 1)

/-- A subdirect product of a two-generated perfect group is the full product
if it is invariant under conjugating the first coordinate by one generator. -/
theorem subdirect_eq_top_of_conj_first
    {P : Type*} [Group P] [Group.IsPerfect P]
    (u v : P) (hgen : Subgroup.closure ({u, v} : Set P) = ⊤)
    (Q : Subgroup (P × P))
    (hfirst : ∀ p : P, ∃ q, (p, q) ∈ Q)
    (hsecond : ∀ q : P, ∃ p, (p, q) ∈ Q)
    (hconj : ∀ p q : P, (p, q) ∈ Q → (u * p * u⁻¹, q) ∈ Q) :
    Q = ⊤ := by
  let N := Q.comap (MonoidHom.inl P P)
  have hn (p : P) : p ∈ N ↔ (p, 1) ∈ Q := Iff.rfl
  have : N.Normal := by
    constructor
    intro p hp g
    obtain ⟨q, hq⟩ := hfirst g
    change (g * p * g⁻¹, 1) ∈ Q
    simpa using Q.mul_mem (Q.mul_mem hq hp) (Q.inv_mem hq)
  have hc : ⁅u, v⁆ ∈ N := by
    obtain ⟨q, hq⟩ := hfirst v
    change (u * v * u⁻¹ * v⁻¹, 1) ∈ Q
    simpa using Q.mul_mem (hconj v q hq) (Q.inv_mem hq)
  have hN : N = ⊤ := normal_eq_top_of_pair_commutator u v hgen N hc
  apply top_unique
  rintro ⟨p, q⟩ _
  obtain ⟨p', hp'⟩ := hsecond q
  have hleft : (p * p'⁻¹, 1) ∈ Q := (hn _).mp (by rw [hN]; trivial)
  simpa [mul_assoc] using Q.mul_mem hleft hp'

/-- Every image of an element of a perfect group belongs to the commutator
subgroup of the target. -/
theorem perfect_image_mem_commutator
    {P G : Type*} [Group P] [Group G] [Group.IsPerfect P]
    (f : P →* G) (p : P) : f p ∈ commutator G := by
  have hmap : (commutator P).map f ≤ commutator G := by
    rw [map_commutator_eq, commutator_def]
    exact Subgroup.commutator_mono le_top le_top
  exact hmap (Subgroup.mem_map.mpr ⟨p, Group.IsPerfect.mem_commutator, rfl⟩)

/-- A finite direct power of a perfect group is perfect. -/
theorem finite_pi_isPerfect
    (P ι : Type*) [Group P] [Group.IsPerfect P] [Finite ι] :
    Group.IsPerfect (ι → P) := by
  classical
  constructor
  apply top_unique
  intro f _
  apply Subgroup.pi_mem_of_mulSingle_mem f
  intro i
  exact perfect_image_mem_commutator (MonoidHom.mulSingle (fun _ : ι => P) i) (f i)

end Kourovka.P21_44
