import Kourovka.Problems.P21_44.Proof.Counting
import Kourovka.Problems.P21_44.Proof.Density
import Kourovka.Problems.P21_44.Proof.GeneratedGeometry
import Kourovka.Problems.P21_44.Proof.Shortening
import Kourovka.Problems.P21_44.Statement

/-!
# A finitely generated dense subgroup of subexponential growth

The witnesses are the two explicit compatible automorphisms `a` and `b` of the
infinite alternating rooted tree. Density comes from finite wreath generation;
subexponential growth comes from the disjoint five-letter shortening argument
and the count of alternating words with few sign changes.
-/

namespace Kourovka.P21_44

/-- The existential section words control the ordinary word lengths of the
actual sections in the generated subgroup. -/
theorem generated_section_shortening (w : Word) (hw : Alternating w) :
    (∑ i : Alphabet,
      (wordGeometry.length (generatedSection (evalWord generatedA generatedB w) i) : ℝ)) +
        (variation w : ℝ) / 10 ≤ (w.length : ℝ) + 1 := by
  obtain ⟨f,hf,hlen⟩ := section_shortening w hw
  have hlength (i : Alphabet) :
      wordGeometry.length (generatedSection (evalWord generatedA generatedB w) i) ≤
        (f i).length := by
    apply (wordGeometry.mem_ball_iff_length_le _ _).mp
    have heq : generatedSection (evalWord generatedA generatedB w) i =
        evalWord generatedA generatedB (f i) := by
      apply Subtype.ext
      change treeSection (evalWord generatedA generatedB w).val i = _
      rw [coe_evalWord, coe_evalWord]
      exact (hf i).symm
    rw [heq]
    exact evalWord_mem_ball (f i)
  have hsum :
      (∑ i : Alphabet,
        (wordGeometry.length (generatedSection (evalWord generatedA generatedB w) i) : ℝ)) ≤
        ((∑ i : Alphabet, (f i).length : ℕ) : ℝ) := by
    rw [Nat.cast_sum]
    exact Finset.sum_le_sum fun i _ => by exact_mod_cast hlength i
  linarith

/-- The ordinary word balls of the fixed two-generated subgroup have
subexponential growth. -/
theorem subexponential_growth :
    RecurrentSections.SubexponentialGrowth wordGeometry.volume := by
  apply subexponential_of_word_shortening wordGeometry generatedA generatedB
    (fun g => root g.val) generatedSection root_sections_injective
  · change Fintype.card (alternatingGroup (Fin 5)) = 60
    rw [card_alternatingGroup]
    decide
  · intro n g hg
    obtain ⟨w,hw,hlen,heval⟩ := exists_alternating_word_of_mem_ball hg
    refine ⟨w,hw,hlen,Subtype.ext ?_⟩
    exact (coe_evalWord w).trans heval
  · exact generated_section_shortening

/-- The subgroup is generated by the displayed pair. -/
theorem generatedSubgroup_fg : generatedSubgroup.FG := by
  classical
  refine ⟨{a,b}, ?_⟩
  simp [generatedSubgroup]

/-- Affirmative answer to Kourovka Notebook Problem 21.44. -/
theorem notebookStatement : NotebookStatement := by
  refine ⟨generatedSubgroup, generatedSubgroup_fg, dense_generated_pair, ?_⟩
  exact ⟨wordGeometry, subexponential_growth⟩

end Kourovka.P21_44
