import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.Tactic.Group

set_option autoImplicit false

namespace Kourovka.Problem2153.Collection

universe u v
variable {G : Type u} [Group G] {A : Type v}

/-- Conjugation membership only needs to be checked on a set of generators. -/
theorem rightConj_mem_closure_of_generators (S : Set G) (U : Subgroup G) (g : G)
    (hgen : ∀ x ∈ S, g⁻¹ * x * g ∈ U) {x : G} (hx : x ∈ Subgroup.closure S) :
    g⁻¹ * x * g ∈ U := by
  induction hx using Subgroup.closure_induction with
  | mem x hx => exact hgen x hx
  | one => simpa only [mul_one, inv_mul_cancel] using U.one_mem
  | mul x y _ _ hx hy => simpa [mul_assoc] using U.mul_mem hx hy
  | inv x _ hx => simpa [mul_inv_rev, mul_assoc] using U.inv_mem hx

/-- The certificate convention is `[g,x] = g⁻¹ x⁻¹ g x`. -/
theorem rightConj_mem_of_commutator (U : Subgroup G) (g x : G)
    (hx : x ∈ U) (hc : g⁻¹ * x⁻¹ * g * x ∈ U) : g⁻¹ * x * g ∈ U := by
  have h := U.mul_mem hx (U.inv_mem hc)
  convert h using 1 <;> group

/-- A single collection step. The parameterized curve need not be a subgroup:
its products and inverses may acquire factors in the already collected tail. -/
structure Step (U : Subgroup G) (r : A → G) where
  zero : A
  at_zero : r zero = 1
  multiply : ∀ a b, ∃ c z, z ∈ U ∧ r a * r b = r c * z
  invert : ∀ a, ∃ b z, z ∈ U ∧ (r a)⁻¹ = r b * z
  normalize : ∀ a z, z ∈ U → (r a)⁻¹ * z * r a ∈ U

namespace Step
variable {U : Subgroup G} {r : A → G} (C : Step U r)

/-- The set of one root factor followed by a tail factor is a subgroup. -/
def subgroup : Subgroup G where
  carrier := {g | ∃ a z, z ∈ U ∧ g = r a * z}
  one_mem' := ⟨C.zero, 1, U.one_mem, by simp [C.at_zero]⟩
  mul_mem' := by
    rintro x y ⟨a, u, hu, rfl⟩ ⟨b, v, hv, rfl⟩
    obtain ⟨c, z, hz, hmul⟩ := C.multiply a b
    refine ⟨c, z * ((r b)⁻¹ * u * r b) * v,
      U.mul_mem (U.mul_mem hz (C.normalize b u hu)) hv, ?_⟩
    calc
      (r a * u) * (r b * v) = (r a * r b) * ((r b)⁻¹ * u * r b) * v := by group
      _ = r c * (z * ((r b)⁻¹ * u * r b) * v) := by rw [hmul]; group
  inv_mem' := by
    rintro x ⟨a, u, hu, rfl⟩
    obtain ⟨b, z, hz, hinv⟩ := C.invert a
    refine ⟨b, ((r b)⁻¹ * u⁻¹ * r b) * z,
      U.mul_mem (C.normalize b u⁻¹ (U.inv_mem hu)) hz, ?_⟩
    calc
      (r a * u)⁻¹ = u⁻¹ * (r b * z) := by rw [mul_inv_rev, hinv]
      _ = r b * (((r b)⁻¹ * u⁻¹ * r b) * z) := by group

theorem mem_subgroup_iff (g : G) : g ∈ C.subgroup ↔ ∃ a z, z ∈ U ∧ g = r a * z :=
  Iff.rfl

theorem root_mem (a : A) : r a ∈ C.subgroup :=
  ⟨a, 1, U.one_mem, by simp⟩

theorem tail_le : U ≤ C.subgroup := by
  intro z hz
  exact ⟨C.zero, z, hz, by simp [C.at_zero]⟩

/-- The finite collection certificate proves coverage of the generated subgroup. -/
theorem subgroup_eq_closure :
    C.subgroup = Subgroup.closure (Set.range r ∪ (U : Set G)) := by
  apply le_antisymm
  · rintro g ⟨a, z, hz, rfl⟩
    exact Subgroup.mul_mem _ (Subgroup.subset_closure (Or.inl ⟨a, rfl⟩))
      (Subgroup.subset_closure (Or.inr hz))
  · apply (Subgroup.closure_le C.subgroup).mpr
    intro g hg
    rcases hg with ⟨a, rfl⟩ | hg
    · exact C.root_mem a
    · exact C.tail_le hg

include C in
theorem exists_normalForm {g : G}
    (hg : g ∈ Subgroup.closure (Set.range r ∪ (U : Set G))) :
    ∃ a z, z ∈ U ∧ g = r a * z := by
  rw [← C.subgroup_eq_closure] at hg
  exact hg

end Step

/-- The subgroup generated by all values of a finite ordered list of curves. -/
def rootClosure (roots : List (A → G)) : Subgroup G :=
  Subgroup.closure {g | ∃ r ∈ roots, ∃ a, r a = g}

theorem rootClosure_tail_le (r : A → G) (roots : List (A → G)) :
    rootClosure roots ≤ rootClosure (r :: roots) := by
  apply (Subgroup.closure_le _).mpr
  rintro g ⟨s, hs, a, rfl⟩
  exact Subgroup.subset_closure ⟨s, List.mem_cons_of_mem r hs, a, rfl⟩

theorem rootClosure_cons (r : A → G) (roots : List (A → G))
    (C : Step (rootClosure roots) r) : rootClosure (r :: roots) = C.subgroup := by
  apply le_antisymm
  · apply (Subgroup.closure_le _).mpr
    rintro g ⟨s, hs, a, rfl⟩
    rcases List.mem_cons.mp hs with rfl | hs
    · exact C.root_mem a
    · exact C.tail_le (Subgroup.subset_closure ⟨s, hs, a, rfl⟩)
  · rintro g ⟨a, z, hz, rfl⟩
    exact Subgroup.mul_mem _ (Subgroup.subset_closure ⟨r, by simp, a, rfl⟩)
      (rootClosure_tail_le r roots hz)

/-- An ordered product has one parameter for each root curve, including zero parameters. -/
inductive NormalForm : List (A → G) → G → Prop
  | nil : NormalForm [] 1
  | cons (r : A → G) (roots : List (A → G)) (a : A) (z : G) :
      NormalForm roots z → NormalForm (r :: roots) (r a * z)

/-- Local collection steps for an ordered root list. -/
inductive Collectible : List (A → G) → Prop
  | nil : Collectible []
  | cons (r : A → G) (roots : List (A → G)) :
      Step (rootClosure roots) r → Collectible roots → Collectible (r :: roots)

/-- Iterating the local certificates gives coverage of the full generated subgroup.
No enumeration of that subgroup or uniqueness of root coordinates is assumed. -/
theorem Collectible.coverage {roots : List (A → G)} (C : Collectible roots)
    {g : G} (hg : g ∈ rootClosure roots) : NormalForm roots g := by
  induction C generalizing g with
  | nil =>
    have he : rootClosure ([] : List (A → G)) = ⊥ := by
      simp [rootClosure]
    have hg1 : g = 1 := by simpa [he] using hg
    subst g
    exact NormalForm.nil
  | cons r roots step rest ih =>
    rw [rootClosure_cons r roots step] at hg
    obtain ⟨a, z, hz, rfl⟩ := hg
    exact NormalForm.cons r roots a z (ih hz)

end Kourovka.Problem2153.Collection
