import Kourovka.Problem2153.WilsonModel.Extras
import Mathlib.Algebra.Group.Subgroup.Lattice

set_option autoImplicit false
set_option maxRecDepth 10000
set_option maxHeartbeats 2000000

namespace Kourovka.Problem2153.WilsonModel
open Field8

/-- The four explicit Wilson generators, as genuine invertible matrices. -/
def tUnit : GL26 := ⟨wilsonT, wilsonT, wilsonT_square, wilsonT_square⟩
def xUnit : GL26 := ⟨wilsonX, x3, x_mul_x3, x3_mul_x⟩
def rhoUnit : GL26 := ⟨rho, rho, rho_square, rho_square⟩
def sigmaUnit : GL26 := ⟨sigma, sigma, sigma_square, sigma_square⟩

/-- Each of the 49 explicitly tabulated torus matrices is invertible. -/
def torusUnit (a b : Fin 7) : GL26 where
  val := Matrix.diagonal (torusDiag a b)
  inv := Matrix.diagonal (fun i => (torusDiag a b i)⁻¹)
  val_inv := by
    rw [Matrix.diagonal_mul_diagonal]
    have h : (fun i => torusDiag a b i * (torusDiag a b i)⁻¹) = fun _ => 1 :=
      funext fun i => mul_inv_cancel₀ (torusDiag_ne_zero a b i)
    rw [h]
    exact Matrix.diagonal_one
  inv_val := by
    rw [Matrix.diagonal_mul_diagonal]
    have h : (fun i => (torusDiag a b i)⁻¹ * torusDiag a b i) = fun _ => 1 :=
      funext fun i => inv_mul_cancel₀ (torusDiag_ne_zero a b i)
    rw [h]
    exact Matrix.diagonal_one

def srsUnit : GL26 := ⟨srs, srs, srs_square, srs_square⟩
def wUnit : GL26 := ⟨w, w, w_square, w_square⟩
def witnessXUnit : GL26 := ⟨witnessX, witnessX, witnessX_square, witnessX_square⟩
def witnessYUnit : GL26 := ⟨witnessY, witnessY, witnessY_square, witnessY_square⟩
def witnessAUnit : GL26 := ⟨witnessA, witnessA, witnessA_square, witnessA_square⟩

theorem srsUnit_word : srsUnit = sigmaUnit * rhoUnit * sigmaUnit := by
  apply Units.ext
  change srs = sigma * rho * sigma
  rw [sr_eq, srs_eq]

theorem wUnit_word : wUnit = sigmaUnit * rhoUnit * sigmaUnit * rhoUnit *
    sigmaUnit * rhoUnit * sigmaUnit := by
  apply Units.ext
  change w = sigma * rho * sigma * rho * sigma * rho * sigma
  rw [sr_eq, srs_eq, srsr_eq, srsrs_eq, srsrsr_eq, w_eq]

theorem witnessXUnit_word : witnessXUnit = srsUnit⁻¹ * xUnit ^ 2 * srsUnit := by
  apply Units.ext
  change witnessX = srs * (wilsonX ^ 2) * srs
  rw [pow_two, x2_eq, zxLeft_eq, witnessX_eq]

theorem witnessYUnit_word : witnessYUnit = (torusUnit 1 0)⁻¹ * witnessXUnit *
    torusUnit 1 0 := by
  apply Units.ext
  change witnessY = Matrix.diagonal (fun i => (torusDiag 1 0 i)⁻¹) * witnessX *
    Matrix.diagonal (torusDiag 1 0)
  rw [← hInv_eq_diagonal, ← h_eq_diagonal, zyLeft_eq, witnessY_eq]

theorem witnessAUnit_word : witnessAUnit = wUnit⁻¹ * witnessXUnit * wUnit := by
  apply Units.ext
  change witnessA = w * witnessX * w
  rw [zaLeft_eq, witnessA_eq]

/-- A concrete ambient subgroup of GL(26,8), generated by Wilson's four matrices
and all 49 specified torus matrices. No identification or simplicity is assumed. -/
def ambient : Subgroup GL26 :=
  Subgroup.closure ({tUnit, xUnit, rhoUnit, sigmaUnit} ∪
    Set.range (fun p : Fin 7 × Fin 7 => torusUnit p.1 p.2))

theorem tUnit_mem : tUnit ∈ ambient := Subgroup.subset_closure (by simp)
theorem xUnit_mem : xUnit ∈ ambient := Subgroup.subset_closure (by simp)
theorem rhoUnit_mem : rhoUnit ∈ ambient := Subgroup.subset_closure (by simp)
theorem sigmaUnit_mem : sigmaUnit ∈ ambient := Subgroup.subset_closure (by simp)
theorem torusUnit_mem (a b : Fin 7) : torusUnit a b ∈ ambient :=
  Subgroup.subset_closure (Or.inr ⟨(a, b), rfl⟩)

theorem srsUnit_mem : srsUnit ∈ ambient := by
  rw [srsUnit_word]
  exact ambient.mul_mem (ambient.mul_mem sigmaUnit_mem rhoUnit_mem) sigmaUnit_mem

theorem wUnit_mem : wUnit ∈ ambient := by
  rw [wUnit_word]
  exact ambient.mul_mem (ambient.mul_mem (ambient.mul_mem (ambient.mul_mem
    (ambient.mul_mem (ambient.mul_mem sigmaUnit_mem rhoUnit_mem) sigmaUnit_mem)
    rhoUnit_mem) sigmaUnit_mem) rhoUnit_mem) sigmaUnit_mem

theorem witnessXUnit_mem : witnessXUnit ∈ ambient := by
  rw [witnessXUnit_word]
  exact ambient.mul_mem (ambient.mul_mem (ambient.inv_mem srsUnit_mem)
    (ambient.pow_mem xUnit_mem 2)) srsUnit_mem

theorem witnessYUnit_mem : witnessYUnit ∈ ambient := by
  rw [witnessYUnit_word]
  exact ambient.mul_mem (ambient.mul_mem (ambient.inv_mem (torusUnit_mem 1 0))
    witnessXUnit_mem) (torusUnit_mem 1 0)

theorem witnessAUnit_mem : witnessAUnit ∈ ambient := by
  rw [witnessAUnit_word]
  exact ambient.mul_mem (ambient.mul_mem (ambient.inv_mem wUnit_mem)
    witnessXUnit_mem) wUnit_mem

private theorem order_prime {M : Type*} [Monoid M] (g : M) (p : ℕ)
    (hp : p.Prime) (hpow : g ^ p = 1) (hne : g ≠ 1) : orderOf g = p := by
  let : Fact p.Prime := ⟨hp⟩
  exact orderOf_eq_prime hpow hne

theorem ax_fifth : ax ^ 5 = 1 := by
  have h2 : ax ^ 2 = ax2 := by simpa [pow_two] using ax2_eq
  have h4 : ax ^ 4 = ax4 := by
    calc ax ^ 4 = ax ^ 2 * ax ^ 2 := by rw [← pow_add]
         _ = ax4 := by rw [h2, ax4_eq]
  calc ax ^ 5 = ax ^ 4 * ax := by rw [pow_succ]
       _ = 1 := by rw [h4, ax_fifth_step]

theorem ay_seventh : ay ^ 7 = 1 := by
  have h2 : ay ^ 2 = ay2 := by simpa [pow_two] using ay2_eq
  have h4 : ay ^ 4 = ay4 := by
    calc ay ^ 4 = ay ^ 2 * ay ^ 2 := by rw [← pow_add]
         _ = ay4 := by rw [h2, ay4_eq]
  have h6 : ay ^ 6 = ay6 := by
    calc ay ^ 6 = ay ^ 4 * ay ^ 2 := by rw [← pow_add]
         _ = ay6 := by rw [h4, h2, ay6_eq]
  calc ay ^ 7 = ay ^ 6 * ay := by rw [pow_succ]
       _ = 1 := by rw [h6, ay_seventh_step]

theorem order_witnessXUnit : orderOf witnessXUnit = 2 := by
  rw [← orderOf_units]
  exact order_prime witnessX 2 (by decide) (by simpa [pow_two] using witnessX_square)
    witnessX_ne_one

theorem order_witnessYUnit : orderOf witnessYUnit = 2 := by
  rw [← orderOf_units]
  exact order_prime witnessY 2 (by decide) (by simpa [pow_two] using witnessY_square)
    witnessY_ne_one

theorem order_witnessAUnit : orderOf witnessAUnit = 2 := by
  rw [← orderOf_units]
  exact order_prime witnessA 2 (by decide) (by simpa [pow_two] using witnessA_square)
    witnessA_ne_one

theorem order_AX : orderOf (witnessAUnit * witnessXUnit) = 5 := by
  rw [← orderOf_units]
  change orderOf (witnessA * witnessX) = 5
  rw [ax_eq]
  exact order_prime ax 5 (by decide) ax_fifth ax_ne_one

theorem order_AY : orderOf (witnessAUnit * witnessYUnit) = 7 := by
  rw [← orderOf_units]
  change orderOf (witnessA * witnessY) = 7
  rw [ay_eq]
  exact order_prime ay 7 (by decide) ay_seventh ay_ne_one

/-- The witnesses are elements of the concrete generated ambient group. -/
def X : ambient := ⟨witnessXUnit, witnessXUnit_mem⟩
def Y : ambient := ⟨witnessYUnit, witnessYUnit_mem⟩
def A : ambient := ⟨witnessAUnit, witnessAUnit_mem⟩

theorem witness_orders : orderOf A = 2 ∧ orderOf X = 2 ∧ orderOf Y = 2 ∧
    orderOf (A * X) = 5 ∧ orderOf (A * Y) = 7 := by
  have hf : Function.Injective ambient.subtype := Subtype.val_injective
  simp only [← orderOf_injective ambient.subtype hf]
  exact ⟨order_witnessAUnit, order_witnessXUnit, order_witnessYUnit, order_AX, order_AY⟩

def W : ambient := ⟨wUnit, wUnit_mem⟩
def H : ambient := ⟨torusUnit 1 0, torusUnit_mem 1 0⟩

theorem A_eq_conj_X : A = W⁻¹ * X * W := Subtype.ext witnessAUnit_word

theorem Y_eq_conj_X : Y = H⁻¹ * X * H := Subtype.ext witnessYUnit_word

theorem X_ne_Y : X ≠ Y := by
  intro h
  exact witnessX_ne_Y (congrArg (fun g : ambient => (g.val : Mat)) h)

theorem ambient_finite : Finite ambient := inferInstance

def C : ambient := ⟨tUnit * sigmaUnit, ambient.mul_mem tUnit_mem sigmaUnit_mem⟩

theorem order_C : orderOf C = 3 := by
  rw [← orderOf_injective ambient.subtype Subtype.val_injective]
  change orderOf (tUnit * sigmaUnit) = 3
  rw [← orderOf_units]
  change orderOf (wilsonT * sigma) = 3
  rw [c3_eq]
  apply order_prime c3 3 (by decide) _ c3_ne_one
  calc c3 ^ 3 = (c3 * c3) * c3 := by simp only [pow_succ, pow_zero, one_mul]
       _ = 1 := by rw [c3Squared_eq, c3_cubed_step]

theorem order_tUnit : orderOf tUnit = 2 := by
  rw [← orderOf_units]
  exact order_prime wilsonT 2 (by decide)
    (by simpa [pow_two] using wilsonT_square) (by decide +kernel)

theorem order_rhoUnit : orderOf rhoUnit = 2 := by
  rw [← orderOf_units]
  exact order_prime rho 2 (by decide)
    (by simpa [pow_two] using rho_square) (by decide +kernel)

theorem order_sigmaUnit : orderOf sigmaUnit = 2 := by
  rw [← orderOf_units]
  exact order_prime sigma 2 (by decide)
    (by simpa [pow_two] using sigma_square) (by decide +kernel)

theorem order_xUnit : orderOf xUnit = 4 := by
  rw [← orderOf_units]
  change orderOf wilsonX = 4
  let : Fact (Nat.Prime 2) := ⟨by decide⟩
  have hnot : wilsonX ^ (2 ^ 1) ≠ 1 := by
    change wilsonX ^ 2 ≠ 1
    rw [pow_two, x2_eq]
    decide +kernel
  have hfin : wilsonX ^ (2 ^ (1 + 1)) = 1 := by
    change wilsonX ^ 4 = 1
    calc wilsonX ^ 4 = (wilsonX * wilsonX) * wilsonX * wilsonX := by
           simp only [pow_succ, pow_zero, one_mul]
         _ = 1 := by rw [x2_eq, x3_eq, x3_mul_x]
  exact orderOf_eq_prime_pow (p := 2) (n := 1) hnot hfin

end Kourovka.Problem2153.WilsonModel
