import Kourovka.Problems.P21_106.Proof.Heisenberg
import Kourovka.Problems.P21_106.Proof.Formula
import Mathlib.Data.Int.Order.Units
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring

/-!
# Exactly two formula values, generating an infinite subgroup

The two-dimensional Plücker identity forces the commutator determinant of any
formula value to be an integer unit. Explicit witnesses realize both units.
The subgroup generated by these two values contains an injective copy of `ℤ`.
-/

namespace Kourovka.P21_106

private def det (a b : H) : ℤ := a.r * b.s - a.s * b.r

private theorem commutator_central (a b : H) :
    commutator a b = central (det a b) := Heisenberg.commutator_eq a b

private theorem plucker (u a v b : H) :
    det u a * det v b - det u v * det a b + det u b * det a v = 0 := by
  unfold det
  ring

private theorem determinant_unit (u a v b : H)
    (hua : det u a = 0) (hvb : det v b = 0)
    (hub : det u b = 1) (hav : det a v = 1) :
    det a b = 1 ∨ det a b = -1 := by
  have h := plucker u a v b
  rw [hua, hvb, hub, hav] at h
  have hm : det a b * det u v = 1 := by nlinarith
  rcases Int.eq_one_or_neg_one_of_mul_eq_one' hm with h | h
  · exact Or.inl h.1
  · exact Or.inr h.1

/-- A formula value must be one of the two primitive central elements. -/
theorem formulaCondition_imp (x : H) (hx : FormulaCondition x) :
    x = central 1 ∨ x = central (-1) := by
  obtain ⟨a, b, hx, hab⟩ := hx
  obtain ⟨u, v, hua, hvb, hub, hav⟩ :=
    hab (⟨1, 0, 0⟩ : H) (⟨0, 1, 0⟩ : H)
  have hua' : det u a = 0 := by
    simpa only [commutator_central, central_t, Heisenberg.one_t] using
      congrArg Heisenberg.t hua
  have hvb' : det v b = 0 := by
    simpa only [commutator_central, central_t, Heisenberg.one_t] using
      congrArg Heisenberg.t hvb
  have hub' : det u b = 1 := by
    simpa [commutator_central, det] using congrArg Heisenberg.t hub
  have hav' : det a v = 1 := by
    simpa [commutator_central, det] using congrArg Heisenberg.t hav
  rw [hx, commutator_central]
  rcases determinant_unit u a v b hua' hvb' hub' hav' with h | h
  · exact Or.inl (congrArg central h)
  · exact Or.inr (congrArg central h)

private theorem central_unit_satisfies (ε : ℤ) (hε : ε * ε = 1) :
    FormulaCondition (central ε) := by
  refine ⟨⟨1, 0, 0⟩, ⟨0, ε, 0⟩, ?_, ?_⟩
  · simp [commutator_central, det]
  · intro g h
    refine ⟨⟨ε * det g h, 0, 0⟩, ⟨0, det g h, 0⟩, ?_, ?_, ?_, ?_⟩
    · simp [commutator_central, det]
    · simp [commutator_central, det]
    · rw [commutator_central, commutator_central]
      congr 1
      change ε * det g h * ε - 0 * 0 = det g h
      calc
        ε * det g h * ε - 0 * 0 = (ε * ε) * det g h := by ring
        _ = det g h := by rw [hε, one_mul]
    · simp [commutator_central, det]

/-- The formula defines exactly the two generators of the infinite cyclic centre. -/
theorem formulaCondition_iff (x : H) :
    FormulaCondition x ↔ x = central 1 ∨ x = central (-1) := by
  refine ⟨formulaCondition_imp x, ?_⟩
  rintro (rfl | rfl)
  · exact central_unit_satisfies 1 (by norm_num)
  · exact central_unit_satisfies (-1) (by norm_num)

/-- The values of the counterexample formula form a finite set. -/
theorem formulaCondition_finite : Set.Finite {x : H | FormulaCondition x} := by
  have h : {x : H | FormulaCondition x} = {central 1, central (-1)} := by
    ext x
    simp only [Set.mem_ofPred_eq, formulaCondition_iff, Set.mem_insert_iff,
      Set.mem_singleton_iff]
  rw [h]
  exact (Set.finite_singleton (central (-1))).insert (central 1)

/-- Every central integer belongs to the subgroup generated by the formula values. -/
theorem central_mem_formulaCondition_closure (n : ℤ) :
    central n ∈ Subgroup.closure {x : H | FormulaCondition x} := by
  have hpos : central 1 ∈ Subgroup.closure {x : H | FormulaCondition x} :=
    Subgroup.subset_closure ((formulaCondition_iff _).mpr (Or.inl rfl))
  simpa only [central_zpow, mul_one] using
    (Subgroup.closure {x : H | FormulaCondition x}).zpow_mem hpos n

/-- The subgroup generated by the finite formula-value set is infinite. -/
theorem formulaCondition_closure_infinite :
    Infinite (Subgroup.closure {x : H | FormulaCondition x}) := by
  apply Infinite.of_injective
    (fun n : ℤ => (⟨central n, central_mem_formulaCondition_closure n⟩ :
      Subgroup.closure {x : H | FormulaCondition x}))
  intro m n h
  exact central_injective (congrArg Subtype.val h)

end Kourovka.P21_106
