#!/usr/bin/env python3
"""Generate untrusted sparse data and kernel-checking Lean statements (Auckland only).

The generated Lean files contain no external proof assumptions.  The Python
assertions are diagnostics; the mathematical acceptance gate is the Lean kernel.
"""
import argparse
from collections import deque
import hashlib
import json
from pathlib import Path

P = 5
PREFIX = "Kourovka.Problems.P21_99.Proof."
NS = "Kourovka.P21_99.Data"
EMITTED = []


def rref(a, width=None):
    a = [list(x) for x in a]
    width = width if width is not None else len(a[0])
    rank = 0
    pivots = []
    for j in range(width):
        k = next((i for i in range(rank, len(a)) if a[i][j] % P), None)
        if k is None:
            continue
        a[k], a[rank] = a[rank], a[k]
        c = pow(a[rank][j] % P, -1, P)
        a[rank] = [x*c % P for x in a[rank]]
        for i in range(len(a)):
            if i != rank and a[i][j]:
                c = a[i][j]
                a[i] = [(x-c*y) % P for x,y in zip(a[i], a[rank])]
        pivots.append(j)
        rank += 1
        if rank == len(a):
            break
    return a, pivots


def identity(n):
    return [[int(i == j) for j in range(n)] for i in range(n)]


def transpose(a):
    return list(map(list, zip(*a)))


def mul(a,b):
    # Sparse multiplication is useful for the 384 x 8 closure table.
    out = [[0]*len(b[0]) for _ in a]
    for i,row in enumerate(a):
        for k,x in enumerate(row):
            if x:
                for j,y in enumerate(b[k]):
                    out[i][j] = (out[i][j]+x*y) % P
    return out


def inverse(a):
    n = len(a)
    reduced,pivots = rref([row+e for row,e in zip(a,identity(n))], n)
    assert pivots == list(range(n))
    return [row[n:] for row in reduced]


def nullspace(a,n):
    reduced,pivots = rref(a,n)
    result=[]
    for j in range(n):
        if j not in pivots:
            row=[0]*n
            row[j]=1
            for i,k in enumerate(pivots):
                row[k]=-reduced[i][j] % P
            result.append(row)
    return result


def right_inverse(a):
    n,m=len(a),len(a[0])
    reduced,pivots=rref([row+e for row,e in zip(a,identity(n))],m)
    assert len(pivots)==n
    out=[[0]*n for _ in range(m)]
    for i,j in enumerate(pivots):
        out[j]=reduced[i][m:]
    assert mul(a,out)==identity(n)
    return out


def row_string(row):
    return "[" + ", ".join(f"({j}, {x})" for j,x in enumerate(row) if x) + "]"


def tuple_string(items):
    return "![" + ", ".join(items) + "]"


def rows_string(a):
    return tuple_string([row_string(row) for row in a])


def blocked_definition(name, values, typ, chunk=16):
    """Keep kernel lookup depth small without introducing more import files."""
    values=list(values)
    assert len(values)%chunk==0
    pieces=[tuple_string(values[i:i+chunk]) for i in range(0,len(values),chunk)]
    return (f"def {name}Chunks : Fin {len(pieces)} → Fin {chunk} → {typ} :=\n  "+tuple_string(pieces)+
            f"\n\ndef {name} (q : Fin {len(values)}) : {typ} :=\n"+
            f"  {name}Chunks ⟨q.val / {chunk}, by omega⟩ ⟨q.val % {chunk}, by omega⟩\n\n")


def emit(path, imports, body):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join("import "+PREFIX+i for i in imports)+
                    "\n\n/-! Generated by scripts/generate_21_99.py; checked by Lean's kernel. -/\n\n"+
                    "set_option maxRecDepth 100000\nset_option maxHeartbeats 0\n\n"+
                    "namespace "+NS+"\n\n"+body+"\n\nend "+NS+"\n")
    EMITTED.append(path)


def emit_chunks(out,name,values,typ,chunk=16):
    assert len(values)%chunk==0
    imports=[]
    pieces=[]
    for start in range(0,len(values),chunk):
        number=start//chunk
        stem=f"Certificates.{name}{number:03d}"
        ident=f"{name[0].lower()+name[1:]}Chunk{number:03d}"
        emit(out/"Certificates"/f"{name}{number:03d}.lean",["DataBasic"],
             f"def {ident} : Fin {chunk} → {typ} :=\n  "+tuple_string(values[start:start+chunk]))
        imports.append(stem)
        pieces.append(ident)
    ident=name[0].lower()+name[1:]
    body=(f"def {ident}Chunks : Fin {len(pieces)} → Fin {chunk} → {typ} :=\n  "+tuple_string(pieces)+
          f"\n\ndef {ident} (q : Fin {len(values)}) : {typ} :=\n"+
          f"  {ident}Chunks ⟨q.val / {chunk}, by omega⟩ ⟨q.val % {chunk}, by omega⟩")
    emit(out/f"Data{name}.lean",imports,body)


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input",type=Path,required=True)
    ap.add_argument("--compact",type=Path,required=True)
    ap.add_argument("--output",type=Path,required=True)
    args=ap.parse_args()
    compact=json.loads(args.compact.read_text())
    input_sha=hashlib.sha256(args.input.read_bytes()).hexdigest()
    assert input_sha==compact["input_sha256"]=="b9c99c8ee4a094bb2f4c7f3ea3c1ff56e4feaa71e90e91082ae7b43f7c8debfe"
    tokens=iter("\n".join(s.split("#")[0] for s in args.input.read_text().splitlines()).split())
    def expect(s):
        assert next(tokens)==s
    def number():
        return int(next(tokens))
    def indices(label):
        expect(label)
        return [number() for _ in range(number())]
    expect("AF2199_V1");expect("META");meta=next(tokens)
    expect("FIELD");assert number()==5
    expect("DIM");assert number()==18
    expect("BLOCKS");assert number()==6
    expect("ELEMENTS");assert number()==384
    expect("IDENTITY");assert number()==0
    gens=indices("GENERATORS");indices("LGENERATORS");reps=indices("REPS")
    assert len(gens)==8
    expect("DATA")
    matrices=[];perms=[]
    for q in range(384):
        assert number()==q
        perms.append([number() for _ in range(6)])
        matrices.append([[number() for _ in range(18)] for _ in range(18)])
    def key(perm,matrix):
        return tuple(perm),tuple(map(tuple,matrix))
    index={key(p,m):q for q,(p,m) in enumerate(zip(perms,matrices))}
    assert len(index)==384
    def product(q,g):
        return index[key([perms[q][perms[g][i]] for i in range(6)],mul(matrices[q],matrices[g]))]
    step=[[product(q,g) for g in gens] for q in range(384)]
    inv=[]
    for q in range(384):
        ip=[perms[q].index(i) for i in range(6)]
        inv.append(index[key(ip,inverse(matrices[q]))])
        assert mul(matrices[q],matrices[inv[-1]])==identity(18)
    words={0:[]};queue=deque([0])
    while queue:
        q=queue.popleft()
        for g,s in enumerate(step[q]):
            if s not in words:
                words[s]=words[q]+[g]
                queue.append(s)
    assert len(words)==384
    projection=[nullspace(w,18) for w in compact["block_W"]]
    assert all(len(a)==14 for a in projection)
    section=[right_inverse(a) for a in projection]
    def quotient(q,i):
        return mul(mul(projection[perms[q][i]],matrices[q]),section[i])
    for q in range(384):
        for i in range(6):
            assert mul(projection[perms[q][i]],matrices[q])==mul(quotient(q,i),projection[i])
    target=[q for q in range(384) if perms[q][0]==2]
    assert len(target)==64
    regular=[];singular=[];rinv=[];psi=[];phi=[]
    records={r["element"]:r for r in compact["all_projected_records"]}
    for q in target:
        record=records[q]
        good=next(x for x in record["fixed_blocks"] if x["S_rank"]==18)
        bad=next(x for x in record["fixed_blocks"] if x["S_rank"]!=18)
        r,s=good["block"],bad["block"]
        assert [i for i in range(6) if perms[q][i]==i]==sorted([r,s])
        regular.append(r);singular.append(s)
        t=quotient(q,r)
        rinv.append(inverse([[(int(i==j)-t[i][j])%P for j in range(14)] for i in range(14)]))
        lam=compact["forbidden_spaces"][bad["covered_by_forbidden"]]["equations"][0]
        psi.append(mul([lam],section[s])[0])
        phi.append(mul([lam],section[2])[0])
        assert mul([psi[-1]],projection[s])==mul([phi[-1]],projection[2])==[lam]
        assert mul([psi[-1]],quotient(q,s))==[psi[-1]]
        assert sum(x*y for x,y in zip(lam,compact["translation"]))%P
    out=args.output
    emit_chunks(out,"MatrixRows",list(map(rows_string,matrices)),"Rows 18 18")
    emit_chunks(out,"Step",[tuple_string(map(str,row)) for row in step],"Fin 8 → Fin 384")
    emit_chunks(out,"RegularInverseRows",list(map(rows_string,rinv)),"Rows 14 14")
    body=(blocked_definition("blockMap",[tuple_string(map(str,p)) for p in perms],"Fin 6 → Fin 6")+
          blocked_definition("inverseIndex",map(str,inv),"Fin 384")+
          "def generatorIndex : Fin 8 → Fin 384 := "+tuple_string(map(str,gens))+"\n\n"+
          "def representativeIndex : Fin 6 → Fin 384 := "+tuple_string(map(str,reps))+"\n\n"+
          "def representativeWord : Fin 6 → List (Fin 8) :=\n  "+tuple_string(["["+", ".join(map(str,words[q]))+"]" for q in reps])+"\n\n"+
          "def projectionRows : Fin 6 → Rows 18 14 :=\n  "+tuple_string(map(rows_string,projection))+"\n\n"+
          "def sectionRows : Fin 6 → Rows 14 18 :=\n  "+tuple_string(map(rows_string,section))+"\n\n"+
          "def targetIndex : Fin 64 → Fin 384 := "+tuple_string(map(str,target))+"\n\n"+
          blocked_definition("targetSlot",(str(target.index(q) if q in target else 0) for q in range(384)),"Fin 64")+
          "def regularBlock : Fin 64 → Fin 6 := "+tuple_string(map(str,regular))+"\n\n"+
          "def singularBlock : Fin 64 → Fin 6 := "+tuple_string(map(str,singular))+"\n\n"+
          "def singularFunctional : Fin 64 → Row 14 :=\n  "+tuple_string(map(row_string,psi))+"\n\n"+
          "def targetFunctional : Fin 64 → Row 14 :=\n  "+tuple_string(map(row_string,phi))+"\n\n"+
          "def translation : Vec 18 := "+tuple_string(map(str,compact["translation"]))+"\n\n"+
          "def quotientLinear (q : Fin 384) (i : Fin 6) : Vec 14 →ₗ[Scalar] Vec 14 :=\n"+
          "  (linear (projectionRows (blockMap q i))).comp ((linear (matrixRows q)).comp (linear (sectionRows i)))\n\n"+
          "def wordIndex (w : List (Fin 8)) : Fin 384 := w.foldl step 0")
    emit(out/"DataRaw.lean",["DataMatrixRows","DataStep","DataRegularInverseRows"],body)
    predicates="""abbrev inverseCheck (q : Fin 384) : Prop :=
  (∀ i j : Fin 18, compEntry (matrixRows q) (matrixRows (inverseIndex q)) i j = identityEntry i j) ∧
  (∀ i j : Fin 18, compEntry (matrixRows (inverseIndex q)) (matrixRows q) i j = identityEntry i j) ∧
  (∀ i : Fin 6, blockMap q (blockMap (inverseIndex q) i) = i) ∧
  (∀ i : Fin 6, blockMap (inverseIndex q) (blockMap q i) = i)

abbrev stepCheck (q : Fin 384) : Prop :=
  ∀ g : Fin 8,
    (∀ i j : Fin 18, compEntry (matrixRows q) (matrixRows (generatorIndex g)) i j = entry (matrixRows (step q g)) i j) ∧
    (∀ i : Fin 6, blockMap q (blockMap (generatorIndex g) i) = blockMap (step q g) i)

abbrev covarianceCheck (q : Fin 384) : Prop :=
  ∀ b : Fin 6, ∀ i : Fin 14, ∀ j : Fin 18,
    linear (projectionRows (blockMap q b)) (linear (matrixRows q) (basisVector j)) i =
      quotientLinear q b (linear (projectionRows b) (basisVector j)) i

abbrev fixedCheck (t : Fin 64) : Prop :=
  (blockMap (targetIndex t) 0 = 2) ∧
  (regularBlock t ≠ singularBlock t) ∧
  (∀ i : Fin 6, blockMap (targetIndex t) i = i ↔ i = regularBlock t ∨ i = singularBlock t) ∧
  (∀ i j : Fin 14,
    linear (regularInverseRows t) (basisVector j - quotientLinear (targetIndex t) (regularBlock t) (basisVector j)) i = identityEntry i j) ∧
  (∀ i j : Fin 14,
    (linear (regularInverseRows t) (basisVector j) - quotientLinear (targetIndex t) (regularBlock t) (linear (regularInverseRows t) (basisVector j))) i = identityEntry i j) ∧
  (∀ j : Fin 14, rowLinear (singularFunctional t) (quotientLinear (targetIndex t) (singularBlock t) (basisVector j)) = rowLinear (singularFunctional t) (basisVector j)) ∧
  (∀ j : Fin 18, rowLinear (singularFunctional t) (linear (projectionRows (singularBlock t)) (basisVector j)) = rowLinear (targetFunctional t) (linear (projectionRows 2) (basisVector j))) ∧
  (rowLinear (targetFunctional t) (linear (projectionRows 2) translation) ≠ 0)
"""
    emit(out/"DataPredicates.lean",["DataRaw"],predicates)
    check_imports=[]
    for predicate, size, chunk in [("inverseCheck",384,16),("stepCheck",384,16),
                                   ("covarianceCheck",384,16),("fixedCheck",64,8)]:
        proofs=[]
        for start in range(0,size,chunk):
            number=start//chunk
            stem=predicate[0].upper()+predicate[1:]+f"{number:03d}"
            theorem=predicate+f"Chunk{number:03d}"
            body=("set_option maxRecDepth 100000\nset_option maxHeartbeats 0\n\n"+
                  f"theorem {theorem} : ∀ k : Fin {chunk}, {predicate} (⟨{start} + k.val, by omega⟩ : Fin {size}) := by\n  decide +kernel")
            emit(out/"Certificates"/f"{stem}.lean",["DataPredicates"],body)
            check_imports.append("Certificates."+stem)
            proofs.append(theorem)
        aggregate=f"theorem {predicate}s (q : Fin {size}) : {predicate} q := by\n"
        for start in range(0,size,chunk):
            theorem=proofs[start//chunk]
            aggregate+=f"  by_cases h{start//chunk} : q.val < {start+chunk}\n  · let k : Fin {chunk} := ⟨q.val - {start}, by omega⟩\n"
            aggregate+=f"    have he : (⟨{start} + k.val, by omega⟩ : Fin {size}) = q := by\n      apply Fin.ext\n      dsimp [k]\n      omega\n"
            aggregate+=f"    simpa only [he] using {theorem} k\n"
        aggregate+="  omega\n"
        emit(out/f"Data{predicate[0].upper()+predicate[1:]}s.lean",check_imports[-len(proofs):],aggregate)
    elementary="""set_option maxRecDepth 100000
set_option maxHeartbeats 0

theorem identity_checked :
    (∀ i j : Fin 18, entry (matrixRows 0) i j = identityEntry i j) ∧
    (∀ i : Fin 6, blockMap 0 i = i) := by decide +kernel

theorem section_checked : ∀ b : Fin 6, ∀ i j : Fin 14,
    compEntry (projectionRows b) (sectionRows b) i j = identityEntry i j := by
  decide +kernel

theorem target_coverage_checked : ∀ q : Fin 384,
    blockMap q 0 = 2 → targetIndex (targetSlot q) = q := by decide +kernel

theorem representative_checked : ∀ b : Fin 6,
    wordIndex (representativeWord b) = representativeIndex b ∧
      blockMap (representativeIndex b) 0 = b := by decide +kernel
"""
    emit(out/"DataElementary.lean",["DataPredicates"],elementary)
    receipt={"input_sha256":input_sha,"compact_sha256":hashlib.sha256(args.compact.read_bytes()).hexdigest(),
             "generator_sha256":hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
             "status":"UNTRUSTED_DATA_GENERATED_REQUIRES_LEAN_KERNEL","quotient_rows":384,
             "closure_pairs":384*8,"inverse_pairs":384,"transporter_rows":64,
             "max_sparse_row_width":max(sum(x!=0 for x in row) for mat in matrices for row in mat),
             "files":{str(p.relative_to(out)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(EMITTED)}}
    (out/"generation_receipt.json").write_text(json.dumps(receipt,indent=2)+"\n")
    print(json.dumps({k:v for k,v in receipt.items() if k!="files"},indent=2))


if __name__=="__main__":
    main()
