import Kourovka.Problems.P21_99.Proof.DataPredicates

/-! Generated by scripts/generate_21_99.py; checked by Lean's kernel. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kourovka.P21_99.Data

set_option maxRecDepth 100000
set_option maxHeartbeats 0

theorem inverseCheckChunk021 : ∀ k : Fin 16, inverseCheck (⟨336 + k.val, by omega⟩ : Fin 384) := by
  decide +kernel

end Kourovka.P21_99.Data
